act_code: '142520'
requisite: Совместные постановление акимата Мактааральского района Туркестанской области от 30 апреля 2020 года № 184 и решение Мактааральского районного маслихата Туркестанской области от 30 апреля 2020 года № 64-398-VI. Зарегистрировано Департаментом юстиции Туркестанской области 4 мая 2020 года № 5596
title:
  rus: Об изменении границ населенных пунктов по Мактааральскому району
  kaz: Мақтаарал ауданы бойынша елді мекендердің шекараларын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2020-04-30
approved_by:
- '166005000001'
- '166005000002'
version_date:
  kaz: 2020-12-14
  rus: 2020-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/142520/kaz/14.12.2020
  rus: https://zan.gov.kz/client/#!/doc/142520/rus/14.12.2020
caused_by:
  code: '150413'
  requisite: Совместные решение Мактааральского районного маслихата Туркестанской области от 14 декабря 2020 года № 74-452-VI и постановление акимата Мактааральского района Туркестанской области от 14 декабря 2020 года № 527. Зарегистрированы Департаментом юстиции Туркестанской области 23 декабря 2020 года № 5966
  title:
    rus: О внесении изменений в совместное постановление акимата Мактааральского района от 30 апреля 2020 года № 184 и в решение Мактааральского районного маслихата от 30 апреля 2020 года № 64-398-VI «Об изменении границ населенных пунктов по Мактааральском району»
    kaz: Мақтаарал ауданы әкімдігінің 2020 жылғы 30 сәуіріндегі № 184 қаулысы мен Мақтаарал аудандық мәслихатының 2020 жылғы 30 сәуіріндегі № 64-398-VI «Мақтаарал ауданы бойынша елді мекендердің шекараларын өзгерту туралы» бірлескен қаулысымен шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150413/rus
