act_code: '32021'
requisite: Қостанай облысы Науырзым ауданы әкімдігінің 2007 жылғы 26 қаңтардағы № 16 қаулысы. Қостанай облысы Науырзым ауданының Әділет басқармасында 2007 жылғы 21 ақпанда № 9-16-48 болып тіркелді
title:
  rus: 18 жасқа дейінгі балаларға арналған ай сайынғы мемлекеттік жәрдемақыны тағайындау кезінде жеке қосалқы шаруашылықтан түскен табысты есептеу үшін статистика органдары ұсынған бағаларды түзету туралы
  kaz: 18 жасқа дейінгі балаларға арналған ай сайынғы мемлекеттік жәрдемақыны тағайындау кезінде жеке қосалқы шаруашылықтан түскен табысты есептеу үшін статистика органдары ұсынған бағаларды түзету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-01-26
approved_by:
- '162014000001'
version_date:
  kaz: 2007-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/32021/kaz/26.01.2007
