act_code: '248'
requisite: Постановление Правительства Республики Казахстан от 12 декабря 1997 г. N 1751. Утратило силу - постановлением Правительства РК от 5 июля 1999 г. N 930.
title:
  rus: О Департаменте государственного имущества и приватизации Министерства финансов Республики Казахстан
  kaz: Қазақстан Республикасы қаржы министрлiгiнiң Мемлекеттiк мүлiк және жекешелендiру департаментi туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1997-12-12
approved_by:
- '103000000000'
version_date:
  rus: 1997-12-12
source:
  rus: https://zan.gov.kz/client/#!/doc/248/rus/12.12.1997
