act_code: '209102'
requisite: Постановление акимата города Туркестан Туркестанской области от 14 апреля 2025 года № 187. Зарегистрировано в Департаменте юстиции Туркестанской области 15 апреля 2025 года № 6680-13
title:
  rus: Об утверждении Правил передачи в управление объектов транспортной инфраструктуры города Туркестан
  kaz: Түркістан қаласының көлік инфрақұрылымы объектілерін басқаруға беру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-04-14
approved_by:
- '166015000001'
version_date:
  kaz: 2025-04-14
  rus: 2025-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/209102/kaz/14.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209102/rus/14.04.2025
