act_code: '172962'
requisite: Постановление акимата Отырарского района Туркестанской области от 7 октября 2022 года № 274
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-10-07
approved_by:
- '166007000001'
version_date:
  kaz: 2022-10-07
  rus: 2022-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/172962/kaz/07.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172962/rus/07.10.2022
