act_code: '199505'
requisite: Постановление акимата Каратобинского района Западно-Казахстанской области от 31 июля 2024 года № 140. Отменено постановлением акимата Каратобинского района Западно-Казахстанской области от 23 декабря 2025 года № 209(вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования).
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» Государственного учреждения "Аппарат акима Каратобинского района" и районных исполнительных органов, финансируемых из местного бюджета
  kaz: «Қаратөбе ауданы әкімінің аппараты» мемлекеттік мекемесінің және жергілікті бюджеттен қаржыланатын аудандық атқарушы органдардың «Б» корпусының мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: ПОСТ
type_codes:
- МЕТ
- ПОСТ
approved_on: 2024-07-31
approved_by:
- '159010000001'
version_date:
  kaz: 2024-07-31
  rus: 2024-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/199505/kaz/31.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199505/rus/31.07.2024
