act_code: '21951'
requisite: Постановление Правительства Республики Казахстан от 26 ноября 2004 года № 1237
title:
  rus: Некоторые вопросы Министерства индустрии и новых технологий Республики Казахстан
  kaz: Қазақстан Республикасы Индустрия және жаңа технологиялар министрлігінiң кейбiр мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2004-11-26
approved_by:
- '103000000000'
version_date:
  kaz: 2013-12-31
  rus: 2013-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/21951/kaz/31.12.2013
  rus: https://zan.gov.kz/client/#!/doc/21951/rus/31.12.2013
caused_by:
  code: '76649'
  requisite: Постановление Правительства Республики Казахстан от 31 декабря 2013 года № 1538. Утратило силу постановлением Правительства Республики Казахстан от 24 сентября 2014 года № 1011
  title:
    rus: Вопросы Агентства Республики Казахстан по защите прав потребителей
    kaz: Қазақстан Республикасы Тұтынушылардың құқықтарын қорғау агенттігінің мәселелері
  link: https://zan.gov.kz/client/#!/doc/76649/rus
