act_code: '24486'
requisite: Постановление Правительства Республики Казахстан от 22 июня 2005 года № 607
title:
  rus: Вопросы Министерства внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасы Iшкi iстер министрлiгiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2005-06-22
approved_by:
- '103000000000'
version_date:
  kaz: 2025-08-28
  rus: 2025-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/24486/kaz/28.08.2025
  rus: https://zan.gov.kz/client/#!/doc/24486/rus/28.08.2025
caused_by:
  code: '213723'
  requisite: Постановление Правительства Республики Казахстан от 28 августа 2025 года № 689
  title:
    rus: О реорганизации республиканского государственного предприятия на праве хозяйственного ведения «Еңбек» учреждений уголовно-исполнительной (пенитенциарной) системы Комитета уголовно-исполнительной системы Министерства внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі істер министрлігі Қылмыстық-атқару жүйесі комитетінің Қылмыстық-атқару жүйесі (пенитенциарлық) мекемелерінің «Еңбек» шаруашылық жүргізу құқығындағы республикалық мемлекеттік кәсіпорнын қайта ұйымдастыру туралы
  link: https://zan.gov.kz/client/#!/doc/213723/rus
