act_code: '24486'
requisite: Постановление Правительства Республики Казахстан от 22 июня 2005 года № 607
title:
  rus: Вопросы Министерства внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасы Iшкi iстер министрлiгiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2005-06-22
approved_by:
- '103000000000'
version_date:
  kaz: 2019-05-24
  rus: 2019-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/24486/kaz/24.05.2019
  rus: https://zan.gov.kz/client/#!/doc/24486/rus/24.05.2019
caused_by:
  code: '131739'
  requisite: Постановление Правительства Республики Казахстан от 24 мая 2019 года № 318
  title:
    rus: О некоторых вопросах Министерства внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі істер министрлігінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/131739/rus
