act_code: '61057'
requisite: Постановление акимата Амангельдинского района Костанайской области от 18 октября 2011 года № 199. Зарегистрировано Управлением юстиции Амангельдинского района Костанайской области 2 ноября 2011 года № 9-6-131. Утратило силу постановлением акимата Амангельдинского района Костанайской области от 16 апреля 2012 года № 87
title:
  rus: Об установлении квоты рабочих мест для лиц, освобожденных из мест лишения свободы и несовершеннолетних выпускников интернатных организаций
  kaz: Бас бостандығынан айыру орындарынан босатылған адамдар және интернаттық ұйымдарды бітіруші кәмелетке толмағандар үшін жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-10-18
approved_by:
- '162004000001'
version_date:
  kaz: 2011-10-18
  rus: 2011-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/61057/kaz/18.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61057/rus/18.10.2011
