act_code: '66180'
requisite: Постановление Правления Национального Банка Республики Казахстан от 28 апреля 2012 года № 165. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 июня 2012 года № 7734
title:
  rus: Об утверждении Требований к программно-техническим средствам и иному оборудованию, необходимым для осуществления деятельности на рынке ценных бумаг
  kaz: Бағалы қағаздар нарығында қызметтi жүзеге асыруға қажеттi бағдарламалық-техникалық құралдар мен өзге жабдықтарға қойылатын талаптарды бекіту туралы
form: ПОСТ
type_codes:
- ИНСТ
- ПОСТ
- ПРЧ
approved_on: 2012-04-28
approved_by:
- '117000000000'
version_date:
  kaz: 2012-08-24
  rus: 2012-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/66180/kaz/24.08.2012
  rus: https://zan.gov.kz/client/#!/doc/66180/rus/24.08.2012
caused_by:
  code: '68166'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 24 августа 2012 года № 277. Зарегистрировано Министерством юстиции Республики Казахстан 15 октября 2012 года № 8006
  title:
    rus: О внесении изменений и дополнения в постановление Правления Национального Банка Республики Казахстан от 28 апреля 2012 года № 165 "Об утверждении Требований к программно-техническим средствам и иному оборудованию, необходимым для осуществления деятельности на рынке ценных бумаг"
    kaz: Қазақстан Республикасының Ұлттық Банкі Басқармасының "Бағалы қағаздар нарығында қызметті жүзеге асыруға қажетті бағдарламалық-техникалық құралдарға және өзге жабдықтарға қойылатын талаптарды бекіту жөнінде" 2012 жылғы 28 сәуірдегі № 165 қаулысына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68166/rus
