act_code: '1824'
requisite: Постановление Правительства Республики Казахстан от 12 декабря 1998 года N 1278. Утратило силу постановлением Правительства РК от 17 августа 2006 года N 778
title:
  rus: Об утверждении Правил государственной регистрации нормативных правовых актов центральных исполнительных и иных центральных государственных органов как входящих, так и не входящих в состав Правительства Республики Казахстан, и актов местных представительных и исполнительных органов Республики Казахстан
  kaz: Қазақстан Республикасының Қазақстан Республикасы Үкіметінің құрамына кіретін де, кірмейтін де орталық атқарушы және өзге де орталық мемлекеттік органдарының нормативтік құқықтық актілері мен жергілікті өкілді және атқарушы органдарының актілерін мемлекеттік тіркеудің тәртібін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 1998-12-12
approved_by:
- '103000000000'
version_date:
  rus: 2000-01-24
source:
  rus: https://zan.gov.kz/client/#!/doc/1824/rus/24.01.2000
caused_by:
  code: '5121'
  requisite: Постановление Правительства Республики Казахстан от 24 января 2000 года № 122. Утратило силу постановлением Правительства Республики Казахстан от 17 августа 2006 года № 778
  title:
    rus: О внесении изменений и дополнений в постановление Правительства Республики Казахстан от 12 декабря 1998 года № 1278
    kaz: Қазақстан Республикасы Үкіметінің 1998 жылғы 12 желтоқсандағы № 1278 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/5121/rus
