act_code: '73799'
requisite: Постановление Правительства Республики Казахстан от 17 июля 2013 года № 730
title:
  rus: Об утверждении Правил субсидирования по удешевлению процентных ставок вознаграждения по кредитам (лизингу) сельскохозяйственной техники на 2013 год
  kaz: 2013 жылға арналған ауыл шаруашылығы техникасының кредиттері (лизингі) бойынша сыйақының пайыздық ставкаларын арзандату жөніндегі субсидиялау қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2013-07-17
approved_by:
- '103000000000'
version_date:
  kaz: 2013-10-08
  rus: 2013-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/73799/kaz/08.10.2013
  rus: https://zan.gov.kz/client/#!/doc/73799/rus/08.10.2013
caused_by:
  code: '74652'
  requisite: Постановление Правительства Республики Казахстан от 8 октября 2013 года № 1064
  title:
    rus: О внесении изменения и дополнения в постановление Правительства Республики Казахстан от 17 июля 2013 года № 730 "Об утверждении Правил субсидирования по удешевлению процентных ставок вознаграждения по кредитам (лизингу) сельскохозяйственной техники на 2013 год"
    kaz: '"2013 жылға арналған ауыл шаруашылығы техникасының кредиттері (лизингі) бойынша сыйақының пайыздық ставкаларын арзандату жөніндегі субсидиялау қағидаларын бекіту туралы" Қазақстан Республикасы Үкіметінің 2013 жылғы 17 шілдедегі № 730 қаулысына өзгеріс пен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74652/rus
