act_code: '22644'
requisite: Постановление Правительства Республики Казахстан от 21 января 2005 года № 40. Утратило силу постановлением Правительства Республики Казахстан от 4 сентября 2015 года № 745
title:
  rus: Об утверждении Правил проведения конкурса по закреплению охотничьих угодий и квалификационных требований, предъявляемых к участникам конкурса
  kaz: Аң аулайтын алқаптарды бекiтiп беру жөнiнде конкурс өткiзу ережесiн және конкурсқа қатысушыларға қойылатын біліктілік талаптарын бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2005-01-21
approved_by:
- '103000000000'
version_date:
  kaz: 2013-01-01
  rus: 2013-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/22644/kaz/01.01.2013
  rus: https://zan.gov.kz/client/#!/doc/22644/rus/01.01.2013
caused_by:
  code: '68447'
  requisite: Постановление Правительства Республики Казахстан от 7 ноября 2012 года № 1413
  title:
    rus: О внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68447/rus
