act_code: '179277'
requisite: Постановление акимата Камыстинского района Костанайской области от 24 марта 2023 года № 37
title:
  rus: Об установлении публичного сервитута ГУ «Управление энергетики и жилищно-коммунального хозяйства акимата Костанайской области»
  kaz: «Қостанай облысы әкімдігінің энергетика және тұрғын үй-коммуналдық шаруашылық басқармасы» ММ қауымдық сервитутты белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2023-03-24
approved_by:
- '162009000001'
version_date:
  kaz: 2023-03-24
  rus: 2023-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/179277/kaz/24.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179277/rus/24.03.2023
