act_code: '188313'
requisite: Постановление Правительства Республики Казахстан от 4 октября 2023 года № 862
title:
  rus: Некоторые вопросы Министерства транспорта Республики Казахстан
  kaz: Қазақстан Республикасы Көлік министрлігінің кейбір мәселелері
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2023-10-04
approved_by:
- '103000000000'
version_date:
  kaz: 2024-12-06
  rus: 2024-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/188313/kaz/06.12.2024
  rus: https://zan.gov.kz/client/#!/doc/188313/rus/06.12.2024
caused_by:
  code: '203784'
  requisite: Постановление Правительства Республики Казахстан от 6 декабря 2024 года № 1032
  title:
    rus: О внесении дополнений в постановление Правительства Республики Казахстан от 4 октября 2023 года № 862 «Некоторые вопросы Министерства транспорта Республики Казахстан»
    kaz: «Қазақстан Республикасы Көлік министрлігінің кейбір мәселелері» туралы Қазақстан Республикасы Үкіметінің 2023 жылғы 4 қазандағы № 862 қаулысына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203784/rus
