act_code: '30862'
requisite: Решение Западно-Казахстанского областного маслихата от 11 декабря 2006 года № 33-24 и постановление акимата Западно-Казахстанской области от 13 октября 2006 года № 319. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 22 декабря 2006 года № 2978
title:
  rus: О переименовании некоторых населенных пунктов Западно-Казахстанской области
  kaz: Батыс Қазақстан облысының кейбір елді мекендердің атауларын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2006-12-11
approved_by:
- '159000000001'
- '159000000002'
version_date:
  kaz: 2006-12-11
  rus: 2006-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/30862/kaz/11.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30862/rus/11.12.2006
