act_code: '15641'
requisite: Постановление Правительства Республики Казахстан от 4 июня 2003 года № 528. Утратило силу постановлением Правительства  Республики Казахстан от 24 сентября 2025 года № 790 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил направления для освидетельствования на состояние опьянения, освидетельствования на состояние опьянения и оформления его результатов
  kaz: Мас күйiн куәландыруға жiберу, мас күйiн куәландыру және оның нәтижелерiн ресiмдеу ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2003-06-04
approved_by:
- '103000000000'
version_date:
  kaz: 2003-06-03
  rus: 2003-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/15641/kaz/03.06.2003
  rus: https://zan.gov.kz/client/#!/doc/15641/rus/03.06.2003
