act_code: '38090'
requisite: Қарағанды облысы Ақтоғай ауданының әкімдігінің 2008 жылғы 28 қаңтардағы № 02/02 қаулысы. Қарағанды облысы Ақтоғай ауданы әділет басқармасында 2008 жылғы 28 ақпанда № 8-10-59 тіркелді
title:
  rus: 2008 жылы мүгедектерге арналған жұмыс орындарына квота белгілеу туралы
  kaz: 2008 жылы мүгедектерге арналған жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-01-28
approved_by:
- '160014000001'
version_date:
  kaz: 2008-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/38090/kaz/28.01.2008
