act_code: '92666'
requisite: Постановление от 13.07.2015 №11995, Акимат г. Усть-Каменогорска. Утратило силу постановлением акимата города Усть-Каменогорска Восточно-Казахстанской области от 09.10.2015 № 13203
title:
  rus: 'Об утверждении Правил поступления и использования безнадзорных животных, поступивших в коммунальную собственность города Усть-Каменогорска '
  kaz: 'Өскемен қаласының коммуналдық меншігіне келіп түскен қараусыз қалған жануарларды келіп түсу және пайдалану Қағидасын бекіту туралы '
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2015-07-13
approved_by:
- '157002000001'
version_date:
  kaz: 2015-07-13
  rus: 2015-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/92666/kaz/13.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92666/rus/13.07.2015
