act_code: '136116'
requisite: Постановление Правления Национального Банка Республики Казахстан от 11 ноября 2019 года № 178. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 ноября 2019 года № 19608
title:
  rus: Об утверждении Правил введения и отмены Национальным Банком Республики Казахстан особого режима регулирования, осуществления деятельности, связанной с цифровыми активами и (или) платежными услугами, в рамках особого режима регулирования, критериев отбора Национальным Банком Республики Казахстан и Правил рассмотрения документов для заключения договора об осуществлении деятельности в рамках особого режима регулирования
  kaz: Қазақстан Республикасы Ұлттық Банкінің ерекше реттеу режимін енгізуі және оның күшін жоюы, ерекше реттеу режимі шеңберінде цифрлық активтермен және (немесе) көрсетілетін төлем қызметтерімен байланысты қызметті жүзеге асыру қағидаларын, Ерекше реттеу режимі шеңберінде қызметті жүзеге асыру туралы шарт жасасу үшін Қазақстан Республикасы Ұлттық Банкінің құжаттарды іріктеуі өлшемшарттарын және оларды қарау қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-11-11
approved_by:
- '117000000000'
version_date:
  kaz: 2025-08-31
  rus: 2025-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/136116/kaz/31.08.2025
  rus: https://zan.gov.kz/client/#!/doc/136116/rus/31.08.2025
caused_by:
  code: '213073'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 25 июля 2025 года № 42. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 августа 2025 года № 36574
  title:
    rus: О внесении изменений в постановление Правления Национального Банка Республики Казахстан от 11 ноября 2019 года № 178 «Об утверждении Правил введения и отмены Национальным Банком Республики Казахстан особого режима регулирования, осуществления деятельности в рамках особого режима регулирования платежными организациями и (или) иными юридическими лицами, не являющимися финансовыми организациями, критериев отбора Национальным Банком Республики Казахстан и Правил рассмотрения документов для заключения договора об осуществлении деятельности в рамках особого режима регулирования»
    kaz: «Қазақстан Республикасы Ұлттық Банкінің ерекше реттеу режимін енгізуі және оның күшін жоюы, қаржы ұйымдары болып табылмайтын төлем ұйымдарының және (немесе) өзге заңды тұлғалардың ерекше реттеу режимі шеңберінде қызметті жүзеге асыруы қағидаларын, Ерекше реттеу режимі шеңберінде қызметті жүзеге асыру туралы шарт жасасу үшін Қазақстан Республикасы Ұлттық Банкінің құжаттарды іріктеуі өлшемшарттарын және оларды қарау қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық Банкі Басқармасының 2019 жылғы 11 қарашадағы № 178 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213073/rus
