act_code: '171661'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 12 сентября 2022 года № 60. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 сентября 2022 года № 29623
title:
  rus: Об утверждении Правил избрания и осуществления деятельности страхового омбудсмана
  kaz: Сақтандыру омбудсманын сайлау және қызметін жүзеге асыру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2022-09-12
approved_by:
- '135000000000'
version_date:
  kaz: 2026-01-27
  rus: 2026-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/171661/kaz/27.01.2026
  rus: https://zan.gov.kz/client/#!/doc/171661/rus/27.01.2026
caused_by:
  code: '221738'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 27 января 2026 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 января 2026 года № 37921
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Республики Казахстан по вопросам совершенствования страхового рынка
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне сақтандыру нарығын жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221738/rus
