act_code: '10874'
requisite: Постановление Правительства Республики Казахстан от 27 декабря 2001 года N 1715
title:
  rus: О реализации Закона Республики Казахстан "О республиканском бюджете на 2002 год"
  kaz: '"2002 жылға арналған республикалық бюджет туралы" Қазақстан Республикасының Заңын iске асыру туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2001-12-27
approved_by:
- '103000000000'
version_date:
  rus: 2002-06-18
source:
  rus: https://zan.gov.kz/client/#!/doc/10874/rus/18.06.2002
caused_by:
  code: '12441'
  requisite: Постановление Правительства Республики Казахстан от 19 июня 2002 года N 673
  title:
    rus: О создании государственного учреждения "Республиканская школа-интернат для одаренных в спорте детей в городе Лениногорске" Агентства Республики Казахстан по туризму и спорту
    kaz: Қазақстан Республикасы Туризм және спорт жөнiндегi агенттiгiнiң "Лениногор қаласындағы спорттағы дарынды балаларға арналған республикалық мектеп-интернат" мемлекеттiк мекемесiн құру туралы
  link: https://zan.gov.kz/client/#!/doc/12441/rus
