act_code: '50110'
requisite: Постановление Правительства Республики Казахстан от 30 декабря 2009 года № 2313
title:
  rus: Об утверждении Правил использования целевых текущих трансфертов из республиканского бюджета 2010 года областными бюджетами и бюджетом города Астаны на поддержку повышения урожайности и качества производимых сельскохозяйственных культур
  kaz: Облыстық бюджеттердің және Астана қаласы бюджетінің өндірілетін ауыл шаруашылығы дақылдарының шығымдылығын және сапасын арттыруды қолдауға 2010 жылғы республикалық бюджеттен бөлінетін ағымдағы нысаналы трансферттерді пайдалану ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2009-12-30
approved_by:
- '103000000000'
version_date:
  kaz: 2009-12-30
  rus: 2009-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/50110/kaz/30.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50110/rus/30.12.2009
