act_code: '5386'
requisite: Постановление Правительства Республики Казахстан от 24 февраля 2000 года № 288. Утратило силу постановлением Правительства Республики Казахстан от 28 декабря 2016 года № 887
title:
  rus: Об упорядочении эксплуатации специальных транспортных средств для обслуживания государственных учреждений, финансируемых из республиканского бюджета
  kaz: Республикалық бюджеттен қаржыландырылатын мемлекеттік мекемелерге қызмет көрсетуге арналған арнайы көлiк құралдарын пайдалануды реттеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2000-02-24
approved_by:
- '103000000000'
version_date:
  kaz: 2016-06-30
  rus: 2016-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/5386/kaz/30.06.2016
  rus: https://zan.gov.kz/client/#!/doc/5386/rus/30.06.2016
caused_by:
  code: '103910'
  requisite: Постановление Правительства Республики Казахстан от 30 июня 2016 года № 388
  title:
    rus: О создании республиканских государственных учреждений «Астанақалалықжолзертханасы» и «Алматықалалықжолзертханасы» и внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: «Астанақалалықжолзертханасы» және «Алматықалалықжолзертханасы» республикалық мемлекеттік мекемелерін құру және Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/103910/rus
