act_code: '22534'
requisite: Постановление Правительства Республики Казахстан от 24 декабря 2004 года № 1362. Утратило силу постановлением Правительства Республики Казахстан от 26 января 2009 года № 45
title:
  rus: Об утверждении Единой бюджетной классификации Республики Казахстан
  kaz: Қазақстан Республикасының Бiрыңғай бюджеттік сыныптамасын бекiту туралы
form: ПОСТ
type_codes:
- КЛАС
- ПОСТ
approved_on: 2004-12-24
approved_by:
- '103000000000'
version_date:
  kaz: 2007-08-17
  rus: 2007-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/22534/kaz/17.08.2007
  rus: https://zan.gov.kz/client/#!/doc/22534/rus/17.08.2007
caused_by:
  code: '34771'
  requisite: Постановление Правительства Республики Казахстан от 17 августа 2007 года № 704
  title:
    rus: О передаче и переименовании государственного учреждения "Центр медицины катастроф" Министерства здравоохранения Республики Казахстан из ведения Министерства здравоохранения Республики Казахстан в ведение Министерства по чрезвычайным ситуациям Республики Казахстан
    kaz: Қазақстан Республикасы Денсаулық сақтау министрлігінің "Апаттар медицинасы орталығы" мемлекеттік мекемесін Қазақстан Республикасы Денсаулық сақтау министрлігінің қарамағынан Қазақстан Республикасы Төтенше жағдайлар министрлігінің қарамағына беру және қайта атау туралы
  link: https://zan.gov.kz/client/#!/doc/34771/rus
