act_code: '131309'
requisite: Постановление акимата Кегенского района Алматинской области от 3 мая 2019 года № 78. Зарегистрировано Департаментом юстиции Алматинской области 4 мая 2019 года № 5129
title:
  rus: Об определении мест для размещения агитационных печатных материалов и предоставлении кандидатам помещений для встреч с избирателями в Кегенском районе
  kaz: Кеген ауданында үгіттік баспа материалдарын орналастыру үшін орындарды белгілеу және кандидаттарға сайлаушылармен кездесуі үшін үй-жайлар беру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-05-03
approved_by:
- '15402100001'
version_date:
  kaz: 2019-05-03
  rus: 2019-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/131309/kaz/03.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131309/rus/03.05.2019
