act_code: '211822'
requisite: Постановление акимата района Мақаншы области Абай от 9 июня 2025 года № 72. Утратило силу постановлением акимата района Мақаншы области Абай от 16 февраля 2026 года № 23
title:
  rus: Об утверждении перечня, наименований и индексов автомобильных дорог общего пользования районного значения района Мақаншы области Абай
  kaz: Абай облысы Мақаншы ауданының жалпыға ортақ пайдаланылатын аудандық маңызы бар автомобиль жолдарының тізбесін,атаулары мен индекстерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2025-06-09
approved_by:
- '168012000001'
version_date:
  kaz: 2025-06-09
  rus: 2025-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/211822/kaz/09.06.2025
  rus: https://zan.gov.kz/client/#!/doc/211822/rus/09.06.2025
