act_code: '208865'
requisite: Постановление акимата Абайского района Карагандинской области от 4 апреля 2025 года № 19/05
title:
  rus: Об утверждении Правил предоставления коммунальных услуг в Абайском районе
  kaz: Абай ауданының коммуналдық көрсетілетін қызметтерді ұсынудың қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2025-04-04
approved_by:
- '160011000001'
version_date:
  kaz: 2025-04-04
  rus: 2025-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/208865/kaz/04.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208865/rus/04.04.2025
