act_code: '40728'
requisite: Постановление Правительства Республики Казахстан от 19 июля 2008 года N 711
title:
  rus: Об утверждении Правил реализации местными исполнительными органами жилья, построенного в рамках Государственной программы жилищного строительства в Республике Казахстан на 2008-2010 годы
  kaz: Жергілікті атқарушы органдардың Қазақстан Республикасындағы тұрғын үй құрылысының 2008 - 2010 жылдарға арналған мемлекеттік бағдарламасы шеңберінде салынған тұрғын үйлерді сату ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2008-07-19
approved_by:
- '103000000000'
version_date:
  kaz: 2010-12-31
  rus: 2010-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/40728/kaz/31.12.2010
  rus: https://zan.gov.kz/client/#!/doc/40728/rus/31.12.2010
caused_by:
  code: '56543'
  requisite: Постановление Правительства Республики Казахстан от 31 декабря 2010 года № 1495
  title:
    rus: О внесении дополнения в постановление Правительства Республики Казахстан от 19 июля 2008 года № 711
    kaz: Қазақстан Республикасы Үкіметінің 2008 жылғы 19 шілдедегі № 711 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56543/rus
