act_code: '103017'
requisite: Постановление акимата Костанайской области от 12 мая 2016 года № 225. Зарегистрировано Департаментом юстиции Костанайской области 6 июня 2016 года № 6431. Утратило силу постановлением акимата Костанайской области от 13 января 2020 года № 11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере архитектурно-градостроительной деятельности
  kaz: Сәулет-қала құрылысы қызметі саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2016-05-12
approved_by:
- '162000000001'
version_date:
  kaz: 2016-05-12
  rus: 2016-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/103017/kaz/12.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103017/rus/12.05.2016
