act_code: '37825'
requisite: Постановление Правительства Республики Казахстан от 22 февраля 2008 года N 184
title:
  rus: Об утверждении государственной квоты на наркотические средства, психотропные вещества и прекурсоры на 2008 год
  kaz: Есірткі құралдарына, психотроптық заттар мен прекурсорларға 2008 жылға арналған мемлекеттік квотаны бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-02-22
approved_by:
- '103000000000'
version_date:
  kaz: 2008-02-22
  rus: 2008-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/37825/kaz/22.02.2008
  rus: https://zan.gov.kz/client/#!/doc/37825/rus/22.02.2008
