act_code: '88207'
requisite: Постановление акимата города Курчатов Восточно-Казахстанской области от 17 марта 2015 года № 84. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 06 апреля 2015 года № 3839. Утратило силу - постановлением акимата города Курчатов Восточно-Казахстанской области от 11.05.2016 № 439
title:
  rus: Об утверждении положения о государственном учреждении «Отдел занятости и социальных программ города Курчатов Восточно-Казахстанской области»
  kaz: «Шығыс Қазақстан облысы Курчатов қаласының жұмыспен қамту және әлеуметтік бағдарламалар бөлімі» мемлекеттік мекемесі туралы ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-03-17
approved_by:
- '157004000001'
version_date:
  kaz: 2015-03-17
  rus: 2015-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/88207/kaz/17.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88207/rus/17.03.2015
