act_code: '37782'
requisite: Атырау облысы Жылыой ауданы әкімиятының 2007 жылғы 24 желтоқсандағы № 368 қаулысы. Жылыой аудандық Әділет басқармасында 2008 жылғы 8 қаңтарда № 4-2-82 болып тіркелді
title:
  rus: Жылыой ауданы білім беру бөлімінің мемлекеттік қызмет көрсетудің стандарттарын бекіту туралы
  kaz: Жылыой ауданы білім беру бөлімінің мемлекеттік қызмет көрсетудің стандарттарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-12-24
approved_by:
- '156009000001'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/37782/kaz/24.12.2007
