act_code: '183629'
requisite: Постановление Правительства Республики Казахстан от 30 июня 2023 года № 520
title:
  rus: Об утверждении Правил осуществления обязательных профессиональных пенсионных взносов
  kaz: Міндетті кәсіптік зейнетақы жарналарын жүзеге асыру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2023-06-30
approved_by:
- '103000000000'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/183629/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/183629/rus/27.03.2024
caused_by:
  code: '194773'
  requisite: Постановление Правительства Республики Казахстан от 27 марта 2024 года № 228
  title:
    rus: О внесении изменений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194773/rus
