act_code: '196167'
requisite: Постановление акимата Мамлютского района Северо-Казахстанской области от 1 апреля 2024 года № 70
title:
  rus: Об утверждении Положения коммунального государственного учреждения «Отдел внутренней политики, культуры и развития языков акимата Мамлютского района Северо-Казахстанской области»
  kaz: «Солтүстік Қазақстан облысы Мамлют ауданы әкімдігінің ішкі саясат, мәдениет және тілдерді дамыту бөлімі» коммуналдық мемлекеттік мекемесінің ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2024-04-01
approved_by:
- '165009000001'
version_date:
  kaz: 2026-02-06
  rus: 2026-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/196167/kaz/06.02.2026
  rus: https://zan.gov.kz/client/#!/doc/196167/rus/06.02.2026
caused_by:
  code: '222156'
  requisite: Постановление акимата Мамлютского района Северо-Казахстанской области от 6 февраля 2026 года № 29
  title:
    rus: О внесении изменения и дополнений в постановление акимата Мамлютского района Северо-Казахстанской области от 1 апреля 2024 года № 70 «Об утверждении Положения коммунального государственного учреждения «Отдел внутренней политики, культуры и развития языков акимата Мамлютского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Мамлют ауданы әкімдігінің ішкі саясат, мәдениет және тілдерді дамыту бөлімі» коммуналдық мемлекеттік мекемесінің ережесін бекіту туралы» Солтүстік Қазақстан облысы Мамлют ауданы әкімдігінің 2024 жылғы 1 сәуірдегі № 70 қаулысына өзгеріс және толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222156/rus
