act_code: '37001'
requisite: Постановление Правительства Республики Казахстан от 29 декабря 2007 года № 1400. Утратило силу постановлением Правительства Республики Казахстан от 31 декабря 2015 года № 1193
title:
  rus: О системе оплаты труда гражданских служащих, работников организаций, содержащихся за счет средств государственного бюджета, работников казенных предприятий
  kaz: Азаматтық қызметшілерге, мемлекеттік бюджет қаражаты есебінен ұсталатын ұйымдардың қызметкерлеріне, қазыналық кәсіпорындардың қызметкерлеріне еңбекақы төлеу жүйесі туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-12-29
approved_by:
- '103000000000'
version_date:
  kaz: 2010-03-31
  rus: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/37001/kaz/31.03.2010
  rus: https://zan.gov.kz/client/#!/doc/37001/rus/31.03.2010
caused_by:
  code: '51641'
  requisite: Постановление Правительства Республики Казахстан от 31 марта 2010 года № 252
  title:
    rus: О некоторых вопросах Министерства культуры Республики Казахстан
    kaz: Қазақстан Республикасы Мәдениет министрлігінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/51641/rus
