act_code: '175'
requisite: Постановление Кабинета Министров Республики Казахстан от 9 декабря 1993 года N 1231. Утратило силу - постановлением Правительства РК от 17 января 2003 г. N 49
title:
  rus: Об утверждении Правил предоставления права плавания морских торговых судов под государственным флагом Республики Казахстан
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫНЫҢ МЕМЛЕКЕТТIК ЖАЛАУЫ АСТЫНДА ТЕҢIЗ САУДА КЕМЕЛЕРIНIҢ ЖҮЗУ ҚҰҚЫҒЫН БЕРУДІҢ ТӘРТІБІН БЕКIТУ ТУРАЛЫ
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1993-12-09
approved_by:
- '103000000000'
version_date:
  rus: 1993-12-09
source:
  rus: https://zan.gov.kz/client/#!/doc/175/rus/09.12.1993
