act_code: '26383'
requisite: Постановление Правительства Республики Казахстан от 13 января 2006 года № 35
title:
  rus: О некоторых вопросах распределения и использования целевых трансфертов областным бюджетам, бюджетам городов Астаны и Алматы в 2006 году на развитие и обустройство инженерно-коммуникационной инфраструктуры
  kaz: Облыстық бюджеттерге, Астана және Алматы қалаларының бюджеттерiне 2006 жылы инженерлiк-коммуникациялық инфрақұрылымды дамытуға және жайластыруға берiлетiн нысаналы трансферттердi бөлу мен пайдаланудың кейбiр мәселелерi туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2006-01-13
approved_by:
- '103000000000'
version_date:
  kaz: 2006-01-13
  rus: 2006-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/26383/kaz/13.01.2006
  rus: https://zan.gov.kz/client/#!/doc/26383/rus/13.01.2006
