act_code: '180538'
requisite: Совместные постановление акимата Жамбылской области от 21 апреля 2023 года № 64 и решение Жамбылского областного маслихата от 21 апреля 2023 года № 2-6. Зарегистрировано Департаментом юстиции Жамбылской области 26 апреля 2023 года № 5002
title:
  rus: Об установлении границ Алгинского, Бирликустемского и Жана жолского сельских округов Шуского района Жамбылской области
  kaz: Жамбыл облысы Шу ауданы Алға, Бірлікүстем және Жаңа жол ауылдық округтерінің шекараларын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2023-04-21
approved_by:
- '158000000001'
- '158000000002'
version_date:
  kaz: 2023-04-21
  rus: 2023-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/180538/kaz/21.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180538/rus/21.04.2023
