act_code: '140981'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 30 марта 2020 года № 40. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 марта 2020 года № 20226
title:
  rus: Об утверждении Правил выдачи, приостановления и лишения лицензий на осуществление видов профессиональной деятельности на рынке ценных бумаг
  kaz: Бағалы қағаздар нарығында кәсіби қызмет түрлерін жүзеге асыруға лицензияларды беру, оларды тоқтата тұру және олардан айыру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2020-03-30
approved_by:
- '135000000000'
version_date:
  kaz: 2022-05-29
  rus: 2022-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/140981/kaz/29.05.2022
  rus: https://zan.gov.kz/client/#!/doc/140981/rus/29.05.2022
caused_by:
  code: '165580'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 14 марта 2022 года № 24. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 марта 2022 года № 27213
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам оказания государственных услуг в сфере государственного регулирования деятельности на рынке ценных бумаг и деятельности добровольных накопительных пенсионных фондов
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне бағалы қағаздар нарығындағы қызметті және ерікті жинақтаушы зейнетақы қорларының қызметін мемлекеттік реттеу саласында мемлекеттік қызметтер көрсету мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165580/rus
