act_code: '25521'
requisite: Маңғыстау облысы Түпқараған ауданы әкімдігінің 2005 жылғы 17 наурыздғы № 53 қаулысы. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2005 жылғы 28 наурызда № 11-6-1 болып тіркелді
title:
  rus: Аудан бойынша жұмыссыздарды кәсіби біліктілігін арттыру және қайта даярлау мамандықтар тізбесін бекіту туралы
  kaz: Аудан бойынша жұмыссыздарды кәсіби біліктілігін арттыру және қайта даярлау мамандықтар тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2005-03-17
approved_by:
- '163006000001'
version_date:
  kaz: 2005-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/25521/kaz/17.03.2005
