act_code: '48170'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 26 сентября 2009 года № 215. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 октября 2009 года № 5810. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 16 июля 2014 года № 146
title:
  rus: Об утверждении Правил расчета пруденциальных нормативов для организаций, совмещающих виды профессиональной деятельности на рынке ценных бумаг
  kaz: Бағалы қағаздар нарығында кәсіби қызмет түрлерін қоса атқаратын ұйымдарға арналған пруденциалдық нормативтерді есептеу ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРАВ
approved_on: 2009-09-26
approved_by:
- '109000000000'
version_date:
  kaz: 2012-12-24
  rus: 2012-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/48170/kaz/24.12.2012
  rus: https://zan.gov.kz/client/#!/doc/48170/rus/24.12.2012
caused_by:
  code: '70598'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 24 декабря 2012 года № 374. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 января 2013 года № 8271. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 23 ноября 2022 года № 99 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Республики Казахстан
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/70598/rus
