act_code: '42399'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 2 октября 2008 года № 141. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 ноября 2008 года № 5362. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 24 декабря 2012 года № 387
title:
  rus: Об утверждении Правил о методике расчета ставки обязательных, дополнительных взносов и условных обязательств, порядке и сроках уплаты обязательных, дополнительных и чрезвычайных взносов, формирования и учета условных обязательств страховыми организациями - участниками Фонда гарантирования страховых выплат
  kaz: Сақтандыру ұйымдарының – Сақтандыру төлемдеріне кепілдік беру қоры қатысушыларының міндетті, қосымша жарналар мен шартты міндеттемелердің ставкасын есептеу әдістемесі, міндетті, қосымша және төтенше жарналар төлеу тәртібі мен мерзімдері, шартты міндеттемелерді қалыптастыру және есебін жүргізу туралы ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2008-10-02
approved_by:
- '109000000000'
version_date:
  kaz: 2010-09-03
  rus: 2010-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/42399/kaz/03.09.2010
  rus: https://zan.gov.kz/client/#!/doc/42399/rus/03.09.2010
caused_by:
  code: '55024'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 3 сентября 2010 года № 138. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 октября 2010 года № 6558
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Республики Казахстан по вопросам деятельности Акционерного общества "Фонд гарантирования страховых выплат"
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне "Сақтандыру төлемдеріне кепілдік беру қоры" акционерлік қоғамының қызметі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55024/rus
