act_code: '87094'
requisite: Постановление акимата города Кентау Южно-Казахстанской области от 3 февраля 2015 года № 26. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 20 февраля 2015 года № 3045. Утратило силу постановлением акимата города Кентау Южно-Казахстанской области от 23 мая 2016 года № 129
title:
  rus: Об утверждении положении аппаратов акима села
  kaz: Ауыл әкімі аппараттарының ережелерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-02-03
approved_by:
- '166014000001'
version_date:
  kaz: 2016-02-16
  rus: 2016-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/87094/kaz/16.02.2016
  rus: https://zan.gov.kz/client/#!/doc/87094/rus/16.02.2016
caused_by:
  code: '99721'
  requisite: Постановление акимата города Кентау Южно-Казахстанской области от 16 февраля 2016 года № 44. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 марта 2016 года № 3611. Утратило силу постановлением акимата города Кентау Южно-Казахстанской области от 9 июня 2016 года № 145
  title:
    rus: О внесении изменений и дополнений в постановление акимата города Кентау от 3 февраля 2015 года № 26 «Об утверждении положении аппаратов акима села»
    kaz: «Ауыл әкімі аппараттарының ережелерін бекіту туралы» Кентау қаласы әкімдігінің 2015 жылғы 3 ақпандағы № 26 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99721/rus
