act_code: '5484'
requisite: Постановление Правительства Республики Казахстан от 10 марта 2000 года N 378. Утратило силу постановлением Правительства Республики Казахстан от 26 января 2009 года N 56.
title:
  rus: Об утверждении Перечня лекарственных средств, в том числе лекарственных субстанций, изделий медицинского (ветеринарного) назначения, включая протезно-ортопедические изделия, сурдотифлотехники и медицинской (ветеринарной) техники, материалов и комплектующих для производства лекарственных и диабетических средств, изделий медицинского (ветеринарного) назначения, включая протезно-ортопедические изделия, и медицинской (ветеринарной) техники, освобождаемых от налога на добавленную стоимость
  kaz: Қосылған құн салығынан босатылатын дәрiлiк заттардың, оның iшiнде дәрiлiк субстанциялардың, протездiк-ортопедиялық бұйымдарды қоса алғанда, медициналық (ветеринарлық) мақсаттағы бұйымдардың, сурдотифлотехника мен медицина (ветеринария) техникасының, дәрi-дәрмек және диабеттiк құралдарды өндiруге арналған материалдар мен жиынтықтаушылардың, протездiк-ортопедиялық бұйымдарды қоса алғанда, медициналық (ветеринарлық) мақсаттағы бұйымдардың және медицина (ветеринария) техникасының тiзбесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2000-03-10
approved_by:
- '103000000000'
version_date:
  kaz: 2004-12-04
  rus: 2004-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/5484/kaz/04.12.2004
  rus: https://zan.gov.kz/client/#!/doc/5484/rus/04.12.2004
caused_by:
  code: '22026'
  requisite: Постановление Правительства Республики Казахстан от 4 декабря 2004 года N 1271. Утратило силу постановлением Правительства Республики Казахстан от 26 января 2009 года N 56
  title:
    rus: О внесении изменений в постановления Правительства Республики Казахстан от 10 марта 2000 года N 378 и от 23 января 2002 года N 84
    kaz: Қазақстан Республикасы Yкiметінiң 2000 жылғы 10 наурыздағы N 378 және 2002 жылғы 23 қаңтардағы N 84 қаулыларына өзгерiстер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/22026/rus
