act_code: '153322'
requisite: Постановление Восточно-Казахстанского областного акимата от 3 марта 2021 года № 55. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 марта 2021 года № 8435
title:
  rus: Об установлении водоохранных зон и водоохранных полос реки Аблакетка в створе от границы села Мамай батыр до границы Уланского района Восточно-Казахстанской области и режима их хозяйственного использования
  kaz: Шығыс Қазақстан облысы Мамай батыр ауылының шекарасынан Ұлан ауданының шекарасына дейінгі тұстамадағы Аблакетка өзенінің су қорғау аймақтары мен су қорғау белдеулерін және оларды шаруашылыққа пайдалану режимін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2021-03-03
approved_by:
- '157000000001'
version_date:
  kaz: 2021-03-03
  rus: 2021-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/153322/kaz/03.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153322/rus/03.03.2021
