act_code: '767'
requisite: Постановление Правительства Республики Казахстан от 24 июня 1998 года № 592. Утратило силу постановлением Правительства Республики Казахстан от 2 июля 2013 года № 673
title:
  rus: Об утверждении формы Договора выкупа занимаемого жилища, приравненного к служебному, работником центрального аппарата государственного органа, содержащегося за счет республиканского бюджета и передислоцированного в город Астану
  kaz: Республикалық бюджет есебiнен ұсталатын және Астана қаласына қоныс аударған мемлекеттiк органның орталық аппараты қызметкерiнiң өзi тұрып жатқан қызметтiкке теңестiрiлген тұрғын үйдi сатып алу шартының нысанын бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-06-23
approved_by:
- '103000000000'
version_date:
  rus: 1998-11-11
source:
  rus: https://zan.gov.kz/client/#!/doc/767/rus/11.11.1998
caused_by:
  code: '1464'
  requisite: Постановление Правительства Республики Казахстан от 11 ноября 1998 года № 1148
  title:
    rus: О внесении изменений в постановления Правительства Республики Казахстан от 24 июля 1997 года № 1173 и от 24 июня 1998 года № 592
    kaz: Қазақстан Республикасы Yкіметінің 1997 жылғы 24 шілдедегі № 1173 және 1998 жылғы 24 маусымдағы № 592 қаулыларына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/1464/rus
