act_code: '38802'
requisite: Постановление Правительства Республики Казахстан от 8 апреля 2008 года № 337. Утратило силу постановлением Правительства Республики Казахстан от 30 января 2017 года № 29
title:
  rus: Об утверждении Технического регламента "Требования к безопасности зерна"
  kaz: '"Астық қауіпсіздігіне қойылатын талаптар" техникалық регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2008-04-08
approved_by:
- '103000000000'
version_date:
  kaz: 2008-04-08
  rus: 2008-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/38802/kaz/08.04.2008
  rus: https://zan.gov.kz/client/#!/doc/38802/rus/08.04.2008
