act_code: '57831'
requisite: Постановление акимата Лебяжинского района Павлодарской области от 18 марта 2011 года № 67/2. Зарегистрировано Управлением юстиции Лебяжинского района Павлодарской области 28 марта 2011 года № 12-9-128
title:
  rus: О социальной помощи отдельным категориям граждан Лебяжинского района на 2011 год
  kaz: Лебяжі ауданының 2011 жылға арналған жекелеген санаттағы азаматтарға әлеуметтік көмек көрсету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-03-18
approved_by:
- '164009000001'
version_date:
  kaz: 2011-06-23
  rus: 2011-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/57831/kaz/23.06.2011
  rus: https://zan.gov.kz/client/#!/doc/57831/rus/23.06.2011
caused_by:
  code: '59424'
  requisite: Постановление акимата Лебяжинского района Павлодарской области от 23 июня 2011 года № 152/4. Зарегистрировано Департаментом юстиции Павлодарской области 23 июня 2011 года № 12-9-132
  title:
    rus: О внесении изменений и дополнений в постановление акимата Лебяжинского района от 18 марта 2011 года № 67/2 "О социальной помощи отдельным категориям граждан Лебяжинского района на 2011 года"
    kaz: Лебяжі ауданы әкімдігінің 2011 жылғы 18 наурыздағы "Лебяжі ауданының 2011 жылға арналған жекелеген санаттағы азаматтарға әлеуметтік көмек көрсету туралы" № 67/2 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59424/rus
