act_code: '224399'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 20 апреля 2026 года № 72. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 апреля 2026 года № 38501
title:
  rus: Об утверждении Правил осуществления инвестиционной деятельности банка, филиала банка-нерезидента Республики Казахстан
  kaz: Банктің, Қазақстан Республикасының бейрезидент банкі филиалының инвестициялық қызметті жүзеге асыру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2026-04-20
approved_by:
- '135000000000'
version_date:
  kaz: 2026-04-20
  rus: 2026-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/224399/kaz/20.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224399/rus/20.04.2026
