act_code: '37995'
requisite: Атырау облысы Құрманғазы ауданы әкімиятының 2007 жылғы 21 желтоқсандағы № 507 қаулысы. Атырау облысы Әділет департаменті Құрманғазы ауданының Әділет басқармасында 2007 жылғы 24 желтоқсанда № 4-8-99 болып тіркелді
title:
  rus: Көптоғай селолық округі әкімі аппаратының мемлекеттік қызмет көрсету стандартын бекіту туралы
  kaz: Көптоғай селолық округі әкімі аппаратының мемлекеттік қызмет көрсету стандартын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-12-21
approved_by:
- '153008013001'
version_date:
  kaz: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37995/kaz/21.12.2007
