act_code: '8261'
requisite: Постановление Правительства Республики Казахстан от 5 марта 2001 года № 329
title:
  rus: О некоторых вопросах повышения размеров пенсионных выплат из Государственного центра по выплате пенсий в 2001 году
  kaz: 2001 жылы Зейнетақы төлеу жөніндегі мемлекеттік орталықтан төленетін зейнетақы төлемдерінің мөлшерін арттырудың кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2001-03-05
approved_by:
- '103000000000'
version_date:
  kaz: 2002-01-11
  rus: 2002-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/8261/kaz/11.01.2002
  rus: https://zan.gov.kz/client/#!/doc/8261/rus/11.01.2002
caused_by:
  code: '10931'
  requisite: Постановление Правительства Республики Казахстан от 11 января 2002 года № 31
  title:
    rus: О повышении размеров пенсионных выплат из Государственного центра по выплате пенсий с 1 января 2002 года
    kaz: 2002 жылдың 1 қаңтарынан бастап Зейнетақы төлеу жөнiндегі мемлекеттiк орталықтан төленетiн зейнетақы төлемдерiнiң мөлшерін арттыру туралы
  link: https://zan.gov.kz/client/#!/doc/10931/rus
