act_code: '76780'
requisite: Постановление акимата города Арыс Южно-Казахстанской области от 23 декабря 2013 года № 605. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 января 2014 года № 2498. Утратило силу постановлением акимата города Арыс Южно-Казахстанской области от 21 декабря 2015 года № 616
title:
  rus: Об утверждении Правил служебной этики государственных служащих аппарата акима города Арыс и исполнительных органов, финансируемых из городского бюджета
  kaz: Арыс қаласы әкімі аппаратының және қалалық бюджеттен қаржыландырылатын атқарушы органдардың мемлекеттік қызметшілерінің қызмет этикасының қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-12-23
approved_by:
- '166016000001'
version_date:
  kaz: 2013-12-23
  rus: 2013-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76780/kaz/23.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76780/rus/23.12.2013
