act_code: '117278'
requisite: Постановление Правительства Республики Казахстан от 29 декабря 2017 года № 927
title:
  rus: Об утверждении перечней объектов, в том числе стратегических, находящихся в государственной собственности и собственности субъектов квазигосударственного сектора, не подлежащих отчуждению
  kaz: Иеліктен шығаруға жатпайтын, мемлекеттік меншіктегі және квазимемлекеттік сектор субъектілерінің меншігіндегі объектілердің, оның ішінде стратегиялық объектілердің тізбелерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2017-12-29
approved_by:
- '103000000000'
version_date:
  kaz: 2026-01-19
  rus: 2026-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/117278/kaz/19.01.2026
  rus: https://zan.gov.kz/client/#!/doc/117278/rus/19.01.2026
caused_by:
  code: '221408'
  requisite: Постановление Правительства Республики Казахстан от 19 января 2026 года № 24
  title:
    rus: О внесении изменения в постановление Правительства Республики Казахстан от 29 декабря 2017 года № 927 «Об утверждении перечней объектов, в том числе стратегических, находящихся в государственной собственности и собственности субъектов квазигосударственного сектора, не подлежащих отчуждению»
    kaz: «Иеліктен шығаруға жатпайтын, мемлекеттік меншіктегі және квазимемлекеттік сектор субъектілерінің меншігіндегі объектілердің, оның ішінде стратегиялық объектілердің тізбелерін бекіту туралы» Қазақстан Республикасы Үкіметінің 2017 жылғы 29 желтоқсандағы № 927 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221408/rus
