act_code: '5910'
requisite: Постановление Правительства Республики Казахстан от 5 мая 2000 года N 674. Утратило силу - постановлением Правительства РК от 27 августа 2005 г. N 889 (вводится в действие с 1 января 2006 г.)
title:
  rus: О мерах по обеспечению лекарственными средствами по видам заболеваний и специализированными продуктами детского и лечебного питания отдельных категорий населения
  kaz: Тұрғындардың жекелеген санаттарын науқастарының түрлерi бойынша дәрi-дәрмекпен және балаларға арналған және шипалы тағамдық арнаулы азық-түлiкпен қамтамасыз ету жөнiндегi шаралар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2000-05-04
approved_by:
- '103000000000'
version_date:
  kaz: 2000-10-17
  rus: 2000-10-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/5910/kaz/17.10.2000
  rus: https://zan.gov.kz/client/#!/doc/5910/rus/17.10.2000
caused_by:
  code: '7133'
  requisite: Постановление Правительства Республики Казахстан от 18 октября 2000 года № 1555. Утратило силу постановлением Правительства Республики Казахстан от 27 августа 2005 года № 889 (вводится в действие с 1 января 2006 года)
  title:
    rus: О внесении дополнения в постановление Правительства Республики Казахстан от 5 мая 2000 года № 674
    kaz: Қазақстан Республикасы Үкіметінің 2000 жылғы 5 мамырдағы № 674 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/7133/rus
