act_code: '50100'
requisite: Решение Уральского городского маслихата Западно-Казахстанской области от 24 декабря 2009 года № 24-8 и постановление акимата города Уральска Западно-Казахстанской области от 20 августа 2009 года № 2131. Зарегистрировано Управлением юстиции города Уральска Западно-Казахстанской области 19 января 2010 года № 7-1-166
title:
  rus: О присвоении наименования "имени А. Дауылбаева" новой улице в микрорайоне "Жақсы ауыл" города Уральска
  kaz: Орал қаласының "Жақсы ауыл" шағынауданындағы жаңа көшеге "А. Дауылбаев атындағы көше" атауын тағайындау туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2009-12-24
approved_by:
- '159002000001'
- '159002000002'
version_date:
  kaz: 2009-12-24
  rus: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50100/kaz/24.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50100/rus/24.12.2009
