act_code: '106448'
requisite: Постановление акимата Шардаринского района Южно-Казахстанской области от 6 сентября 2016 года № 309. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 26 сентября 2016 года № 3856. Утратило силу постановлением акимата Шардаринского района Южно-Казахстанской области от 16 марта 2017 года № 81
title:
  rus: Об утверждении государственного образовательного заказа на дошкольное воспитание и обучение, размера подушевого финансирования и родительской платы
  kaz: Мектепке дейінгі тәрбие мен оқытуға мемлекеттік білім беру тапсырысын, жан басына шаққандағы қаржыландыру және ата-ананың ақы төлеу мөлшерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-09-06
approved_by:
- '166013000001'
version_date:
  kaz: 2016-09-06
  rus: 2016-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/106448/kaz/06.09.2016
  rus: https://zan.gov.kz/client/#!/doc/106448/rus/06.09.2016
