act_code: '173078'
requisite: Постановление акимата Баянаульского района Павлодарской области от 4 октября 2022 года № 229/10. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 октября 2022 года № 30232
title:
  rus: Об определении и утверждении мест размещения нестационарных торговых объектов на территории Баянаульского района
  kaz: Баянауыл ауданының аумағында стационарлық емес сауда объектілерін орналастыру орындарын айқындау және бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-10-04
approved_by:
- '164005000001'
version_date:
  kaz: 2022-10-04
  rus: 2022-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/173078/kaz/04.10.2022
  rus: https://zan.gov.kz/client/#!/doc/173078/rus/04.10.2022
