act_code: '49886'
requisite: Постановление Правительства Республики Казахстан от 30 декабря 2009 года № 2280. Утратило силу постановлением Правительства Республики Казахстан от 23 мая 2016 года № 298
title:
  rus: Об утверждении Правил проведения аттестации государственных информационных систем и негосударственных информационных систем, интегрируемых с государственными информационными системами, на соответствие их требованиям информационной безопасности и принятым на территории Республики Казахстан стандартам
  kaz: Мемлекеттік ақпараттық жүйелерді және мемлекеттік ақпараттық жүйелермен интеграцияланатын мемлекеттік емес ақпараттық жүйелерді олардың ақпараттық қауіпсіздік талаптарына және Қазақстан Республикасының аумағында қабылданған стандарттарға сәйкестігіне аттестаттау жүргізу ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2009-12-30
approved_by:
- '103000000000'
version_date:
  kaz: 2011-11-03
  rus: 2011-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/49886/kaz/03.11.2011
  rus: https://zan.gov.kz/client/#!/doc/49886/rus/03.11.2011
caused_by:
  code: '61129'
  requisite: Постановление Правительства Республики Казахстан от 3 ноября 2011 года № 1285. Утратило силу постановлением Правительства Республики Казахстан от 23 мая 2016 года № 298
  title:
    rus: О внесении изменений и дополнений в постановление Правительства Республики Казахстан от 30 декабря 2009 года № 2280 "Об утверждении Правил проведения аттестации государственных информационных систем и негосударственных информационных систем, интегрируемых с государственными информационными системами, на соответствие их требованиям информационной безопасности и принятым на территории Республики Казахстан стандартам"
    kaz: '"Мемлекеттiк ақпараттық жүйелердi және мемлекеттiк ақпараттық жүйелермен интеграцияланатын мемлекеттiк емес ақпараттық жүйелердi олардың ақпараттық қауiпсiздiк талаптарына және Қазақстан Республикасының аумағында қабылданған стандарттарға сәйкестiгiне аттестаттау жүргiзу ережесiн бекіту туралы" Қазақстан Республикасы Үкiметiнiң 2009 жылғы 30 желтоқсандағы № 2280 қаулысына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61129/rus
