act_code: '126812'
requisite: Постановление акимата Чингирлауского района Западно-Казахстанской области от 4 декабря 2018 года № 211. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 10 декабря 2018 года № 5424. Утратило силу постановлением акимата Чингирлауского района Западно-Казахстанской области от 28 декабря 2020 года № 204 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об определении мест принудительного труда осужденных к ограничению свободы на территории Чингирлауского района Западно-Казахстанской области
  kaz: Батыс Қазақстан облысы Шыңғырлау ауданының аумағында бас бостандығын шектеуге сотталғандарды мәжбүрлі еңбекке тарту орындарын айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-12-04
approved_by:
- '159014000001'
version_date:
  kaz: 2018-12-04
  rus: 2018-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/126812/kaz/04.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126812/rus/04.12.2018
