act_code: '29159'
requisite: Решение Западно-Казахстанского областного маслихата от 1 июля 2006 года № 28-11 и постановление акимата Западно-Казахстанской области от 12 июня 2006 года № 192. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 2 августа 2006 года № 2972
title:
  rus: Об изменении подчиненности некоторых населенных пунктов Таскалинского района
  kaz: Тасқала ауданының кейбір елді мекендерінің бағыныстылығын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2006-06-12
approved_by:
- '159000000001'
- '159000000002'
version_date:
  rus: 2006-06-12
source:
  rus: https://zan.gov.kz/client/#!/doc/29159/rus/12.06.2006
