act_code: '45181'
requisite: Жамбыл облысы әкімиятының 2009 жылғы 26 ақпандағы № 58 қаулысы. Жамбыл облыстық Әділет департаментінде 2009 жылғы 3 сәуірде № 1722 тіркелді. Күші жойылды - Жамбыл облысы әкімдігінің 2010 жылғы 29 сәуірдегі № 116 қаулысымен
title:
  rus: 2009 жылға көшіп келу квотасы бойынша Жамбыл облысына келетін оралмандарды қабылдау мен орналастыруды ұйымдастыру туралы
  kaz: 2009 жылға көшіп келу квотасы бойынша Жамбыл облысына келетін оралмандарды қабылдау мен орналастыруды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-02-26
approved_by:
- '158000000001'
version_date:
  kaz: 2009-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/45181/kaz/26.02.2009
