act_code: '105001'
requisite: Постановление акимата Акмолинской области от 10 июня 2016 года № А-7/269. Зарегистрировано Департаментом юстиции Акмолинской области 20 июля 2016 года № 5460. Утратило силу постановлением акимата Акмолинской области от 29 апреля 2021 года № А-5/216 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении перечня открытых данных, размещаемого на интернет-портале открытых данных
  kaz: Ашық деректердің интернет-порталында орналастырылатын ашық деректер тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2016-06-10
approved_by:
- '152000000001'
version_date:
  kaz: 2019-10-30
  rus: 2019-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/105001/kaz/30.10.2019
  rus: https://zan.gov.kz/client/#!/doc/105001/rus/30.10.2019
caused_by:
  code: '135701'
  requisite: Постановление акимата Акмолинской области от 30 октября 2019 года № А-11/520. Зарегистрировано Департаментом юстиции Акмолинской области 1 ноября 2019 года № 7465. Утратило силу постановлением акимата Акмолинской области от 29 апреля 2021 года № А-5/216 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменений в постановление акимата Акмолинской области от 10 июня 2016 года № А-7/269 «Об утверждении перечня открытых данных, размещаемого на интернет-портале открытых данных»
    kaz: «Ашық деректердің интернет-порталында орналастырылатын ашық деректер тізбесін бекіту туралы» Ақмола облысы әкімдігінің 2016 жылғы 10 маусымдағы № А-7/269 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135701/rus
