act_code: '72473'
requisite: Постановление акимата Аршалынского района Акмолинской области от 22 апреля 2013 года № А-165. Зарегистрировано Департаментом юстиции Акмолинской области 06 мая 2013 года № 3719. Утратило силу постановлением акимата Аршалынского района Акмолинской области от 8 января 2014 года № А-29
title:
  rus: Об определении сроков предоставления заявок на включение в список получателей субсидий и оптимальных сроков сева по каждому виду субсидируемых приоритетных сельскохозяйственных культур по Аршалынскому району на 2013 год
  kaz: Аршалы ауданы бойынша 2013 жылы субсидия алушылардың тізіміне қосуға арналған өтінімдерді ұсыну мерзімдерін және субсидияланатын басым ауыл шаруашылығы дақылдарының әрбір түрі бойынша оңтайлы себу мерзімдерін анықтау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-04-22
approved_by:
- '152005000001'
version_date:
  kaz: 2013-04-22
  rus: 2013-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/72473/kaz/22.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72473/rus/22.04.2013
