act_code: '223607'
requisite: Постановление акимата города Темиртау Карагандинской области от 1 апреля 2026 года № 13/51
title:
  rus: Об утверждении Положения ГУ «Отдел жилищной инспекции города Темиртау» в новой редакции
  kaz: «Теміртау қаласының тұрғын үй инспекциясы бөлімі» ММ-нің Ережесін жаңа редакцияда бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2026-04-01
approved_by:
- '160005000001'
version_date:
  kaz: 2026-09-14
  rus: 2026-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/223607/kaz/14.09.2026
  rus: https://zan.gov.kz/client/#!/doc/223607/rus/14.09.2026
caused_by:
  code: '230055'
  requisite: Постановление акимата города Темиртау Карагандинской области от 14 сентября 2026 года № 37/1
  title:
    rus: Об утверждении Положения ГУ «Отдел жилищной инспекции города Темиртау» в новой редакции
    kaz: «Теміртау қаласының тұрғын үй инспекциясы бөлімі» ММ-нің Ережесін жаңа редакцияда бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/230055/rus
