act_code: '37758'
requisite: Атырау облысының Мақат ауданы әкімиятының 2007 жылғы 19 желтоқсандағы № 203 қаулысы. Атырау облыстық Мақат ауданының Әділет басқармасында 2007 жылғы 28 желтоқсанда № 4-7-66 болып тіркелді
title:
  rus: Аудандық білім беру бөлімінің мемлекеттік қызмет көрсетудің стандарттарын бекіту туралы
  kaz: Аудандық білім беру бөлімінің мемлекеттік қызмет көрсетудің стандарттарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-12-19
approved_by:
- '156006000001'
version_date:
  kaz: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37758/kaz/19.12.2007
