act_code: '17812'
requisite: Алматы облысы Сарқан ауданы әкімиятының 2003 жылғы 14 қазандағы N 117 қаулысы. Алматы облыстық Әділет басқармасында 2003 жылы 20 қарашада N 1372 тіркелді. Күші жойылды - Алматы облысы Сарқан аудандық әкімдігінің 2011 жылғы 13 желтоқсандағы N 462 қаулысымен
title:
  rus: Аудан аумағында шыққан өртті сөндіруді ұйымдастыру, басқа төтенше жағдайлар зардаптарын жою туралы
  kaz: Аудан аумағында шыққан өртті сөндіруді ұйымдастыру, басқа төтенше жағдайлар зардаптарын жою туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-10-13
approved_by:
- '154005000001'
version_date:
  kaz: 2003-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/17812/kaz/13.10.2003
