act_code: '39231'
requisite: Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2008 жылғы 28 наурыздағы N 6-75/IV шешімі және Оңтүстік Қазақстан облысы Сайрам ауданы әкімдігінің 2008 жылғы 28 наурыздағы N 4 қаулысы. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2008 жылғы 28 сәуірде N 14-10-92 тіркелді
title:
  rus: Жеке тұрғын үй құрылысын жүргізу үшін Қарабұлақ ауыл округіне жер телімін беру және елді мекеннің шегін өзгерту туралы
  kaz: Жеке тұрғын үй құрылысын жүргізу үшін Қарабұлақ ауыл округіне жер телімін беру және елді мекеннің шегін өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2008-03-28
approved_by:
- '166008000001'
- '166008000002'
version_date:
  kaz: 2008-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/39231/kaz/28.03.2008
