act_code: '14817'
requisite: Постановление акимата Уланского района от 10 февраля 2003 года № 436. Зарегистрировано Управлением юстиции Восточно-Казахстанской области 13 марта 2003 года за № 1149. Утратило силу на основании письма акимата Уланского района от 5 апреля 2007 года № 20
title:
  rus: О создании районной бюджетной комиссии
  kaz: О создании районной бюджетной комиссии
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-02-10
approved_by:
- '157018000001'
version_date:
  rus: 2003-02-10
source:
  rus: https://zan.gov.kz/client/#!/doc/14817/rus/10.02.2003
