act_code: '160204'
requisite: Постановление акимата города Алматы от 12 ноября 2021 года № 4/577. Зарегистрировано Министерством юстиции Республики Казахстан 12 ноября 2021 года № 25129
title:
  rus: Об утверждении объема полной компенсации расходов за питание воспитанников частных дошкольных организаций и филиалов частных дошкольных организаций города Алматы, созданных в 2021 году с размещенным государственным образовательным заказом, на 2021 год
  kaz: 2021 жылға арналған мемлекеттік білім беру тапсырысы орналастырылып, 2021 жылы құрылған Алматы қаласының жеке меншік мектепке дейінгі ұйымдары және жеке меншік мектепке дейінгі ұйымдар филиалдарының тәрбиеленушілерін тамақтандыруға кететін шығындарының толық өтемақы  көлемін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2021-11-12
approved_by:
- '155000000001'
version_date:
  kaz: 2021-11-12
  rus: 2021-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/160204/kaz/12.11.2021
  rus: https://zan.gov.kz/client/#!/doc/160204/rus/12.11.2021
