act_code: '88095'
requisite: Постановление акимата города Павлодара Павлодарской области от 4 марта 2015 года № 268/5. Зарегистрировано Департаментом юстиции Павлодарской области 30 марта 2015 года № 4400. Утратило силу постановлением акимата города Павлодара Павлодарской области от 10 апреля 2017 года № 391/12 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении  Положения государственного учреждения «Отдел образования города Павлодара»
  kaz: «Павлодар қаласы білім беру бөлімі» мемлекеттік мекемесінің Ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2015-03-04
approved_by:
- '164002000001'
version_date:
  kaz: 2015-03-04
  rus: 2015-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/88095/kaz/04.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88095/rus/04.03.2015
