act_code: '2128'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 1998 года № 1397. Утратило силу постановлением Правительства Республики Казахстан от 19 января 2002 года № 62
title:
  rus: О сборах за проезд автотранспортных средств по территории Республики Казахстан
  kaz: Қазақстан Республикасының аумағы бойынша автокөлік құралдарының жүріп өтуі үшін алынатын алымдар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-12-31
approved_by:
- '103000000000'
version_date:
  rus: 1999-05-25
source:
  rus: https://zan.gov.kz/client/#!/doc/2128/rus/25.05.1999
caused_by:
  code: '3030'
  requisite: Постановление Правительства Республики Казахстан от 26 мая 1999 года № 643. Утратило силу постановлением Правительства Республики Казахстан от 13 ноября 2014 года № 1196
  title:
    rus: Отдельные вопросы регулирования проезда автотранспортных средств по территории Республики Казахстан
    kaz: Қазақстан Республикасының аумағы бойынша автокөлік құралдарының жүріп өтуін реттеудің жекелеген мәселелері
  link: https://zan.gov.kz/client/#!/doc/3030/rus
