act_code: '3164'
requisite: Постановление Правительства Республики Казахстан от 14 февраля 1996 г. N 196. Утратило силу - постановлением Правительства РК от 30 апреля 1997 г. N 689 ~P970689.
title:
  rus: Об утверждении Положения об Аппарате Правительства Республики Казахстан
  kaz: Қазақстан Республикасы Үкiметiнiң аппараты туралы ереже жөнiнде
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1996-02-14
approved_by:
- '103000000000'
version_date:
  rus: 1996-05-16
source:
  rus: https://zan.gov.kz/client/#!/doc/3164/rus/16.05.1996
