act_code: '2087'
requisite: Постановление Правительства Республики Казахстан от 20 июня 1997 года № 999. Утратило силу постановлением Правительства Республики Казахстан от 26 декабря 2001 года № 1705
title:
  rus: Об утверждении Положения о порядке проведения налоговой экспертизы контрактов на недропользование
  kaz: Жер қойнауын пайдалануға арналған келiсiм-шарттарға салық сараптамасын жүргiзудiң тәртiбi туралы ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1997-06-19
approved_by:
- '103000000000'
version_date:
  rus: 1997-06-19
source:
  rus: https://zan.gov.kz/client/#!/doc/2087/rus/19.06.1997
