act_code: '37731'
requisite: Постановление Правительства Республики Казахстан от 19 февраля 2008 года N 153
title:
  rus: Об утверждении Правил бюджетного субсидирования развития систем управления производством сельскохозяйственной продукции на 2008 год
  kaz: Ауыл шаруашылығы өнімдері өндірісін басқару жүйелерін дамытуды бюджеттік субсидиялаудың 2008 жылға арналған ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2008-02-19
approved_by:
- '103000000000'
version_date:
  kaz: 2008-02-19
  rus: 2008-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37731/kaz/19.02.2008
  rus: https://zan.gov.kz/client/#!/doc/37731/rus/19.02.2008
