act_code: '1066'
requisite: Постановление Правительства Республики Казахстан от 3 июля 1998 года № 634. Утратило силу постановлением Правительства Республики Казахстан от 11 января 2000 года № 45
title:
  rus: Вопросы Комитета по стандартизации, метрологии и сертификации Министерства энергетики, индустрии и торговли Республики Казахстан
  kaz: Қазақстан Республикасының Энергетика, индустрия және сауда министрлiгi Стандарттау, метрология және сертификаттау жөнiндегi комитетiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-07-02
approved_by:
- '103000000000'
version_date:
  rus: 1999-06-13
source:
  rus: https://zan.gov.kz/client/#!/doc/1066/rus/13.06.1999
caused_by:
  code: '3236'
  requisite: Постановление Правительства Республики Казахстан от 14 июня 1999 года № 743
  title:
    rus: О создании Республиканского государственного предприятия "Казахстанский центр стандартизации, метрологии и сертификации"
    kaz: '"Қазақстан стандарттау, метрология және сертификаттау орталығы" республикалық мемлекеттiк кәсіпорнын құру туралы'
  link: https://zan.gov.kz/client/#!/doc/3236/rus
