act_code: '4370'
requisite: Постановление Правления Национального Банка Республики Казахстан от 23 мая 1997 г. N 220. Зарегистрирован в Министерстве юстиции 30 июля 1997 г. N 339. Утратило силу - постановлением Правления Национального Банка РК от 3.08.2002 г. № 304
title:
  rus: О Правилах проведения экспертизы Национальным Банком Республики Казахстан проспектов эмиссий ценных бумаг банков и их отчетов об итогах выпуска и размещения ценных бумаг
  kaz: '"Қазақстан Республикасы Ұлттық Банкiнiң банктердiң бағалы қағаздар эмиссиясының жобаларына және олардың бағалы қағаздарды шығару мен орналастыру қорытындылары туралы есептерiне сараптама жүргiзу тәртiбi туралы" Ереже жөнiнде'
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРАВ
approved_on: 1997-05-22
approved_by:
- '117000000000'
version_date:
  rus: 1997-05-22
source:
  rus: https://zan.gov.kz/client/#!/doc/4370/rus/22.05.1997
