act_code: '99337'
requisite: Постановление Аральского районного акимата Кызылординской области от 27 января 2016 года № 16-қ. Зарегистрировано Департаментом юстиции Кызылординской области 11 февраля 2016 года № 5346. Утратило силу постановлением акимата Сырдарьинского района Кызылординской области от 25.04.2016 № 84-қ.
title:
  rus: Об установлении дополнительного перечня лиц, относящихся к целевым группам, проживающих на территории Аральского района на 2016 год
  kaz: 2016 жылға арналған Арал ауданының аумағында тұратын нысаналы топтарға жататын адамдардың қосымша тізбесін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-01-27
approved_by:
- '161003000001'
version_date:
  kaz: 2016-01-27
  rus: 2016-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/99337/kaz/27.01.2016
  rus: https://zan.gov.kz/client/#!/doc/99337/rus/27.01.2016
