act_code: '39146'
requisite: Постановление Правительства Республики Казахстан от 24 апреля 2008 года № 387
title:
  rus: О некоторых вопросах Министерства финансов Республики Казахстан
  kaz: Қазақстан Республикасы Қаржы министрлігінің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2008-04-24
approved_by:
- '103000000000'
version_date:
  kaz: 2014-04-02
  rus: 2014-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/39146/kaz/02.04.2014
  rus: https://zan.gov.kz/client/#!/doc/39146/rus/02.04.2014
caused_by:
  code: '78425'
  requisite: Постановление Правительства Республики Казахстан от 2 апреля 2014 года № 300
  title:
    rus: Об образовании Комитета по государственным закупкам Министерства финансов Республики Казахстан и о внесении изменений и дополнений в постановление Правительства Республики Казахстан от 24 апреля 2008 года № 387 "О некоторых вопросах Министерства финансов Республики Казахстан"
    kaz: Қазақстан Республикасы Қаржы министрлігінің мемлекеттік сатып алу комитетін құру туралы және "Қазақстан Республикасы Қаржы министрлiгiнiң кейбiр мәселелерi туралы" Қазақстан Республикасы Үкiметiнiң 2008 жылғы 24 сәуiрдегi № 387 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/78425/rus
