act_code: '39146'
requisite: Постановление Правительства Республики Казахстан от 24 апреля 2008 года № 387
title:
  rus: О некоторых вопросах Министерства финансов Республики Казахстан
  kaz: Қазақстан Республикасы Қаржы министрлігінің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2008-04-24
approved_by:
- '103000000000'
version_date:
  kaz: 2021-06-22
  rus: 2021-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/39146/kaz/22.06.2021
  rus: https://zan.gov.kz/client/#!/doc/39146/rus/22.06.2021
caused_by:
  code: '156568'
  requisite: Постановление Правительства Республики Казахстан от 22 июня 2021 года № 427
  title:
    rus: О внесении дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/156568/rus
