act_code: '102130'
requisite: Постановление Правления Национального Банка Республики Казахстан от 29 февраля 2016 года № 69. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 апреля 2016 года № 13606. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 28 декабря 2018 года № 317 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении факторов, влияющих на ухудшение финансового положения банка и банковского конгломерата, а также утверждении Правил применения мер раннего реагирования и методики определения факторов, влияющих на ухудшение финансового положения банка и банковского конгломерата
  kaz: Банктің және банк конгломератының қаржылық жай-күйінің нашарлауына әсер ететін факторларды белгілеу, сондай-ақ Ертерек ден қою шараларын қолдану қағидаларын және банк пен банк конгломератының қаржылық жай-күйінің нашарлауына әсер ететін факторларды анықтау әдістемесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2016-02-29
approved_by:
- '117000000000'
version_date:
  kaz: 2016-02-29
  rus: 2016-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/102130/kaz/29.02.2016
  rus: https://zan.gov.kz/client/#!/doc/102130/rus/29.02.2016
