act_code: '165699'
requisite: Постановление акимата района Тереңкөл Павлодарской области от 14 марта 2022 года № 55
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат акима района Тереңкөл»
  kaz: «Тереңкөл ауданы әкімінің аппараты» мемлекеттік мекемесі жөніндегі ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2022-03-14
approved_by:
- '164008000001'
version_date:
  kaz: 2022-10-28
  rus: 2022-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/165699/kaz/28.10.2022
  rus: https://zan.gov.kz/client/#!/doc/165699/rus/28.10.2022
caused_by:
  code: '173473'
  requisite: Постановление акимата района Тереңкөл Павлодарской области от 28 октября 2022 года № 303/7
  title:
    rus: О внесении изменения в постановление акимата района Тереңкөл от 14 марта 2022 года № 55 «Об утверждении Положения о государственном учреждении «Аппарат акима района Тереңкөл»
    kaz: Тереңкөл ауданы әкімдігінің 2022 жылғы 14 наурыздағы № 55 «Тереңкөл ауданы әкімінің аппараты» мемлекеттік мекемесі жөніндегі ережені бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173473/rus
