act_code: '63947'
requisite: Постановление Правительства Республики Казахстан от 11 марта 2012 года № 307. Утратило силу постановлением Правительства Республики Казахстан от 20 апреля 2018 года № 208 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил формирования финансового обеспечения, представления документов, подтверждающих наличие такого обеспечения у управляющей компании специальной экономической зоны или автономного кластерного фонда, а также возмещения потерь бюджета за счет средств финансового обеспечения
  kaz: Қаржылық қамтамасыз етуді қалыптастыру, арнайы экономикалық аймақтың басқарушы компаниясында немесе дербес кластерлік қорда осындай қамтамасыз етудің болуын растайтын құжаттарды ұсыну, сондай-ақ қаржылық қамтамасыз ету қаражаты есебінен бюджет шығындарын өтеу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2012-03-11
approved_by:
- '103000000000'
version_date:
  kaz: 2012-03-11
  rus: 2012-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/63947/kaz/11.03.2012
  rus: https://zan.gov.kz/client/#!/doc/63947/rus/11.03.2012
