act_code: '50238'
requisite: Постановление акимата Алматинской области от 22 декабря 2009 года № 227. Зарегистрировано Департаментом юстиции Алматинской области 27 января 2010 года № 2044. Утратило силу постановлением акимата Алматинской области от 02 июня 2014 года № 196
title:
  rus: Об утверждении перечня рыбохозяйственных водоемов местного значения
  kaz: Жергілікті маңызы бар балық шаруашылығы су тоғандарының тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-12-22
approved_by:
- '154000000001'
version_date:
  kaz: 2012-04-02
  rus: 2012-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/50238/kaz/02.04.2012
  rus: https://zan.gov.kz/client/#!/doc/50238/rus/02.04.2012
caused_by:
  code: '65599'
  requisite: Постановление акимата Алматинской области от 02 апреля 2012 года № 79. Зарегистрировано Департаментом юстиции Алматинской области 14 мая 2012 года за № 2091. Утратило силу постановлением акимата Алматинской области от 02 июня 2014 года № 196
  title:
    rus: О внесении дополнений в постановление акимата области от 22 декабря 2009 года N 227 "Об утверждении перечня рыбохозяйсвенных водоемов местного значения"
    kaz: Облыс әкімінің 2009 жылғы 22 желтоқсандағы "Жергілікті маңызы бар балық шаруашылығы су тоғандарының тізбесін бекіту туралы" N 227 қаулысына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65599/rus
