act_code: '1501'
requisite: Постановление Кабинета Министров Республики Казахстан от 2 декабря 1992 года № 1014. Утратило силу постановлением Правительства Республики Казахстан от 14 октября 1996 года № 1257
title:
  rus: Об обязательном страховании пассажиров в Республике Казахстан
  kaz: Қазақстан Республикасында жолаушыларды мiндеттi сақтандыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1992-12-02
approved_by:
- '103000000000'
version_date:
  rus: 1993-06-10
source:
  rus: https://zan.gov.kz/client/#!/doc/1501/rus/10.06.1993
