act_code: '2493'
requisite: Постановление Кабинета Министров Республики Казахстан от 9 октября 1992 года № 851. Утратил силу постановлением Правительства Республики Казахстан от 6 октября 2001 года № 1293
title:
  rus: Об утверждении Положения о порядке приобретения, проектирования, строительства (установки), эксплуатации на территории Республики Казахстан и ввоза из-за границы радиоэлектронных средств и высокочастотных устройств
  kaz: Қазақстан Республикасының аумағында радиоэлектрондық құралдарды және жоғары жиiлiктегi құрылғыларды алу, жобалау, жасау (орнату), пайдалану және шет елдерден әкелу тәртiбi туралы ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1992-10-09
approved_by:
- '103000000000'
version_date:
  rus: 1997-01-14
source:
  rus: https://zan.gov.kz/client/#!/doc/2493/rus/14.01.1997
caused_by:
  code: '82434'
  requisite: Постановление Правительства Республики Казахстан от 14 января 1997 г. N 60
  title:
    rus: О внесении дополнений в постановление Кабинета Министров Республики Казахстан от 9 октября 1992 г. N 851
    kaz: Қазақстан Республикасы Министрлер Кабинетiнiң 1992 жылғы 9 қазандағы N 851 қаулысына толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/82434/rus
