act_code: '44029'
requisite: Постановление Правления Национального Банка Республики Казахстан от 31 декабря 2008 года № 117. Зарегистрировано в Министерстве юстиции Республики Казахстан 3 февраля 2009 года № 5526. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 26 февраля 2018 года № 39 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении формы и содержания контрольного чека компьютерных систем, применяемых банками и организациями, осуществляющими отдельные виды банковских операций
  kaz: Банктер және банк операцияларының жекелеген түрлерін жүзеге асыратын ұйымдар қолданатын компьютер жүйелерінің бақылау чегінің нысанын және мазмұнын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-12-31
approved_by:
- '117000000000'
version_date:
  kaz: 2008-12-31
  rus: 2008-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/44029/kaz/31.12.2008
  rus: https://zan.gov.kz/client/#!/doc/44029/rus/31.12.2008
