act_code: '55567'
requisite: Алматы облысы Талдықорған қаласы әкімдігінің 2010 жылғы 25 қазандағы № 29-951 қаулысы. Алматы облысының Әділет департаменті Талдықорған қаласының Әділет басқармасында 2010 жылы 25 қарашада № 2-1-131 тіркелді. Күші жойылды - Алматы облысы Талдықорған қаласы әкімдігінің 2014 жылғы 08 желтоқсандағы № 36-1289 қаулысымен
title:
  rus: Эротикалық сипаттағы материалдар жариялайтын мерзімді баспасөз басылымдарын бөлшек саудада сату үшін әдейі бөлінген тұрақты үй-жайларды белгілеу туралы
  kaz: Эротикалық сипаттағы материалдар жариялайтын мерзімді баспасөз басылымдарын бөлшек саудада сату үшін әдейі бөлінген тұрақты үй-жайларды белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-10-25
approved_by:
- '154002000001'
version_date:
  kaz: 2014-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/55567/kaz/08.12.2014
