act_code: '136795'
requisite: Постановление Правления Национального Банка Республики Казахстан от 28 ноября 2019 года № 223. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 декабря 2019 года № 19701. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 2 декабря 2025 года № 85 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня, форм, сроков представления отчетности о выполнении пруденциальных нормативов страховой (перестраховочной) организацией, страховой группой и исламской страховой (перестраховочной) организацией и Правил ее представления
  kaz: Сақтандыру (қайта сақтандыру) ұйымының, сақтандыру тобының және исламдық сақтандыру (қайта сақтандыру) ұйымының пруденциялық нормативтерді орындауы туралы есептіліктің тізбесін, нысандарын, ұсыну мерзімдерін және оны ұсыну қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2019-11-28
approved_by:
- '117000000000'
version_date:
  kaz: 2022-02-28
  rus: 2022-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/136795/kaz/28.02.2022
  rus: https://zan.gov.kz/client/#!/doc/136795/rus/28.02.2022
caused_by:
  code: '165266'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 28 февраля 2022 года № 15. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 марта 2022 года № 27129
  title:
    rus: О внесении изменений и дополнения в некоторые постановления Правления Национального Банка Республики Казахстан по вопросам представления отчетности участниками страхового рынка и рынка ценных бумаг
    kaz: Қазақстан Республикасы Ұлттық Банкі Басқармасының кейбір қаулыларына сақтандыру нарығына және бағалы қағаздар нарығына қатысушылардың есептілікті ұсынуы мәселелері бойынша өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165266/rus
