act_code: '71986'
requisite: Постановление акимата Сырымского района Западно-Казахстанской области от 11 марта 2013 года № 38. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 11 апреля 2013 года № 3242. Утратило силу постановлением акимата Сырымского района Западно-Казахстанской области от 27 мая 2013 года № 80
title:
  rus: Об утверждении регламентов оказания государственных услуг в сфере строительства
  kaz: Құрылыс саласындағы мемлекеттiк қызмет көрсету регламенттерiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2013-03-11
approved_by:
- '159011000001'
version_date:
  kaz: 2013-03-11
  rus: 2013-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/71986/kaz/11.03.2013
  rus: https://zan.gov.kz/client/#!/doc/71986/rus/11.03.2013
