act_code: '24911'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 25 июня 2005 года N 230. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 июля 2005 года за N 3755. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 2 октября 2008 года № 145
title:
  rus: Об утверждении Перечня оффшорных зон для целей банковской и страховой деятельности, деятельности профессиональных участников рынка ценных бумаг и иных лицензируемых видов деятельности на рынке ценных бумаг, деятельности накопительных пенсионных фондов и акционерных инвестиционных фондов
  kaz: Банктік және сақтандыру қызметінің, бағалы қағаздар рыногына кәсіби қатысушылардың және бағалы қағаздар рыногында лицензияланатын басқа да қызмет түрлерінің, жинақтаушы зейнетақы қорлары мен акционерлік инвестициялық қорлар қызметінің мақсаттары үшін оффшорлық аймақтардың тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2005-06-25
approved_by:
- '109000000000'
version_date:
  kaz: 2005-06-25
  rus: 2005-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/24911/kaz/25.06.2005
  rus: https://zan.gov.kz/client/#!/doc/24911/rus/25.06.2005
