act_code: '36843'
requisite: Шығыс Қазақстан облысы Тарбағатай ауданы әкімдігінің 2007 жылғы 12 желтоқсандағы № 445 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық Әділет басқармасында 2008 жылғы 5 қаңтарда № 5-16-46 болып тіркелді. Күші жойылды - 2009 жылғы 5 маусымдағы № 1240 Тарбағатай ауданы әкімінің аппаратының хаты негізінде, қабылданған мерзімінің бітуіне байланысты
title:
  rus: Қызыл кесік ауылдық округіне қарасты Қуан елді мекенінде қой-ешкі малдарынан бруцеллез ауруының шығуына байланысты шектеу қою туралы
  kaz: Қызыл кесік ауылдық округіне қарасты Қуан елді мекенінде қой-ешкі малдарынан бруцеллез ауруының шығуына байланысты шектеу қою туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-12-12
approved_by:
- '157017000001'
version_date:
  kaz: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/36843/kaz/12.12.2007
