act_code: '92207'
requisite: Постановление от 22.07.2015 №91, Акимат Кызылординской области. Утратило силу постановлением акимата Кызылординской области от 19.05.2016 N 461.
title:
  rus: Об утверждении Положения государственного учреждения "Управление сельского хозяйства Кызылординской области"
  kaz: '"Қызылорда облысының ауыл шаруашылығы басқармасы" мемлекеттік мекемесінің Ережесін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-07-22
approved_by:
- '161000000001'
version_date:
  kaz: 2015-07-22
  rus: 2015-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/92207/kaz/22.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92207/rus/22.07.2015
