act_code: '73025'
requisite: Постановление акимата Тарановского района Костанайской области от 27 мая 2013 года № 198. Зарегистрировано Департаментом юстиции Костанайской области 14 июня 2013 года № 4152
title:
  rus: Об определении сроков предоставления заявки на включение в список получателей субсидий и оптимальных сроков сева субсидируемых приоритетных сельскохозяйственных культур в 2013 году по Тарановскому району
  kaz: 2013 жылы Таран ауданы бойынша субсидия алушылардың тізіміне қосуға арналған өтінімдерді ұсыну мерзімдерін және субсидияланатын басым ауыл шаруашылығы дақылдарын оңтайлы себу мерзімдерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-05-27
approved_by:
- '162016000001'
version_date:
  kaz: 2013-05-27
  rus: 2013-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/73025/kaz/27.05.2013
  rus: https://zan.gov.kz/client/#!/doc/73025/rus/27.05.2013
