act_code: '163635'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 2021 года № 988
title:
  rus: Об утверждении Правил определения предельных аукционных цен на электрическую энергию, произведенную путем энергетической утилизации отходов, и индексации аукционных цен
  kaz: Қалдықтарды энергетикалық кәдеге жарату арқылы өндірілген электр энергиясына шекті аукциондық бағаларды айқындау және аукциондық бағаларды индекстеу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2021-12-31
approved_by:
- '103000000000'
version_date:
  kaz: 2025-07-01
  rus: 2025-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/163635/kaz/01.07.2025
  rus: https://zan.gov.kz/client/#!/doc/163635/rus/01.07.2025
caused_by:
  code: '211857'
  requisite: Постановление Правительства Республики Казахстан от 1 июля 2025 года № 496
  title:
    rus: О внесении изменений в постановление Правительства Республики Казахстан от 31 декабря 2021 года № 988 «Об утверждении Правил определения предельных аукционных цен на электрическую энергию, произведенную путем энергетической утилизации отходов, и индексации аукционных цен»
    kaz: «Қалдықтарды энергетикалық кәдеге жарату арқылы өндірілген электр энергиясына шекті аукциондық бағаларды айқындау және аукциондық бағаларды индекстеу қағидаларын бекіту туралы» Қазақстан Республикасы Үкіметінің 2021 жылғы 31 желтоқсандағы № 988 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211857/rus
