act_code: '53566'
requisite: Постановление Правительства Республики Казахстан от 20 июля 2010 года № 739. Утратило силу постановлением Правительства Республики Казахстан от 3 июля 2025 года № 506 (вводится в действие по истечении десяти календарных дней со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил регистрации и учета государственных и гарантированных государством займов, займов под поручительство государства, государственных гарантий, государственных гарантий по поддержке экспорта и поручительств государства
  kaz: Мемлекеттік және мемлекет кепілдік берген қарыздарды, мемлекет кепілгерлігімен берілетін қарыздарды, мемлекеттік кепілдіктерді, экспортты қолдау бойынша мемлекеттік кепілдіктер мен мемлекет кепілгерліктерін тіркеу және есепке алу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2010-07-20
approved_by:
- '103000000000'
version_date:
  kaz: 2010-07-20
  rus: 2010-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/53566/kaz/20.07.2010
  rus: https://zan.gov.kz/client/#!/doc/53566/rus/20.07.2010
