act_code: '60440'
requisite: Нормативное постановление Счетного комитета по контролю за исполнением республиканского бюджета от 12 августа 2011 года № 1-НП. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 сентября 2011 года № 7164. Утратило силу нормативным постановлением Счетного комитета по контролю за исполнением республиканского бюджета от 28 ноября 2015 года № 11-НҚ
title:
  rus: О некоторых вопросах внешнего государственного финансового контроля
  kaz: Сыртқы мемлекеттік қаржылық бақылаудың кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-08-12
approved_by:
- '115000000000'
version_date:
  kaz: 2014-02-11
  rus: 2014-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/60440/kaz/11.02.2014
  rus: https://zan.gov.kz/client/#!/doc/60440/rus/11.02.2014
caused_by:
  code: '78530'
  requisite: Нормативное постановление Счетного комитета по контролю за исполнением республиканского бюджета от 11 февраля 2014 года № 1-НҚ. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 марта 2014 года № 9206. Утратило силу нормативным постановлением Счетного комитета по контролю за исполнением республиканского бюджета от 28 ноября 2015 года № 11-НҚ
  title:
    rus: О внесении изменений в нормативное постановление Счетного комитета по контролю за исполнением республиканского бюджета от 12 августа 2011 года № 1-НП "О некоторых вопросах внешнего государственного финансового контроля"
    kaz: '"Сыртқы мемлекеттік қаржылық бақылаудың кейбір мәселелері туралы" Республикалық бюджеттің атқарылуын бақылау жөніндегі есеп комитетінің 2011 жылғы 12 тамыздағы № 1-НП нормативтік қаулысына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/78530/rus
