act_code: '52448'
requisite: Постановление акимата г.Кокшетау Акмолинской области от 16 апреля 2010 года № A-4/547. Зарегистрировано Управлением юстиции г.Кокшетау Акмолинской области 11 мая 2010 года № 1-1-122. Утратило силу - постановлением акимата города Кокшетау Акмолинской области от 16 марта 2011 года № А-3/526
title:
  rus: Об организации и обеспечении очередного призыва граждан на срочную воинскую службу в апреле-июне и октябре-декабре 2010 года
  kaz: 2010 жылдың сәуір-маусымында және қазан-желтоқсанында азаматтарды мерзімді әскери қызметке кезекті шақыруды ұйымдастыру және қамтамасыз ету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-04-16
approved_by:
- '152002000001'
version_date:
  kaz: 2010-04-16
  rus: 2010-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/52448/kaz/16.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52448/rus/16.04.2010
