act_code: '49222'
requisite: Бірлескен Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2009 жылғы 30 қазандағы N 25-185-IV шешімі және Оңтүстік Қазақстан облысы Мақтаарал ауданы әкімдігінің 2009 жылғы 21 тамыздағы N 761 қаулысы. Оңтүстік Қазақстан облысы Мақтаарал ауданы Әділет басқармасында 2009 жылғы 10 желтоқсанда N 14-7-109 тіркелді
title:
  rus: Аудандағы жекелеген елді мекендердің шекараларын белгілеу туралы
  kaz: Аудандағы жекелеген елді мекендердің шекараларын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2009-10-30
approved_by:
- '166005000001'
- '166005000002'
version_date:
  kaz: 2009-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/49222/kaz/30.10.2009
