act_code: '67444'
requisite: Постановление Правительства Республики Казахстан от 5 сентября 2012 года № 1142
title:
  rus: О создании Совета по конкурентоспособности при Правительстве Республики Казахстан
  kaz: Қазақстан Республикасы Үкіметінің жанынан Бәсекеге қабілеттілік жөніндегі кеңес құру туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2012-09-05
approved_by:
- '103000000000'
version_date:
  kaz: 2013-03-11
  rus: 2013-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/67444/kaz/11.03.2013
  rus: https://zan.gov.kz/client/#!/doc/67444/rus/11.03.2013
caused_by:
  code: '71517'
