act_code: '207372'
requisite: Постановление Правления Национального Банка Республики Казахстан от 20 февраля 2025 года № 11. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 февраля 2025 года № 35749
title:
  rus: Об установлении пределов отклонения курса покупки от курса продажи иностранной валюты за тенге по операциям, проводимым через обменные пункты
  kaz: Айырбастау пункттері арқылы жүргізілетін операциялар бойынша шетел валютасын теңгеге сатып алу бағамының сату бағамынан ауытқу шектерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-02-20
approved_by:
- '117000000000'
version_date:
  kaz: 2025-02-20
  rus: 2025-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/207372/kaz/20.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207372/rus/20.02.2025
