act_code: '39165'
requisite: Постановление акимата Иртышского района Павлодарской области от 25 марта 2008 года № 60/2. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 24 апреля 2008 года № 12-7-67
title:
  rus: О пособиях семьям, воспитывающим и обучающим на дому детей-инвалидов
  kaz: Үйде тәрбиеленіп және оқып жатқан мүгедек-балалар отбасының жәрдемақылары туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-03-25
approved_by:
- '164007000001'
version_date:
  kaz: 2008-03-25
  rus: 2008-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/39165/kaz/25.03.2008
  rus: https://zan.gov.kz/client/#!/doc/39165/rus/25.03.2008
