act_code: '163238'
requisite: Совместные постановление акимата Жамбылской области от 13 декабря 2021 года № 291 и решение Жамбылского областного маслихата от 13 декабря 2021 года № 12-9. Зарегистрированы в Министерстве юстиции Республики Казахстан 11 января 2022 года № 26441
title:
  rus: Об изменении и установлении границы Каратобинского сельского округа Жамбылского района Жамбылской области
  kaz: Жамбыл облысы Жамбыл ауданы Қаратөбе ауылдық округінің шекарасын өзгерту және белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2021-12-13
approved_by:
- '158000000001'
- '158000000002'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/163238/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163238/rus/13.12.2021
