act_code: '21789'
requisite: Жамбыл облысы әкімиятының 2004 жылғы 30 қыркүйектегі № 251 қаулысы. Жамбыл облыстық әділет департаментінде 2004 жылғы 5 қарашада 1490 нөмірімен тіркелді. Қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
title:
  rus: Металл сынықтарын өткізуге құқығы бар мамандандырылған қызмет көрсететін ұйымдардың тізбесін бекіту туралы
  kaz: Металл сынықтарын өткізуге құқығы бар мамандандырылған қызмет көрсететін ұйымдардың тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-09-29
approved_by:
- '158000000001'
version_date:
  kaz: 2005-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/21789/kaz/24.02.2005
caused_by:
  code: '23227'
  requisite: Жамбыл облысы әкімиятының 2005 жылғы 24 ақпандағы № 48 қаулысы. Жамбыл облыстық әділет департаментінде 2005 жылғы 18 наурызда 1584 нөмірімен тіркелді. Қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
  title:
    rus: Жамбыл облысы әкімиятының 2004 жылғы 30 қыркүйектегі № 251 "Металл сынықтарын өткізуге құқығы бар мамандандырылған қызмет көрсететін ұйымдардың тізбесін бекіту туралы" қаулысына толықтыру енгізу туралы
    kaz: Жамбыл облысы әкімиятының 2004 жылғы 30 қыркүйектегі № 251 "Металл сынықтарын өткізуге құқығы бар мамандандырылған қызмет көрсететін ұйымдардың тізбесін бекіту туралы" қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/23227/rus
