act_code: '16616'
requisite: Постановление Правления Национального Банка Республики Казахстан от 4 июля 2003 года N 217. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 августа 2003 года N 2443. Утратило силу - постановлением Правления Агентства РК по регулированию и надзору фин.рынка и фин.организаций от 30 июля 2005 года N 268 (V053832)(вводится в действие по истечении 14 дней со дня гос.регистрации в МЮ РК)
title:
  rus: Об утверждении Правил государственной регистрации выпуска объявленных акций, утверждения отчета об итогах размещения акций и аннулирования выпуска акций
  kaz: Жарияланған акциялар шығарылымын мемлекеттiк тiркеу, акцияларды орналастыру қорытындылары туралы есептi бекiту және акциялар шығарылымын жою ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2003-07-03
approved_by:
- '117000000000'
version_date:
  kaz: 2003-07-03
  rus: 2003-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/16616/kaz/03.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16616/rus/03.07.2003
