act_code: '1782'
requisite: Постановление Правительства Республики Казахстан от 31 октября 1997 года № 1474. Утратило силу постановлением Правительства Республики Казахстан от 29 апреля 1999 года № 499
title:
  rus: Об утверждении Положения и структуры Министерства информации и общественного согласия Республики Казахстан (МИОС)
  kaz: Қазақстан Республикасы Ақпарат және қоғамдық келiсiм министрлiгiнiң (АҚКМ) ережесi мен құрылымын бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1997-10-31
approved_by:
- '103000000000'
version_date:
  rus: 1998-12-29
source:
  rus: https://zan.gov.kz/client/#!/doc/1782/rus/29.12.1998
caused_by:
  code: '1878'
  requisite: Постановление Правительства Республики Казахстан от 29 декабря 1998 года N 1348
  title:
    rus: О внесении изменений в некоторые решения Правительства Республики Казахстан и признании утратившим силу постановления Правительства Республики Казахстан от 19 ноября 1996 года N 1403
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер енгізу және Қазақстан Республикасы Үкіметінің 1996 жылғы 19 қарашадағы N 1403 қаулысының күші жойылған деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/1878/rus
