act_code: '44012'
requisite: Шығыс Қазақстан облысы Тарбағатай аудандық әкімдігінің 2008 жылғы 30 желтоқсандағы № 531 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық әділет басқармасында 2009 жылғы 27 қаңтарда № 5-16-67 тіркелді. Күші жойылды - Тарбағатай аудандық әкімдігінің 2010 жылғы 25 қаңтардағы № 17 қаулысымен
title:
  rus: Ауданда 2009 жылы ақылы қоғамдық жұмысты ұйымдастыру туралы
  kaz: Ауданда 2009 жылы ақылы қоғамдық жұмысты ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-12-30
approved_by:
- '157017000001'
version_date:
  kaz: 2008-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/44012/kaz/30.12.2008
