act_code: '79966'
requisite: Постановление акимата города Усть-Каменогорска Восточно-Казахстанской области от 21 апреля 2014 года № 4852. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 мая 2014 года № 3314. Утратило силу - постановлением акимата города Усть-Каменогорска Восточно-Казахстанской области от 24 мая 2016 года № 369
title:
  rus: Об утверждении Положения о государственном учреждении "Отдел архитектуры и градостроительства города Усть-Каменогорска"
  kaz: '"Өскемен қаласының сәулет және қала құрылысы бөлімі" мемлекеттік мекемесі туралы Ережені бекіту туралы'
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2014-04-21
approved_by:
- '157002000001'
version_date:
  kaz: 2015-07-07
  rus: 2015-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/79966/kaz/07.07.2015
  rus: https://zan.gov.kz/client/#!/doc/79966/rus/07.07.2015
caused_by:
  code: '92488'
  requisite: Постановление акимата города Усть-Каменогорска Восточно-Казахстанской области от 7 июля 2015 года № 11919. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 августа 2015 года № 4086.  Утратило силу - постановлением акимата города Усть-Каменогорска Восточно-Казахстанской области от 24 мая 2016 года № 369
  title:
    rus: О внесении дополнения в постановление акимата города Усть-Каменогорска от 21 апреля 2014 года № 4852 «Об утверждении Положения о государственном учреждении «Отдел архитектуры и градостроительства города Усть-Каменогорска»
    kaz: Өскемен қаласы әкімдігінің 2014 жылғы 21 сәуірдегі № 4852 «Өскемен қаласының сәулет және қала құрылысы бөлімі» мемлекеттік мекемесі туралы Ережені бекіту туралы» қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92488/rus
