act_code: '28339'
requisite: Постановление акимата города Актау Мангистауской области от 24 мая 2006 года № 445. Зарегистрировано Департаментом юстиции Мангистауской области 14 июня 2006 года № 31
title:
  rus: Об утверждении Порядка отбора работодателей предлагающих организацию социальных рабочих мест для трудоустройства безработных из целевых групп
  kaz: Нысаналы топтардан жұмыссыздарды жұмысқа орналастыру үшін әлеуметтiк жұмыс орындарын ұйымдастыруды ұсынатын жұмыс берушілерді іріктеу Тәртібін  бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-05-24
approved_by:
- '163002000001'
version_date:
  kaz: 2010-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/28339/kaz/13.09.2010
caused_by:
  code: '55049'
  requisite: Постановление Актауского городского акимата от 13 сентября 2010 года № 864. Зарегистрировано Департаментом юстиции Мангистауской области 22 октября 2010 года № 11-1-140
  title:
    rus: О внесении изменения в постановление акимата города Актау от 24 мая 2006 года № 445 "Об утверждении Порядка отбора работадателей предлагающих организацию социальных рабочих мест для трудоустройства безработных из целевых групп"
    kaz: Ақтау қаласы әкімдігінің 2006 жылғы 24 мамырдағы № 445 "Нысаналы топтардан жұмыссыздарды жұмысқа орналастыру үшін әлеуметтік жұмыс орындарын ұйымдастыруды ұсынатын жұмыс берушілерді іріктеу Тәртібін бекіту туралы" қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55049/rus
