act_code: '17162'
requisite: Постановление Правительства Республики Казахстан от 8 октября 2003 года № 1037
title:
  rus: Об утверждении нормативов возмещения потерь сельскохозяйственного и лесохозяйственного производства, вызванных изъятием сельскохозяйственных и лесных угодий для использования их в целях, не связанных с ведением сельского и лесного хозяйства, и Правил возмещения потерь сельскохозяйственного производства с зачетом сумм, затрачиваемых на восстановление угодий, а также возмещения потерь и убытков лесохозяйственного производства
  kaz: Ауыл және орман шаруашылығын жүргiзуге байланысты емес мақсаттарға оларды пайдалану үшiн ауыл шаруашылығы және орман алқаптарын алып қоюдан туындаған ауыл шаруашылығы мен орман шаруашылығы өндiрiсiнiң шығындарын өтеу нормативтерiн және Алқаптарды қалпына келтiруге жұмсалатын сома есепке алынып, ауыл шаруашылығы өндiрiсiнiң шығындарын өтеу, сондай-ақ орман шаруашылығы өндірісінің шығындары мен залалдарын өтеу ережесiн бекiту туралы
form: ПОСТ
type_codes:
- НОРМ
- ПОСТ
- ПРАВ
approved_on: 2003-10-07
approved_by:
- '103000000000'
version_date:
  kaz: 2011-04-07
  rus: 2011-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/17162/kaz/07.04.2011
  rus: https://zan.gov.kz/client/#!/doc/17162/rus/07.04.2011
caused_by:
  code: '58214'
  requisite: Постановление Правительства Республики Казахстан от 7 апреля 2011 года № 402
  title:
    rus: О внесении дополнений и изменения в постановление Правительства Республики Казахстан от 8 октября 2003 года № 1037
    kaz: Қазақстан Республикасы Үкіметінің 2003 жылғы 8 қазандағы № 1037 қаулысына толықтырулар мен өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58214/rus
