act_code: '39980'
requisite: Постановление Правительства Республики Казахстан от 6 июня 2008 года № 541. Утратило силу постановлением Правительства Республики Казахстан от 30 января 2017 года № 29
title:
  rus: Об утверждении Технического регламента "Требования к безопасности плодов, овощей, корнеплодов и продуктов их переработки"
  kaz: '"Жемістер, көкөністер, түйнекжемістілер мен оларды қайта өңдеу өнімдерінің қауіпсіздігіне қойылатын талаптар" техникалық регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2008-06-06
approved_by:
- '103000000000'
version_date:
  kaz: 2008-06-06
  rus: 2008-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/39980/kaz/06.06.2008
  rus: https://zan.gov.kz/client/#!/doc/39980/rus/06.06.2008
