act_code: '91'
requisite: Постановление Правительства Республики Казахстан от 26 февраля 1998 года № 151. Утратило силу постановлением Правительства РК от 7 декабря 1998 года № 1249
title:
  rus: Вопросы Комитета по использованию воздушного пространства и деятельности гражданской авиации Министерства транспорта и коммуникаций Республики Казахстан
  kaz: Қазақстан Республикасының Көлiк және коммуникациялар министрлiгi Әуе кеңiстiгiн пайдалану және азаматтық авиация қызметi жөнiндегi комитетiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-02-26
approved_by:
- '103000000000'
version_date:
  rus: 1998-02-26
source:
  rus: https://zan.gov.kz/client/#!/doc/91/rus/26.02.1998
