act_code: '54720'
requisite: Постановление Правительства Республики Казахстан от 5 октября 2010 года № 1025
title:
  rus: О некоторых вопросах расширения территории государственного учреждения "Алакольский государственный природный заповедник" Комитета лесного и охотничьего хозяйства Министерства сельского хозяйства Республики Казахстан
  kaz: Қазақстан Республикасы Ауыл шаруашылығы министрлігі Орман және аңшылық шаруашылығы комитетінің "Алакөл мемлекеттік табиғи қорығы" мемлекеттік мекемесінің аумағын кеңейтудің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-10-05
approved_by:
- '103000000000'
version_date:
  kaz: 2010-10-05
  rus: 2010-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/54720/kaz/05.10.2010
  rus: https://zan.gov.kz/client/#!/doc/54720/rus/05.10.2010
