act_code: '213106'
requisite: Постановление акимата Чингирлауского района Западно-Казахстанской области от 4 августа 2025 года № 212
title:
  rus: Об утверждении Правил организации и проведения мероприятий по текущему или капитальному ремонту фасадов, кровли многоквартирных жилых домов, направленных на придание единого архитектурного облика населенным пунктам Чингирлауского района
  kaz: Шыңғырлау ауданының елді мекендеріне бірыңғай сәулеттік келбет беруге бағытталған, көппәтерлі тұрғын үйлердің қасбеттерін, шатырларын ағымдағы немесе күрделі жөндеу жөніндегі іс-шараларды ұйымдастыру және жүргізу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2025-08-04
approved_by:
- '159014000001'
version_date:
  kaz: 2025-08-04
  rus: 2025-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/213106/kaz/04.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213106/rus/04.08.2025
