act_code: '186658'
requisite: Постановление акимата города Шымкент от 19 июня 2023 года № 1443
title:
  rus: О создании и утверждении положения коммунального государственного учреждения «Управление по мобилизационной подготовке, территориальной и гражданской обороне города Шымкент»
  kaz: «Шымкент қаласының жұмылдыру дайындығы, аумақтық және азаматтық қорғаныс басқармасы» коммуналдық мемлекеттік мекемесін құру және ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2023-06-19
approved_by:
- '167000000001'
version_date:
  kaz: 2026-04-02
  rus: 2026-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/186658/kaz/02.04.2026
  rus: https://zan.gov.kz/client/#!/doc/186658/rus/02.04.2026
caused_by:
  code: '223876'
  requisite: Постановление акимата города Шымкент от 2 апреля 2026 года № 1244
  title:
    rus: О переименовании некоторых учреждений акимата города Шымкент
    kaz: Шымкент қаласы әкімдігінің кейбір мекемелерін қайта атау туралы
  link: https://zan.gov.kz/client/#!/doc/223876/rus
