act_code: '208417'
requisite: Постановление акимата Мангистауской области от 11 февраля 2025 года № 3 дсп
title:
  rus: Об утверждении Положения государственного учреждения «Управление по мобилизационной подготовке, территориальной и гражданской обороне Мангистауской области»
  kaz: «Маңғыстау облысының жұмылдыру дайындығы, аумақтық және азаматтық қорғаныс басқармасы» мемлекеттік мекемесінің Ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-02-11
approved_by:
- '163000000001'
version_date:
  kaz: 2025-02-11
  rus: 2025-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/208417/kaz/11.02.2025
  rus: https://zan.gov.kz/client/#!/doc/208417/rus/11.02.2025
