act_code: '225004'
requisite: Постановление акимата Аулиекольского района Костанайской области от 5 мая 2026 года № 65
title:
  rus: Об отмене постановления акимата Аулиекольского района от 30 декабря 2025 года № 234 «Об установлении публичного сервитута»
  kaz: Әулиекөл ауданы әкімнің 2025 жылғы 30 желтоқсандағы № 234 «Қауымдық сервитут белгілеу туралы» қаулысының күшін жою туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2026-05-05
approved_by:
- '162005000001'
version_date:
  kaz: 2026-05-05
  rus: 2026-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/225004/kaz/05.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225004/rus/05.05.2026
