act_code: '2214'
requisite: Постановление Национальной комиссии Республики Казахстан по ценным бумагам от 4 февраля 1999 года № 22. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 февраля 1999 года № 684. Утратил силу постановлением Правления Национального Банка Республики Казахстан от 4 июля 2003 года № 218
title:
  rus: О порядке приобретения и утраты статуса открытого народного акционерного общества
  kaz: Ашық халықтық акционерлiк қоғам мәртебесiн алудың және жоюдың тәртiбi тypaлы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1999-02-04
approved_by:
- '111000000000'
version_date:
  kaz: 1999-02-04
  rus: 1999-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/2214/kaz/04.02.1999
  rus: https://zan.gov.kz/client/#!/doc/2214/rus/04.02.1999
