act_code: '140075'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 24 февраля 2020 года № 8. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 марта 2020 года № 20095
title:
  rus: Об установлении Перечня офшорных зон для целей банковской и страховой деятельности, деятельности профессиональных участников рынка ценных бумаг и иных лицензируемых видов деятельности на рынке ценных бумаг, деятельности акционерных инвестиционных фондов и деятельности организаций, осуществляющих микрофинансовую деятельность
  kaz: Банктік және сақтандыру қызметінің, бағалы қағаздар рыногының кәсіби қатысушылары қызметінің және бағалы қағаздар рыногында лицензияланатын басқа да қызмет түрлерінің, акционерлік инвестициялық қорлар және микроқаржылық қызметті жүзеге асыратын ұйымдар қызметінің мақсаттары үшін офшорлық аймақтардың тізбесін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2020-02-24
approved_by:
- '135000000000'
version_date:
  kaz: 2022-02-21
  rus: 2022-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/140075/kaz/21.02.2022
  rus: https://zan.gov.kz/client/#!/doc/140075/rus/21.02.2022
caused_by:
  code: '164806'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 21 февраля 2022 года № 7. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 февраля 2022 года № 26922
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Республики Казахстан по вопросам кредитных бюро и регулирования банковской и микрофинансовой деятельности
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне кредиттік бюролар мен банктік және микроқаржылық қызметті реттеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164806/rus
