act_code: '11736'
requisite: Постановление Правительства Республики Казахстан от 2 апреля 2002 года N 388
title:
  rus: Вопросы отдельных государственных учреждений, подведомственных Министерству сельского хозяйства Республики Казахстан
  kaz: Қазақстан Республикасы Ауыл шаруашылығы министрлігіне ведомстволық бағыныстағы жекелеген мемлекеттік мекемелердің мәселелері
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2002-04-01
approved_by:
- '103000000000'
version_date:
  kaz: 2002-04-01
  rus: 2002-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/11736/kaz/01.04.2002
  rus: https://zan.gov.kz/client/#!/doc/11736/rus/01.04.2002
