act_code: '66639'
requisite: Совместное решение Бескарагайского районного маслихата от 11 июля 2012 года N 6/6-V и постановление Бескарагайского районного акимата Восточно-Казахстанской области от 10 июля 2012 года N 301. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 июля 2012 года за N 2589
title:
  rus: Об установлении границы (черты) села Донгулек Карабасского сельского округа
  kaz: Қарабас ауылдық округінің Дөңгелек ауылының шекарасын (шегін) белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2012-07-11
approved_by:
- '157009000001'
- '157009000002'
version_date:
  kaz: 2012-07-11
  rus: 2012-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/66639/kaz/11.07.2012
  rus: https://zan.gov.kz/client/#!/doc/66639/rus/11.07.2012
