act_code: '7165'
requisite: Постановление Правления Национального Банка Республики Казахстан от 24 августа 2000 года № 331. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 октября 2000 года № 1260. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 31 августа 2016 года № 205 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выпуска платежных карточек, а также требований к деятельности по обслуживанию операций с их использованием на территории Республики Казахстан
  kaz: Төлем карточкаларын шығару қағидаларын, сондай-ақ Қазақстан Республикасының аумағында оларды пайдалана отырып жүргізілетін операцияларға қызмет көрсету бойынша қызметке қойылатын талаптарды бекіту туралы
form: ПОСТ
type_codes:
- ИНСТ
- ПОСТ
approved_on: 2000-08-23
approved_by:
- '117000000000'
version_date:
  kaz: 2015-02-25
  rus: 2015-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/7165/kaz/25.02.2015
  rus: https://zan.gov.kz/client/#!/doc/7165/rus/25.02.2015
caused_by:
  code: '89131'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 25 февраля 2015 года № 28. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 апреля 2015 года № 10715
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам кардинального улучшения условий для предпринимательской деятельности в Республике Казахстан
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне Қазақстан Республикасында кәсіпкерлік қызмет үшін жағдайды түбегейлі жақсарту мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89131/rus
