act_code: '17206'
requisite: Постановление Правительства Республики Казахстан от 14 октября 2003 года № 1052. Заголовок в редакции постановления Правительства Республики Казахстан от 23 сентября 2014 года № 1003
title:
  rus: О создании государственного учреждения «Государственный историко-культурный и природный заповедник-музей «Танбалы» в Алматинской области
  kaz: Алматы облысында "Таңбалы" мемлекеттiк тарихи-мәдени және табиғи қорық мұражайы" мемлекеттiк мекемесiн құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-10-13
approved_by:
- '103000000000'
version_date:
  rus: 2014-09-23
source:
  rus: https://zan.gov.kz/client/#!/doc/17206/rus/23.09.2014
caused_by:
  code: '83326'
  requisite: Постановление Правительства Республики Казахстан от 23 сентября 2014 года № 1003. Утратил силу постановлением Правительства Республики Казахстан от 4 октября 2023 года № 865
  title:
    rus: Вопросы Министерства культуры и спорта Республики Казахстан
    kaz: Қазақстан Республикасы Мәдениет және спорт министрлігінің мәселелері
  link: https://zan.gov.kz/client/#!/doc/83326/rus
