act_code: '38405'
requisite: Постановление акимата города Экибастуза Павлодарской области от 31 января 2008 года № 55/1. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 1 февраля 2008 года за № 123-136
title:
  rus: О согласовании коэффициента зонирования по городу Экибастузу для оценки недвижимого имущества физических лиц, не используемых в предпринимательской деятельности для целей налогообложения
  kaz: Жеке тұлғалардың кәсіпкерлік қызметінде пайданылмайтын, жылжымайтын мүліктерін салық салу мақсаты үшін бағалауға Екібастұз қаласы бойынша аймақтандыру коэффицентін келісу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-01-31
approved_by:
- '164013000001'
version_date:
  kaz: 2008-01-31
  rus: 2008-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/38405/kaz/31.01.2008
  rus: https://zan.gov.kz/client/#!/doc/38405/rus/31.01.2008
