act_code: '14204'
requisite: Постановление Правительства Республики Казахстан от 23 января 2003 года N 84
title:
  rus: О переименовании Республиканского государственного казенного предприятия "Академический ансамбль классического танца Республики Казахстан" Комитета культуры Министерства культуры, информации и общественного согласия Республики Казахстан
  kaz: Қазақстан Республикасының Мәдениет, ақпарат және қоғамдық келiсiм министрлiгі Мәдениет комитетінің "Қазақстан Республикасының академиялық классикалық би ансамблi" республикалық мемлекеттiк қазыналық кәсiпорнын қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-01-23
approved_by:
- '103000000000'
version_date:
  kaz: 2003-11-24
  rus: 2003-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/14204/kaz/24.11.2003
  rus: https://zan.gov.kz/client/#!/doc/14204/rus/24.11.2003
caused_by:
  code: '17550'
  requisite: Постановление Правительства Республики Kазахстан от 24 ноября 2003 года N 1172. Утратило силу - постановлением Правительства РК от 29 октября 2004 г. N 1130 (P041130)
  title:
    rus: Вопросы Министерства культуры Республики Казахстан
    kaz: Қазақстан Республикасы Мәдениет министрлігінiң мәселелерi
  link: https://zan.gov.kz/client/#!/doc/17550/rus
