act_code: '132088'
requisite: Постановление Глубоковского районного акимата Восточно-Казахстанской области от 29 мая 2019 года № 209. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 мая 2019 года № 5988
title:
  rus: Об утверждении государственного образовательного заказа на дошкольное воспитание и обучение, размера родительской платы на 2019 год по Глубоковскому району
  kaz: Глубокое ауданы бойынша 2019 жылға арналған мектепке дейінгі тәрбие мен оқытуға мемлекеттік білім беру тапсырысын, ата-ананың ақы төлеу мөлшерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-05-29
approved_by:
- '157010000001'
version_date:
  kaz: 2019-05-29
  rus: 2019-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/132088/kaz/29.05.2019
  rus: https://zan.gov.kz/client/#!/doc/132088/rus/29.05.2019
