act_code: '70882'
requisite: Постановление акимата города Астаны от 29 декабря 2012 года № 158-1925. Зарегистрировано Департаментом юстиции города Астаны 11 февраля 2013 года № 770. Утратило силу постановлением акимата города Астаны от 22 июля 2014 года № 158-1179
title:
  rus: Об утверждении регламентов государственных услуг в сфере социальной защиты, оказываемых в городе Астане
  kaz: Астана қаласында көрсетілетін әлеуметтік қорғау саласындағы мемлекеттік қызметтердің регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-12-29
approved_by:
- '151000000001'
version_date:
  kaz: 2012-12-29
  rus: 2012-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/70882/kaz/29.12.2012
  rus: https://zan.gov.kz/client/#!/doc/70882/rus/29.12.2012
