act_code: '32918'
requisite: Постановление Правительства Республики Казахстан от 27 апреля 2007 года № 336
title:
  rus: Об утверждении Правил выплаты единовременной компенсации при получении увечья (травмы, ранения, контузии, профессионального заболевания) или гибели (смерти) судьи в связи с исполнением служебных обязанностей
  kaz: Судьяға қызметтік міндеттерін орындауына байланысты мертіккен (жарақаттанған, жараланған, контузия алған, кәсіптік ауруға шалдыққан) немесе қаза тапқан (қайтыс болған) жағдайда біржолғы өтемақы төлеу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2007-04-27
approved_by:
- '103000000000'
version_date:
  kaz: 2024-07-25
  rus: 2024-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/32918/kaz/25.07.2024
  rus: https://zan.gov.kz/client/#!/doc/32918/rus/25.07.2024
caused_by:
  code: '199129'
  requisite: Постановление Правительства Республики Казахстан от 25 июля 2024 года № 604
  title:
    rus: О внесении изменений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199129/rus
