act_code: '97838'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 2015 года № 1194. Утратило силу постановлением Правительства Республики Казахстан от 18 марта 2021 года № 151 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Типового положения об Общественном совете
  kaz: Қоғамдық кеңес туралы үлгілік ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2015-12-31
approved_by:
- '103000000000'
version_date:
  kaz: 2016-12-28
  rus: 2016-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/97838/kaz/28.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97838/rus/28.12.2016
caused_by:
  code: '108778'
  requisite: Постановление Правительства Республики Казахстан от 28 декабря 2016 года № 886
  title:
    rus: О некоторых вопросах Управления Делами Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президенті Іс Басқармасының кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/108778/rus
