act_code: '32106'
requisite: Постановление акимата Алтынсаринского района Костанайской области от 25 января 2007 года № 58. Зарегистрировано Управлением юстиции Алтынсаринского района Костанайской области 26 февраля 2007 года № 9-5-41
title:
  rus: Об организации, объемах и видах общественных работ на 2007 год
  kaz: 2007 жылға қоғамдық жұмыстарды ұйымдастыру, көлемдері және түрлері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-01-25
approved_by:
- '162003000001'
version_date:
  kaz: 2007-01-25
  rus: 2007-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/32106/kaz/25.01.2007
  rus: https://zan.gov.kz/client/#!/doc/32106/rus/25.01.2007
