act_code: '2820'
requisite: Постановление Правительства Республики Казахстан от 6 мая 1999 года N 539 . Утратило силу - постановлением Правительства РК от 19 ноября 1999 г. N 1755
title:
  rus: Вопросы Комитета спорта и физической культуры Министерства здравоохранения, образования и спорта Республики Казахстан
  kaz: Қазақстан Республикасы Денсаулық сақтау, білім және спорт министрлігі Спорт және дене тәрбиесі комитетінің мәселелері
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1999-05-05
approved_by:
- '103000000000'
version_date:
  rus: 1999-08-26
source:
  rus: https://zan.gov.kz/client/#!/doc/2820/rus/26.08.1999
caused_by:
  code: '3940'
  requisite: Постановление Правительства Республики Казахстан от 27 августа 1999 года № 1264
  title:
    rus: О реорганизации учреждений Министерства здравоохранения, образования и спорта Республики Казахстан
    kaz: Қазақстан Республикасы Денсаулық сақтау, білім және спорт министрлігінің мекемелерін қайта ұйымдастыру туралы
  link: https://zan.gov.kz/client/#!/doc/3940/rus
