act_code: '203056'
requisite: Постановление акимата Павлодарской области от 20 ноября 2024 года № 276/2
title:
  rus: Об утверждении государственного образовательного заказа на подготовку кадров с высшим и послевузовским образованием на 2024-2025 учебный год
  kaz: 2024-2025 оқу жылына арналған жоғары және жоғары оқу орнынан кейінгі білімі бар кадрларды даярлауға мемлекеттік білім беру тапсырысын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2024-11-20
approved_by:
- '164000000001'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/203056/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203056/rus/20.11.2024
