act_code: '89099'
requisite: Постановление Правительства Республики Казахстан от 22 апреля 2015 года № 250. Утратило силу постановлением Правительства Республики Казахстан от 17 июля 2023 года № 603
title:
  rus: Об определении параметров финансовой устойчивости (коэффициентов) Банка Развития Казахстана, их пороговых значений и утверждении методики расчета пороговых значений параметров финансовой устойчивости (коэффициентов) Банка Развития Казахстана
  kaz: Қазақстанның Даму Банкінің қаржылық тұрақтылығының параметрлерін (коэффициенттерін), олардың шекті мәндерін айқындау және Қазақстанның Даму Банкінің қаржылық тұрақтылығы параметрлерінің (коэффициенттерінің) шекті мәндерін есептеу әдістемесін бекіту туралы
form: ПОСТ
type_codes:
- МЕТ
- ПОСТ
approved_on: 2015-04-22
approved_by:
- '103000000000'
version_date:
  kaz: 2016-10-31
  rus: 2016-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/89099/kaz/31.10.2016
  rus: https://zan.gov.kz/client/#!/doc/89099/rus/31.10.2016
caused_by:
  code: '107381'
  requisite: Постановление Правительства Республики Казахстан от 31 октября 2016 года № 633. Утратило силу постановлением Правительства Республики Казахстан от 17 июля 2023 года № 603
  title:
    rus: О внесении изменений и дополнения в постановление Правительства Республики Казахстан от 22 апреля 2015 года № 250 "Об определении параметров финансовой устойчивости (коэффициентов) Банка Развития Казахстана, их пороговых значений и утверждении методики расчета пороговых значений параметров финансовой устойчивости (коэффициентов) Банка Развития Казахстана"
    kaz: '"Қазақстанның Даму Банкінің қаржылық тұрақтылығының параметрлерін (коэффициенттерін), олардың шекті мәндерін айқындау және Қазақстанның Даму Банкінің қаржылық тұрақтылығы параметрлерінің (коэффициенттерінің) шекті мәндерін есептеу әдістемесін бекіту туралы" Қазақстан Республикасы Үкіметінің 2015 жылғы 22 сәуірдегі № 250 қаулысына өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/107381/rus
