act_code: '109800'
requisite: Постановление Правительства Республики Казахстан от 18 февраля 2017 года № 81
title:
  rus: О некоторых вопросах Министерства труда и социальной защиты населения Республики Казахстан
  kaz: Қазақстан Республикасы Еңбек және халықты әлеуметтiк қорғау министрлiгінiң кейбiр мәселелерi туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2017-02-18
approved_by:
- '103000000000'
version_date:
  kaz: 2024-07-25
  rus: 2024-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/109800/kaz/25.07.2024
  rus: https://zan.gov.kz/client/#!/doc/109800/rus/25.07.2024
caused_by:
  code: '199127'
  requisite: Постановление Правительства Республики Казахстан от 25 июля 2024 года № 603
  title:
    rus: О внесении изменений и дополнений в постановление Правительства Республики Казахстан от 18 февраля 2017 года № 81 «Некоторые вопросы Министерства труда и социальной защиты населения Республики Казахстан»
    kaz: «Қазақстан Республикасы Еңбек және халықты әлеуметтік қорғау министрлiгінiң кейбiр мәселелері туралы» Қазақстан Республикасы Үкіметінің 2017 жылғы 18 ақпандағы № 81 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199127/rus
