act_code: '97552'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 2015 года № 1165
title:
  rus: Об утверждении перечня товаров, работ, услуг, приобретаемых в соответствии с международными договорами Республики Казахстан
  kaz: Қазақстан Республикасының халықаралық шарттарына сәйкес сатып алынатын тауарлардың, жұмыстардың, көрсетілетін қызметтердің тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2015-12-31
approved_by:
- '103000000000'
version_date:
  kaz: 2016-11-24
  rus: 2016-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/97552/kaz/24.11.2016
  rus: https://zan.gov.kz/client/#!/doc/97552/rus/24.11.2016
caused_by:
  code: '107747'
  requisite: Постановление Правительства Республики Казахстан от 24 ноября 2016 года № 738
  title:
    rus: О внесении дополнения в постановление Правительства Республики Казахстан от 31 декабря 2015 года № 1165 «Об утверждении перечня товаров, работ, услуг, приобретаемых в соответствии с международными договорами Республики Казахстан
    kaz: «Қазақстан Республикасының халықаралық шарттарына сәйкес сатып алынатын тауарлардың, жұмыстардың, көрсетілетін қызметтердің тізбесін бекіту туралы» Қазақстан Республикасы Үкіметінің 2015 жылғы 31 желтоқсандағы № 1165 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107747/rus
