act_code: '30485'
requisite: Постановление Правления Национального Банка Республики Казахстан от 27 октября 2006 года N 107. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 ноября 2006 года N 4458. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 28 ноября 2008 года N 99
title:
  rus: Об утверждении Инструкции по ведению бухгалтерского учета операций с пенсионными активами, осуществляемых накопительными пенсионными фондами Республики Казахстан
  kaz: Қазақстан Республикасының жинақтаушы зейнетақы қорлары зейнетақы активтерімен жүзеге асыратын операциялардың бухгалтерлік есебін жүргізу жөніндегі нұсқаулықты бекіту туралы
form: ПОСТ
type_codes:
- ИНСТ
- ПОСТ
approved_on: 2006-10-27
approved_by:
- '117000000000'
version_date:
  kaz: 2007-08-27
  rus: 2007-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/30485/kaz/27.08.2007
  rus: https://zan.gov.kz/client/#!/doc/30485/rus/27.08.2007
caused_by:
  code: '35219'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 27 августа 2007 года N 96. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 октября 2007 года N 4957. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 28 ноября 2008 года N 99
  title:
    rus: О внесении дополнений и изменений в постановление Правления Национального Банка Республики Казахстан от 27 октября 2006 года N 107 "Об утверждении Инструкции по ведению бухгалтерского учета операций с пенсионными активами, осуществляемых накопительными пенсионными фондами Республики Казахстан"
    kaz: Қазақстан Республикасының Ұлттық Банкің Басқармасының "Қазақстан Республикасының жинақтаушы зейнетақы қорлары зейнетақы активтерімен жүзеге асыратын операциялардың бухгалтерлік есебін жүргізу жөніндегі нұсқаулықты бекіту туралы" 2006 жылғы 27 қазандағы N 107 қаулысына толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/35219/rus
