act_code: '44027'
requisite: Постановление Правительства Республики Казахстан от 5 февраля 2009 года № 109. Утратило силу постановлением Правительства Республики Казахстан от 30 января 2017 года № 29
title:
  rus: Об утверждении Технического регламента "Требования к безопасности метрополитенов"
  kaz: '"Метрополитендердің қауіпсіздігіне қойылатын талаптар" техникалық регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2009-02-05
approved_by:
- '103000000000'
version_date:
  kaz: 2009-02-05
  rus: 2009-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/44027/kaz/05.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44027/rus/05.02.2009
