act_code: '77755'
requisite: Постановление акимата города Петропавловска Северо-Казахстанской области от 20 февраля 2014 года № 266. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 февраля 2014 года № 2573. Утратило силу в связи с истечением срока действия (письмо аппарата акима города Петропавловска Северо-Казахстанской области от 11 декабря 2014 года № 16-1.-3-19/2830)
title:
  rus: Об определении мест в городе Петропавловске для размещения агитационных печатных материалов и предоставлении помещения для встреч с избирателями кандидатов в депутаты Петропавловского городского маслихата
  kaz: Петропавл қаласында Петропавл қалалық мәслихатының депутаттығына кандидаттардың сайлаушылармен кездесуіне үй-жай беруге және үгіттік баспа материалдарын орналастыруға арналған орындар белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-02-20
approved_by:
- '165002000001'
version_date:
  kaz: 2014-02-20
  rus: 2014-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/77755/kaz/20.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77755/rus/20.02.2014
