act_code: '91390'
requisite: Постановление акимата Акмолинской области от 1 июня 2015 года № А-6/247. Зарегистрировано Департаментом юстиции Акмолинской области 3 июля 2015 года № 4852
title:
  rus: Об утверждении порядка и условий классификации автомобильных дорог общего пользования областного и районного значения Акмолинской области
  kaz: Ақмола облысының облыстық және аудандық маңызы бар жалпыға ортақ пайдаланылатын автомобиль жолдарын сыныптау тәртібі мен шарттарын бекіту туралы
form: ПОСТ
type_codes:
- ПОР
- ПОСТ
- УСЛ
approved_on: 2015-06-01
approved_by:
- '152000000001'
version_date:
  kaz: 2022-09-20
  rus: 2022-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/91390/kaz/20.09.2022
  rus: https://zan.gov.kz/client/#!/doc/91390/rus/20.09.2022
caused_by:
  code: '172097'
  requisite: Постановление акимата Акмолинской области от 20 сентября 2022 года № А-9/449. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 сентября 2022 года № 29834
  title:
    rus: О внесении изменений в некоторые постановления акимата Акмолинской области
    kaz: Ақмола облысы әкімдігінің кейбір қаулыларына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172097/rus
