act_code: '91769'
requisite: Постановление от 15.06.2015 №255, Акимат Алматинской области
title:
  rus: 'Об установлении охранной зоны и режима природопользования Иле-Алатауского государственного национального природного парка на территории Алматинской области  '
  kaz: 'Алматы облысының аумағындағы Іле-Алатау  мемлекеттік ұлттық табиғи паркінің күзет аймағы мен табиғатты пайдалану режимін белгілеу туралы '
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-06-15
approved_by:
- '154000000001'
version_date:
  kaz: 2015-06-15
  rus: 2015-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/91769/kaz/15.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91769/rus/15.06.2015
