act_code: '13966'
requisite: Атырау облыстық әкiмиятының 2002 жылғы 3 маусымдағы № 174 қаулысы. Атырау облысының Әдiлет басқармасында 2002 жылғы 23 тамызда № 1098 тiркелдi
title:
  rus: 2002 жылы жекешелендiруге және тұрғын үй қорына беруге жататын коммуналдық меншiк объектiлерiнiң тiзбесi туралы
  kaz: 2002 жылы жекешелендiруге және тұрғын үй қорына беруге жататын коммуналдық меншiк объектiлерiнiң тiзбесi туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2002-06-02
approved_by:
- '156000000001'
version_date:
  kaz: 2002-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/13966/kaz/02.06.2002
