act_code: '95120'
requisite: Постановление Восточно-Казахстанского областного акимата от 8 сентября 2015 года № 227. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 октября 2015 года № 4177. Утратило силу постановлением Восточно-Казахстанского областного акимата от 24 февраля 2020 года № 43 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере земельных отношений
  kaz: Жер қатынастары саласында мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2015-09-08
approved_by:
- '157000000001'
version_date:
  kaz: 2016-04-19
  rus: 2016-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/95120/kaz/19.04.2016
  rus: https://zan.gov.kz/client/#!/doc/95120/rus/19.04.2016
caused_by:
  code: '102010'
  requisite: Постановление Восточно-Казахстанского областного акимата от 19 апреля 2016 года № 114. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 мая 2016 года № 4533. Утратило силу постановлением Восточно-Казахстанского областного акимата от 24 февраля 2020 года № 43 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в постановление Восточно-Казахстанского областного акимата от 8 сентября 2015 года № 227 «Об утверждении регламентов государственных услуг в сфере земельных отношений»
    kaz: «Жер қатынастары саласында мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы» Шығыс Қазақстан облысы әкімдігінің 2015 жылғы 8 қыркүйектегі № 227 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102010/rus
