act_code: '12864'
requisite: Постановление акимата Актюбинской области от 11 июля 2002 года № 106. Зарегистрировано Управлением юстиции Актюбинской области 2 августа 2002 года № 1746
title:
  rus: О создании рабочей группы по обеспечению полноты поступления налогов и сборов в бюджет области
  kaz: Облыс бюджетіне түсетін салықтар мен алымдар түсімдерінің толықтығын қамтамасыз ету жөніндегі жұмыс тобын құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2002-07-10
approved_by:
- '153000000001'
version_date:
  kaz: 2004-04-14
  rus: 2004-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/12864/kaz/14.04.2004
  rus: https://zan.gov.kz/client/#!/doc/12864/rus/14.04.2004
caused_by:
  code: '19529'
  requisite: Постановление акимата Актюбинской области от 15 апреля 2004 года № 92. Зарегистрировано Управлением юстиции Актюбинской области 27 апреля 2004 года № 2685
  title:
    rus: О внесении изменений в постановление акимата области № 106 от 11 июля 2002 года «О создании рабочей группы обеспечению полноты поступления налогов и сборов в бюджет области» (Зарегистрировано в Департаменте юстиции 2 августа 2002 года № 1746)
    kaz: «Облыс бюджетіне түсетін салықтар мен алымдар түсімдерінің толықтығын қамтамасыз ету жөніндегі жұмыс тобын құру туралы» облыс әкімиятының 2002 жылғы 11 шілдедегі № 106 қаулысына өзгерістер енгізу туралы (Әділет Департаментінде 2002 жылы 2 тамызда № 1746 тіркелген)
  link: https://zan.gov.kz/client/#!/doc/19529/rus
