act_code: '103828'
requisite: Постановление Правительства Республики Казахстан от 28 июня 2016 года № 374
title:
  rus: О распределении и Правилах использования средств целевого трансферта из Национального фонда Республики Казахстан на реализацию проектов по содействию устойчивому развитию и росту Республики Казахстан, осуществляемых совместно с международными финансовыми организациями в рамках рамочных соглашений о партнерстве
  kaz: Әріптестік туралы негіздемелік келісімдер шеңберінде халықаралық қаржы ұйымдарымен бірлесіп жүзеге асырылатын Қазақстан Республикасының орнықты дамуына және өсуіне жәрдемдесу жөніндегі жобаларды іске асыруға Қазақстан Республикасының Ұлттық қорынан берілетін нысаналы трансферт қаражатын бөлу және пайдалану қағидалары туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2016-06-28
approved_by:
- '103000000000'
version_date:
  kaz: 2016-08-31
  rus: 2016-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/103828/kaz/31.08.2016
  rus: https://zan.gov.kz/client/#!/doc/103828/rus/31.08.2016
caused_by:
  code: '105899'
  requisite: Постановление Правительства Республики Казахстан от 31 августа 2016 года № 495
  title:
    rus: О внесении дополнений в постановление Правительства Республики Казахстан от 28 июня 2016 года № 374 «О распределении и Правилах использования средств целевого трансферта из Национального фонда Республики Казахстан на реализацию проектов по содействию устойчивому развитию и росту Республики Казахстан, осуществляемых совместно с международными финансовыми организациями в рамках рамочных соглашений о партнерстве»
    kaz: «Әріптестік туралы негіздемелік келісімдер шеңберінде халықаралық қаржы ұйымдарымен бірлесіп жүзеге асырылатын Қазақстан Республикасының орнықты дамуына және өсуіне жәрдемдесу жөніндегі жобаларды іске асыруға Қазақстан Республикасының Ұлттық қорынан берілетін нысаналы трансферт қаражатын бөлу және пайдалану қағидалары туралы» Қазақстан Республикасы Үкіметінің 2016 жылғы 28 маусымдағы № 374 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105899/rus
