act_code: '139714'
requisite: Постановление акимата города Шымкент от 4 февраля 2020 года № 54. Зарегистрировано Департаментом юстиции города Шымкент 21 февраля 2020 года № 88
title:
  rus: Об утверждении Правил организации отбора инновационных проектов в области агропромышленного комплекса города Шымкент
  kaz: Шымкент қаласының агроөнеркәсіптік кешен саласында инновациялық жобаларды іріктеуді ұйымдастыру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-02-04
approved_by:
- '167000000001'
version_date:
  kaz: 2022-08-15
  rus: 2022-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/139714/kaz/15.08.2022
  rus: https://zan.gov.kz/client/#!/doc/139714/rus/15.08.2022
caused_by:
  code: '170683'
  requisite: Постановление акимата города Шымкент от 15 августа 2022 года № 1535. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 августа 2022 года № 29149
  title:
    rus: О внесении изменений в постановление акимата города Шымкент от 4 февраля 2020 года № 54 «Об утверждении Правил организации отбора инновационных проектов в сфере агропромышленного комплекса города Шымкент»
    kaz: Шымкент қаласы әкімдігінің 2020 жылғы 4 ақпандағы № 54 «Шымкент қаласының агроөнеркәсіптік кешен саласында инновациялық жобаларды іріктеуді ұйымдастыру қағидаларын бекіту туралы» қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170683/rus
