act_code: '213118'
requisite: Постановление акимата Каркаралинского района Карагандинской области от 4 августа 2025 года № 271
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Горно-Рудная Компания «Қарқаралы»
  kaz: «Горно-Рудная Компания «Қарқаралы» жауапкершілігі шектеулі серіктестігіне қауымдық сервитутты белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-08-04
approved_by:
- '160013000001'
version_date:
  kaz: 2025-08-04
  rus: 2025-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/213118/kaz/04.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213118/rus/04.08.2025
