act_code: '109765'
requisite: Постановление Правительства Республики Казахстан от 14 февраля 2017 года № 66
title:
  rus: Об утверждении Положения об особом статусе организаций высшего и (или) послевузовского образования
  kaz: Жоғары және (немесе) жоғары оқу орнынан кейінгі білім беру ұйымдарының ерекше мәртебесі туралы ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2017-02-14
approved_by:
- '103000000000'
version_date:
  kaz: 2018-04-05
  rus: 2018-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/109765/kaz/05.04.2018
  rus: https://zan.gov.kz/client/#!/doc/109765/rus/05.04.2018
caused_by:
  code: '120243'
  requisite: Постановление Правительства Республики Казахстан от 5 апреля 2018 года № 169
  title:
    rus: О внесении дополнения в постановление Правительства Республики Казахстан от 14 февраля 2017 года № 66 «Об утверждении Положения об особом статусе высших учебных заведений»
    kaz: «Жоғары оқу орындарының ерекше мәртебесі туралы ережені бекіту туралы» Қазақстан Республикасы Үкіметінің 2017 жылғы 14 ақпандағы № 66 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120243/rus
