act_code: '138135'
requisite: Постановление акимата Тимирязевского района Северо-Казахстанской области от 9 января 2020 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2020 года № 5829. Утратило силу постановлением акимата Тимирязевского района Северо-Казахстанской области от 4 февраля 2021 года № 25 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении квоты рабочих мест для трудоустройства лиц, освобожденных из мест лишения cвободы
  kaz: Бас бостандығынан айыру орындарынан босатылған адамдарды жұмысқа орналастыру үшін жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-01-09
approved_by:
- '165012000001'
version_date:
  kaz: 2020-01-09
  rus: 2020-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138135/kaz/09.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138135/rus/09.01.2020
