act_code: '9147'
requisite: Постановление Правления Национального Банка Республики Казахстан от 20 апреля 2001 года № 120. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 июня 2001 года № 1532. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 16 июля 2014 года № 151
title:
  rus: Об утверждении Правил осуществления актуарной деятельности, выдачи лицензии на право осуществления актуарной деятельности на страховом рынке, сдачи квалификационного экзамена актуарием, привлечения независимого актуария для проверки деятельности актуария, направления независимым актуарием результатов проверки достоверности расчетов, проведенных актуарием, состоящим в штате страховой (перестраховочной) организации
  kaz: Сақтандыру нарығында актуарийлiк қызметтi жүзеге асыру, актуарийлік қызметті жүзеге асыру құқығына лицензия беру, актуарийдің біліктілік емтиханын тапсыру, актуарийдiң қызметін тексеру үшін тәуелсіз актуарийдi тарту, тәуелсіз актуарийдiң сақтандыру (қайта сақтандыру) ұйымының штатында тұрған актуарий жүргізген есептердің шынайылығын тексеру нәтижелерін жіберу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2001-04-19
approved_by:
- '117000000000'
version_date:
  kaz: 2014-02-03
  rus: 2014-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/9147/kaz/03.02.2014
  rus: https://zan.gov.kz/client/#!/doc/9147/rus/03.02.2014
caused_by:
  code: '78710'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 3 февраля 2014 года № 8. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 марта 2014 года № 9263
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам страховой деятельности
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне сақтандыру қызметі мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/78710/rus
