act_code: '51066'
requisite: Постановление акимата города Усть-Каменогорска Восточно-Казахстанской области от 15 февраля 2010 года № 5683. Зарегистрировано Управлением юстиции города Усть-Каменогорск Департамента юстиции Восточно-Казахстанской области 3 марта 2010 года за № 5-1-134. Утратило силу - постановлением акимата города Усть-Каменогорска ВКО от 9 апреля 2010 года N 6632
title:
  rus: Об определении мест для размещения агитационных печатных материалов кандидатов в депутаты Усть-Каменогорского городского маслихата по избирательному округу № 16 вместо выбывшего
  kaz: Өскемен қалалық мәслихатының шығып қалған депутатының орнына № 16 сайлау округі бойынша үміткерлердің үгіттік баспа материалдарын орналастыру үшін орындар белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-02-15
approved_by:
- '157002000001'
version_date:
  kaz: 2010-02-15
  rus: 2010-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/51066/kaz/15.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51066/rus/15.02.2010
