act_code: '216227'
requisite: Совместное решение Алматинского областного маслихата от 22 октября 2025 года № 42-233 и постановление акимата Алматинской области от 22 октября 2025 года № 321
title:
  rus: Об установлении минимальных размеров земельных участков сельскохозяйственного назначения, предоставляемых в собственность или землепользование в Алматинской области
  kaz: Алматы облысында меншікке немесе жер пайдалануға берілетін ауыл шаруашылығы мақсатындағы жер телімдерінің ең аз мөлшерлерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2025-10-22
approved_by:
- '154000000001'
- '154000000002'
version_date:
  kaz: 2025-10-22
  rus: 2025-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/216227/kaz/22.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216227/rus/22.10.2025
