act_code: '48474'
requisite: Батыс Қазақстан облысы Жәнібек ауданы әкімдігінің 2009 жылғы 19 қазандағы № 276 қаулысы. Батыс Қазақстан облысы Жәнібек ауданы әділет басқармасында 2009 жылғы 5 қарашада № 7-6-94 тіркелді. Күші жойылды - Батыс Қазақстан облысы Жәнібек ауданы әкімдігінің 2010 жылғы 2 наурыздағы № 33 қаулысымен
title:
  rus: Жәнібек ауданының Күйгенкөл, Ұзынкөл, Қамысты ауылдық округтерінің аумақтарына карантиндік режимді және шектеу іс-шараларын енгізу туралы
  kaz: Жәнібек ауданының Күйгенкөл, Ұзынкөл, Қамысты ауылдық округтерінің аумақтарына карантиндік режимді және шектеу іс-шараларын енгізу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-10-19
approved_by:
- '159007000001'
version_date:
  kaz: 2009-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/48474/kaz/19.10.2009
