act_code: '20035'
requisite: Постановление Акимата Мангистауской области от 29 апреля 2004 года N 111. Зарегистрировано Департаментом юстиции Мангистауской области 2 июня 2004 года за № 1699. Утратило силу постановлением акимата Мангистауской области от 6 августа 2008 года № 734
title:
  rus: Об организации и проведении единого национального тестирования
  kaz: Об организации и проведении единого национального тестирования
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-04-28
approved_by:
- '163000000001'
version_date:
  rus: 2004-04-28
source:
  rus: https://zan.gov.kz/client/#!/doc/20035/rus/28.04.2004
