act_code: '36938'
requisite: Постановление акимата города Петропавловска Северо-Казахстанской области от 11 декабря 2007 года № 1965. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 11 января 2008 года № 13-1-99. Утратило силу - постановлением акимата города Петропавловска Северо-Казахстанской области от 17 июля 2009 года № 824
title:
  rus: Об утверждении стандарта оказания государственной услуги "Назначение и выплата социальной помощи пенсионерам на проезд в городском транспорте в период дачного сезона с 1 мая по 30 сентября" государственным учреждением "Отдел занятости и социальных программ города Петропавловска"
  kaz: '"Петропавл қаласының жұмыспен қамту және әлеуметтік бағдарламалар бөлімі" мемлекеттік мекемесімен "Саяжай маусымы кезеңінде 1 мамырдан бастап 30 қыркүйек аралығында қалалық көлікте жүру үшін зейнеткерлерге әлеуметтік көмек тағайындау және төлеу" мемлекеттік қызметін көрсету стандартын бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- СТНД
approved_on: 2007-12-11
approved_by:
- '165002000001'
version_date:
  kaz: 2007-12-11
  rus: 2007-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/36938/kaz/11.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36938/rus/11.12.2007
