act_code: '212104'
requisite: Постановление акимата города Арыс Туркестанской области от 4 апреля 2025 года № 192
title:
  rus: О государственной регистрации изменении и дополнении в Положение государственного учреждения «Аппарат акима» города Арыс
  kaz: Арыс қаласы «Әкімінің аппараты» мемлекеттік мекемесінің ережесіне енгізілген өзгерістер мен толықтыруларды мемлекеттік тіркеу туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2025-04-04
approved_by:
- '166016000001'
version_date:
  kaz: 2025-04-04
  rus: 2025-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/212104/kaz/04.04.2025
  rus: https://zan.gov.kz/client/#!/doc/212104/rus/04.04.2025
