act_code: '93959'
requisite: Постановление акимата Мангистауской области от 10 августа 2015 года № 238. Зарегистрировано Департаментом юстиции Мангистауской области от 16 сентября 2015 года № 2828.  Утратило силу постановлением акимата Мангистауской области от 20 марта 2020 года № 45
title:
  rus: Об утверждении регламента государственной услуги «Выдача архивных справок»
  kaz: «Мұрағат анықтамаларын беру» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2015-08-10
approved_by:
- '163000000001'
version_date:
  kaz: 2016-06-22
  rus: 2016-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/93959/kaz/22.06.2016
  rus: https://zan.gov.kz/client/#!/doc/93959/rus/22.06.2016
caused_by:
  code: '104978'
  requisite: Постановление акимата Мангистауской области от 22 июня 2016 года № 178. Зарегистрировано Департаментом юстиции Мангистауской области 22 июля 2016 года № 3089. Утратило силу постановлением акимата Мангистауской области от 20 марта 2020 года № 45
  title:
    rus: О внесении изменений в постановление акимата Мангистауской области  от 10 августа 2015 года № 238 «Об утверждении регламента государственной  услуги «Выдача архивных справок»
    kaz: Маңғыстау облысы әкімдігінің  2015 жылғы 10 тамыздағы № 238  «Мұрағат анықтамаларын  беру» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы» қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104978/rus
