act_code: '45777'
requisite: Батыс Қазақстан облысы Ақжайық ауданы әкімдігінің 2009 жылғы 21 сәуірдегі № 136 қаулысы. Батыс Қазақстан облысы Ақжайық ауданы әділет басқармасында 2009 жылғы 7 мамырда № 7-2-73 тіркелді. Күші жойылды - Батыс Қазақстан облысы Ақжайық ауданы әкімдігінің 2009 жылғы 20 мамырдағы № 170 қаулысымен
title:
  rus: 2009 жылдың мамыр-маусым және қазан-желтоқсан айларында 1982-1991 жылдары туған азаматтарды кезекті мерзімді әскери қызметке шақыру туралы
  kaz: 2009 жылдың мамыр-маусым және қазан-желтоқсан айларында 1982-1991 жылдары туған азаматтарды кезекті мерзімді әскери қызметке шақыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-04-21
approved_by:
- '159003000001'
version_date:
  kaz: 2009-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/45777/kaz/21.04.2009
