act_code: '21350'
requisite: Павлодар облысы Павлодар ауданының әкімиятының 2004 жылғы 8 қыркүйектегі № 313/9 қаулысы. Павлодар облысының әділет департаментінде 2004 жылғы 23 қыркүйекте № 2728 тіркелді
title:
  rus: Мүгедектер ісі жөніндегі аудандық кеңес құру туралы
  kaz: Мүгедектер ісі жөніндегі аудандық кеңес құру туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2004-09-07
approved_by:
- '164014000001'
version_date:
  kaz: 2004-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/21350/kaz/07.09.2004
