act_code: '38848'
requisite: Постановление акимата района Шал акына Северо-Казахстанской области от 3 апреля 2008 года № 56. Зарегистрировано Управлением юстиции района Шал акына Северо-Казахстанской области 14 апреля 2008 года № 13-14-55
title:
  rus: Об очередном призыве граждан на срочную воинскую службу в апреле - июне, октябре - декабре 2008 года
  kaz: 2008 жылы сәуір-маусым, қазан-желтоқсан айларында азаматтарды кезекті жедел әскери қызметке шақыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-04-03
approved_by:
- '165010000001'
version_date:
  kaz: 2008-04-03
  rus: 2008-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/38848/kaz/03.04.2008
  rus: https://zan.gov.kz/client/#!/doc/38848/rus/03.04.2008
