act_code: '57776'
requisite: Постановление акимата Бейнеуского района Мангистауской область от 24 февраля 2011 года № 30. Зарегистрировано Управлением юстиции Мангистауской область Бейнеуского района 28 февраля 2011 года № 11-3-114. Утратило силу постановлением акимата Бейнеуского района Мангистауской области от 14 сентября 2020 года № 254
title:
  rus: Об утверждении Списка помещений, предоставляемых кандидатам на договорной основе для встерч с избирателями
  kaz: Қазақстан Республикасының Президенттігіне кандидаттарға сайлаушылармен кездесу үшін берілетін үй-жайлар тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-02-24
approved_by:
- '163007000001'
version_date:
  kaz: 2011-02-24
  rus: 2011-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/57776/kaz/24.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57776/rus/24.02.2011
