act_code: '143971'
requisite: Постановление акимата Сарыагашского района Туркестанской области от 18 июня 2020 года № 150. Зарегистрировано Департаментом юстиции Туркестанской области 19 июня 2020 года № 5662
title:
  rus: О признании утратившим силу постановление акимата Сарыагашского района от 07 февраля 2017 года № 40 «Об утверждении Правил выдачи служебного удостоверения исполнительных органов финансируемых из Сарыагашского районного бюджета и его описание»
  kaz: Сарыағаш ауданы әкімдігінің 2017 жылғы 07 ақпандағы № 40 «Сарыағаш аудандық бюджетiнен қаржыландырылатын атқарушы органдардың қызметтiк куәлiктi беру қағидаларын және оның сипаттамасын бекiту туралы» қаулысының күшін жою туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-06-18
approved_by:
- '166009000001'
version_date:
  kaz: 2020-06-18
  rus: 2020-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/143971/kaz/18.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143971/rus/18.06.2020
