act_code: '26831'
requisite: Абай аудандық әкімдігінің 2006 жылғы 6 ақпандағы № 943 қаулысы. Шығыс Қазақстан облысы Әділет департаменті Абай ауданының әділет басқармасында 2006 жылғы 20 наурызында № 5-5-19 тіркелді
title:
  rus: Тұрғын үй комиссиясын құру туралы
  kaz: Тұрғын үй комиссиясын құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-02-06
approved_by:
- '157006000001'
version_date:
  kaz: 2006-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/26831/kaz/06.02.2006
