act_code: '24072'
requisite: Постановление акимата города Петропавловска Северо-Казахстанской области от 11 апреля 2005 года № 287. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 10 мая 2005 года № 13-1-16. Утратило силу - постановлением акимата города Петропавловска Северо-Казахстанской области от 16 апреля 2010 года № 432
title:
  rus: Об утверждении Правил предоставления социальной помощи студентам из малообеспеченных семей
  kaz: Аз қамтамасыз етiлген отбасыларынан шыққан студенттерге әлеуметтiк көмек беру Ережелерiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2005-04-11
approved_by:
- '165002000001'
version_date:
  kaz: 2007-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/24072/kaz/14.06.2007
