act_code: '123812'
requisite: Постановление Правительства Республики Казахстан от 11 июля 2018 года № 420
title:
  rus: О некоторых вопросах реализации Указа Президента Республики Казахстан от 19 июня 2018 года № 702 «О некоторых вопросах административно-территориального устройства Республики Казахстан»
  kaz: «Қазақстан Республикасының әкімшілік-аумақтық құрылысының кейбір мәселелері туралы» Қазақстан Республикасы Президентінің 2018 жылғы 19 маусымдағы № 702 Жарлығын іске асырудың кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-07-11
approved_by:
- '103000000000'
version_date:
  kaz: 2019-03-26
  rus: 2019-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/123812/kaz/26.03.2019
  rus: https://zan.gov.kz/client/#!/doc/123812/rus/26.03.2019
caused_by:
  code: '129945'
  requisite: Постановление Правительства Республики Казахстан от 26 марта 2019 года № 142. Утратило силу постановлением Правительства Республики Казахстан от 4 октября 2023 года № 866 (вводится в действие со дня его подписания)
  title:
    rus: О некоторых вопросах Министерства информации и общественного развития Республики Казахстан
    kaz: Қазақстан Республикасының Ақпарат және қоғамдық даму министрлігінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/129945/rus
