act_code: '44681'
requisite: Постановление Правительства Республики Казахстан от 6 марта 2009 года № 259. Утратило силу постановлением Правительства Республики Казахстан от 30 января 2017 года № 29
title:
  rus: Об утверждении Технического регламента "Требования к безопасности систем газоснабжения"
  kaz: '"Газбен жабдықтау жүйелерінің қауіпсіздігіне қойылатын талаптар" техникалық регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2009-03-06
approved_by:
- '103000000000'
version_date:
  kaz: 2009-03-06
  rus: 2009-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/44681/kaz/06.03.2009
  rus: https://zan.gov.kz/client/#!/doc/44681/rus/06.03.2009
