act_code: '17117'
requisite: Постановление Правительства Республики Казахстан от 29 сентября 2003 года N 997. Утратило силу - постановлением Правительства РК от 21 июня 2005 г. N 599
title:
  rus: Об утверждении типовой формы договора о жилищных строительных сбережениях
  kaz: Тұрғын үй құрылысы жинақ ақшасы туралы шарттың үлгi нысанын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-09-28
approved_by:
- '103000000000'
version_date:
  kaz: 2003-09-28
  rus: 2003-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/17117/kaz/28.09.2003
  rus: https://zan.gov.kz/client/#!/doc/17117/rus/28.09.2003
