act_code: '145649'
requisite: Решение Панфиловского районного маслихата Алматинской области от 10 августа 2020 года № 6-73-413 и постановление акимата Панфиловского района Алматинской области от 10 августа 2020 года № 334. Зарегистрировано Департаментом юстиции Алматинской области 19 августа 2020 года № 5611
title:
  rus: О переименовании улицы города Жаркент
  kaz: Жаркент қаласының көшесін қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2020-08-10
approved_by:
- '154004000001'
- '154004000002'
version_date:
  kaz: 2020-08-10
  rus: 2020-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/145649/kaz/10.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145649/rus/10.08.2020
