act_code: '99926'
requisite: Постановление акимата города Сатпаев Карагандинской области от 4 февраля 2016 года № 03/01. Зарегистрировано Департаментом юстиции Карагандинской области 16 февраля 2016 года № 3663. Утратило силу постановлением акимата города Сатпаев Карагандинской области от 22 февраля 2021 года № 17/01 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О перечне мест для размещения агитационных печатных материалов и помещений для встреч кандидатов с избирателями
  kaz: Үгіттік баспа материалдарын орналастыру үшін  орындарының және кандидаттардың сайлаушылармен кездесуі үшін  үй-жайлардың тізімі туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-02-04
approved_by:
- '160007000001'
version_date:
  kaz: 2016-02-04
  rus: 2016-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/99926/kaz/04.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99926/rus/04.02.2016
