act_code: '208378'
requisite: Постановление акимата города Шымкент от 18 марта 2025 года № 1360. Зарегистрировано в Департаменте юстиции города Шымкент 26 марта 2025 года № 234-17
title:
  rus: Об утверждении объемов субсидирования повышения продуктивности и качества продукции аквакультуры (рыбоводства), а также развития племенного рыбоводства по городу Шымкент на 2025 год
  kaz: Шымкент қаласы бойынша 2025 жылға арналған акваөсіру (балық өсіру шаруашылығы) өнімділігі мен өнім сапасын арттыруды, сондай-ақ асыл тұқымды балық өсіруді дамытуды субсидиялау көлемдерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-03-18
approved_by:
- '167000000001'
version_date:
  kaz: 2025-03-18
  rus: 2025-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/208378/kaz/18.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208378/rus/18.03.2025
