act_code: '67857'
requisite: Постановление Правления Национального Банка Республики Казахстан от 24 августа 2012 года № 253. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 сентября 2012 года № 7926
title:
  rus: Об утверждении Правил обмена банкнот и монет национальной валюты Республики Казахстан, изымаемых и изъятых из обращения, а также ветхих и поврежденных банкнот и монет национальной валюты Республики Казахстан
  kaz: Қазақстан Республикасы ұлттық валютасының айналыстан алынатын және алынған банкноттары мен монеталарын, сондай-ақ Қазақстан Республикасы ұлттық валютасының тозған және бүлінген банкноттары мен монеталарын айырбастау қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2012-08-24
approved_by:
- '117000000000'
version_date:
  kaz: 2013-05-27
  rus: 2013-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/67857/kaz/27.05.2013
  rus: https://zan.gov.kz/client/#!/doc/67857/rus/27.05.2013
caused_by:
  code: '73471'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 27 мая 2013 года № 128. Зарегистрирован в Министерстве юстиции Республики Казахстан 9 июля 2013 года № 8567
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Национального Банка Республики Казахстан
    kaz: Қазақстан Республикасы Ұлттық Банкінің кейбір нормативтік құқықтық актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73471/rus
