act_code: '143207'
requisite: Постановление акимата Жамбылской области от 26 мая 2020 года № 114. Зарегистрировано Департаментом юстиции Жамбылской области 26 мая 2020 года № 4615. Утратило силу постановлением акимата Жамбылской области от 30 марта 2021 года № 76 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня субсидируемых пестицидов и норм субсидий, а также объемов бюджетных средств на субсидирование пестицидов
  kaz: Субсидияланатын пестицидтердің тізбесін және субсидиялар нормаларын, сондай-ақ пестицидтерді субсидиялауға бюджеттік қаражат көлемдерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2020-05-26
approved_by:
- '158000000001'
version_date:
  kaz: 2020-08-13
  rus: 2020-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/143207/kaz/13.08.2020
  rus: https://zan.gov.kz/client/#!/doc/143207/rus/13.08.2020
caused_by:
  code: '145507'
  requisite: Постановление акимата Жамбылской области от 13 августа 2020 года № 178. Зарегистрировано Департаментом юстиции Жамбылской области 14 августа 2020 года № 4697. Утратило силу постановлением акимата Жамбылской области от 30 марта 2021 года № 76 (вводится в действие после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в постановление акимата Жамбылской области от 26 мая 2020 года № 114 «Об утверждении перечня субсидируемых пестицидов и норм субсидий, а также объемов бюджетных средств на субсидирование пестицидов»
    kaz: Жамбыл облысы әкімдігінің 2020 жылғы 26 мамырдағы № 114 «Субсидияланатын пестицидтердің тізбесін және субсидиялар нормаларын, сондай-ақ пестицидтерді субсидиялауға бюджеттік қаражат көлемдерін бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145507/rus
