act_code: '206803'
requisite: Постановление акимата Узункольского района Костанайской области от 24 января 2025 года № 5
title:
  rus: О предоставлении права ограниченного целевого землепользования (публичный сервитут), на неделимый земельный участок из земель, расположенных на территории Узункольского района, государственному учреждению «Управление пассажирского транспорта и автомобильных дорог акимата Костанайской области» для устройства временной объездной дороги и технологической площадки
  kaz: «Қостанай облысы әкімдігінің жолаушылар көлігі және автомобиль жолдары баскармасы» мемлекеттік мекемесіне технологиялық учаскесін және уақытша айналма жолды құру үшін Ұзынкөл ауданының аумағында орналасқан жерлерден бөлінбейтін жер учаскелеріне шектеулі нысаналы жерге пайдалану (қауымдық сервитут) құқығын беру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-01-24
approved_by:
- '162017000001'
version_date:
  kaz: 2025-01-24
  rus: 2025-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206803/kaz/24.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206803/rus/24.01.2025
