act_code: '56549'
requisite: Постановление акимата города Астаны от 20 декабря 2010 года № 23-119п. Зарегистрировано Департаментом юстиции города Астаны 31 декабря 2010 года № 663. Утратило силу постановлением акимата города Астаны от 9 января 2012 года № 158-17
title:
  rus: Об организации оплачиваемых общественных работ в 2011 году
  kaz: 2011 жылы ақылы қоғамдық жұмыстарды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-12-20
approved_by:
- '151000000001'
version_date:
  kaz: 2010-12-20
  rus: 2010-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/56549/kaz/20.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56549/rus/20.12.2010
