act_code: '29114'
requisite: Ақмола облысы Қорғалжын ауданы әкімдігінің 2006 жылғы 10 шілдедегі № 89 қаулысы. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2006 жылғы 15 шілдеде № 1-15-73 болып тіркелді
title:
  rus: Ауыл тұрғындарына бастапқы медициналық-санитарлық көмек көрсетуді жақсарту жөніндегі шаралар туралы
  kaz: Ауыл тұрғындарына бастапқы медициналық-санитарлық көмек көрсетуді жақсарту жөніндегі шаралар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-07-10
approved_by:
- '152016000001'
version_date:
  kaz: 2006-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/29114/kaz/10.07.2006
