act_code: '15938'
requisite: Постановление Правительства Республики Казахстан от 27 июня 2003 года N 623
title:
  rus: О реализации Указа Президента Республики Казахстан от 31 марта 2003 года N 1051 "О реорганизации республиканского государственного учреждения "Национальная академия наук Республики Казахстан"
  kaz: Қазақстан Республикасы Президентінің "Қазақстан Республикасының Ұлттық ғылым академиясы" республикалық мемлекеттiк мекемесiн қайта ұйымдастыру туралы" 2003 жылғы 31 наурыздағы N 1051 Жарлығын iске асыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-06-27
approved_by:
- '103000000000'
version_date:
  kaz: 2004-10-27
  rus: 2004-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/15938/kaz/27.10.2004
  rus: https://zan.gov.kz/client/#!/doc/15938/rus/27.10.2004
caused_by:
  code: '21721'
  requisite: Постановление Правительства Республики Казахстан от 28 октября 2004 года № 1111. Утратило силу постановлением Правительства Республики Казахстан от 19 августа 2022 года № 581 (вводится в действие со дня его подписания)
  title:
    rus: Вопросы Министерства образования и науки Республики Казахстан
    kaz: Қазақстан Республикасы Бiлiм және ғылым министрлігінiң мәселелерi
  link: https://zan.gov.kz/client/#!/doc/21721/rus
