act_code: '48887'
requisite: Батыс Қазақстан облысы Сырым аудандық мәслихатының 2009 жылғы 28 қазандағы № 15-5 шешімі және Сырым ауданы әкімдігінің 2009 жылғы 30 қыркүйектегі № 241 қаулысы. Батыс Қазақстан облысы Сырым ауданы әділет басқармасында 2009 жылғы 30 қарашада № 7-10-65 тіркелді. Күші жойылды - Батыс Қазақстан облысы Сырым аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 17-4 шешімі және Батыс Қазақстан облысы Сырым ауданы әкімдігінің 2009 жылғы 25 желтоқсандағы № 379 Қаулысымен
title:
  rus: Жымпиты ауылының Қаратөбе көшесінің атауын өзгерту туралы
  kaz: Жымпиты ауылының Қаратөбе көшесінің атауын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2009-10-28
approved_by:
- '159011000001'
- '159011000002'
version_date:
  kaz: 2009-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/48887/kaz/28.10.2009
