act_code: '4955'
requisite: Постановление Правительства Республики Казахстан от 11 августа 1999 года N 1143. Утратило силу постановлением Правительства РК от 14 июля 2006 года N 674
title:
  rus: Отдельные вопросы транзита продукции, подлежащей экспортному контролю
  kaz: Экспорттық бақылауға жататын өнімдер транзитінің кейбір мәселелері
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1999-08-10
approved_by:
- '103000000000'
version_date:
  rus: 2000-03-27
source:
  rus: https://zan.gov.kz/client/#!/doc/4955/rus/27.03.2000
caused_by:
  code: '5629'
  requisite: Постановление Правительства Республики Казахстан от 28 марта 2000 года N 450. Утратило силу постановлением Правительства РК от 14 июля 2006 года N 674 (вводится в действие со дня первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в постановление Правительства Республики Казахстан от 11 августа 1999 года N 1143
    kaz: Қазақстан Республикасы Yкiметiнің 1999 жылғы 11 тамыздағы N 1143 қаулысына өзгерiстер мен толықтыру енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/5629/rus
