act_code: '4598'
requisite: Постановление Правительства Республики Казахстан от 19 ноября 1999 года N 1754. Утратило силу - постановлением Правительства Республики Казахстан от 28 октября 2004 года N 1111
title:
  rus: Вопросы Министерства образования и науки Республики Казахстан
  kaz: Қазақстан Республикасы Білім және ғылым министрлігінің мәселелері
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 1999-11-19
approved_by:
- '103000000000'
version_date:
  rus: 2001-05-22
source:
  rus: https://zan.gov.kz/client/#!/doc/4598/rus/22.05.2001
caused_by:
  code: '8997'
  requisite: Постановление Правительства Республики Казахстан от 23 мая 2001 года № 692
  title:
    rus: О создании Республиканского государственного казенного предприятия "Институт гармоничного развития человека" Министерства образования и науки Республики Казахстан
    kaz: Қазақстан Республикасы Білім және ғылым министрлігінің "Адамның үйлесімді дамуы институты" республикалық мемлекеттік қазыналық кәсіпорнын құру туралы
  link: https://zan.gov.kz/client/#!/doc/8997/rus
