act_code: '4598'
requisite: Постановление Правительства Республики Казахстан от 19 ноября 1999 года N 1754. Утратило силу - постановлением Правительства Республики Казахстан от 28 октября 2004 года N 1111
title:
  rus: Вопросы Министерства образования и науки Республики Казахстан
  kaz: Қазақстан Республикасы Білім және ғылым министрлігінің мәселелері
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 1999-11-19
approved_by:
- '103000000000'
version_date:
  kaz: 2004-10-06
  rus: 2004-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/4598/kaz/06.10.2004
  rus: https://zan.gov.kz/client/#!/doc/4598/rus/06.10.2004
caused_by:
  code: '21453'
  requisite: Постановление Правительства Республики Казахстан от 7 октября 2004 года N 1041
  title:
    rus: О переименовании государственного учреждения "Республиканская казахская средняя музыкальная школа-интернат имени А. Жубанова"»Министерства образования и науки Республики Казахстан
    kaz: Қазақстан Республикасы Бiлiм және ғылым министрлігінiң "А. Жұбанов атындағы республикалық қазақ орта музыка мектеп-интернаты" мемлекеттiк мекемесiн қайта атау туралы
  link: https://zan.gov.kz/client/#!/doc/21453/rus
