act_code: '31787'
requisite: Оңтүстік Қазақстан облысы Сарыағаш ауданы әкімдігінің 2007 жылғы 23 қаңтардағы № 104 қаулысы. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2007 жылғы 7 ақпанда № 14-11-62 болып тіркелді
title:
  rus: Азаматтарды шақыру учаскелеріне тіркеу туралы
  kaz: Азаматтарды шақыру учаскелеріне тіркеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-01-23
approved_by:
- '166009000001'
version_date:
  kaz: 2007-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/31787/kaz/23.01.2007
