act_code: '160914'
requisite: Постановление акимата города Костаная Костанайской области от 23 ноября 2021 года № 2560. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 ноября 2021 года № 25467
title:
  rus: Об определении и утверждении мест размещения нестационарных торговых объектов на территории города Костаная
  kaz: Қостанай қаласының аумағында стационарлық емес сауда объектілерін орналастыру орындарын айқындау және бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2021-11-23
approved_by:
- '162002000001'
version_date:
  kaz: 2026-05-19
  rus: 2026-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/160914/kaz/19.05.2026
  rus: https://zan.gov.kz/client/#!/doc/160914/rus/19.05.2026
caused_by:
  code: '225784'
  requisite: Постановление акимата города Костаная Костанайской области от 19 мая 2026 года № 788
  title:
    rus: О внесении изменений в постановление акимата города Костаная от 23 ноября 2021 года № 2560 «Об определении и утверждении мест размещения нестационарных торговых объектов на территории города Костаная»
    kaz: Қостанай қаласы әкімдігінің 2021 жылғы 23 қарашадағы № 2560 «Қостанай қаласының аумағында стационарлық емес сауда объектілерін орналастыру орындарын айқындау және бекіту туралы» қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225784/rus
