act_code: '87707'
requisite: Постановление акимата Лебяжинского района Павлодарской области от 19 февраля 2015 года № 39/2. Зарегистрировано Департаментом юстиции Павлодарской области 17 марта 2015 года № 4370. Утратило силу постановлением акимата Лебяжинского района Павлодарской области от 7 ноября 2016 года № 263/11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Положения о государственном учреждении «Отдел занятости и социальных программ Лебяжинского района»
  kaz: «Лебяжі  аудандық  жұмыспен қамту және әлеуметтік бағдарламалар бөлімі» мемлекеттік мекемесі туралы  Ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-02-19
approved_by:
- '164009000001'
version_date:
  kaz: 2015-02-19
  rus: 2015-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/87707/kaz/19.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87707/rus/19.02.2015
