act_code: '15214'
requisite: Постановление Правительства Республики Казахстан от 28 апреля 2003 года № 407. Утратило силу постановлением Правительства Республики Казахстан от 21 февраля 2015 года № 85
title:
  rus: Об утверждении нормативных правовых актов в области ветеринарии
  kaz: Ветеринария саласындағы нормативтік құқықтық кесiмдердi бекiту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРАВ
approved_on: 2003-04-27
approved_by:
- '103000000000'
version_date:
  kaz: 2013-02-15
  rus: 2013-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/15214/kaz/15.02.2013
  rus: https://zan.gov.kz/client/#!/doc/15214/rus/15.02.2013
caused_by:
  code: '71084'
  requisite: Постановление Правительства Республики Казахстан от 15 февраля 2013 года № 136. Утратило силу постановлением Правительства Республики Казахстан от 21 февраля 2015 года № 85
  title:
    rus: О внесении изменений и дополнений в постановление Правительства Республики Казахстан от 28 апреля 2003 года № 407 "Об утверждении нормативных правовых актов в области ветеринарии"
    kaz: '"Ветеринария саласындағы нормативтік құқықтық кесімдерді бекіту туралы" Қазақстан Республикасы Үкіметінің 2003 жылғы 28 сәуірдегі № 407 қаулысына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/71084/rus
