act_code: '145946'
requisite: Постановление Сырдарьинского районного акимата Кызылординской области от 26 августа 2020 года № 183. Зарегистрировано Департаментом юстиции Кызылординской области 27 августа 2020 года № 7608
title:
  rus: Об определении и утверждении мест размещения нестационарных торговых объектов на территории Сырдарьинского района
  kaz: Сырдария ауданының аумағында стационарлық емес сауда объектілерін орналастыру орындарын айқындау және бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-08-26
approved_by:
- '161007000001'
version_date:
  kaz: 2023-05-24
  rus: 2023-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/145946/kaz/24.05.2023
  rus: https://zan.gov.kz/client/#!/doc/145946/rus/24.05.2023
caused_by:
  code: '183010'
  requisite: Постановление Сырдарьинского районного акимата Кызылординской области от 24 мая 2023 года № 166. Зарегистрировано Департаментом юстиции Кызылординской области 12 июня 2023 года № 8421-11
  title:
    rus: О внесении изменений в постановление акимата Сырдарьинского района от 26 августа 2020 года № 183 «Об утверждении мест размещения нестационарных торговых объектов на территории Сырдарьинского района»
    kaz: «Сырдария ауданының аумағында стационарлық емес сауда объектілерін орналастыру орындарын бекіту туралы» Сырдария ауданы әкімдігінің 2020 жылғы 26 тамыздағы № 183 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183010/rus
