act_code: '2831'
requisite: Постановление Правления Национального Банка Республики Казахстан от 31 декабря 1998 года N 339. Зарегистрировано в Министерстве юстиции Республики Казахстан 4.05.1999 г. за N 750. Утратило силу - постановлением Правления Агентства РК по регулированию и надзору финансового рынка и финансовых организаций от 25 октября 2004 года N 305
title:
  rus: Об утверждении изменений и дополнений в Положение о порядке перехода банков второго уровня к международным стандартам
  kaz: Екiншi деңгейдегi банктердiң халықаралық стандарттарға көшу тәртiбi туралы ережеге өзгерiстер мен толықтыруларды бекiту жөнінде
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-12-31
approved_by:
- '117000000000'
version_date:
  kaz: 1998-12-31
  rus: 1998-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/2831/kaz/31.12.1998
  rus: https://zan.gov.kz/client/#!/doc/2831/rus/31.12.1998
