act_code: '53199'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 30 апреля 2010 года № 59. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июня 2010 года № 6290. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 3 февраля 2014 года № 10
title:
  rus: Об утверждении Правил осуществления деятельности по управлению инвестиционным портфелем
  kaz: Инвестициялық портфельді басқару жөнiндегi қызметті жүзеге асыру ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРАВ
approved_on: 2010-04-30
approved_by:
- '109000000000'
version_date:
  kaz: 2013-08-27
  rus: 2013-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/53199/kaz/27.08.2013
  rus: https://zan.gov.kz/client/#!/doc/53199/rus/27.08.2013
caused_by:
  code: '74840'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 27 августа 2013 года № 215. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 октября 2013 года № 8799. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 19 декабря 2015 года № 254
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Республики Казахстан по вопросам регистрации операций с финансовыми инструментами
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне қаржы құралдарымен операцияларды тіркеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/74840/rus
