act_code: '44048'
requisite: Постановление Акимата города Лисаковска Костанайской области от 20 января 2009 года № 26. Зарегистрировано управлением юстиции города Лисаковска Костанайской области 5 февраля 2009 года № 9-4-135.  Утратило силу постановлением акимата города Лисаковска Костанайской области от 5 января 2010 года № 1
title:
  rus: Об организации бесплатного питания для воспитанников детских дошкольных организаций
  kaz: Мектеп жасына дейінгі балалар ұйымдарының тәрбиеленушілері үшін тегін тамақтандыруды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-01-20
approved_by:
- '162020000001'
version_date:
  kaz: 2009-07-28
  rus: 2009-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44048/kaz/28.07.2009
  rus: https://zan.gov.kz/client/#!/doc/44048/rus/28.07.2009
caused_by:
  code: '47453'
  requisite: Постановление акимата города Лисаковска Костанайской области от 28 июля 2009 года № 402. Зарегистрировано управлением юстиции города Лисаковска Костанайской области 19 августа 2009 года № 9-4-150. Утратило силу постановлением акимата города Лисаковска Костанайской области от 5 января 2010 года № 1
  title:
    rus: О внесении изменения в постановление акимата от 20 января 2009 года № 26 "Об организации бесплатного питания для воспитанников детских дошкольных организаций"
    kaz: '"Мектеп жасына дейінгі балалар ұйымдарының тәрбиеленушілері үшiн тегiн тамақтандыруды ұйымдастыру туралы" әкімдіктің 2009 жылғы 20 қаңтардағы № 26 қаулысына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47453/rus
