act_code: '105639'
requisite: Постановление акимата Кызылжарского района Северо-Казахстанской области от 19 августа 2016 года № 327. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 августа 2016 года № 3871
title:
  rus: Об определении сроков представления заявки для включения в список сельскохозяйственных производителей на получение субсидий по повышению урожайности и качества продукции растениеводства, стоимости горюче-смазочных материалов и других товарно-материальных ценностей, необходимых для проведения весенне-полевых и уборочных работ, путем субсидирования производства приоритетных культур и стоимости затрат на возделывание сельскохозяйственных культур в защищенном грунте по Кызылжарскому району Северо-Казахстанской области в 2016 году
  kaz: 2016 жылы Солтүстік Қазақстан облысы Қызылжар ауданы бойынша өсiмдiк шаруашылығының шығымдылығын және өнім сапасын арттыруға, жанар-жағармай материалдарының және көктемгi егіс пен егiн жинау жұмыстарын жүргiзу үшін қажеттi басқа да тауарлық-материалдық құндылықтардың құнына және ауыл шаруашылығы дақылдарын қорғалған топырақта өңдеп өсіру шығындарының құнына субсидия алу үшін ауылшаруашылық тауар өндірушілердің тізіміне енгізу үшін өтінім беру мерзімдерін анықтау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-08-19
approved_by:
- '165008000001'
version_date:
  kaz: 2016-08-19
  rus: 2016-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/105639/kaz/19.08.2016
  rus: https://zan.gov.kz/client/#!/doc/105639/rus/19.08.2016
