act_code: '28940'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 17 июня 2006 года № 136. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 июля 2006 года № 4301. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 8 мая 2015 года № 75
title:
  rus: Об утверждении Правил представления отчетности о выполнении пруденциальных нормативов банками второго уровня
  kaz: Екінші деңгейдегі банктердің пруденциалдық нормативтерді орындауы жөніндегі есеп беру ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2006-06-17
approved_by:
- '109000000000'
version_date:
  kaz: 2008-02-26
  rus: 2008-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/28940/kaz/26.02.2008
  rus: https://zan.gov.kz/client/#!/doc/28940/rus/26.02.2008
caused_by:
  code: '38708'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 26 февраля 2008 года № 21. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 марта 2008 года № 5175. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 8 мая 2015 года № 75
  title:
    rus: О внесении изменений и дополнений в постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 17 июня 2006 года № 136 "Об утверждении Правил представления отчетности о выполнении пруденциальных нормативов банками второго уровня"
    kaz: Қазақстан Республикасы Қаржы нарығын және қаржы ұйымдарын реттеу мен қадағалау агенттігі Басқармасының "Екінші деңгейдегі банктердің пруденциалдық нормативтерді орындауы жөніндегі есеп беру ережесін бекіту туралы" 2006 жылғы 17 маусымдағы № 136 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/38708/rus
