act_code: '4044'
requisite: Постановление Правления Национального Банка Республики Казахстан от 16 августа 1999 года № 271. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 сентября 1999 года № 888. Утратило силу - постановлением Правления Национального Банка Республики Казахстан от 6 декабря 2003 года № 445
title:
  rus: Об утверждении Правил лицензирования и регулирования деятельности организаций, осуществляющих отдельные виды банковских операций
  kaz: Банк операцияларының жекелеген түрлерін жүзеге асыратын ұйымдардың қызметін лицензиялау және реттеу ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 1999-08-15
approved_by:
- '117000000000'
version_date:
  kaz: 1999-08-15
  rus: 1999-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/4044/kaz/15.08.1999
  rus: https://zan.gov.kz/client/#!/doc/4044/rus/15.08.1999
