act_code: '34781'
requisite: Постановление Правления Национального Банка Республики Казахстан от 20 июля 2007 года № 81. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 августа 2007 года № 4867. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 27 июля 2012 года № 223
title:
  rus: О сроках составления аудиторского отчета финансовых организаций и его представления в уполномоченный орган по регулированию и надзору финансового рынка и финансовых организаций
  kaz: Қаржы ұйымдарының аудиторлық есебін жасау, оны қаржы нарығын және қаржы ұйымдарын реттеу мен қадағалау жөніндегі уәкілетті органға ұсыну мерзімдері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-07-20
approved_by:
- '117000000000'
version_date:
  kaz: 2007-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/34781/kaz/27.07.2007
caused_by:
  code: '67474'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 27 июля 2012 года № 223. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 сентября 2012 года № 7903. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 13 сентября 2019 года № 156 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О сроке составления аудиторского отчета финансовых организаций и его представления в Национальный Банк Республики Казахстан
    kaz: Қаржы ұйымдарының аудиторлық есебін жасау және оны Қазақстан Республикасының Ұлттық Банкіне ұсыну мерзімі туралы
  link: https://zan.gov.kz/client/#!/doc/67474/rus
