act_code: '79701'
requisite: Постановление акимата Актюбинской области от 9 апреля 2014 года № 103. Зарегистрировано Департаментом юстиции Актюбинской области 12 мая 2014 года № 3895. Утратило силу постановлением акимата Актюбинской области от 20 мая 2015 года № 154
title:
  rus: Об утверждении регламентов государственных услуг в области культуры
  kaz: Мәдениет саласындағы мемлекеттік көрсетілетін қызмет регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2014-04-09
approved_by:
- '153000000001'
version_date:
  kaz: 2014-04-09
  rus: 2014-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/79701/kaz/09.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79701/rus/09.04.2014
