act_code: '66937'
requisite: Постановление акимата Алматинской области от 12 июня 2012 года № 182. Зарегистрировано Департаментом юстиции Алматинской области 20 июля 2012 года за № 2100
title:
  rus: Об установлении границ охранной зоны и определении режима использования земель магистрального газопровода "Казахстан-Китай"
  kaz: '"Қазақстан-Қытай" магистральды газ құбырының күзету аймағы шекарасын белгілеу және жерді пайдалану режимін айқындау туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-06-12
approved_by:
- '154000000001'
version_date:
  kaz: 2012-06-12
  rus: 2012-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/66937/kaz/12.06.2012
  rus: https://zan.gov.kz/client/#!/doc/66937/rus/12.06.2012
