act_code: '70537'
requisite: Постановление акимата района Шал акына Северо-Казахстанской области от 21 декабря 2012 года № 391. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 января 2013 года № 2120. Утратило силу постановлением акимата района Шал акын Северо-Казахстанской области от 24 мая 2013 года № 142
title:
  rus: Об утверждении регламента электронной государственной услуги "Выдача справок в пенсионные фонды, банки для распоряжения вкладами несовершеннолетних детей, в территориальные подразделения Комитета дорожной полиции Министерства внутренних дел Республики Казахстан для оформления наследства несовершеннолетним детям"
  kaz: '"Зейнетақы қорларына, банктерге кәмелетке толмағандардың салымдарына иелік ету үшін, Қазақстан Республикасы Ішкі істер министрлігі Жол полициясы комитетінің аумақтық бөлімшелеріне кәмелетке толмаған балаларға мұраны ресімдеу үшін анықтамалар беру" электрондық мемлекеттік қызмет регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2012-12-21
approved_by:
- '165010000001'
version_date:
  kaz: 2012-12-21
  rus: 2012-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/70537/kaz/21.12.2012
  rus: https://zan.gov.kz/client/#!/doc/70537/rus/21.12.2012
