act_code: '115430'
requisite: Постановление акимата Алматинской области от 02 октября 2017 года № 405. Зарегистрировано Департаментом юстиции Алматинской области 20 октября 2017 года № 4348. Утратило силу постановлением акимата Алматинской области от 31 января 2020 года № 35
title:
  rus: Об утверждении регламентов государственных услуг в сфере долевого участия в жилищном строительстве
  kaz: Тұрғын үй құрылысына үлестік қатысу саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2017-10-02
approved_by:
- '154000000001'
version_date:
  kaz: 2019-04-25
  rus: 2019-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/115430/kaz/25.04.2019
  rus: https://zan.gov.kz/client/#!/doc/115430/rus/25.04.2019
caused_by:
  code: '131294'
  requisite: Постановление акимата Алматинской области от 25 апреля 2019 года № 161. Зарегистрировано Департаментом юстиции Алматинской области 2 мая 2019 года № 5126. Утратило силу постановлением акимата Алматинской области от 31 января 2020 года № 35
  title:
    rus: О внесении изменений в постановление акимата Алматинской области от 2 октября 2017 года № 405 «Об утверждении регламентов государственных услуг в сфере долевого участия в жилищном строительстве»
    kaz: Алматы облысы әкімдігінің 2017 жылғы 2 қазандағы «Тұрғын үй құрылысына үлестік қатысу саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы» № 405 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131294/rus
