act_code: '24080'
requisite: Постановление Восточно-Казахстанского областного Акимата от 13 мая 2005 года N 192. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 мая 2005 года за N 2348. Утратило силу письмом акимата Восточно-Казахстанской области от 16 мая 2006 года N 6/1637 в связи с истечением срока действия
title:
  rus: О мерах по усилению противопожарной защиты лесов и населенных пунктов Восточно-Казахстанской области в пожароопасный период 2005 года
  kaz: 2005 жылғы өрт қауіптілігі маусымында Шығыс Қазақстан облысының ормандары мен елді мекендерін өртке қарсы қорғауды күшейту жөніндегі шаралар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2005-05-13
approved_by:
- '157000000001'
version_date:
  kaz: 2005-05-13
  rus: 2005-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/24080/kaz/13.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24080/rus/13.05.2005
