act_code: '428'
requisite: Постановление Правительства Республики Казахстан от 12 ноября 1997 г. № 1556 . Утратило силу - постановлением Правительства РК от 12 марта 1999 г. N 233
title:
  rus: Вопросы Министерства образования, культуры и здравоохранения Республики Казахстан
  kaz: Қазақстан Республикасы Бiлiм, мәдениет және денсаулық сақтау министрлiгiнiң мәселелерi туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 1997-11-12
approved_by:
- '103000000000'
version_date:
  rus: 1999-01-29
source:
  rus: https://zan.gov.kz/client/#!/doc/428/rus/29.01.1999
caused_by:
  code: '2100'
  requisite: Постановление Правительства Республики Казахстан от 29 января 1999 года N 70 . Утратило силу - постановлением Правительства РК от 27 января 2000 г. N 135
  title:
    rus: Об утверждении перечня бесплатного гарантированного объема медицинской помощи гражданам, финансируемого за счет средств республиканского и местных бюджетов на 1999 год в рамках государственного заказа
    kaz: Азаматтарға 1999 жылға арналған республикалық және жергілікті бюджеттер қаражатының есебінен мемлекеттік тапсырыстың шеңберінде қаржыландырылатын медициналық көмектің тегін кепілдендірілген көлемінің тізбесін бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/2100/rus
