act_code: '165654'
requisite: Постановление акимата Карагандинской области от 15 марта 2022 года № 15/02. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 марта 2022 года № 27237
title:
  rus: Об утверждении объемов бюджетных средств на субсидирование развития семеноводства на 2022 год
  kaz: 2022 жылға тұқым шаруашылығын дамытуды субсидиялауға арналған бюджет қаражатының көлемін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-03-15
approved_by:
- '160000000001'
version_date:
  kaz: 2022-08-17
  rus: 2022-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/165654/kaz/17.08.2022
  rus: https://zan.gov.kz/client/#!/doc/165654/rus/17.08.2022
caused_by:
  code: '170864'
  requisite: Постановление акимата Карагандинской области от 17 августа 2022 года № 53/02. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 августа 2022 года № 29227
  title:
    rus: О внесении изменения в постановление акимата Карагандинской области от 15 марта 2022 года № 15/02 «Об утверждении объемов субсидий на субсидирование развития семеноводства на 2022 год»
    kaz: Қарағанды облысы әкімдігінің 2022 жылғы 15 наурыздағы № 15/02 «2022 жылға тұқым шаруашылығын дамытуды субсидиялауға арналған субсидиялар көлемдерін бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170864/rus
