act_code: '209528'
requisite: Постановление акимата города Семей области Абай от 23 апреля 2025 года № 347
title:
  rus: Об утверждении Правил предоставления коммунальных услуг по городу Семей
  kaz: Семей қаласы бойынша коммуналдық қызметтерді ұсыну қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2025-04-23
approved_by:
- '168002000001'
version_date:
  kaz: 2025-04-23
  rus: 2025-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/209528/kaz/23.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209528/rus/23.04.2025
