act_code: '65247'
requisite: Постановление Правительства Республики Казахстан от 5 мая 2012 года № 578. Утратило силу постановлением Правительства Республики Казахстан от 25 апреля 2015 года № 312
title:
  rus: Об утверждении Правил учета иностранцев, желающих усыновить детей, являющихся гражданами Республики Казахстан
  kaz: Қазақстан Республикасының азаматтары болып табылатын балаларды асырап алуға тілек білдірген шетелдіктерді есепке алу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
- СПРА
approved_on: 2012-05-05
approved_by:
- '103000000000'
version_date:
  kaz: 2012-05-05
  rus: 2012-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/65247/kaz/05.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65247/rus/05.05.2012
