act_code: '134644'
requisite: Постановление Правительства Республики Казахстан от 12 сентября 2019 года № 687
title:
  rus: О принятии акций акционерного общества «Казтелерадио» из частной собственности в республиканскую собственность по договору дарения
  kaz: «Қазтелерадио» акционерлік қоғамының акцияларын сыйға тарту шарты бойынша жеке меншіктен республикалық меншікке қабылдау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-09-12
approved_by:
- '103000000000'
version_date:
  kaz: 2023-10-04
  rus: 2023-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/134644/kaz/04.10.2023
  rus: https://zan.gov.kz/client/#!/doc/134644/rus/04.10.2023
caused_by:
  code: '187008'
  requisite: Постановление Правительства Республики Казахстан от 4 октября 2023 года № 866
  title:
    rus: О некоторых вопросах Министерства культуры и информации Республики Казахстан
    kaz: Қазақстан Республикасының Мәдениет және ақпарат министрлігінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/187008/rus
