act_code: '121162'
requisite: Постановление акимата Майского района Павлодарской области от 3 апреля 2018 года № 58/4. Зарегистрировано Департаментом юстиции Павлодарской области 19 апреля 2018 года № 5957
title:
  rus: Об утверждении методики оценки деятельности  административных государственных служащих корпуса «Б» исполнительных органов акимата Майского района
  kaz: Май ауданы әкімдігі атқарушы органдары «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: ПОСТ
type_codes:
- МЕТ
- ПОСТ
approved_on: 2018-04-03
approved_by:
- '164010000001'
version_date:
  kaz: 2022-03-14
  rus: 2022-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/121162/kaz/14.03.2022
  rus: https://zan.gov.kz/client/#!/doc/121162/rus/14.03.2022
caused_by:
  code: '165232'
  requisite: Постановление акимата Майского района Павлодарской области от 14 марта 2022 года № 42/3
  title:
    rus: О внесении изменений в постановление акимата Майского района от 3 апреля 2018 года № 58/4 «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» исполнительных органов акимата Майского района»
    kaz: Май ауданы әкімдігінің 2018 жылғы 3 сәуірдегі «Май ауданы әкімдігі атқарушы органдары «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» № 58/4 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165232/rus
