act_code: '48335'
requisite: Шығыс Қазақстан облысы Күршім ауданы әкімдігінің 2009 жылғы 1 қазандағы № 1343 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық Әділет басқармасында 2009 жылғы 27 қазанда № 5-14-95 тіркелді. Күші жойылды - Күршім ауданы әкімдігінің 2010 жылғы 29 қаңтардағы № 1508 қаулысымен
title:
  rus: Жастарды әлеуметтік қорғау шаралары туралы
  kaz: Жастарды әлеуметтік қорғау шаралары туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-10-01
approved_by:
- '157016000001'
version_date:
  kaz: 2009-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/48335/kaz/01.10.2009
