act_code: '50583'
requisite: Постановление акимата Лебяжинского района Павлодарской области от 27 января 2010 года № 7/1. Зарегистрировано Управлением юстиции Лебяжинского района Павлодарской области 9 февраля 2010 года № 12-9-104
title:
  rus: О социальной помощи отдельным категориям граждан Лебяжинского района на 2010 год
  kaz: Лебяжі ауданының жекелеген санаттағы азаматтарына 2010 жылға арналған әлеуметтік көмек көрсету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-01-27
approved_by:
- '164009000001'
version_date:
  kaz: 2010-02-26
  rus: 2010-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/50583/kaz/26.02.2010
  rus: https://zan.gov.kz/client/#!/doc/50583/rus/26.02.2010
caused_by:
  code: '51228'
  requisite: Постановление акимата Лебяжинского района Павлодарской области от 26 февраля 2010 года № 25/2. Зарегистрировано Управлением юстиции Лебяжинского района Павлодарской области 11 марта 2010 года № 12-9-108
  title:
    rus: О внесении изменений и дополнений в постановление акимата Лебяжинского района от 27 января 2010 года № 7/1 "О социальной помощи отдельным категориям граждан Лебяжинского района на 2010 год"
    kaz: Лебяжі ауданы әкімдігінің 2010 жылғы 27 қаңтардағы "Лебяжі ауданының жекелеген санаттағы азаматтарына 2010 жылға арналған әлеуметтік көмек көрсету туралы" № 7/1 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51228/rus
