act_code: '21822'
requisite: Постановление Правительства Республики Казахстан от 11 ноября 2004 года N 1185. Утратило силу постановлением Правительства Республики Казахстан от 10 августа 2015 года № 624
title:
  rus: Об определении социально значимых межобластных сообщений
  kaz: Әлеуметтік мәні бар облысаралық қатынастарды айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-11-11
approved_by:
- '103000000000'
version_date:
  kaz: 2012-12-14
  rus: 2012-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/21822/kaz/14.12.2012
  rus: https://zan.gov.kz/client/#!/doc/21822/rus/14.12.2012
caused_by:
  code: '69221'
  requisite: Постановление Правительства Республики Казахстан от 14 декабря 2012 года № 1592. Утратило силу постановлением Правительства Республики Казахстан от 10 августа 2015 года № 624
  title:
    rus: О внесении дополнений в постановление Правительства Республики Казахстан от 11 ноября 2004 года № 1185 "Об определении социально значимых межобластных сообщений"
    kaz: '"Әлеуметтік мәні бар облысаралық қатынастарды айқындау туралы" Қазақстан Республикасы Үкіметінің 2004 жылғы 11 қарашадағы № 1185 қаулысына толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/69221/rus
