act_code: '4360'
requisite: Постановление Правления Национального Банка Республики Казахстан от 23 мая 1997 года N 219. Зарегистрировано в Министерстве юстиции 23 июня 1997 г. N 325. Утратило силу (со дня введения в действие постановления Правления НБ РК от 3.06.2002г. № 213) - постановлением Правления Национального Банка Республики Казахстан от 3.06.2002г. № 213
title:
  rus: О Правилах о пруденциальных нормативах
  kaz: '"Пруденциалдық нормативтер туралы ережелер" Ереже жөнiнде'
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 1997-05-22
approved_by:
- '117000000000'
version_date:
  kaz: 2000-11-25
  rus: 2000-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/4360/kaz/25.11.2000
  rus: https://zan.gov.kz/client/#!/doc/4360/rus/25.11.2000
caused_by:
  code: '7756'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 25 ноября 2000 года № 435 Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2000 года № 1345. Утратило силу постановлением Правления Национального Банка РК от 1 ноября 2010 года № 88
  title:
    rus: Об утверждении Изменения в Правила о пруденциальных нормативах, утвержденные постановлением Правления Национального Банка Республики Казахстан от 23 мая 1997 года № 219 "О Положении "О пруденциальных нормативах"
    kaz: Қазақстан Республикасының Ұлттық Банкi Басқармасының "Пруденциалдық нормативтер туралы" ереже туралы" 1997 жылғы 23 мамырдағы N 219 қаулысымен бекiтiлген Пруденциалдық нормативтер туралы ережеге өзгерiстi бекiту туралы
  link: https://zan.gov.kz/client/#!/doc/7756/rus
