act_code: '70171'
requisite: Постановление акимата города Уральска Западно-Казахстанской области от 13 декабря 2012 года № 3194. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 18 января 2013 года № 3160. Утратило силу постановлением акимата города Уральска Западно-Казахстанской области от 30 декабря 2013 года № 4111
title:
  rus: Об организации и финансировании общественных работ на 2013 год по городу Уральск
  kaz: Орал қаласы бойынша 2013 жылы қоғамдық жұмыстарды ұйымдастыру және қаржыландыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-12-13
approved_by:
- '159002000001'
version_date:
  kaz: 2013-10-10
  rus: 2013-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/70171/kaz/10.10.2013
  rus: https://zan.gov.kz/client/#!/doc/70171/rus/10.10.2013
caused_by:
  code: '75015'
  requisite: Постановление акимата города Уральска Западно-Казахстанской области от 10 октября 2013 года № 3104. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 30 октября 2013 года № 3353. Утратило силу постановлением акимата города Уральска Западно-Казахстанской области от 30 декабря 2013 года № 4111
  title:
    rus: О внесении дополнений в постановление акимата города Уральска от 13 декабря 2012 года № 3194 "Об организации и финансировании общественных работ на 2013 год по городу Уральск"
    kaz: Орал қаласы әкімдігінің 2012 жылғы 13 желтоқсандағы № 3194 "Орал қаласы бойынша 2013 жылы қоғамдық жұмыстарды ұйымдастыру және қаржыландыру туралы" қаулысына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75015/rus
