act_code: '92061'
requisite: Постановление Кызылординского областного акимата от 12 июня 2015 года № 37. Зарегистрировано Департаментом юстиции Кызылординской области 23 июля 2015 года № 5068. Утратило силу постановлением акимата Кызылординской области от 15 ноября 2019 года № 98
title:
  rus: Об утверждении регламентов государственных услуг в сфере архитектуры, градостроительства и строительства
  kaz: Сәулет, қала құрылысы және құрылыс саласындағы мемлекеттік көрсетілетін қызметтердің регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-06-12
approved_by:
- '161000000001'
version_date:
  kaz: 2015-06-12
  rus: 2015-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/92061/kaz/12.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92061/rus/12.06.2015
