act_code: '188516'
requisite: Постановление Правительства Республики Казахстан от 17 ноября 2023 года № 1011
title:
  rus: О некоторых вопросах предоставления исключительного права на экспорт отдельных видов углей
  kaz: Жекелеген көмір түрлерінің экспортына айрықша құқық берудің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2023-11-17
approved_by:
- '103000000000'
version_date:
  kaz: 2024-10-18
  rus: 2024-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/188516/kaz/18.10.2024
  rus: https://zan.gov.kz/client/#!/doc/188516/rus/18.10.2024
caused_by:
  code: '201848'
  requisite: Постановление Правительства Республики Казахстан от 18 октября 2024 года № 861
  title:
    rus: О внесении изменений и дополнений в постановление Правительства Республики Казахстан от 17 ноября 2023 года № 1011 «О некоторых вопросах предоставления исключительного права на экспорт отдельных видов углей»
    kaz: «Жекелеген көмір түрлерінің экспортына айрықша құқық берудің кейбір мәселелері туралы» Қазақстан Республикасы Үкіметінің 2023 жылғы 17 қарашадағы № 1011 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201848/rus
