act_code: '104613'
requisite: Постановление Правления Национального Банка Республики Казахстан от 30 мая 2016 года № 144. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2016 года № 13939. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 28 апреля 2026 года № 85 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении пруденциальных нормативов и иных обязательных к соблюдению норм и лимитов для исламских банков, их нормативных значений и методики расчетов пруденциальных нормативов и иных обязательных к соблюдению норм и лимитов для исламских банков
  kaz: Ислам банктері үшін пруденциалдық нормативтерді және өзге де сақтауға міндетті нормалар мен лимиттерді, олардың нормативтік мәнін және ислам банктері үшін пруденциалдық нормативтерді және өзге де сақтауға міндетті нормалар мен лимиттерді есеп айырысу әдістемесін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-05-30
approved_by:
- '117000000000'
version_date:
  kaz: 2021-04-16
  rus: 2021-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/104613/kaz/16.04.2021
  rus: https://zan.gov.kz/client/#!/doc/104613/rus/16.04.2021
caused_by:
  code: '155260'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 16 апреля 2021 года № 56. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 апреля 2021 года № 22620
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам регулирования финансового рынка
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне қаржы нарығын реттеу мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155260/rus
