act_code: '27787'
requisite: Постановление акимата Енбекшильдерского района Акмолинской области от 20 апреля 2006 года № а-3/66. Зарегистрировано Управлением юстиции Енбекшильдерского района Акмолинской области 26 апреля 2006 года № 1-10-38
title:
  rus: О проведении очередного призыва граждан на срочную военную службу в апреле-июне и октябре-декабре 2006 года, отбор кандидатов в военные высшие учебные заведения из числа гражданской молодежи
  kaz: 2006 жылдың сәуір-маусым және қазан-желтоқсан айларында азаматтарды мерзімді әскери қызметке шақыруды өткізу, азаматтық жастар қатарынан жоғары әскери оқу орындарында үміткерлерді алдын ала кәсіби іріктеуден өткізу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-04-20
approved_by:
- '152010007001'
version_date:
  kaz: 2006-04-20
  rus: 2006-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/27787/kaz/20.04.2006
  rus: https://zan.gov.kz/client/#!/doc/27787/rus/20.04.2006
