act_code: '132265'
requisite: Постановление Восточно-Казахстанского областного акимата от 30 мая 2019 года № 180. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 июня 2019 года № 6001
title:
  rus: Об установлении водоохранной зоны и водоохранной полосы на участке правобережья Бухтарминского водохранилища от ручья Урунхайка в поселке Октябрьский до причала паромной переправы «Октябрьская» в районе Алтай Восточно-Казахстанской области и режима их хозяйственного использования
  kaz: Шығыс Қазақстан облысы Алтай ауданы Октябрьский кентіндегі Урунхайка бұлағынан «Октябрьская» паром өткелі айлағына дейін Бұқтырма су қоймасының оң жақ жағалау учаскесінде су қорғау аймағы мен су қорғау белдеуін және оларды шаруашылыққа пайдалану режимін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-05-30
approved_by:
- '157000000001'
version_date:
  kaz: 2019-05-30
  rus: 2019-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/132265/kaz/30.05.2019
  rus: https://zan.gov.kz/client/#!/doc/132265/rus/30.05.2019
