act_code: '45202'
requisite: Постановление от 06.04.2009 №1249, Акимат г. Кызылорды
title:
  rus: Он сегізден жиырма жеті жасқа дейінгі азаматтарды мерзімді әскери қызметке шақыру туралы
  kaz: Он сегізден жиырма жеті жасқа дейінгі азаматтарды мерзімді әскери қызметке шақыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-04-06
approved_by:
- '161002000001'
version_date:
  kaz: 2009-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/45202/kaz/06.04.2009
