act_code: '112495'
requisite: Постановление Правления Национального Банка Республики Казахстан от 27 марта 2017 года № 53. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 мая 2017 года № 15115
title:
  rus: Об утверждении условий и минимальных требований к порядку предоставления информации поставщиками информации в кредитные бюро, Правил оформления согласия субъектов кредитных историй на предоставление информации о них в кредитные бюро (за исключением кредитного бюро с государственным участием), оформления согласия на выдачу кредитного отчета о нем другим лицам из кредитного бюро, а также Правил и условий предоставления кредитного отчета
  kaz: Ақпарат берушiлердiң кредиттiк бюроларға ақпарат беру тәртiбiнiң шарттары мен ең төмен талаптарын, Кредиттiк тарих субъектiлерiнiң өздерi туралы ақпаратты кредиттiк бюроларға (мемлекет қатысатын кредиттік бюроны қоспағанда) беруге келiсiмiн ресiмдеу, кредиттік бюродан басқа адамдарға ол туралы кредиттiк есептi беруге келiсiмiн ресімдеу қағидаларын, сондай-ақ Кредиттiк есептi берудiң қағидалары мен шарттарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
- УСЛ
approved_on: 2017-03-27
approved_by:
- '117000000000'
version_date:
  kaz: 2023-03-01
  rus: 2023-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/112495/kaz/01.03.2023
  rus: https://zan.gov.kz/client/#!/doc/112495/rus/01.03.2023
caused_by:
  code: '171699'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 12 сентября 2022 года № 68. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 сентября 2022 года № 29628
  title:
    rus: О внесении изменения в постановление Правления Национального Банка Республики Казахстан от 27 марта 2017 года № 53 «Об утверждении условий и минимальных требований к порядку предоставления информации поставщиками информации в кредитные бюро, Правил оформления согласия субъектов кредитных историй на предоставление информации о них в кредитные бюро (за исключением кредитного бюро с государственным участием), оформления согласия на выдачу кредитного отчета из кредитного бюро, а также Правил и условий предоставления кредитного отчета»
    kaz: «Ақпарат берушiлердiң кредиттiк бюроларға ақпарат беру тәртiбiнiң шарттары мен ең төмен талаптарын, Кредиттiк тарих субъектiлерiнiң өздерi туралы ақпаратты кредиттiк бюроларға (мемлекет қатысатын кредиттік бюроны қоспағанда) беруге келiсiмiн ресiмдеу, кредиттік бюродан кредиттiк есептi беруге келiсiмiн ресімдеу қағидаларын, сондай-ақ Кредиттiк есептi берудiң қағидалары мен шарттарын бекіту туралы» Қазақстан Республикасы Ұлттық Банкі Басқармасының 2017 жылғы 27 наурыздағы № 53 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171699/rus
