act_code: '38874'
requisite: Решение маслихата Южно-Казахстанской области N 5/80-IV от 27 марта 2008 года и постановление акимата Южно-Казахстанской области N 82 от 28 марта 2008 года. Зарегистрировано департаментом Юстиции Южно-Казахстанской области от 15 апреля 2008 года за N 1977
title:
  rus: О переименовании отдельных административно-территориальных единиц Южно-Казахстанской области
  kaz: Оңтүстік Қазақстан облысының жекелеген әкімшілік-аумақтық бірліктерін қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2008-03-27
approved_by:
- '166000000001'
- '166000000002'
version_date:
  kaz: 2008-03-27
  rus: 2008-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/38874/kaz/27.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38874/rus/27.03.2008
