act_code: '33748'
requisite: Постановление акимата Карасуского района Костанайской области от 28 мая 2007 года № 89. Зарегистрировано Управлением юстиции Карасуского района Костанайской области 20 июня 2007 года № 9-13-39
title:
  rus: Об определении стационарного помещения, предназначенного для розничной торговли периодическими печатными изданиями, публикующими материалы эротического характера
  kaz: Эротикалық сипаттағы материалдар жариялайтын мерзімді баспасөз басылымдарын бөлшек сатуға арналған стационарлық үй-жайды белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-05-28
approved_by:
- '162011000001'
version_date:
  kaz: 2007-05-28
  rus: 2007-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/33748/kaz/28.05.2007
  rus: https://zan.gov.kz/client/#!/doc/33748/rus/28.05.2007
