act_code: '92204'
requisite: Постановление акимата города Алматы от 08 июля 2015 года № 3/429. Зарегистрировано в Департаменте юстиции города Алматы 30 июля 2015 года № 1187
title:
  rus: 'О лишении статуса памятников истории и культуры местного значения и исключении их из Государственного списка памятников истории и культуры местного значения города Алматы '
  kaz: 'Алматы қаласының жергілікті маңызы бар тарих және мәдениет ескерткіштерін мәртебесінен айыру және оларды жергілікті маңызы бар Тарих және мәдениет ескерткіштерінің мемлекеттік тізімінен шығарып тастау туралы '
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2015-07-08
approved_by:
- '155000000001'
version_date:
  kaz: 2016-12-02
  rus: 2016-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/92204/kaz/02.12.2016
  rus: https://zan.gov.kz/client/#!/doc/92204/rus/02.12.2016
caused_by:
  code: '108463'
  requisite: Постановление акимата города Алматы от 2 декабря 2016 года № 4/565. Зарегистрировано Департаментом юстиции города Алматы 23 декабря 2016 года № 1335
  title:
    rus: О внесении изменения в постановление акимата города Алматы от 8 июля 2015 года № 3/429 «О лишении статуса памятников истории и культуры местного значения и исключении их из Государственного списка памятников истории и культуры местного значения города Алматы»
    kaz: Алматы қаласы әкімдігінің «Алматы қаласының жергілікті маңызы бар тарих және мәдениет ескерткіштерін мәртебесінен айыру және оларды жергілікті маңызы бар Тарих және мәдениет ескерткіштерінің Мемлекеттік тізімінен шығарып тастау туралы» 2015 жылғы 8 шілдедегі № 3/429 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108463/rus
