act_code: '148615'
requisite: Постановление Правительства Республики Казахстан от 24 сентября 2020 года № 612
title:
  rus: Об утверждении перечня заболеваний, против которых проводятся обязательные профилактические прививки в рамках гарантированного объема медицинской помощи, правил, сроков их проведения и групп населения, подлежащих профилактическим прививкам
  kaz: Медициналық көмектің кепілдік берілген көлемі шеңберінде оларға қарсы міндетті профилактикалық екпелер жүргізілетін аурулардың тізбесін, екпелерді жүргізу қағидаларын, мерзімдерін және халықтың профилактикалық екпелерге жататын топтарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2020-09-24
approved_by:
- '103000000000'
version_date:
  kaz: 2020-09-24
  rus: 2020-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/148615/kaz/24.09.2020
  rus: https://zan.gov.kz/client/#!/doc/148615/rus/24.09.2020
