act_code: '173764'
requisite: Постановление акимата Аягозского района области Абай от 27 октября 2022 года № 595
title:
  rus: Об установлении квоты рабочих мест для трудоустройства лиц, состоящих на учете службы пробации, а также для лиц, освобожденных из мест лишения свободы
  kaz: Пробация қызметінің есебінде тұрған адамдарды, сондай-ақ бас бостандығынан айыру орындарынан босатылған адамдарды жұмысқа орналастыру үшін жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-10-27
approved_by:
- '168006000001'
version_date:
  kaz: 2022-10-27
  rus: 2022-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/173764/kaz/27.10.2022
  rus: https://zan.gov.kz/client/#!/doc/173764/rus/27.10.2022
