act_code: '27052'
requisite: Шығыс Қазахстан облысы Тарбағатай ауданы әкімдігінің 2006 жылғы 6 наурыздағы № 127 қаулысы. Шығыс Қазақстан облысының Әділет департаментінің Тарбағатай аудандық Әділет басқармасында 2006 жылғы 14 наурызда № 5-16-13 тіркелді
title:
  rus: Аудандағы елдi мекендердi тазарту және көркейтуге байланысты  санитарлық тазалық жүргiзу туралы
  kaz: Аудандағы елдi мекендердi тазарту және көркейтуге байланысты  санитарлық тазалық жүргiзу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-03-06
approved_by:
- '157017000001'
version_date:
  kaz: 2006-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/27052/kaz/06.03.2006
