act_code: '7321'
requisite: Постановление Правительства Республики Казахстан от 10 ноября 2000 года N 1693. Утратило силу постановлением Правительства Республики Казахстан от 12 декабря 2014 года № 1315
title:
  rus: Об утверждении Правил осуществления государственного контроля над оборотом наркотических средств, психотропных веществ и прекурсоров в Республике Казахстан
  kaz: Қазақстан Республикасында есiрткi құралдары, психотроптық заттар және прекурсорлар айналымын мемлекеттік бақылауды жүзеге асыру ережесін бекiту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРАВ
approved_on: 2000-11-10
approved_by:
- '103000000000'
version_date:
  rus: 2001-02-16
source:
  rus: https://zan.gov.kz/client/#!/doc/7321/rus/16.02.2001
caused_by:
  code: '8160'
  requisite: Постановление Правительства Республики Казахстан от 16 февраля 2001 года N 247. Утратило силу постановлением Правительства Республики Казахстан от 12 декабря 2014 года № 1315
  title:
    rus: О внесении изменения и дополнения в постановление Правительства Республики Казахстан от 10 ноября 2000 года N 1693
    kaz: Қазақстан Республикасы Үкіметінің 2000 жылғы 10 қарашадағы N 1693 қаулысына өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/8160/rus
