act_code: '50729'
requisite: Постановление Правительства Республики Казахстан от 15 февраля 2010 года № 91
title:
  rus: Об утверждении Правил использования целевых текущих трансфертов из республиканского бюджета 2010 года областными бюджетами, бюджетами городов Астаны и Алматы на обеспечение закладки и выращивания многолетних насаждений плодово-ягодных культур и винограда
  kaz: Облыстық бюджеттердің, Астана және Алматы қалалары бюджеттерінің жеміс-жидек дақылдарының және жүзімнің көп жылдық екпелерін отырғызу мен өсіруді қамтамасыз етуге 2010 жылғы республикалық бюджеттен бөлінетін ағымдағы нысаналы трансферттерді пайдалану ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2010-02-15
approved_by:
- '103000000000'
version_date:
  kaz: 2010-02-15
  rus: 2010-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/50729/kaz/15.02.2010
  rus: https://zan.gov.kz/client/#!/doc/50729/rus/15.02.2010
