act_code: '98929'
requisite: Постановление Правления Национального Банка Республики Казахстан от 19 декабря 2015 года № 227. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 февраля 2016 года № 13057. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 14 декабря 2020 года № 116 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении форм, сроков и периодичности предоставления ликвидационной комиссией добровольно и принудительно ликвидируемых банков отчетов и дополнительной информации
  kaz: Ерікті және мәжбүрлеп таратылатын банктердің тарату комиссиясының есеп және қосымша ақпарат беру нысандарын, мерзімдері мен кезеңділігін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-12-19
approved_by:
- '117000000000'
version_date:
  kaz: 2015-12-19
  rus: 2015-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/98929/kaz/19.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98929/rus/19.12.2015
