act_code: '59610'
requisite: Постановление акимата Акмолинской области от 13 июня 2011 года № А-5/220. Зарегистрировано Департаментом юстиции Акмолинской области 14 июля 2011 года № 3395. Утратило силу - постановлением акимата Акмолинской области от 26 ноября 2012 года № А-12/555
title:
  rus: Об утверждении регламента государственной услуги "Регистрация договора залога права недропользования на разведку, добычу и на совмещенную разведку и добычу общераспространенных полезных ископаемых"
  kaz: '"Барлауға, өндіруге және бірлескен барлауға және жалпыға таралған пайдалы қазбаларды өндіруге жер қойнауын пайдалану құқығы кепілдігі шартын тіркеу" мемлекеттік қызметтің регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2011-06-13
approved_by:
- '152000000001'
version_date:
  kaz: 2011-06-13
  rus: 2011-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/59610/kaz/13.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59610/rus/13.06.2011
