act_code: '5942'
requisite: Постановление Правительства Республики Казахстан от 10 мая 2000 года № 685. Утратило силу постановлением Правительства Республики Казахстан от 19 июля 2011 года № 830
title:
  rus: О премиях в области науки
  kaz: Ғылым саласындағы сыйлықтар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2000-05-09
approved_by:
- '103000000000'
version_date:
  rus: 2000-05-09
source:
  rus: https://zan.gov.kz/client/#!/doc/5942/rus/09.05.2000
