act_code: '20584'
requisite: Нормативное постановление Верховного Суда Республики Казахстан от 18 июня 2004 года N 2. Утратило силу нормативным постановлением Верховного Суда Республики Казахстан от 24 января 2020 года № 3 (вводится в действие со дня первого официального опубликования)
title:
  rus: О некоторых вопросах квалификации уголовных правонарушений в сфере экономической деятельности
  kaz: Экономикалық қызмет саласындағы қылмыстық құқық бұзушылықтарды саралаудың кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-06-17
approved_by:
- '105000000000'
version_date:
  kaz: 2014-04-04
  rus: 2014-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/20584/kaz/04.04.2014
  rus: https://zan.gov.kz/client/#!/doc/20584/rus/04.04.2014
caused_by:
  code: '78912'
  requisite: Нормативное постановление Верховного суда Республики Казахстан от 4 апреля 2014 года № 1. Утратило силу нормативным постановлением Верховного Суда Республики Казахстан от 24 января 2020 года № 3 (вводится в действие со дня первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в нормативное постановление Верховного суда Республики Казахстан "О некоторых вопросах квалификации преступлений в сфере экономической деятельности" № 2 от 18 июня 2004 года (с изменениями и дополнениями, внесенными нормативным постановлением Верховного суда Республики Казахстан № 1 от 21 апреля 2011 года)
    kaz: '"Экономикалық қызмет саласындағы қылмыстарды саралаудың кейбір мәселелері туралы" Қазақстан Республикасы Жоғарғы Сотының 2004 жылғы 18 маусымдағы № 2 нормативтік қаулысына (Қазақстан Республикасы Жоғарғы Сотының 2011 жылғы 21 сәуірдегі № 1 нормативтік қаулысымен енгізілген өзгерістерімен және толықтыруларымен бірге) өзгерістер мен толықтырулар енгізу туралы"'
  link: https://zan.gov.kz/client/#!/doc/78912/rus
