act_code: '4337'
requisite: Постановление Правительства Республики Казахстан от 21 октября 1999 года N 1578. Утратило силу - постановлением Правительства РК от 28 октября 2004 г. N 1118 (P041118)
title:
  rus: Вопросы Министерства иностранных дел Республики Казахстан
  kaz: Қазақстан Республикасы Сыртқы істер министрлігінің мәселелері
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 1999-10-20
approved_by:
- '103000000000'
version_date:
  kaz: 2002-09-25
  rus: 2002-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/4337/kaz/25.09.2002
  rus: https://zan.gov.kz/client/#!/doc/4337/rus/25.09.2002
caused_by:
  code: '13239'
  requisite: Постановление Правительства Республики Казахстан от 26 сентября 2002 года № 1060. Утратило силу постановлением Правительства Республики Казахстан от 28 октября 2004 года № 1118
  title:
    rus: Некоторые вопросы Министерства иностранных дел Республики Казахстан
    kaz: Қазақстан Республикасы Сыртқы істер министрлігінің кейбір мәселелері
  link: https://zan.gov.kz/client/#!/doc/13239/rus
