act_code: '139834'
requisite: Постановление акимата Курчумского района Восточно-Казахстанской области от 19 февраля 2020 года № 56. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 февраля 2020 года № 6737
title:
  rus: Об утверждении перечня автомобильных дорог районного значения Курчумского района
  kaz: Күршім ауданының аудандық маңызы бар автомобиль жолдарының тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-02-19
approved_by:
- '157016000001'
version_date:
  kaz: 2020-02-19
  rus: 2020-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/139834/kaz/19.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139834/rus/19.02.2020
