act_code: '24300'
requisite: Постановление Акимата города Алматы от 12 апреля 2005 года N 2/211. Зарегистрировано Департаментом юстиции города Алматы 20 мая 2005 года за N 658. Утратило силу постановлением акимата города Алматы от 22 января 2008 года N 1/56
title:
  rus: О некоторых вопросах деятельности уполномоченных государственных органов города Алматы в области регулирования земельных правоотношений
  kaz: Жер құқық қатынастарын реттеу салалары бойынша Алматы қаласының мемлекеттік уәкілетті органдарының қызметі жайлы кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2005-04-12
approved_by:
- '155000000001'
version_date:
  kaz: 2006-10-03
  rus: 2006-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/24300/kaz/03.10.2006
  rus: https://zan.gov.kz/client/#!/doc/24300/rus/03.10.2006
caused_by:
  code: '30326'
  requisite: Постановление Акимата города Алматы от 3 октября 2006 года N 6/1167. Зарегистрировано Департаментом юстиции города Алматы 2 ноября 2006 года за N 715. Утратило силу постановлением акимата города Алматы от 22 января 2008 года N 1/56
  title:
    rus: О внесении изменения и дополнения в постановление акимата города Алматы от 12 апреля 2005 года N 2/211 "О некоторых вопросах деятельности уполномоченных государственных органов города Алматы в области регулирования земельных правоотношений"
    kaz: Алматы қаласы әкімдігінің 2005 жылғы 12 сәуірдегі N 2/211 "Жер құқық қатынастарын реттеу салалары бойынша Алматы қаласының мемлекеттік өкілетті органдарының қызметі жайлы кейбір мәселелері туралы" қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/30326/rus
