act_code: '64179'
requisite: Постановление акимата Сарыкольского района Костанайской области от 1 марта 2012 года № 66. Зарегистрировано Управлением юстиции Сарыкольского района Костанайской области 16 марта 2012 года № 9-17-134. Утратило силу - Постановлением акимата Сарыкольского района Костанайской области от 3 мая 2012 года № 198
title:
  rus: Об утверждении перечней работодателей, где будут организованы социальные рабочие места и рабочие места для прохождения молодежной практики в Сарыкольском районе в 2012 году
  kaz: 2012 жылы Сарыкөл ауданында әлеуметтік жұмыс орындарын және жастар практикасынан өту үшін жұмыс орындарын ұйымдастыратын жұмыс берушілердің тізбелерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2012-03-01
approved_by:
- '162015000001'
version_date:
  kaz: 2012-03-01
  rus: 2012-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/64179/kaz/01.03.2012
  rus: https://zan.gov.kz/client/#!/doc/64179/rus/01.03.2012
