act_code: '123065'
requisite: Постановление Восточно-Казахстанского областного акимата от 11 июня 2018 года № 168. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 июня 2018 года № 5653. Утратило силу постановлением Восточно-Казахстанского областного акимата от 14 июля 2020 года № 233 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента государственной услуги «Субсидирование повышения продуктивности и качества продукции аквакультуры (рыбоводства)»
  kaz: «Акваөсіру (балық өсіру) өнімділігі мен сапасын арттыруды субсидиялау» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2018-06-11
approved_by:
- '157000000001'
version_date:
  kaz: 2018-06-11
  rus: 2018-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/123065/kaz/11.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123065/rus/11.06.2018
