act_code: '155953'
requisite: Совместные постановление акимата города Экибастуза Павлодарской области от 28 апреля 2021 года № 328/4 и решение Экибастузского городского маслихата Павлодарской области от 28 апреля 2021 года № 31/4. Зарегистрированы Департаментом юстиции Павлодарской области 18 мая 2021 года № 7284. Утратило силу совместным постановлением акимата города Экибастуза Павлодарской области от 17 декабря 2025 года № 969/12 и решением Экибастузского городского маслихата Павлодарской области от 17 декабря 2025 года № 299/38 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О льготном проезде отдельных категорий граждан города Экибастуза на общественном пассажирском транспорте (кроме такси)
  kaz: Екібастұз қаласының жекелеген санаттағы азаматтарының қоғамдық жолаушылар көлігінде (таксиден басқа) жеңілдікпен жол жүруі туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2021-04-28
approved_by:
- '164013000001'
- '164013000002'
version_date:
  kaz: 2022-04-29
  rus: 2022-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/155953/kaz/29.04.2022
  rus: https://zan.gov.kz/client/#!/doc/155953/rus/29.04.2022
caused_by:
  code: '167404'
  requisite: Совместные постановление акимата города Экибастуза Павлодарской области от 29 апреля 2022 года № 292/4 и решение Экибастузского городского маслихата Павлодарской области от 29 апреля 2022 года № 116/18. Зарегистрированы в Министерстве юстиции Республики Казахстан 6 мая 2022 года № 27929. Утратило силу совместным постановлением акимата города Экибастуза Павлодарской области от 17 декабря 2025 года № 969/12 и решением Экибастузского городского маслихата Павлодарской области от 17 декабря 2025 года № 299/38 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в совместные постановление акимата города Экибастуза Павлодарской области от 28 апреля 2021 года № 328/4 и решение Экибастузского городского маслихата Павлодарской области от 28 апреля 2021 года № 31/4 «О льготном проезде отдельных категорий граждан города Экибастуза на общественном пассажирском транспорте (кроме такси)»
    kaz: Павлодар облысы Екібастұз қаласы әкімдігінің 2021 жылғы 28 сәуірдегі № 328/4 және Павлодар облысы Екібастұз қалалық мәслихатының 2021 жылғы 28 сәуірдегі № 31/4 «Екібастұз қаласының жекелеген санаттағы азаматтарының қоғамдық жолаушылар көлігінде (таксиден басқа) жеңілдікпен жол жүруі туралы» бірлескен қаулысымен шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167404/rus
