act_code: '106230'
requisite: Постановление акимата Бурлинского района Западно-Казахстанской области от 8 августа 2016 года № 487. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 13 сентября 2016 года № 4552. Утратило силу постановлением акимата Бурлинского района Западно-Казахстанской области от 29 сентября 2016 года № 684
title:
  rus: Об определении оптимальных сроков начала и завершения посевных работ на 2016 год
  kaz: 2016 жылға егіс жұмыстардың басталуы мен аяқталуының оңтайлы мерзімдерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-08-08
approved_by:
- '159005000001'
version_date:
  kaz: 2016-08-08
  rus: 2016-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/106230/kaz/08.08.2016
  rus: https://zan.gov.kz/client/#!/doc/106230/rus/08.08.2016
