act_code: '70994'
requisite: Постановление Правления Национального Банка Республики Казахстан от 24 декабря 2012 года № 387. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 февраля 2013 года № 8329
title:
  rus: «Об утверждении Методики расчета ставки обязательных, дополнительных взносов и условных обязательств, порядка и сроков уплаты обязательных, первоначальных разовых, дополнительных и чрезвычайных взносов, порядка формирования и учета условных обязательств страховыми организациями, филиалами страховых организаций-нерезидентов Республики Казахстан - участниками Фонда гарантирования страховых выплат»;
  kaz: Сақтандыру төлемдеріне кепілдік беру қорының қатысушылары – сақтандыру ұйымдарының, Қазақстан Республикасының бейрезидент-сақтандыру ұйымдары филиалдарының міндетті, қосымша жарналар мен шартты міндеттемелердің мөлшерлемесін есептеу әдістемесін, міндетті, бастапқы біржолғы, қосымша және төтенше жарналарды төлеу тәртібі мен мерзімдерін, шартты міндеттемелерді қалыптастыру мен есепке алу тәртібін бекіту туралы
form: ПОСТ
type_codes:
- МЕТ
- ПОСТ
approved_on: 2012-12-24
approved_by:
- '117000000000'
version_date:
  kaz: 2021-06-14
  rus: 2021-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/70994/kaz/14.06.2021
  rus: https://zan.gov.kz/client/#!/doc/70994/rus/14.06.2021
caused_by:
  code: '156533'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 14 июня 2021 года № 70. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 июня 2021 года № 23105
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам участия в системе гарантирования страховых выплат
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне сақтандыру төлемдеріне кепілдік беру жүйесіне қатысу мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156533/rus
