act_code: '32752'
requisite: Постановление акимата города Экибастуза Павлодарской области от 7 марта 2007 года № 106/3. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 10 апреля 2007 года № 12-3-92
title:
  rus: 'О порядке организации и проведения конкурса на право обслуживания регулярных автомобильных перевозок пассажиров и багажа на городских, пригородных маршрутах и соединяющие населенные пункты: поселки, аулы (села) с городом Экибастузом'
  kaz: 'Қалалық, қала маңындағы және Екібастұз қаласының елді мекендерін: поселкелерді, ауылдарды (селоны) біріктіретін бағыттарына жолаушылар мен жүктерді үнемі автомобильмен тасымалдау үшін қызмет көрсету құқығына конкурс ұйымдастыру және өткізу тәртібі туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-03-07
approved_by:
- '164013000001'
version_date:
  kaz: 2007-03-07
  rus: 2007-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/32752/kaz/07.03.2007
  rus: https://zan.gov.kz/client/#!/doc/32752/rus/07.03.2007
