act_code: '39557'
requisite: Постановление Глубоковского районного акимата Восточно-Казахстанской области от 9 апреля 2008 года № 846. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 13 мая 2008 года № 5-9-85. Утратило силу постановлением Глубоковского районного акимата от 6 апреля 2009 года № 93
title:
  rus: О проведении очередного призыва граждан Глубоковского района на срочную воинскую службу в апреле-июне и октябре-декабре 2008 года
  kaz: О проведении очередного призыва граждан Глубоковского района на срочную воинскую службу в апреле-июне и октябре-декабре 2008 года
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-04-09
approved_by:
- '157010000001'
version_date:
  rus: 2008-04-09
source:
  rus: https://zan.gov.kz/client/#!/doc/39557/rus/09.04.2008
