act_code: '118204'
requisite: Постановление акимата города Астаны от 8 января 2018 года № 112-10. Зарегистрировано Департаментом юстиции города Астаны 19 января 2018 года № 1154. Утратило силу постановлением акимата города Нур-Султана от 5 октября 2020 года № 112-2072 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении размеров выплат ежемесячного денежного содержания спортсменам города Астаны, входящим в состав сборных команд Республики Казахстан по видам спорта (национальных сборных команд по видам спорта), их тренерам, а также спортсменам города Астаны, выступающим в составах сборных команд Республики Казахстан (национальных сборных команд) по игровым видам спорта, их тренерам и руководителям клубных команд
  kaz: Астана қаласының спорт түрлері бойынша Қазақстан Республикасы құрама командаларының (спорт түрлері бойынша ұлттық құрама командалардың) құрамына кіретін спортшыларға, олардың жаттықтырушыларына, сондай-ақ Астана қаласында спорттың ойналатын түрлері бойынша Қазақстан Республикасы құрама командаларының (ұлттық құрама командалардың) құрамдарында қатысатын спортшыларға, олардың жаттықтырушыларына және клубтық командалардың жетекшілеріне ай сайынғы ақшалай жабдықталым төлемдерінің мөлшерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-01-08
approved_by:
- '151000000001'
version_date:
  kaz: 2018-01-08
  rus: 2018-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/118204/kaz/08.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118204/rus/08.01.2018
