act_code: '107920'
requisite: Постановление акимата Майского района Павлодарской области от 14 ноября 2016 года № 222/11. Зарегистрировано Департаментом юстиции Павлодарской области 2 декабря 2016 года № 5286. Утратило силу постановлением акимата Майского района Павлодарской области от 10 сентября 2021 года № 220/9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении квоты рабочих мест для инвалидов организациям Майского района
  kaz: Май ауданының ұйымдарына мүгедектер үшін жұмыс орындарының квотасын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-11-14
approved_by:
- '164010000001'
version_date:
  kaz: 2016-11-14
  rus: 2016-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/107920/kaz/14.11.2016
  rus: https://zan.gov.kz/client/#!/doc/107920/rus/14.11.2016
