act_code: '579'
requisite: ПОСТАНОВЛЕНИЕ Кабинета Министpов Республики Казахстан от 22 апpеля 1994 г. N 430. Утратило силу - постановлением Правительства РК от 30 июня 2005 г. N 662
title:
  rus: О порядке организации Государственной противопожарной службы Агентства Республики Казахстан по чрезвычайным ситуациям
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫ ТӨТЕНШЕ ЖАҒДАЙЛАР ЖӨНIНДЕГI АГЕНТТIГIНIҢ МЕМЛЕКЕТТIК ӨРТКЕ ҚАРСЫ ҚЫЗМЕТIН ҰЙЫМДАСТЫРУДЫҢ ТӘРТIБI ТУРАЛЫ
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1994-04-21
approved_by:
- '103000000000'
version_date:
  kaz: 2004-02-27
  rus: 2004-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/579/kaz/27.02.2004
  rus: https://zan.gov.kz/client/#!/doc/579/rus/27.02.2004
caused_by:
  code: '18758'
  requisite: Постановление Правительства Республики Казахстан от 27 февраля 2004 года N 239. Утратило силу постановлением Правительства Республики Казахстан от 9 сентября 2007 года N 781
  title:
    rus: Об утверждении перечня организаций и объектов, на которых в обязательном порядке создается противопожарная служба
    kaz: Мiндеттi түрде өртке қарсы қызмет құрылатын ұйымдар мен объектiлердiң тiзбесiн бекiту туралы
  link: https://zan.gov.kz/client/#!/doc/18758/rus
