act_code: '71209'
requisite: Постановление Правительства Республики Казахстан от 24 июля 2015 года № 584. Утратило  силу постановлением Правительства Республики Казахстан от 13 апреля 2026 года № 260 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня международных товарных бирж, на которых производятся приобретение и продажа товара в рамках финансирования физических и юридических лиц в качестве торгового посредника путем предоставления коммерческого кредита на условиях последующей продажи товара третьему лицу
  kaz: Сауда делдалы ретіндегі жеке және заңды тұлғаларды тауарды кейіннен үшінші тұлғаға сату талаптарымен коммерциялық кредит беру жолымен қаржыландыру шеңберінде тауарды сатып алу және сату жүргізілетін халықаралық тауар биржаларының тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-07-24
approved_by:
- '103000000000'
version_date:
  kaz: 2015-07-24
  rus: 2015-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/71209/kaz/24.07.2015
  rus: https://zan.gov.kz/client/#!/doc/71209/rus/24.07.2015
