act_code: '160681'
requisite: Постановление акимата Житикаринского района Костанайской области от 18 ноября 2021 года № 255
title:
  rus: Об утверждении Правил предоставления коммунальных услуг по Житикаринскому району Костанайской области
  kaz: Қостанай облысының Жітіқара ауданы бойынша коммуналдық көрсетілетін қызметтерді ұсыну қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2021-11-18
approved_by:
- '162008000001'
version_date:
  kaz: 2021-11-18
  rus: 2021-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/160681/kaz/18.11.2021
  rus: https://zan.gov.kz/client/#!/doc/160681/rus/18.11.2021
