act_code: '70728'
requisite: Постановление Правительства Республики Казахстан от 31 января 2013 года № 71. Утратило силу постановлением Правительства Республики Казахстан от 27 июля 2015 года № 592
title:
  rus: О некоторых вопросах лицензирования медицинской и фармацевтической деятельности
  kaz: Медициналық және фармацевтикалық қызметті лицензиялаудың кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-01-31
approved_by:
- '103000000000'
version_date:
  kaz: 2013-01-31
  rus: 2013-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/70728/kaz/31.01.2013
  rus: https://zan.gov.kz/client/#!/doc/70728/rus/31.01.2013
