act_code: '11023'
requisite: Постановление Правительства Республики Казахстан от 21 января 2002 года № 74. Утратило силу постановлением Правительства Республики Казахстан от 10 апреля 2007 года № 285
title:
  rus: Об утверждении ставок сбора за государственную регистрацию гражданских воздушных судов
  kaz: Азаматтық әуе кемелерiн мемлекеттiк тiркегенi үшiн алым ставкаларын бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2002-01-21
approved_by:
- '103000000000'
version_date:
  kaz: 2002-01-21
  rus: 2002-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/11023/kaz/21.01.2002
  rus: https://zan.gov.kz/client/#!/doc/11023/rus/21.01.2002
