act_code: '110699'
requisite: Постановление акимата Мангистауского района Мангистауской области от 22 февраля 2017 года № 62. Зарегистрировано Департаментом юстиции Мангистауской области 24 марта 2017 года № 3293. Утратило силу постановлением Мангистауского районного акимата Мангистауской области от 12 марта 2018 года № 57
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат акима Мангистауского района», районных исполнительных органов, финансируемых из районного бюджета
  kaz: «Маңғыстау ауданы әкімінің аппараты» мемлекеттік мекемесінің, аудандық бюджеттен қаржыландырылатын  аудандық атқарушы органдарының  «Б» корпусы мемлекеттік әкімшілік  қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2017-02-22
approved_by:
- '163004000001'
version_date:
  kaz: 2017-02-22
  rus: 2017-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/110699/kaz/22.02.2017
  rus: https://zan.gov.kz/client/#!/doc/110699/rus/22.02.2017
