act_code: '32655'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 23 февраля 2007 года № 49. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 апреля 2007 года № 4602. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 29 октября 2018 года № 257 (вводится в действие с 1 января 2019 года)
title:
  rus: Об утверждении Правил ведения документации по кредитованию
  kaz: Кредиттеу жөніндегі құжаттамасын жүргізу ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
- ПРЧ
approved_on: 2007-02-23
approved_by:
- '109000000000'
version_date:
  kaz: 2015-04-24
  rus: 2015-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/32655/kaz/24.04.2015
  rus: https://zan.gov.kz/client/#!/doc/32655/rus/24.04.2015
caused_by:
  code: '90563'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 24 апреля 2015 года № 70. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 июня 2015 года № 11297. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 29 октября 2018 года № 257 (вводится в действие с 1 января 2019 года)
  title:
    rus: О внесении дополнений в постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 23 февраля 2007 года № 49 «Об утверждении Правил ведения документации по кредитованию»
    kaz: «Кредиттеу жөніндегі құжаттамасын жүргізу ережесін бекіту туралы» Қазақстан Республикасы Қаржы нарығын және қаржы ұйымдарын реттеу мен қадағалау агенттігі Басқармасының 2007 жылғы 23 ақпандағы № 49 қаулысына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90563/rus
