act_code: '57149'
requisite: Постановление Глубоковского районного акимата Восточно-Казахстанской области от 23 декабря 2010 года № 923. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 30 января 2011 года за № 5-9-145. Прекращено действие по истечении срока, на который постановление было принято (письмо Глубоковского районного акимата Восточно-Казахстанской области от 4 января 2012 года № 09-02-10)
title:
  rus: Об определении целевых групп на 2011 год
  kaz: 2011 жылға арналған нысаналы топтарды анықтау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-12-23
approved_by:
- '157010000001'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/57149/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/57149/rus/23.12.2010
