act_code: '16399'
requisite: Постановление Правления Национального Банка Республики Казахстан от 4 июля 2003 года N 222. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 июля 2003 года N 2417. Утратило силу - постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 25 февраля 2006 года N 55 (V064139)
title:
  rus: Об утверждении требований к рейтингу юридических лиц-нерезидентов Республики Казахстан, являющихся учредителями или акционерами банков второго уровня, организаций, осуществляющих инвестиционное управление пенсионными активами, открытых накопительных пенсионных фондов Республики Казахстан и страховых (перестраховочных) организаций-нерезидентов Республики Казахстан, создающих, имеющих дочерние страховые (перестраховочные) организации Республики Казахстан, и Перечня рейтинговых агентств, присваивающих данный рейтинг
  kaz: Қазақстан Республикасының екінші деңгейдегі банктерінің, зейнетақы активтерін инвестициялық басқаруды жүзеге асыратын ұйымдарының, ашық жинақтаушы зейнетақы қорларының және сақтандыру (қайта сақтандыру) ұйымдарының - Қазақстан Республикасының еншілес сақтандыру (қайта сақтандыру) ұйымдарын құратын, иеленуші Қазақстан Республикасының резиденті еместердің құрылтайшылары немесе акционерлері болып табылатын Қазақстан Республикасының резиденті емес заңды тұлғалардың рейтингіне қойылатын талаптарды және осы рейтингті беретін Рейтинг агенттіктерінің тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
- ТРЕБ
approved_on: 2003-07-03
approved_by:
- '117000000000'
version_date:
  kaz: 2004-10-24
  rus: 2004-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/16399/kaz/24.10.2004
  rus: https://zan.gov.kz/client/#!/doc/16399/rus/24.10.2004
caused_by:
  code: '22119'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 25 октября 2004 года № 304. Зарегистрировано Министерством юстиции Республики Казахстан 1 декабря 2004 года № 3236. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 24 декабря 2012 года № 385
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам регулирования и надзора финансового рынка и финансовых организаций
    kaz: Қаржы рыногын және қаржы ұйымдарын реттеу және қадағалау мәселелері бойынша Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/22119/rus
