act_code: '12015'
requisite: Постановление Атырауского областного акимата от 12 марта 2002 года № 124. Зарегистрировано Управлением юстиции Атырауской области 4 апреля 2002 года № 888
title:
  rus: О проведении весеннего двухмесячника по санитарной очистке и благоустройству населенных пунктов, смотра готовности объектов водоснабжения и канализации к летнему сезону 2002 года
  kaz: Облыс елді мекендерін санитарлық тазалау, көріктендіру жөнінде, ауыз сумен қамту және канализация объектілерінің 2002 жылдың жазғы маусымға дайындығы байқауының көктемгі екі айлығын өткізу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2002-03-12
approved_by:
- '156000000001'
version_date:
  kaz: 2002-03-12
  rus: 2002-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/12015/kaz/12.03.2002
  rus: https://zan.gov.kz/client/#!/doc/12015/rus/12.03.2002
