act_code: '72606'
requisite: Постановление акимата Теректинского района Западно-Казахстанской области от 22 апреля 2013 года №93. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 15 мая 2013 года №3291. Утратило силу постановлением акимата Теректинского района Западно-Казахстанской области от 16 мая 2016 года № 143
title:
  rus: Об установлении квоты рабочих мест для лиц, состоящих на учете службы пробации уголовно-исполнительной инспекции, а также лиц, освобожденных из мест лишения свободы и для несовершеннолетних выпускников интернатных организаций
  kaz: Қылмыстық-атқару инспекциясы пробация қызметінің есебінде тұрған адамдар үшін, сондай-ақ бас бостандығынан айыру орындарынан босатылған адамдар үшiн және интернаттық ұйымдарды бiтiрушi кәмелетке толмағандар үшiн жұмыс орындарына квота белгiлеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-04-22
approved_by:
- '159013000001'
version_date:
  kaz: 2013-04-22
  rus: 2013-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/72606/kaz/22.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72606/rus/22.04.2013
