act_code: '51256'
requisite: Батыс Қазақстан облысы Зеленов ауданы әкімдігінің 2010 жылғы 23 ақпандағы № 70 қаулысы. Батыс Қазақстан облысы Зеленов ауданы әділет басқармасында 2010 жылғы 18 наурызда № 7-7-103 тіркелді. Күші жойылды - Батыс Қазақстан облысы Зеленов ауданы әкімдігінің 2014 жылғы 16 қазандағы № 816 қаулысымен
title:
  rus: Халықтың нысаналы топтары үшін әлеуметтік жұмыс орындарын ұйымдастыру шаралары туралы
  kaz: Халықтың нысаналы топтары үшін әлеуметтік жұмыс орындарын ұйымдастыру шаралары туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-02-23
approved_by:
- '159008000001'
version_date:
  kaz: 2010-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/51256/kaz/23.02.2010
