act_code: '59800'
requisite: Бірлескен Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2011 жылғы 30 маусымдағы № 47-324-IV шешімі және Мақтаарал ауданы әкімдігінің 2011 жылғы 21 маусымдағы № 1563 қаулысы. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2011 жылғы 28 шілдеде № 14-7-147 тіркелді
title:
  rus: Жетісай қаласындағы Данько көшесінің атауын өзгерту туралы
  kaz: Жетісай қаласындағы Данько көшесінің атауын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2011-06-30
approved_by:
- '166005000001'
- '166005000002'
version_date:
  kaz: 2011-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/59800/kaz/30.06.2011
