act_code: '171139'
requisite: Постановление Аральского районного акимата Кызылординской области от 17 августа 2022 года № 93-қ
title:
  rus: О помещениях, предоставляемые кандидатам на договорной основе для встреч с избирателями
  kaz: Кандидаттарға сайлаушылармен кездесу үшін шарттық негізде үй-жай беру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-08-17
approved_by:
- '161003000001'
version_date:
  kaz: 2022-08-17
  rus: 2022-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/171139/kaz/17.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171139/rus/17.08.2022
