act_code: '137168'
requisite: Постановление акимата Жамбылской области от 12 декабря 2019 года № 285 и решение Жамбылского областного маслихата от 12 декабря 2019 года № 41-12. Зарегистрировано Департаментом юстиции Жамбылской области 19 декабря 2019 года № 4448
title:
  rus: Об упразднении некоторых населенных пунктов Жамбылской области
  kaz: Жамбыл облысының кейбір елді мекендерін тарату туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2019-12-12
approved_by:
- '158000000001'
- '158000000002'
version_date:
  kaz: 2020-06-15
  rus: 2020-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/137168/kaz/15.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137168/rus/15.06.2020
caused_by:
  code: '143926'
  requisite: Постановление акимата Жамбылской области от 15 июня 2020 года № 131 и решение Жамбылского областного маслихата от 15 июня 2020 года № 47-10. Зарегистрировано Департаментом юстиции Жамбылской области 18 июня 2020 года № 4632
  title:
    rus: О внесении изменения в постановление акимата Жамбылской области от 12 декабря 2019 года № 285 и решение Жамбылского областного маслихата от 12 декабря 2019 года № 41-12 «Об упразднении некоторых населенных пунктов Жамбылской области»
    kaz: «Жамбыл облысының кейбір елді мекендерін тарату туралы» Жамбыл облысы әкімдігінің 2019 жылғы 12 желтоқсандағы № 285 қаулысы және Жамбыл облыстық мәслихатының 2019 жылғы 12 желтоқсандағы № 41-12 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143926/rus
