act_code: '51029'
requisite: Постановление акимата Каркаралинского района Карагандинской области от 1 февраля 2010 года № 12. Зарегистрировано Управлением юстиции Каркаралинского района Карагандинской области 4 марта 2010 года № 8-13-78. Утратило силу постановлением акимата Каркаралинского района Карагандинской области от 14 декабря 2015 года № 364
title:
  rus: О выплате малообеспеченным гражданам компенсации в связи с ростом цен на основные продукты питания
  kaz: Аз қамтылған азаматтарға бастапқы азық-түлік бағасының қымбаттауына байланысты өтемақы төлеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-02-01
approved_by:
- '160013000001'
version_date:
  kaz: 2010-02-01
  rus: 2010-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/51029/kaz/01.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51029/rus/01.02.2010
