act_code: '63589'
requisite: Постановление акимата Бейнеуского района от 01 февраля 2012 года № 5. Зарегистрировано Департаментом юстиции Мангистауской области 21 февраля 2012 года № 11-3-130
title:
  rus: О занятости населения по району в 2012 году
  kaz: Аудан бойынша 2012 жылда халықты жұмыспен қамту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-02-01
approved_by:
- '163007000001'
version_date:
  kaz: 2012-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/63589/kaz/14.06.2012
caused_by:
  code: '66592'
  requisite: Маңғыстау облысы Бейнеу ауданы әкімдігінің 2012 жылғы 14 маусымдағы № 86 қаулысы. Маңғыстау облысының Әділет департаментінде 2012 жылғы 13 шілдеде № 11-3-136 тіркелді
  title:
    rus: Аудандық әкімдіктің 2012 жылғы 1 ақпандағы № 5 "Аудан бойынша 2012 жылда халықты жұмыспен қамту туралы" қаулысына өзгеріс енгізу туралы
    kaz: Аудандық әкімдіктің 2012 жылғы 1 ақпандағы № 5 "Аудан бойынша 2012 жылда халықты жұмыспен қамту туралы" қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66592/rus
