act_code: '161746'
requisite: Постановление Правительства Республики Казахстан от 9 декабря 2021 года № 872
title:
  rus: О реализации Закона Республики Казахстан «О республиканском бюджете на 2022 – 2024 годы»
  kaz: «2022 – 2024 жылдарға арналған республикалық бюджет туралы» Қазақстан Республикасының Заңын іске асыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2021-12-09
approved_by:
- '103000000000'
version_date:
  kaz: 2022-03-01
  rus: 2022-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/161746/kaz/01.03.2022
  rus: https://zan.gov.kz/client/#!/doc/161746/rus/01.03.2022
caused_by:
  code: '165093'
  requisite: Постановление Правительства Республики Казахстан от 1 марта 2022 года № 93
  title:
    rus: Об увеличении годовых плановых назначений соответствующих бюджетных программ за счет остатков бюджетных средств 2021 года и использовании (доиспользовании) в 2022 году неиспользованных (недоиспользованных) сумм целевых трансфертов на развитие, выделенных из республиканского бюджета в 2021 году, и внесении изменений и дополнений в постановление Правительства Республики Казахстан от 9 декабря 2021 года № 872 «О реализации Закона Республики Казахстан «О республиканском бюджете на 2022 – 2024 годы»
    kaz: 2021 жылғы бюджет қаражатының қалдықтары есебінен тиісті бюджеттік бағдарламалардың жылдық жоспарлы тағайындауларын ұлғайту және 2021 жылы республикалық бюджеттен бөлінген нысаналы даму трансферттерінің пайдаланылмаған (толық пайдаланылмаған) сомаларын 2022 жылы пайдалану (толық пайдалану) және «2022 – 2024 жылдарға арналған республикалық бюджет туралы» Қазақстан Республикасының Заңын іске асыру туралы» Қазақстан Республикасы Үкіметінің 2021 жылғы 9 желтоқсандағы № 872 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165093/rus
