act_code: '94532'
requisite: Постановление акимата Карагандинской области от 17 сентября 2015 года № 54/01. Зарегистрировано Департаментом юстиции Карагандинской области 13 октября 2015 года № 3441. Утратило силу постановлением акимата Карагандинской области от 3 июня 2020 года № 35/01 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг
  kaz: Мемлекеттік  көрсетілетін қызмет регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2015-09-17
approved_by:
- '160000000001'
version_date:
  kaz: 2016-10-25
  rus: 2016-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/94532/kaz/25.10.2016
  rus: https://zan.gov.kz/client/#!/doc/94532/rus/25.10.2016
caused_by:
  code: '107762'
  requisite: Постановление акимата Карагандинской области от 25 октября 2016 года № 76/04. Зарегистрировано Департаментом юстиции Карагандинской области 25 ноября 2016 года № 4029. Утратило силу постановлением акимата Карагандинской области от 3 июня 2020 года № 35/01 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в постановление акимата Карагандинской области от 17 сентября 2015 года № 54/01 «Об утверждении регламентов государственных услуг»
    kaz: «Мемлекеттік көрсетілетін қызмет регламенттерін бекіту туралы» Қарағанды облысы әкімдігінің 2015 жылғы 17 қыркүйектегі № 54/01 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107762/rus
