act_code: '135831'
requisite: Совместное постановление акимата Жетысайского района Туркестанской области от 9 октября 2019 года № 812 и решение Жетысайского районного маслихата Туркестанской области от 9 октября 2019 года № 20-122-VI. Зарегистрировано Департаментом юстиции Туркестанской области 28 октября 2019 года № 5229
title:
  rus: Об изменении границ населенных пунктов по Жетысайскому району
  kaz: Жетісай ауданы бойынша елді мекендердің шекараларын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2019-10-09
approved_by:
- '166017000001'
- '166017000002'
version_date:
  kaz: 2019-10-09
  rus: 2019-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/135831/kaz/09.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135831/rus/09.10.2019
