act_code: '40448'
requisite: Ақтөбе облысы Ырғыз аудандық әкімиятының 2008 жылғы 21 мамырдағы N 123 қаулысы. Ақтөбе облысының Ырғыз аудандық Әділет басқармасыда 2008 жылдың 27 маусымдағы N 3-5-74 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық әкімиятының 2009 жылғы 6 қаңтардағы N 3 қаулысымен
title:
  rus: Әлеуметтік жұмыс орындарын ұйымдастыру туралы
  kaz: Әлеуметтік жұмыс орындарын ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-05-21
approved_by:
- '153006000001'
version_date:
  kaz: 2008-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/40448/kaz/21.05.2008
