act_code: '29391'
requisite: Қостанай облысы Қамысты ауданы әкімдігінің 2006 жылғы 17 шілдедегі № 178 қаулысы. Қостанай облысы Қамысты ауданының Әділет басқармасында 2006 жылғы 15 тамызда № 9-11-42 болып тіркелді
title:
  rus: 2005 жылғы 20 желтоқсан айының № 149 «Қамысты ауданының 2006 жылға арналған аудандық бюджеті туралы» шешімін іске асыру туралы
  kaz: 2005 жылғы 20 желтоқсан айының № 149 «Қамысты ауданының 2006 жылға арналған аудандық бюджеті туралы» шешімін іске асыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-07-17
approved_by:
- '162009000001'
version_date:
  kaz: 2006-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/29391/kaz/17.07.2006
