act_code: '79361'
requisite: Постановление Правительства Республики Казахстан от 29 мая 2014 года № 578
title:
  rus: О некоторых вопросах вывоза лесоматериалов с территории Республики Казахстан
  kaz: Қазақстан Республикасының аумағынан ағаш материалдарды әкетудің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-05-29
approved_by:
- '103000000000'
version_date:
  kaz: 2014-05-29
  rus: 2014-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/79361/kaz/29.05.2014
  rus: https://zan.gov.kz/client/#!/doc/79361/rus/29.05.2014
