act_code: '39601'
requisite: Постановление Правительства Республики Казахстан от 13 мая 2008 года № 452
title:
  rus: О создании акционерного общества "Өркен" и выделения средств из резерва Правительства Республики Казахстан
  kaz: '"Өркен" акционерлік коғамын құру және Қазақстан Республикасы Үкіметінің резервінен қаражат бөлу туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-05-13
approved_by:
- '103000000000'
version_date:
  kaz: 2022-08-19
  rus: 2022-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/39601/kaz/19.08.2022
  rus: https://zan.gov.kz/client/#!/doc/39601/rus/19.08.2022
caused_by:
  code: '170948'
  requisite: Постановление Правительства Республики Казахстан от 19 августа 2022 года № 581
  title:
    rus: Некоторые вопросы Министерства просвещения Республики Казахстан
    kaz: Қазақстан Республикасы Оқу-ағарту министрлiгінің кейбiр мәселелерi
  link: https://zan.gov.kz/client/#!/doc/170948/rus
