act_code: '41518'
requisite: Постановление акимата Акмолинской области от 4 августа 2008 года № А-6/328. Зарегистрировано департаментом юстиции Акмолинской области 12 сентября 2008 года № 3274. Утратило силу - постановлением акимата Акмолинской области от 2 апреля 2010 года № а-4/103
title:
  rus: Об утверждении стандарта оказания государственной услуги "Регистрации договора залога на разведку, добычу и на совмещенную разведку и добычу общераспространенных полезных ископаемых"
  kaz: '"Барлауға, өндіруге және бірлескен барлауға жалпыға таралған пайдалы қазбаларды өндіруге кепілдік шартын тіркеу" мемлекеттік қызмет көрсету стандартын бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- СТНД
approved_on: 2008-08-04
approved_by:
- '152000000001'
version_date:
  kaz: 2008-08-04
  rus: 2008-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/41518/kaz/04.08.2008
  rus: https://zan.gov.kz/client/#!/doc/41518/rus/04.08.2008
