act_code: '136457'
requisite: Постановление акимата Мугалжарского района Актюбинской области от 27 ноября 2019 года № 452. Зарегистрировано Департаментом юстиции Актюбинской области 28 ноября 2019 года № 6498
title:
  rus: Об утверждении коэффициентов зонирования, учитывающих месторасположение объекта налогообложения по Мугалжарскому району
  kaz: Мұғалжар ауданы бойынша салық салу объектісінің орналасуын ескеретін аймаққа бөлу коэффициенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-11-27
approved_by:
- '153009000001'
version_date:
  kaz: 2025-01-01
  rus: 2025-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/136457/kaz/01.01.2025
  rus: https://zan.gov.kz/client/#!/doc/136457/rus/01.01.2025
caused_by:
  code: '202981'
  requisite: Постановление акимата Мугалжарского района Актюбинской области от 19 ноября 2024 года № 373. Зарегистрировано Департаментом юстиции Актюбинской области 21 ноября 2024 года № 8653-04
  title:
    rus: О внесении изменения в постановление акимата Мугалжарского района от 27 ноября 2019 года № 452 «Об утверждении коэффициентов зонирования, учитывающих месторасположение объекта налогообложения по Мугалжарскому району»
    kaz: Мұғалжар ауданы әкімдігінің 2019 жылғы 27 қарашадағы № 452 «Мұғалжар ауданы бойынша салық салу объектісінің орналасуын ескеретін аймаққа бөлу коэффициентерін бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202981/rus
