act_code: '79275'
requisite: Постановление Правления Национального Банка Республики Казахстан от 26 февраля 2014 года № 31. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 апреля 2014 года № 9326. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 7 июня 2023 года № 51 (вводится в действие с 1 июля 2023 года)
title:
  rus: Об утверждении Правил перевода пенсионных накоплений из единого накопительного пенсионного фонда в добровольный накопительный пенсионный фонд, из добровольного накопительного пенсионного фонда в единый накопительный пенсионный фонд, а также из одного добровольного накопительного пенсионного фонда в другой добровольный накопительный пенсионный фонд
  kaz: Зейнетақы жинақтарын бірыңғай жинақтаушы зейнетақы қорынан ерікті жинақтаушы зейнетақы қорына, ерікті жинақтаушы зейнетақы қорынан бірыңғай жинақтаушы зейнетақы қорына, сондай-ақ бір ерікті жинақтаушы зейнетақы қорынан басқа ерікті жинақтаушы зейнетақы қорына ауыстыру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2014-02-26
approved_by:
- '117000000000'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/79275/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/79275/rus/13.12.2021
caused_by:
  code: '161936'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 13 декабря 2021 года № 104. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 декабря 2021 года № 25889
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Республики Казахстан по вопросам регулирования рынка ценных бумаг и пенсионного обеспечения
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне бағалы қағаздар нарығын реттеу және зейнетақымен қамсыздандыру мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161936/rus
