act_code: '93840'
requisite: Постановление от 11.09.2015 №287, Акимат Атырауской области
title:
  rus: 'Об утверждении государственного образовательного заказа на подготовку специалистов с техническим и профессиональным, послесредним образованием на 2015 - 2016 учебный год '
  kaz: '2015-2016 оқу жылына арналған техникалық және кәсіптік, орта білімнен кейінгі білімі бар мамандарды даярлауға арналған мемлекеттік білім беру тапсырысын бекіту туралы '
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-09-11
approved_by:
- '156000000001'
version_date:
  kaz: 2015-09-11
  rus: 2015-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/93840/kaz/11.09.2015
  rus: https://zan.gov.kz/client/#!/doc/93840/rus/11.09.2015
