act_code: '52961'
requisite: Қостанай облысы Меңдіқара ауданы әкімдігінің 2010 жылғы 14 мамырдағы № 226 қаулысы. Қостанай облысы Меңдіқара ауданының Әділет басқармасында 2010 жылғы 3 маусымда № 9-15-128 тіркелді
title:
  rus: Өсімдік шаруашылығындағы міндетті сақтандыруға жататын ауыл шаруашылығы дақылдарды егісінің басталуы мен аяқталуының оңтайлы мерзімдерін белгілеу туралы
  kaz: Өсімдік шаруашылығындағы міндетті сақтандыруға жататын ауыл шаруашылығы дақылдарды егісінің басталуы мен аяқталуының оңтайлы мерзімдерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-05-14
approved_by:
- '162013000001'
version_date:
  kaz: 2010-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52961/kaz/14.05.2010
