act_code: '146685'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 21 сентября 2020 года № 90. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 сентября 2020 года № 21274
title:
  rus: Об утверждении Требований к службам реагирования на инциденты информационной безопасности, проведению внутренних расследований инцидентов информационной безопасности
  kaz: Ақпараттық қауіпсіздіктің оқыс оқиғаларына ден қою қызметтеріне, ақпараттық қауіпсіздіктің оқыс оқиғаларына ішкі тергеп-тексерулер жүргізуге қойылатын талаптарды бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ТРЕБ
approved_on: 2020-09-21
approved_by:
- '135000000000'
version_date:
  kaz: 2022-11-23
  rus: 2022-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/146685/kaz/23.11.2022
  rus: https://zan.gov.kz/client/#!/doc/146685/rus/23.11.2022
caused_by:
  code: '174389'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 23 ноября 2022 года № 95. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 ноября 2022 года № 30744
  title:
    rus: О внесении изменения в постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 21 сентября 2020 года № 90 «Об утверждении Требований к службам реагирования на инциденты информационной безопасности, проведению внутренних расследований инцидентов информационной безопасности»
    kaz: «Ақпараттық қауіпсіздіктің оқыс оқиғаларына ден қою қызметтеріне, ақпараттық қауіпсіздіктің оқыс оқиғаларына ішкі тергеп-тексерулер жүргізуге қойылатын талаптарды бекіту туралы» Қазақстан Республикасының Қаржы нарығын реттеу және дамыту агенттігі Басқармасының 2020 жылғы 21 қыркүйектегі № 90 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174389/rus
