act_code: '57243'
requisite: Постановление Правительства Республики Казахстан от 7 февраля 2011 года № 85. Утратило силу постановлением Правительства Республики Казахстан от 28 августа 2015 года № 685
title:
  rus: Об утверждении требований к программным продуктам, используемым декларантами или лицами, осуществляющими деятельность в сфере таможенного дела, для представления документов и сведений, предусмотренных Кодексом Республики Казахстан "О таможенном деле в Республике Казахстан"
  kaz: '"Қазақстан Республикасындағы кеден ісі туралы" Қазақстан Республикасының Кодексінде көзделген құжаттар мен мәліметтерді ұсыну үшін декларанттар немесе кеден ісі саласындағы қызметті жүзеге асыратын тұлғалар пайдаланатын бағдарламалық өнімдерге қойылатын талаптарды бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- ТРЕБ
approved_on: 2011-02-07
approved_by:
- '103000000000'
version_date:
  kaz: 2011-02-07
  rus: 2011-02-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/57243/kaz/07.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57243/rus/07.02.2011
