act_code: '12440'
requisite: Постановление Правительства Республики Казахстан от 18 июня 2002 года N 668. Утратило силу постановлением Правительства Республики Казахстан от 4 декабря 2009 года № 2015
title:
  rus: Об утверждении перечня медицинских психиатрических противопоказаний для осуществления отдельных видов профессиональной деятельности, а также работ, связанных с источником повышенной опасности
  kaz: Кәсiптiк қызметтiң жекелеген түрлерiн, сондай-ақ аса қатерлi көздермен байланысты жұмыстарды жүзеге асыру үшiн медициналық психиатриялық жарамсыздықтар тiзбесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2002-06-17
approved_by:
- '103000000000'
version_date:
  kaz: 2002-06-17
  rus: 2002-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/12440/kaz/17.06.2002
  rus: https://zan.gov.kz/client/#!/doc/12440/rus/17.06.2002
