act_code: '193216'
requisite: Постановление акимата города Сарани Карагандинской области от 8 февраля 2024 года № 08/01. Зарегистрировано в Департаменте юстиции Карагандинской области 13 февраля 2024 года № 6557-09. Утратило силу постановлением акимата города Сарани Карагандинской области от 12 мая 2026 года № 34/02 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об определении мест размещения агитационных печатных материалов для всех кандидатов
  kaz: Барлық кандидаттар үшін үгіттік баспа материалдарын орналастыру орындарын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2024-02-08
approved_by:
- '160003000001'
version_date:
  kaz: 2024-02-08
  rus: 2024-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/193216/kaz/08.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193216/rus/08.02.2024
