act_code: '51168'
requisite: Алматы облысы Кербұлақ ауданы әкімдігінің 2010 жылғы 27 қаңтардағы № 12 қаулысы. Алматы облысының Әділет департаменті Кербұлақ ауданының Әділет басқармасында 2010 жылы 9 наурызда № 2-13-107 тіркелді. Күші жойылды - Алматы облысы Кербұлақ ауданы әкімдігінің 2012 жылғы 22 ақпандағы № 33 қаулысымен
title:
  rus: Әлеуметтік жұмыс орындарын ұйымдастыру туралы
  kaz: Әлеуметтік жұмыс орындарын ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-01-27
approved_by:
- '154010000001'
version_date:
  kaz: 2010-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/51168/kaz/27.01.2010
