act_code: '103108'
requisite: Постановление Восточно-Казахстанского областного акимата от 19 мая 2016 года № 144. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 июня 2016 года № 4559. Утратило силу  постановлением Восточно-Казахстанского областного акимата от 10 августа 2020 года № 276 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении карантинной зоны  с введением карантинного режима  на территории Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы аумағында карантин режимін енгізе отырып, карантин аймағын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-05-19
approved_by:
- '157000000001'
version_date:
  kaz: 2016-05-19
  rus: 2016-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/103108/kaz/19.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103108/rus/19.05.2016
