act_code: '65042'
requisite: Постановление акимата Узункольского района Костанайской области от 26 марта 2012 года № 103. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 23 апреля 2012 года № 9-19-176. Утратило силу постановлением акимата Узункольского района Костанайской области от 26 июня 2013 года № 140
title:
  rus: О материальном обеспечении детей-инвалидов, воспитывающихся и обучающихся на дому
  kaz: Үйде тәрбиеленетін және оқитын мүгедек балаларды материалдық қамтамасыз ету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-03-26
approved_by:
- '162017000001'
version_date:
  kaz: 2012-03-26
  rus: 2012-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/65042/kaz/26.03.2012
  rus: https://zan.gov.kz/client/#!/doc/65042/rus/26.03.2012
