act_code: '93'
requisite: Постановление Правительства Республики Казахстан от 26 августа 1996 года № 1054. Утратило силу постановлением Правительства Республики Казахстан от 17 марта 2003 года № 258
title:
  rus: О тарифах на услуги железной дороги
  kaz: Темiр жол қызметiне арналған тарифтер туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1996-08-25
approved_by:
- '103000000000'
version_date:
  kaz: 1996-08-25
  rus: 1996-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/93/kaz/25.08.1996
  rus: https://zan.gov.kz/client/#!/doc/93/rus/25.08.1996
