act_code: '106222'
requisite: Постановление Правительства Республики Казахстан от 17 июня 2015 года № 439
title:
  rus: Об утверждении перечня инвестиционных проектов, предлагаемых к финансированию за счет средств негосударственных займов под государственные гарантии на 2015 год
  kaz: Мемлекеттік кепілдікпен берілетін мемлекеттік емес қарыздардың қаражаты есебінен қаржыландыру ұсынылып отырған инвестициялық жобалардың 2015 жылға арналған тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2015-06-17
approved_by:
- '103000000000'
version_date:
  kaz: 2015-06-17
  rus: 2015-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/106222/kaz/17.06.2015
  rus: https://zan.gov.kz/client/#!/doc/106222/rus/17.06.2015
