act_code: '40256'
requisite: Батыс Қазақстан облысы Ақжайық ауданы әкімдігінің 2008 жылғы 20 мамырдағы № 186 қаулысы. Батыс Қазақстан облысы Ақжайық ауданы әділет басқармасында 2008 жылғы 30 маусымда № 7-2-57 тіркелді. Күші жойылды - Батыс Қазақстан облысы Ақжайық ауданы әкімдігінің 2010 жылғы 6 қыркүйектегі № 252 қаулысымен
title:
  rus: Мемлекеттік қызмет көрсетудің кейбір стандарттарын бекіту туралы
  kaz: Мемлекеттік қызмет көрсетудің кейбір стандарттарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-05-20
approved_by:
- '159003000001'
version_date:
  kaz: 2008-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/40256/kaz/20.05.2008
