act_code: '193882'
requisite: Постановление акимата Атырауской области от 29 февраля 2024 года № 47. Зарегистрировано в Департаменте юстиции Атырауской области 4 марта 2024 года № 5142-06. Утратило силу постановлением акимата Атырауской области от 28 февраля 2025 года № 47 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования).
title:
  rus: Об определении перечня должностей специалистов в области здравоохранения, социального обеспечения, образования, культуры и спорта, являющихся гражданскими служащими и работающих в сельской местности, финансируемых из областного бюджета
  kaz: Облыстық бюджеттен қаржыландырылатын, азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт саласындағы мамандар лауазымдарының тізбесін айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2024-02-29
approved_by:
- '156000000001'
version_date:
  kaz: 2024-02-29
  rus: 2024-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/193882/kaz/29.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193882/rus/29.02.2024
