act_code: '46411'
requisite: Алматы облысы Қаратал ауданы әкімдігінің 2009 жылғы 18 мамырдағы № 112 қаулысы. Алматы облысының Әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 10 маусымда № 2-12-111 тіркелді. Күші жойылды - Алматы облысы Қаратал ауданы әкімдігінің 2009 жылғы 22 қазандағы № 337 қаулысымен
title:
  rus: Бастөбе ауылдық округінің "Жылыбұлақ" ауылына жеке аулаларында қой, ешкі малдарының ішінен бруцеллез ауруының шығуына байланысты шектеу енгізілуі туралы
  kaz: Бастөбе ауылдық округінің "Жылыбұлақ" ауылына жеке аулаларында қой, ешкі малдарының ішінен бруцеллез ауруының шығуына байланысты шектеу енгізілуі туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-05-18
approved_by:
- '154009000001'
version_date:
  kaz: 2009-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/46411/kaz/18.05.2009
