act_code: '56902'
requisite: Шығыс Қазақстан облысы Катонқарағай аудандық әкімдігінің 2010 жылғы 30 желтоқсандағы № 234 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық әділет басқармасында 2011 жылғы 18 қаңтарда № 5-13-83 тіркелді. Күші жойылды - ШҚО Катонқарағай аудандық әкімдігінің 2012 жылғы 10 ақпандағы № 698 қаулысымен
title:
  rus: 2011 жылға әлеуметтік жұмыс орындарын құру туралы
  kaz: 2011 жылға әлеуметтік жұмыс орындарын құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-12-30
approved_by:
- '157014000001'
version_date:
  kaz: 2011-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56902/kaz/25.07.2011
caused_by:
  code: '59795'
  requisite: Постановление акимата Катон-Карагайского района Восточно-Казахстанской области от 25 июля 2011 года № 447. Зарегистрировано управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 28 июля 2011 года за № 5-13-92. Утратило силу - постановлением акимата Катон-Карагайского района ВКО от 10 февраля 2012 года № 698
  title:
    rus: О внесении изменения в постановление от 30 декабря 2010 года № 234 "О создании социальных рабочих мест на 2011 год"
    kaz: '"2011 жылға әлеуметтік жұмыс орындарын құру туралы" 2010 жылғы 30 желтоқсандағы № 234 қаулысына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59795/rus
