act_code: '44670'
requisite: Жамбыл облысы Талас ауданы әкімиятының 2009 жылғы 27 қаңтардағы № 57 қаулысы. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 6 наурызда 6-10-74 нөмірімен тіркелді
title:
  rus: 2009 жылға қоғамдық жұмыстарды ұйымдастыру туралы
  kaz: 2009 жылға қоғамдық жұмыстарды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-01-27
approved_by:
- '158011000001'
version_date:
  kaz: 2009-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/44670/kaz/24.11.2009
caused_by:
  code: '49399'
  requisite: Жамбыл облысы Талас ауданы әкімдігінің 2009 жылғы 24 қарашадағы № 525 қаулысы. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 21 желтоқсанда 6-10-89 нөмірімен тіркелді
  title:
    rus: '"2009 жылға қоғамдық жұмыстарды ұйымдастыру туралы" Талас ауданы әкімиятының 2009 жылғы 27 қаңтардағы № 57 қаулысына өзгеріс енгізу туралы'
    kaz: '"2009 жылға қоғамдық жұмыстарды ұйымдастыру туралы" Талас ауданы әкімиятының 2009 жылғы 27 қаңтардағы № 57 қаулысына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/49399/rus
