act_code: '15582'
requisite: Постановление от 21.02.2003 №46, Акимат Жалагашского района
title:
  rus: Кезеңдік өрттің алдын-алу іс-шараларын өткізу тура
  kaz: Кезеңдік өрттің алдын-алу іс-шараларын өткізу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-02-21
approved_by:
- '161006000001'
version_date:
  kaz: 2003-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/15582/kaz/21.02.2003
