act_code: '7724'
requisite: Постановление Правительства Республики Казахстан от 29 декабря 2000 года № 1946
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Таджикистан о сотрудничестве в области образования
  kaz: Қазақстан Республикасының Үкіметі мен Тәжікстан Республикасының Үкіметі арасындағы Білім беру саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2000-12-29
approved_by:
- '103000000000'
version_date:
  kaz: 2000-12-29
  rus: 2000-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/7724/kaz/29.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7724/rus/29.12.2000
