act_code: '101436'
requisite: Постановление акимата города Экибастуза Павлодарской области от 17 марта 2016 года № 291/3. Зарегистрировано Департаментом юстиции Павлодарской области 19 апреля 2016 года № 5085. Утратило силу постановлением акимата города Экибастуза Павлодарской области от 30 ноября 2023 года № 1010/11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении мест размещения нестационарных торговых объектов на территории города Экибастуза
  kaz: Екібастұз қаласының аумағында стационарлық емес сауда объектілерін орналастыру орындарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-03-17
approved_by:
- '164013000001'
version_date:
  kaz: 2016-03-17
  rus: 2016-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/101436/kaz/17.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101436/rus/17.03.2016
