act_code: '39888'
requisite: Постановление акимата Актюбинской области от 12 мая 2008 года № 167. Зарегистрировано Департаментом юстиции Актюбинской области 5 июня 2008 года № 3254
title:
  rus: Об утверждении перечня рыбохозяйственных водоемов местного значения
  kaz: Жергілікті маңызы бар балық шаруашылығы су айдындарының тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-05-12
approved_by:
- '153000000001'
version_date:
  kaz: 2008-05-12
  rus: 2008-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/39888/kaz/12.05.2008
  rus: https://zan.gov.kz/client/#!/doc/39888/rus/12.05.2008
