act_code: '3620'
requisite: Постановление Департамента управления государственным имуществом и активами Министерства финансов Республики Казахстан от 2 августа 1997 г. N 231. Зарегистрировано в Министерстве юстиции Республики Казахстан 13.08.1997г. за N 48. Утратило силу - постановлением Департамента госимущества и приватизации Минфина РК от 22 октября 1998 г. N 618
title:
  rus: '"О внесении изменений и дополнений в постановление Государственного комитета Республики Казахстан от 23 мая 1996 г. N 381'
  kaz: Қазақстан Республикасы Мемлекеттiк комитетiнiң 1996 жылғы 23 мамырдағы N 381 қаулысына өзгерiстер мен толықтырулар енгiзу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1997-08-01
approved_by:
- '103002000000'
version_date:
  rus: 1997-08-01
source:
  rus: https://zan.gov.kz/client/#!/doc/3620/rus/01.08.1997
