act_code: '35105'
requisite: Постановление Правительства Республики Казахстан от 27 сентября 2007 года № 850. Утратило силу постановлением Правительства Республики Казахстан от 27 ноября 2015 года № 957
title:
  rus: Об утверждении перечня должностей гражданских служащих
  kaz: Азаматтық қызметшілер лауазымдарының тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2007-09-27
approved_by:
- '103000000000'
version_date:
  kaz: 2014-12-31
  rus: 2014-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/35105/kaz/31.12.2014
  rus: https://zan.gov.kz/client/#!/doc/35105/rus/31.12.2014
caused_by:
  code: '85752'
  requisite: Постановление Правительства Республики Казахстан от 31 декабря 2014 года № 1427
  title:
    rus: О внесении изменений в постановления Правительства Республики Казахстан от 27 сентября 2007 года № 850 "Об утверждении перечня должностей гражданских служащих" и от 29 декабря 2007 года № 1400 "О системе оплаты труда гражданских служащих, работников организаций, содержащихся за счет средств государственного бюджета, работников казенных предприятий"
    kaz: Қазақстан Республикасы Үкіметінің "Азаматтық қызметшілер лауазымдарының тізбесін бекіту туралы" 2007 жылғы 27 қыркүйектегі № 850 және "Азаматтық қызметшілерге, мемлекеттік бюджет қаражаты есебінен ұсталатын ұйымдардың қызметкерлеріне, қазыналық кәсіпорындардың қызметкерлеріне еңбекақы төлеу жүйесі туралы" 2007 жылғы 29 желтоқсандағы № 1400 қаулыларына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85752/rus
