act_code: '35577'
requisite: Решение Мангистауского областного Маслихата от 8 октября 2007 года N 2/17 и постановление Акимата Мангистауской области от 5 октября 2007 года N 327-2. Зарегистрировано Департаментом юстиции Мангистауской области 31 октября 2007 года N 1981
title:
  rus: Об изменениях в административно-территориальном устройстве Мунайлинского района
  kaz: Мұнайлы ауданының әкімшілік-аумақтық құрылысындағы өзгерістер туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2007-10-08
approved_by:
- '163000000001'
- '163000000002'
version_date:
  kaz: 2007-10-08
  rus: 2007-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/35577/kaz/08.10.2007
  rus: https://zan.gov.kz/client/#!/doc/35577/rus/08.10.2007
