act_code: '209170'
requisite: Постановление акимата Кызылжарского района Северо-Казахстанской области от 11 апреля 2025 года № 85
title:
  rus: Об установлении права ограниченного целевого пользования (публичный сервитут) акционерному обществу «Транснефть-Урал»
  kaz: «Транснефть-Урал» акционерлік қоғамына шектеулі нысаналы пайдалану құқығын (қауымдық сервитут) белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-04-11
approved_by:
- '165008000001'
version_date:
  kaz: 2025-04-11
  rus: 2025-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/209170/kaz/11.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209170/rus/11.04.2025
