act_code: '121786'
requisite: Постановление акимата Шардаринского района Южно-Казахстанской области от 27 апреля 2018 года № 215. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 17 мая 2018 года № 4602
title:
  rus: Об утверждении перечня, наименований и индексов автомобильных дорог общего пользования районного значения
  kaz: Жалпыға ортақ пайдаланылатын аудандық маңызы бар автомобиль жолдарының тізбесін, атаулары мен индекстерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-04-27
approved_by:
- '166013000001'
version_date:
  kaz: 2022-02-17
  rus: 2022-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/121786/kaz/17.02.2022
  rus: https://zan.gov.kz/client/#!/doc/121786/rus/17.02.2022
caused_by:
  code: '164817'
  requisite: Постановление акимата Шардаринского района Туркестанской области от 17 февраля 2022 года № 62. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 февраля 2022 года № 26928
  title:
    rus: О внесении изменения в постановление акимата Шардаринского района от 27 апреля 2018 года № 215 «Об утверждении перечня, наименований и индексов автомобильных дорог общего пользования районного значения»
    kaz: Шардара ауданы әкімдігінің 2018 жылғы 27 сәуірдегі № 215 «Жалпыға ортақ пайдаланылатын аудандық маңызы бар автомобиль жолдарының тізбесін, атаулары мен индекстерін бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164817/rus
