act_code: '224112'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 14 апреля 2026 года № 64. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 апреля 2026 года № 38437
title:
  rus: Об установлении минимального рейтинга для юридических лиц и государств, необходимость наличия которого требуется в соответствии с законодательством Республики Казахстан, регулирующим деятельность финансовых организаций, филиалов банков-нерезидентов Республики Казахстан, филиалов страховых (перестраховочных) организаций-нерезидентов Республики Казахстан, перечня рейтинговых агентств, присваивающих данный рейтинг
  kaz: Болу қажеттілігі қаржы ұйымдарының, Қазақстан Республикасының бейрезидент банктері филиалдарының, Қазақстан Республикасының бейрезидент сақтандыру (қайта сақтандыру) ұйымдары   филиалдарының қызметін реттейтін Қазақстан Республикасының заңнамасына сәйкес талап етілетін заңды тұлғалар және мемлекеттер үшін ең төменгі рейтингіні, осы рейтингіні беретін рейтингтік агенттіктер тізбесін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2026-04-14
approved_by:
- '135000000000'
version_date:
  kaz: 2026-04-14
  rus: 2026-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/224112/kaz/14.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224112/rus/14.04.2026
