act_code: '77363'
requisite: Постановление акимата Сайрамского района Южно-Казахстанской области от 17 января 2014 года № 64. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 11 февраля 2014 года № 2524
title:
  rus: Об организации и объемах общественных работ за счет средств местного бюджета в 2014 году
  kaz: 2014 жылы қоғамдық жұмыстарды жергілікті бюджет қаражаты есебінен ұйымдастыру және оның көлемі туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-01-17
approved_by:
- '166008000001'
version_date:
  kaz: 2014-08-13
  rus: 2014-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/77363/kaz/13.08.2014
  rus: https://zan.gov.kz/client/#!/doc/77363/rus/13.08.2014
caused_by:
  code: '83109'
  requisite: Постановление акимата Сайрамского района Южно-Казахстанской области от 13 августа 2014 года № 646. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 сентября 2014 года № 2802
  title:
    rus: О внесении изменения в постановление акимата Сайрамского района от 17 января 2014 года № 64 "Об организации и объемах общественных работ за счет средств местного бюджета в 2014 году"
    kaz: Сайрам ауданы әкімдігінің 2014 жылғы 17 қаңтардағы № 64 "2014 жылы қоғамдық жұмыстарды жергілікті бюджет қаражаты есебінен ұйымдастыру және оның көлемі туралы" қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/83109/rus
