act_code: '657'
requisite: Постановление Правительства Республики Казахстан от 22 мая 1998 года № 469
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Турецкой Республики о торгово-экономическом и техническом сотрудничестве
  kaz: Қазақстан Республикасының Үкiметi мен Түркия Республикасының Үкiметi арасындағы Сауда-экономикалық және техникалық ынтымақтастық туралы келiсiмдi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-05-21
approved_by:
- '103000000000'
version_date:
  kaz: 1998-05-21
  rus: 1998-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/657/kaz/21.05.1998
  rus: https://zan.gov.kz/client/#!/doc/657/rus/21.05.1998
