act_code: '39197'
requisite: Постановление Правительства Республики Казахстан от 26 апреля 2008 года № 392. Утратило силу постановлением Правительства Республики Казахстан от 30 января 2017 года № 29
title:
  rus: Об утверждении Технического регламента "Требования к безопасности продуктов мукомольно-крупяной промышленности, крахмалов и крахмальной продукции"
  kaz: '"Ұн-жарма өнеркәсібі өнімдерінің, крахмалдар мен крахмал өнімдерінің қауіпсіздігіне қойылатын талаптар" техникалық регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2008-04-26
approved_by:
- '103000000000'
version_date:
  kaz: 2008-04-26
  rus: 2008-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/39197/kaz/26.04.2008
  rus: https://zan.gov.kz/client/#!/doc/39197/rus/26.04.2008
