act_code: '653'
requisite: Постановление Кабинета Министров Республики Казахстан от 7 сентября 1994 г. N 1004. Утратило силу - постановлением Правительства РК от 15 ноября 2004 г. N 1198
title:
  rus: Об утверждении Правил об операциях с драгоценными металлами и драгоценными камнями, а также изделиями из них
  kaz: Қымбат металдармен және асыл тастармен, сондай-ақ олардан жасалған бұйымдармен жүргiзiлетiн операциялар туралы ережелердi бекiту жөнiнде
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1994-09-06
approved_by:
- '103000000000'
version_date:
  kaz: 1994-09-06
  rus: 1994-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/653/kaz/06.09.1994
  rus: https://zan.gov.kz/client/#!/doc/653/rus/06.09.1994
