act_code: '1639'
requisite: Постановление Правительства Республики Казахстан от 7 июня 1996 года № 720.  Утратило силу постановлением  Правительства Республики Казахстан от 2 апреля 2025 года № 202 (вводится в действие со дня его подписания)
title:
  rus: Об утверждении Положения о порядке и условиях предоставления государственным служащим, нуждающимся в улучшении жилищных условий, земельных участков для индивидуального жилищного строительства
  kaz: Тұрғын үй жағдайын жақсартуға мұқтаж мемлекеттiк қызметшiлерге жеке тұрғын үй салу үшiн жер учаскелерiн берудiң тәртiбi мен шарттары жөнiндегi Ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1996-06-07
approved_by:
- '103000000000'
version_date:
  kaz: 2005-09-29
  rus: 2005-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/1639/kaz/29.09.2005
  rus: https://zan.gov.kz/client/#!/doc/1639/rus/29.09.2005
caused_by:
  code: '25387'
  requisite: Постановление Правительства Республики Казахстан от 29 сентября 2005 года № 964.  Утратило силу постановлением  Правительства Республики Казахстан от 2 апреля 2025 года № 202 (вводится в действие со дня его подписания)
  title:
    rus: О внесении изменений в некоторые решения Правительства Республики Казахстан и признании утратившими силу некоторых решений Кабинета Министров Казахской ССР, Кабинета Министров Республики Казахстан, Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкiметiнiң кейбiр шешiмдерiне өзгерiстер енгізу және Қазақ КCP Министрлер Кабинетiнiң, Қазақстан Республикасы Министрлер Кабинетiнiң, Қазақстан Республикасы Үкiметінің кейбiр шешiмдерiнiң күшi жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/25387/rus
