act_code: '133005'
requisite: Постановление акимата города Шымкент от 19 июня 2019 года № 533. Зарегистрировано Департаментом юстиции города Шымкент 27 июня 2019 года № 47. Утратило силу постановлением акимата города Шымкент от 23 декабря 2020 года № 810 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере ветеринарии
  kaz: Ветеринария саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2019-06-19
approved_by:
- '167000000001'
version_date:
  kaz: 2019-06-19
  rus: 2019-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/133005/kaz/19.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133005/rus/19.06.2019
