act_code: '136595'
requisite: Постановление акимата Павлодарской области от 27 ноября 2019 года № 338/3. Зарегистрировано Департаментом юстиции Павлодарской области 3 декабря 2019 года № 6647
title:
  rus: Об утверждении Правил реализации механизмов стабилизации цен на социально значимые продовольственные товары по Павлодарской области
  kaz: Павлодар облысы бойынша әлеуметтік маңызы бар азық-түлік тауарларына бағаларды тұрақтандыру тетіктерін іске асырудың қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-11-27
approved_by:
- '164000000001'
version_date:
  kaz: 2024-11-28
  rus: 2024-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/136595/kaz/28.11.2024
  rus: https://zan.gov.kz/client/#!/doc/136595/rus/28.11.2024
caused_by:
  code: '203271'
  requisite: Постановление акимата Павлодарской области от 28 ноября 2024 года № 285/2
  title:
    rus: О внесении изменения в постановление акимата Павлодарской области от 27 ноября 2019 года № 338/3 «Об утверждении Правил реализации механизмов стабилизации цен на социально значимые  продовольственные товары по Павлодарской области»
    kaz: Павлодар облысы әкімдігінің 2019 жылғы 27 қарашадағы «Павлодар облысы бойынша әлеуметтік маңызы бар азық-түлік тауарларына бағаларды тұрақтандыру тетіктерін іске асырудың қағидаларын бекіту туралы» № 338/3 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203271/rus
