act_code: '53627'
requisite: Постановление Правительства Республики Казахстан от 20 июля 2010 года № 745. Утратило силу постановлением Правительства Республики Казахстан от 18 сентября 2013 года № 983
title:
  rus: Об утверждении реестра государственных услуг, оказываемых физическим и юридическим лицам
  kaz: Жеке және заңды тұлғаларға көрсетілетін мемлекеттік қызметтердің тізілімін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-07-20
approved_by:
- '103000000000'
version_date:
  rus: 2011-04-04
source:
  rus: https://zan.gov.kz/client/#!/doc/53627/rus/04.04.2011
caused_by:
  code: '58076'
  requisite: Постановление Правительства Республики Казахстан от 4 апреля 2011 года № 351. Утратило силу постановлением Правительства Республики Казахстан от 24 февраля 2014 года № 142
  title:
    rus: Об утверждении стандарта государственной услуги "Государственная регистрация, перерегистрация и внесение изменений в регистрационное досье лекарственных средств, изделий медицинского назначения и медицинской техники" и внесении дополнения и изменений в постановление Правительства Республики Казахстан от 20 июля 2010 года № 745
    kaz: '"Дәрілік заттарды, медициналық мақсаттағы бұйымдар мен медициналық техниканы мемлекеттік тіркеу, қайта тіркеу және олардың тіркеу құжатына өзгерістер енгізу" мемлекеттік қызмет стандартын бекіту және Қазақстан Республикасы Үкіметінің 2010 жылғы 20 шілдедегі № 745 қаулысына толықтыру мен өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58076/rus
