act_code: '53627'
requisite: Постановление Правительства Республики Казахстан от 20 июля 2010 года № 745. Утратило силу постановлением Правительства Республики Казахстан от 18 сентября 2013 года № 983
title:
  rus: Об утверждении реестра государственных услуг, оказываемых физическим и юридическим лицам
  kaz: Жеке және заңды тұлғаларға көрсетілетін мемлекеттік қызметтердің тізілімін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-07-20
approved_by:
- '103000000000'
version_date:
  kaz: 2012-12-11
  rus: 2012-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/53627/kaz/11.12.2012
  rus: https://zan.gov.kz/client/#!/doc/53627/rus/11.12.2012
caused_by:
  code: '69581'
  requisite: Постановление Правительства Республики Казахстан от 11 декабря 2012 года № 1575. Утратило силу постановлением Правительства Республики Казахстан от 28 мая 2014 года № 562
  title:
    rus: Об утверждении стандарта государственной услуги "Выдача документов о прохождении подготовки, повышения квалификации и переподготовки кадров отрасли здравоохранения" и внесении изменения в постановление Правительства Республики Казахстан от 20 июля 2010 года № 745 "Об утверждении реестра государственных услуг, оказываемых физическим и юридическим лицам"
    kaz: '"Денсаулық сақтау саласы кадрларының даярлаудан, біліктілікті жоғарылатудан және қайта даярлаудан өткені туралы құжаттар беру" мемлекеттік қызмет көрсету стандартын бекіту және "Жеке және заңды тұлғаларға көрсетілетін мемлекеттік қызметтердің тізілімін бекіту туралы" Қазақстан Республикасы Үкіметінің 2010 жылғы 20 шілдедегі № 745 қаулысына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/69581/rus
