act_code: '179925'
requisite: Постановление Правительства Республики Казахстан от 12 апреля 2023 года № 284
title:
  rus: Об основных условиях кредитования областных бюджетов, бюджетов городов республиканского значения, столицы на проведение капитального ремонта общего имущества объектов кондоминиумов на 2023 год
  kaz: Облыстық бюджеттерге, республикалық маңызы бар қалалардың, астананың бюджеттеріне кондоминиум объектілерінің ортақ мүлкіне күрделі жөндеу жүргізуге 2023 жылға арналған кредит берудің негізгі шарттары туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2023-04-12
approved_by:
- '103000000000'
version_date:
  kaz: 2023-04-12
  rus: 2023-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/179925/kaz/12.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179925/rus/12.04.2023
