act_code: '68697'
requisite: Постановление акимата района Магжана Жумабаева Северо-Казахстанской области от 18 октября 2012 года № 455. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 ноября 2012 года № 1958. Утратило силу постановлением акимата района Магжана Жумабаева Северо-Казахстанской области от 24 мая 2013 года № 184
title:
  rus: 'Об утверждении регламента государственной услуги "Присвоение спортивных разрядов и категорий: второй и третий, первый, второй и третий юношеские, тренер высшего и среднего уровня квалификации второй категории, инструктор-спортсмен высшего уровня квалификации второй категории, методист высшего и среднего уровня квалификации второй категории, судья по спорту"'
  kaz: '"Екінші және үшінші разрядтар, бірінші, екінші және үшінші жасөспірімдік разрядтар, біліктілігі жоғары және орта деңгейдегі екінші санатты жаттықтырушы, біліктілігі жоғары деңгейдегі екінші санатты нұсқаушы-спортшы, біліктілігі жоғары және орта деңгейдегі екінші санатты әдіскер, спорт төрешісі спорттық разрядтары мен санаттарын беру" мемлекеттік қызмет регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2012-10-18
approved_by:
- '165015000001'
version_date:
  kaz: 2012-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/68697/kaz/18.10.2012
