act_code: '193126'
requisite: Постановление акимата Ерейментауского района Акмолинской области от 6 февраля 2024 года № а-2/34. Утратило силу постановлением акимата Ерейментауского района Акмолинской области от 30 декабря 2025 года № а-13/343 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении схем пастбищеоборотов на основании геоботанического обследования пастбищ
  kaz: Жайылымдарды геоботаникалық зерттеу негізінде жайылым айналымының схемаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2024-02-06
approved_by:
- '152011000001'
version_date:
  kaz: 2024-02-06
  rus: 2024-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/193126/kaz/06.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193126/rus/06.02.2024
