act_code: '173961'
requisite: Постановление Правительства Республики Казахстан от 21 ноября 2022 года № 932
title:
  rus: Об утверждении перечня национальных институтов развития и иных юридических лиц, пятьдесят и более процентов голосующих акций (долей участия в уставном капитале) которых прямо либо косвенно принадлежат государству, уполномоченных на реализацию мер государственного стимулирования промышленности
  kaz: Өнеркәсіпті мемлекеттік ынталандыру шараларын іске асыруға уәкілеттік берілген ұлттық даму институттарының және дауыс беретін акцияларының (жарғылық капиталға қатысу үлестерінің) елу және одан көп пайызы тікелей не жанама түрде мемлекетке тиесілі өзге де заңды тұлғалардың тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2022-11-21
approved_by:
- '103000000000'
version_date:
  kaz: 2024-04-08
  rus: 2024-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/173961/kaz/08.04.2024
  rus: https://zan.gov.kz/client/#!/doc/173961/rus/08.04.2024
caused_by:
  code: '195528'
  requisite: Постановление Правительства Республики Казахстан от 8 апреля 2024 года № 261
  title:
    rus: О некоторых вопросах акционерного общества «Экспортная страховая компания «KazakhExport» и внесении изменений в некоторые решения Правительства Республики Казахстан
    kaz: «KazakhExport» экспорттық сақтандыру компаниясы» акционерлік қоғамының кейбір мәселелері және Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195528/rus
