act_code: '183043'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 7 июня 2023 года № 45. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 июня 2023 года № 32831
title:
  rus: Об утверждении типового договора пенсионного аннуитета, установлении Методики расчета страховой премии и страховой выплаты из страховой организации по договору пенсионного аннуитета, допустимого уровня расходов страховой организации на ведение дела по заключаемым договорам пенсионного аннуитета, а также ставки индексации страховой выплаты
  kaz: Зейнетақы аннуитетінің үлгілік шартын бекіту, Зейнетақы аннуитеті шарты бойынша сақтандыру ұйымынан сақтандыру сыйлықақысын және сақтандыру төлемін есептеу әдістемесін, сақтандыру ұйымының жасалатын зейнетақы аннуитеті шарттары бойынша істі жүргізуге арналған шығыстарының жол берілетін деңгейін, сондай-ақ сақтандыру төлемін индекстеу мөлшерлемесін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2023-06-07
approved_by:
- '135000000000'
version_date:
  kaz: 2023-06-07
  rus: 2023-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/183043/kaz/07.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183043/rus/07.06.2023
