act_code: '56937'
requisite: Постановление акимата Атбасарского района Акмолинской области от 29 декабря 2010 года № А-13/250. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 21 января 2011 года № 1-5-155
title:
  rus: Об организации общественных работ в Атбасарском районе на 2011 год
  kaz: 2011 жылғы Атбасар ауданында қоғамдық жұмыстарда ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-12-29
approved_by:
- '152007000001'
version_date:
  kaz: 2010-12-29
  rus: 2010-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/56937/kaz/29.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56937/rus/29.12.2010
