act_code: '124469'
requisite: Постановление Правительства Республики Казахстан от 11 сентября 2018 года № 556
title:
  rus: О принятии государственного коммунального предприятия на праве хозяйственного ведения «Акмола су арнасы» при отделе жилищно-коммунального хозяйства, пассажирского транспорта и автомобильных дорог Коргалжынского района Акмолинской области из коммунальной собственности в республиканскую собственность
  kaz: Ақмола облысы Қорғалжын ауданының тұрғын үй-коммуналдық шаруашылығы, жолаушылар көлігі және автомобиль жолдары бөлімінің жанындағы «Ақмола су арнасы» шаруашылық жүргізу құқығындағы мемлекеттік коммуналдық кәсіпорнын коммуналдық меншіктен республикалық меншікке қабылдау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-09-11
approved_by:
- '103000000000'
version_date:
  kaz: 2025-08-26
  rus: 2025-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/124469/kaz/26.08.2025
  rus: https://zan.gov.kz/client/#!/doc/124469/rus/26.08.2025
caused_by:
  code: '213590'
  requisite: Постановление Правительства Республики Казахстан от 26 августа 2025 года № 681
  title:
    rus: Об определении перечня водохозяйственных сооружений, находящихся в республиканской собственности
    kaz: Республикалық меншіктегі су шаруашылығы құрылысжайларының тізбесін айқындау туралы
  link: https://zan.gov.kz/client/#!/doc/213590/rus
