act_code: '49846'
requisite: Постановление Правительства Республики Казахстан от 30 декабря 2009 года № 2315. Утратило силу постановлением Правительства Республики Казахстан от 5 марта 2014 года № 180
title:
  rus: Об утверждении стандартов государственных услуг в области информации и архивного дела
  kaz: Ақпарат және мұрағат ісі саласындағы мемлекеттік қызмет стандарттарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-12-30
approved_by:
- '103000000000'
version_date:
  kaz: 2011-07-22
  rus: 2011-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49846/kaz/22.07.2011
  rus: https://zan.gov.kz/client/#!/doc/49846/rus/22.07.2011
caused_by:
  code: '60143'
  requisite: Постановление Правительства Республики Казахстан от 22 июля 2011 года № 842. Утратило силу постановлением Правительства Республики Казахстан от 5 марта 2014 года № 180
  title:
    rus: О внесении изменений и дополнений в постановления Правительства Республики Казахстан от 30 декабря 2009 года № 2315 "О внесении изменения и дополнений в постановление Правительства Республики Казахстан от 30 июня 2007 года № 561 и об утверждении стандартов государственных услуг" и от 20 июля 2010 года № 745 "Об утверждении реестра государственных услуг, оказываемых физическим и юридическим лицам"
    kaz: Қазақстан Республикасы Үкіметінің «Қазақстан Республикасы Үкіметінің 2007 жылғы 30 маусымдағы № 561 қаулысына өзгеріс пен толықтырулар енгізу туралы және мемлекеттік қызмет стандарттарын бекіту туралы» 2009 жылғы 30 желтоқсандағы № 2315 және «Жеке және заңды тұлғаларға көрсетілетін мемлекеттік қызметтердің тізілімін бекіту туралы» 2010 жылғы 20 шілдедегі № 745 қаулыларына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60143/rus
