act_code: '92871'
requisite: Постановление акимата Кызылординской области от 23 июля 2015 года № 93. Зарегистрировано Департаментом юстиции Кызылординской области 13 августа 2015 года № 5103. Утратило силу постановлением акимата Кызылординской области от 6 февраля 2020 года № 163
title:
  rus: Об утверждении регламента государственной услуги
  kaz: Мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-07-23
approved_by:
- '161000000001'
version_date:
  kaz: 2015-07-23
  rus: 2015-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/92871/kaz/23.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92871/rus/23.07.2015
