act_code: '47121'
requisite: Бірлескен Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2009 жылғы 22 маусымдағы N 20-206/IV шешімі және Оңтүстік Қазақстан облысы Сайрам ауданы әкімдігінің 2009 жылғы 22 маусымдағы N 6 қаулысы. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2009 жылғы 31 шілдеде N 14-10-120 тіркелді
title:
  rus: Қарабұлақ ауылының шегін өзгерту туралы
  kaz: Қарабұлақ ауылының шегін өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2009-06-22
approved_by:
- '166008000001'
- '166008000002'
version_date:
  kaz: 2009-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/47121/kaz/22.06.2009
