act_code: '82336'
requisite: Постановление Кабинета Министров Республики Казахстан от 24 августа 1994 г. N 959
title:
  rus: О реализации Закона Республики Казахстан от 14 июля 1994 г. N 137 "Об уточненном республиканском бюджете на 1994 год"
  kaz: О реализации Закона Республики Казахстан от 14 июля 1994 г. N 137 "Об уточненном республиканском бюджете на 1994 год"
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1994-08-23
approved_by:
- '103000000000'
version_date:
  rus: 1994-08-23
source:
  rus: https://zan.gov.kz/client/#!/doc/82336/rus/23.08.1994
