act_code: '20135'
requisite: Павлодар облысы Май аудандық әкімиятының 2004 жылғы 13 мамырдағы № 72/1 қаулысы. Павлодар облысының Әділет департаментінде 2004 жылғы 4 маусымда № 2544 тіркелді
title:
  rus: 2004 жылы аудан аумағындағы азаматтардың жекелеген санаттарына әлеуметтік қолдау туралы
  kaz: 2004 жылы аудан аумағындағы азаматтардың жекелеген санаттарына әлеуметтік қолдау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-05-12
approved_by:
- '164010000001'
version_date:
  kaz: 2007-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/20135/kaz/03.10.2007
