act_code: '881'
requisite: Постановление Кабинета Министpов Республики Казахстан от 30 сентябpя 1993 года № 978. Утратило силу постановлением Правительства Республики Казахстан от 4 марта 1997 года № 299
title:
  rus: Об утверждении положения о порядке возмещения убытков землевладельцам, землепользователям, арендаторам и потерь сельскохозяйственного производства при изъятии сельскохозяйственных угодий для несельскохозяйственных нужд
  kaz: Ауыл шаруашылығының мұқтажына арналмаған ауыл шаруашылық алаптарын алу барысында жер иеленушiлердiң, жер пайдаланушылардың, жалгерлердiң шығындарын және ауыл шаруашылық өндiрiсiнiң залалдарын өтеу тәртiбi туралы Ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1993-09-30
approved_by:
- '103000000000'
version_date:
  rus: 1996-01-19
source:
  rus: https://zan.gov.kz/client/#!/doc/881/rus/19.01.1996
