act_code: '57417'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық әкімдігінің 2011 жылғы 22 ақпандағы № 48 қаулысы. Солтүстік Қазақстан облысының Әділет департаментінде 2011 жылғы 24 ақпанда № 13-13-136 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов ауданы әкімі аппаратының 2012 жылғы 29 желтоқсандағы № 02.12-06-09/362 хаты)
title:
  rus: Уәлиханов ауданының аумағында үгіттік баспа материалдарын орналастыру және сайлаушылармен кездесуі үшін үй-жай белгілеу туралы
  kaz: Уәлиханов ауданының аумағында үгіттік баспа материалдарын орналастыру және сайлаушылармен кездесуі үшін үй-жай белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-02-22
approved_by:
- '165013000001'
version_date:
  kaz: 2011-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/57417/kaz/22.02.2011
