act_code: '52786'
requisite: Атырау облысы Исатай ауданы әкімдігінің 2010 жылғы 12 сәуірдегі № 66 қаулысы. Исатай аудандық Әділет басқармасында 2010 жылғы 20 мамырда № 4-4-162 тіркелді. Күші жойылды - Атырау облысы Исатай ауданы әкімдігінің 2011 жылғы 27 маусымдағы № 98 қаулысымен
title:
  rus: Ұлы Отан соғысындағы жеңістің 65 жылдығына орай соғыс және тыл еңбеккерлері мен жесірлерге жергілікті бюджет есебінен төленетін бір жолғы материалдық көмек төлеу туралы
  kaz: Ұлы Отан соғысындағы жеңістің 65 жылдығына орай соғыс және тыл еңбеккерлері мен жесірлерге жергілікті бюджет есебінен төленетін бір жолғы материалдық көмек төлеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-04-12
approved_by:
- '156005000001'
version_date:
  kaz: 2010-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/52786/kaz/12.04.2010
