act_code: '120244'
requisite: Постановление Правительства Республики Казахстан от 5 апреля 2018 года № 171
title:
  rus: Об утверждении ставок таможенных сборов, взимаемых органами государственных доходов
  kaz: Мемлекеттік кірістер органдары өндіріп алатын кедендік алымдардың мөлшерлемелерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-04-05
approved_by:
- '103000000000'
version_date:
  kaz: 2018-04-05
  rus: 2018-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/120244/kaz/05.04.2018
  rus: https://zan.gov.kz/client/#!/doc/120244/rus/05.04.2018
