act_code: '39948'
requisite: Бірлескен Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2008 жылғы 13 мамырдағы N 7/3-04 шешімі және Түлкібас ауданы әкімдігінің 2008 жылғы 13 мамырдағы N 234 қаулысы. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2008 жылғы 29 мамырда N 14-14-51 тіркелді
title:
  rus: Кемербастау ауылдық округіне қарасты Кемербастау, Мәнтай Жәрімбетов атындағы, Алғабас ауылдарының, Майлыкент ауылдық округіне қарасты Т.Рысқұлов ауылының шекараларын өзгерту туралы
  kaz: Кемербастау ауылдық округіне қарасты Кемербастау, Мәнтай Жәрімбетов атындағы, Алғабас ауылдарының, Майлыкент ауылдық округіне қарасты Т.Рысқұлов ауылының шекараларын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2008-05-13
approved_by:
- '166012000001'
- '166012000002'
version_date:
  kaz: 2008-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/39948/kaz/13.05.2008
