act_code: '14961'
requisite: Постановление акимата города Рудного Костанайской области от 28 января 2003 года № 20. Зарегистрировано Управлением юстиции Костанайской области 18 февраля 2003 года № 2034. Утратило силу постановлением акимата города Рудного Костанайской области от 27 июня 2006 года № 532
title:
  rus: 'Об утверждении Правил оказания социальной помощи: на оздоровление детей в профилакториях и летних лагерях отдыха и семьям, имеющим детей школьного возраста к началу учебного года'
  kaz: Профилакторияларда және жазғы демалыс лагерьлерінде балаларды сауықтыру үшін, оқу жылының басында мектеп жасындағы балалары бар отбасыларға әлеуметтік көмек көрсету ережелерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-01-28
approved_by:
- '162021000001'
version_date:
  kaz: 2003-01-28
  rus: 2003-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/14961/kaz/28.01.2003
  rus: https://zan.gov.kz/client/#!/doc/14961/rus/28.01.2003
