act_code: '142134'
requisite: Постановление Правления Национального Банка Республики Казахстан от 21 апреля 2020 года № 54. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 апреля 2020 года № 20474. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 2 декабря 2025 года № 88 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня, форм, сроков и Правил представления отчетности банками второго уровня
  kaz: Екінші деңгейдегі банктер есептілігінің тізбесін, нысандарын, мерзімдерін және ұсыну қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
- ПРЧ
approved_on: 2020-04-21
approved_by:
- '117000000000'
version_date:
  kaz: 2020-04-21
  rus: 2020-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/142134/kaz/21.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142134/rus/21.04.2020
