act_code: '49374'
requisite: Постановление Правительства Республики Казахстан от 15 декабря 2009 года № 2136. Утратило силу постановлением Правительства Республики Казахстан от 16 октября 2020 года № 672 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня гарантированного объема бесплатной медицинской помощи
  kaz: Тегін медициналық көмектің кепілдік берілген көлемінің тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2009-12-15
approved_by:
- '103000000000'
version_date:
  kaz: 2019-09-03
  rus: 2019-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/49374/kaz/03.09.2019
  rus: https://zan.gov.kz/client/#!/doc/49374/rus/03.09.2019
caused_by:
  code: '134517'
  requisite: Постановление Правительства Республики Казахстан от 3 сентября 2019 года № 655. Утратило силу постановлением Правительства Республики Казахстан от 16 октября 2020 года № 672 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О некоторых вопросах апробирования обязательного социального медицинского страхования в пилотном режиме и внесении дополнений в постановление Правительства Республики Казахстан от 15 декабря 2009 года № 2136 «Об утверждении перечня гарантированного объема бесплатной медицинской помощи»
    kaz: Пилоттық режимде міндетті әлеуметтік медициналық сақтандыруды сынақтан өткізудің кейбір мәселелері және «Тегін медициналық көмектің кепілдік берілген көлемінің тізбесін бекіту туралы» Қазақстан Республикасы Үкіметінің 2009 жылғы 15 желтоқсандағы № 2136 қаулысына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134517/rus
