act_code: '22437'
requisite: Постановление Правительства Республики Казахстан от 24 декабря 2004 года N 1379
title:
  rus: О целевых текущих трансфертах областным бюджетам, бюджетам городов Астаны и Алматы на реализацию Государственной программы реформирования и развития здравоохранения Республики Казахстан на 2005-2010 годы
  kaz: Қазақстан Республикасының денсаулық сақтау iсiн реформалау мен дамытудың 2005-2010 жылдарға арналған мемлекеттiк бағдарламасын iске асыруға облыстық бюджеттерге, Астана және Алматы қалаларының бюджеттерiне берiлетiн ағымдағы нысаналы трансферттер туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2004-12-24
approved_by:
- '103000000000'
version_date:
  kaz: 2004-12-24
  rus: 2004-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/22437/kaz/24.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22437/rus/24.12.2004
