act_code: '49518'
requisite: Постановление Правительства Республики Казахстан от 25 декабря 2009 года № 2204
title:
  rus: Об утверждении перечня участков недр, подлежащих выставлению на конкурс
  kaz: Конкурсқа шығарылуға тиіс жер қойнауы учаскелерінің тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2009-12-25
approved_by:
- '103000000000'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49518/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49518/rus/25.12.2009
