act_code: '92319'
requisite: Постановление от 17.07.2015 №А-1/400, Акимат Зерендинского района
title:
  rus: Об определении сроков предоставления заявок на получение субсидий на повышение урожайности и качества продукции растениеводства, стоимости горюче-смазочных материалов и других товарно-материальных ценностей, необходимых для проведения весенне-полевых и уборочных работ, путем субсидирования производства приоритетных культур и стоимости затрат на возделывание сельскохозяйственных культур в защищенном грунте для включения в список сельскохозяйственных товаропроизводителей на получение субсидий и оптимальных сроков сева по каждому виду субсидируемых приоритетных сельскохозяйственных культур по Зерендинскому району на 2015 год
  kaz: Зеренді ауданы бойынша 2015 жылға арналған субсидияланатын басым ауыл шаруашылығы дақылдарының әрбір түрі бойынша оңтайлы себу мерзімдерін және субсидияларды алуға ауыл шаруашылығы тауар өндірушілерінің тізіміне енгізу үшін басым дақылдар өндіруді субсидиялау арқылы өсімдік шаруашылығының шығындылығын және өнім сапасын арттыруды, жанар-жағармай материалдарының және көктемгі егіс пен егін жинау жұмыстарын жүргізу үшін қажетті басқа да тауарлық-материалдық құндылықтардың құнына және ауыл шаруашылығы дақылдарын қорғалған топырақта өңдеп өсіру шығындарының құнына субсидиялар алу үшін өтінімдерді ұсыну мерзімдерін айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-07-17
approved_by:
- '152015000001'
version_date:
  kaz: 2015-07-17
  rus: 2015-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/92319/kaz/17.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92319/rus/17.07.2015
