act_code: '43334'
requisite: Постановление акимата Кордайского района Жамбылской области от 3 декабря 2008 года № 601. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 9 января 2009 года № 6-5-70. Утратило силу постановлением акимата Кордайского района Жамбылской области от 30 июня 2009 года № 285
title:
  rus: Об оказании материальной помощи
  kaz: Материалдық көмек көрсету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-12-03
approved_by:
- '158006000001'
version_date:
  kaz: 2008-12-03
  rus: 2008-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/43334/kaz/03.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43334/rus/03.12.2008
