act_code: '10871'
requisite: Постановление Правительства Республики Казахстан от 28 декабря 2001 года N 1755. Утратило силу постановлением Правительства Республики Казахстан от 19 ноября 2015 года № 925
title:
  rus: Вопросы Комитета уголовно-исполнительной системы Министерства юстиции Республики Казахстан
  kaz: Қазақстан Республикасы Әдiлет министрлiгiнiң Қылмыстық-атқару жүйесі комитетiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2001-12-28
approved_by:
- '103000000000'
version_date:
  kaz: 2002-12-29
  rus: 2002-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/10871/kaz/29.12.2002
  rus: https://zan.gov.kz/client/#!/doc/10871/rus/29.12.2002
caused_by:
  code: '13992'
  requisite: Постановление Правительства Республики Казахстан от 29 декабря 2002 года N 1443. Утратило силу - постановлением Правительства РК от 17 марта 2004 г. N 330 (P040330)
  title:
    rus: Об утверждении лимита штатной численности системы органов внутренних дел Республики Казахстан, финансируемых из республиканского бюджета
    kaz: Республикалық бюджеттен қаржыландырылатын Қазақстан Республикасының ішкі істер органдары жүйесі штат санының лимитiн бекiту туралы
  link: https://zan.gov.kz/client/#!/doc/13992/rus
