act_code: '27114'
requisite: Постановление акимата Катон-Карагайского района Восточно-Казахстанской области от 27 марта 2006 года № 2255. Зарегистрировано управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 7 апреля 2006 года за № 5-13-16
title:
  rus: Об утверждении Правил назначения и выплаты материального обеспечения на детей-инвалидов, воспитывающихся и обучающихся на дому
  kaz: Об утверждении Правил назначения и выплаты материального обеспечения на детей-инвалидов, воспитывающихся и обучающихся на дому
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2006-03-27
approved_by:
- '157014000001'
version_date:
  rus: 2006-03-27
source:
  rus: https://zan.gov.kz/client/#!/doc/27114/rus/27.03.2006
