act_code: '23502'
requisite: Постановление Правительства Республики Казахстан от 6 апреля 2005 года № 310
title:
  rus: Некоторые вопросы Министерства сельского хозяйства Республики Казахстан
  kaz: Қазақстан Республикасы Ауыл шаруашылығы министрлігінiң кейбiр мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2005-04-06
approved_by:
- '103000000000'
version_date:
  kaz: 2021-03-19
  rus: 2021-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/23502/kaz/19.03.2021
  rus: https://zan.gov.kz/client/#!/doc/23502/rus/19.03.2021
caused_by:
  code: '153773'
  requisite: Постановление Правительства Республики Казахстан от 19 марта 2021 года № 159
  title:
    rus: О внесении изменений и дополнений в постановления Правительства Республики Казахстан от 6 апреля 2005 года № 310 «Некоторые вопросы Министерства сельского хозяйства Республики Казахстан» и от 3 апреля 2008 года № 316 «О некоторых вопросах сотрудничества с Международным консультативным комитетом по хлопку»
    kaz: Қазақстан Республикасы Үкіметінің «Қазақстан Республикасы Ауыл шаруашылығы министрлігінің кейбір мәселелері» туралы 2005 жылғы 6 сәуірдегі № 310 және «Халықаралық мақта жөніндегі консультативтік комитетпен ынтымақтастықтың кейбір мәселелері туралы» 2008 жылғы 3 сәуірдегі № 316 қаулыларына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153773/rus
