act_code: '96724'
requisite: Нормативное постановление Счетного комитета по контролю за исполнением республиканского бюджета от 28 ноября 2015 года № 11-НҚ. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 декабря 2015 года № 12514
title:
  rus: Об утверждении Типового положения о ревизионных комиссиях столицы, областей, городов республиканского значения
  kaz: Астананың, облыстардың, республикалық маңызы бар қалалардың тексеру комиссиялары туралы үлгілік ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2015-11-28
approved_by:
- '115000000000'
version_date:
  kaz: 2020-04-23
  rus: 2020-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/96724/kaz/23.04.2020
  rus: https://zan.gov.kz/client/#!/doc/96724/rus/23.04.2020
caused_by:
  code: '142207'
  requisite: Нормативное постановление Счетного комитета по контролю за исполнением республиканского бюджета от 23 апреля 2020 года № 4-НҚ. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 апреля 2020 года № 20492
  title:
    rus: О внесении дополнения в нормативное постановление Счетного комитета по контролю за исполнением республиканского бюджета от 28 ноября 2015 года № 11-НҚ «Об утверждении Типового положения о ревизионных комиссиях областей, городов республиканского значения, столицы»
    kaz: «Облыстардың, республикалық маңызы бар қалалардың, астананың тексеру комиссиялары туралы Үлгілік ережені бекіту туралы» Республикалық бюджеттің атқарылуын бақылау жөніндегі есеп комитетінің 2015 жылғы 28 қарашадағы № 11-НҚ нормативтік қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142207/rus
