act_code: '274'
requisite: Постановление Кабинета Министров Республики Казахстан от 20 июля 1993 года № 630. Утратило силу постановлением Правительства Республики Казахстан от 1 марта 2005 года № 187
title:
  rus: О порядке выезда за границу по служебным делам и мерах по усилению контроля за расходованием валютных средств на заграничные командировки
  kaz: Қызмет бабымен шетелге шығудың тәртiбi және шетелдiк iссапарларға валюта қаржысының жұмсалуын бақылауды күшейту жөнiндегi шаралар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1993-07-19
approved_by:
- '103000000000'
version_date:
  rus: 1993-10-29
source:
  rus: https://zan.gov.kz/client/#!/doc/274/rus/29.10.1993
