act_code: '219743'
requisite: Постановление акимата Сарыкольского района Костанайской области от 19 декабря 2025 года № 207
title:
  rus: Об утверждении Положения о государственном учреждении «Отдел культуры и развития языков акимата Сарыкольского района»
  kaz: «Сарыкөл ауданы әкімдігінің мәдениет және тілдерді дамыту бөлімі» мемлекеттік мекемесі туралы ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2025-12-19
approved_by:
- '162015000001'
version_date:
  kaz: 2025-12-19
  rus: 2025-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219743/kaz/19.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219743/rus/19.12.2025
