act_code: '83400'
requisite: Постановление Правления Национального Банка Республики Казахстан от 16 июля 2014 года № 147. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 сентября 2014 года № 9711. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 3 апреля 2026 года № 48 (вводится в действие с 1 июля 2026 года)
title:
  rus: Об утверждении Правил назначения и полномочий временной администрации (временного администратора) банка, страховой (перестраховочной) организации
  kaz: Банктің, сақтандыру (қайта сақтандыру) ұйымының уақытша әкімшілігін (уақытша әкiмшісін) тағайындау және оның өкілеттіктері қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-07-16
approved_by:
- '117000000000'
version_date:
  kaz: 2018-04-27
  rus: 2018-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/83400/kaz/27.04.2018
  rus: https://zan.gov.kz/client/#!/doc/83400/rus/27.04.2018
caused_by:
  code: '122211'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 27 апреля 2018 года № 72. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 мая 2018 года № 16959. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 3 апреля 2026 года № 48 (вводится в действие с 1 июля 2026 года)
  title:
    rus: О внесении изменений и дополнения в постановление Правления Национального Банка Республики Казахстан от 16 июля 2014 года № 147 «Об утверждении Правил назначения и полномочий временной администрации (временного администратора) банка, страховой (перестраховочной) организации»
    kaz: «Банктің, сақтандыру (қайта сақтандыру) ұйымының уақытша әкімшілігін (уақытша басқарушысын) тағайындау және олардың өкілеттіктері қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық Банкі Басқармасының 2014 жылғы 16 шілдедегі № 147 қаулысына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122211/rus
