act_code: '107259'
requisite: Постановление акимата Байдибекского района Южно-Казахстанской области от 11 октября 2016 года № 346. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 ноября 2016 года № 3872. Утратило силу постановлением акимата Байдибекского района Южно-Казахстанской области от 24 июля 2017 года № 228
title:
  rus: Об установлении квоты рабочих мест для инвалидов
  kaz: Мүгедектер үшін жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-10-11
approved_by:
- '166003000001'
version_date:
  kaz: 2016-10-11
  rus: 2016-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/107259/kaz/11.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107259/rus/11.10.2016
