act_code: '3547'
requisite: Постановление Правления Национального Банка Республики Казахстан от 31 декабря 1996 г. N 351. Зарегистрирован в Министерстве юстиции Республики Казахстан 21.01.1998г. N 434. Утратило силу - постановлением Правления Агентства РК по регулированию и надзору финансового рынка и финансовых организаций от 27 августа 2005 года N 320 (V053841)(порядок введения в действие см.2 пост. N 320
title:
  rus: Об утверждении Инструкции об оформлении и учете документов, подлежащих хранению в банках, и требованиях по организации хранения документов
  kaz: '"Банктерде сақталуы тиіс құжаттарды ресімдеу және есепке алу тәртібі және құжаттарды сақтауды ұйымдастыру жөніндегі талаптар туралы" Нұсқаулық туралы'
form: ПОСТ
type_codes:
- ИНСТ
- ПОСТ
approved_on: 1996-12-31
approved_by:
- '117000000000'
version_date:
  rus: 1996-12-31
source:
  rus: https://zan.gov.kz/client/#!/doc/3547/rus/31.12.1996
