act_code: '83203'
requisite: Постановление Правительства Республики Казахстан от 29 августа 2014 года № 959
title:
  rus: О некоторых вопросах реализации Закона Республики Казахстан от 30 июня 2014 года "Об амнистии граждан Республики Казахстан, оралманов и лиц, имеющих вид на жительство в Республике Казахстан, в связи с легализацией ими имущества"
  kaz: '"Қазақстан Республикасының азаматтарына, оралмандарға және Қазақстан Республикасында тұруға ықтиярхаты бар адамдарға олардың мүлікті жария етуіне байланысты рақымшылық жасау туралы" 2014 жылғы 30 маусымдағы Қазақстан Республикасының Заңын іске асырудың кейбір мәселелері туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-08-29
approved_by:
- '103000000000'
version_date:
  kaz: 2014-08-29
  rus: 2014-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/83203/kaz/29.08.2014
  rus: https://zan.gov.kz/client/#!/doc/83203/rus/29.08.2014
