act_code: '54204'
requisite: Постановление акимата Аршалынского района Акмолинской области от 29 июля 2010 года № А-329. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 26 августа 2010 года № 1-4-173. Утратило силу - постановлением акимата Аршалынского района Акмолинской области от 23 февраля 2011 года № А-56
title:
  rus: Об установлении дополнительного перечня лиц, относящихся к целевым группам населения Аршалынского района
  kaz: Аршалы ауданындағы халықтың мақсатты топтарына жататын адамдардың қосымша тізбелерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-07-29
approved_by:
- '152005000001'
version_date:
  kaz: 2010-07-29
  rus: 2010-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/54204/kaz/29.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54204/rus/29.07.2010
