act_code: '96453'
requisite: Постановление акимата Тарановского района Костанайской области от 18 ноября 2015 года № 286. Зарегистрировано Департаментом юстиции Костанайской области 14 декабря 2015 года № 6059. Утратило силу постановлением акимата Тарановского района Костанайской области от 15 апреля 2016 года № 132
title:
  rus: Об определении целевых групп населения в 2016 году
  kaz: 2016 жылға халықтың нысаналы топтарын анықтау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-11-18
approved_by:
- '162016000001'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/96453/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96453/rus/24.12.2015
caused_by:
  code: '97590'
  requisite: Постановление акимата Тарановского района Костанайской области от 24 декабря 2015 года № 308. Зарегистрировано Департаментом юстиции Костанайской области 12 января 2016 года № 6133. Утратило силу постановлением акимата Тарановского района Костанайской области от 15 апреля 2016 года № 132
  title:
    rus: О внесении изменений в постановление акимата района от 18 ноября 2015 года № 286 "Об определении целевых групп населения в 2016 году"
    kaz: Аудан әкімдігінің 2015 жылғы 18 қарашадағы № 286 "2016 жылға халықтың нысаналы топтарын анықтау туралы" қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97590/rus
