act_code: '61469'
requisite: Постановление Правительства Республики Казахстан от 18 ноября 2011 года № 1353. Утратило силу постановлением Правительства Республики Казахстан от 28 ноября 2015 года № 960
title:
  rus: Об утверждении Правил назначения и аттестации руководителя государственного предприятия, а также согласования его кандидатуры
  kaz: Мемлекеттік кәсіпорынның басшысын тағайындау және аттестаттау, сондай-ақ оның кандидатурасын келісу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2011-11-18
approved_by:
- '103000000000'
version_date:
  kaz: 2011-11-18
  rus: 2011-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/61469/kaz/18.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61469/rus/18.11.2011
