act_code: '2140'
requisite: Постановление Правительства Республики Казахстан от 26 декабря 1996 года № 1624. Утратило силу постановлением Правительства Республики Казахстан от 28 февраля 2000 года № 323
title:
  rus: Об утверждении Положения о порядке приобретения, учета и выдачи путевок на санаторно-курортное лечение и организованный отдых детей за счет средств Фонда государственного социального страхования Республики Казахстан
  kaz: Қазақстан Республикасы Мемлекеттiк әлеуметтiк сақтандыру қорының қаражаты есебiнен санаторий-курорттық емдеуге және балалардың ұйымдастырылған демалысына жолдамалар сатып алу, оларды есепке алу және беру тәртiбi туралы ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1996-12-26
approved_by:
- '103000000000'
version_date:
  rus: 1996-12-26
source:
  rus: https://zan.gov.kz/client/#!/doc/2140/rus/26.12.1996
