act_code: '89227'
requisite: Постановление акимата Жанааркинского района Карагандинской области от 20 марта 2015 года № 22/01. Зарегистрировано Департаментом юстиции Карагандинской области 16 апреля 2015 года № 3148. Утратило силу постановлением акимата Жанааркинского района Карагандинской области от 22 апреля 2016 года N 37/05
title:
  rus: Об утверждении Положения государственного учреждения «Отдел сельского хозяйства  Жанааркинского района»
  kaz: «Жаңаарқа ауданының  ауыл шаруашылығы бөлімі» мемлекеттік мекемесінің Ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2015-03-20
approved_by:
- '160016000001'
version_date:
  kaz: 2016-01-19
  rus: 2016-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/89227/kaz/19.01.2016
  rus: https://zan.gov.kz/client/#!/doc/89227/rus/19.01.2016
caused_by:
  code: '99815'
  requisite: Постановление акимата Жанааркинского района Карагандинской области от 19 января 2016 года № 04/02. Зарегистрировано Департаментом юстиции Карагандинской области 18 февраля 2016 года № 3670. Утратило силу постановлением акимата Жанааркинского района Карагандинской области от 22 апреля 2016 года N 37/05
  title:
    rus: О внесении изменения в постановление акимата Жанааркинского района от 20 марта 2015 года № 22/01 «Об утверждении Положения государственного учреждения «Отдел сельского хозяйства Жанааркинского района»
    kaz: Жаңаарқа ауданы әкімдігінің 2015 жылғы 20 наурыздағы №22/01 «Жаңаарқа ауданының ауыл шаруашылығы бөлімі» мемлекеттік мекемесінің Ережесін бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99815/rus
