act_code: '1404'
requisite: Постановление Правительства Республики Казахстан от 22 апреля 1997 г. N 619. Утратило силу - постановлением Правительства РК от 13 апреля 2000 г. N 565
title:
  rus: Об утверждении Порядка выделения официальных трансфертов (субвенций) бюджетам областей
  kaz: Облыс бюджеттерiне ресми трансферттер (субвенциялар) бөлу тәртiбiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1997-04-21
approved_by:
- '103000000000'
version_date:
  rus: 1997-04-21
source:
  rus: https://zan.gov.kz/client/#!/doc/1404/rus/21.04.1997
