act_code: '39911'
requisite: Батыс Қазақстан облысы Орал қаласы әкімдігінің 2008 жылғы 29 мамырдағы № 1360 қаулысы. Батыс Қазақстан облысы Орал қаласының Әділет басқармасында 2008 жылғы 30 мамырда № 7-1-90 тіркелді. Күші жойылды - Батыс Қазақстан облысы Орал қаласы әкімдігінің 2009 жылғы 9 cәуірдегі № 959 қаулысымен
title:
  rus: Шақыру жасындағы азаматтарды 2008 жылғы көктемде және күзде кезекті мерзімді әскери қызметке шақыру туралы
  kaz: Шақыру жасындағы азаматтарды 2008 жылғы көктемде және күзде кезекті мерзімді әскери қызметке шақыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-05-29
approved_by:
- '159002000001'
version_date:
  kaz: 2008-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/39911/kaz/29.05.2008
