act_code: '164538'
requisite: Постановление акимата Павлодарской области от 17 января 2022 года № 19/1
title:
  rus: Об утверждении Положения о государственном учреждении «Управление культуры, развития языков и архивного дела Павлодарской области»
  kaz: «Павлодар облысының мәдениет, тілдерді дамыту және архив ісі басқармасы» мемлекеттік мекемесі туралы ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2022-01-17
approved_by:
- '164000000001'
version_date:
  kaz: 2022-01-17
  rus: 2022-01-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/164538/kaz/17.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164538/rus/17.01.2022
