act_code: '106725'
requisite: Постановление Правительства Республики Казахстан от 6 октября 2016 года № 569. Утратило силу постановлением Правительства Республики Казахстан от 13 июля 2023 года № 560
title:
  rus: Об утверждении Правил разработки, согласования проектов подзаконных нормативных правовых актов
  kaz: Заңға тәуелді нормативтік құқықтық актілердің жобаларын әзірлеу, келісу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2016-10-06
approved_by:
- '103000000000'
version_date:
  kaz: 2018-07-24
  rus: 2018-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/106725/kaz/24.07.2018
  rus: https://zan.gov.kz/client/#!/doc/106725/rus/24.07.2018
caused_by:
  code: '123738'
  requisite: Постановление Правительства Республики Казахстан от 24 июля 2018 года № 463. Утратило силу постановлением Правительства Республики Казахстан от 13 июля 2023 года № 560
  title:
    rus: О внесении изменений и дополнений в постановления Правительства Республики Казахстан от 6 октября 2016 года № 568 «Об утверждении Правил оформления, согласования, государственной регистрации нормативных правовых актов и их отмены» и от 6 октября 2016 года № 569 «Об утверждении Правил разработки, согласования проектов нормативных правовых актов»
    kaz: Қазақстан Республикасы Үкіметінің «Нормативтік құқықтық актілерді ресiмдеу, келісу, мемлекеттік тіркеу және олардың күшін жою қағидаларын бекіту туралы» 2016 жылғы 6 қазандағы № 568 және «Заңға тәуелді нормативтік құқықтық актілердің жобаларын әзірлеу, олардың келісілу қағидаларын бекіту туралы» 2016 жылғы 6 қазандағы № 569 қаулыларына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123738/rus
