act_code: '29188'
requisite: Постановление акимата Атбасарского района Акмолинской области от 14 июля 2006 года № а-7/138. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 31 июля 2006 года № 1-5-57
title:
  rus: Об определении помещений для встреч с избирателями и мест для проведения мирных собраний, митингов, шествий, пикетов и демонстраций в сельских населенных пунктах Атбасарского района
  kaz: Атбасар ауданының селолық елді мекендерінде сайлаушылармен кездесу үшін үй-жай және бейбіт жиналыстар, митингілер, шерулер, пикеттер өткізу орындарын белгілеу жөнінде
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-07-14
approved_by:
- '152007000001'
version_date:
  kaz: 2006-07-14
  rus: 2006-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/29188/kaz/14.07.2006
  rus: https://zan.gov.kz/client/#!/doc/29188/rus/14.07.2006
