act_code: '20252'
requisite: Постановление Правительства Республики Казахстан от 21 июня 2004 года N 677. Утратило силу постановлением Правительства Республики Казахстан от 22 ноября 2021 года № 827 (вводится в действие со дня подписания)
title:
  rus: Об утверждении Правил разработки среднесрочной фискальной политики
  kaz: Орта мерзiмдi фискалдық саясатты әзiрлеу ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-06-20
approved_by:
- '103000000000'
version_date:
  kaz: 2006-09-25
  rus: 2006-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/20252/kaz/25.09.2006
  rus: https://zan.gov.kz/client/#!/doc/20252/rus/25.09.2006
caused_by:
  code: '29731'
  requisite: Постановление Правительства Республики Казахстан от 25 сентября 2006 года № 909. Утратило силу постановлением Правительства Республики Казахстан от 22 ноября 2021 года № 827 (вводится в действие со дня подписания)
  title:
    rus: О внесении изменений и дополнений в постановление Правительства Республики Казахстан от 21 июня 2004 года № 677
    kaz: Қазақстан Республикасы Үкiметiнiң 2004 жылғы 21 маусымдағы № 677 қаулысына өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/29731/rus
