act_code: '34771'
requisite: Постановление Правительства Республики Казахстан от 17 августа 2007 года № 704
title:
  rus: О передаче и переименовании государственного учреждения "Центр медицины катастроф" Министерства здравоохранения Республики Казахстан из ведения Министерства здравоохранения Республики Казахстан в ведение Министерства по чрезвычайным ситуациям Республики Казахстан
  kaz: Қазақстан Республикасы Денсаулық сақтау министрлігінің "Апаттар медицинасы орталығы" мемлекеттік мекемесін Қазақстан Республикасы Денсаулық сақтау министрлігінің қарамағынан Қазақстан Республикасы Төтенше жағдайлар министрлігінің қарамағына беру және қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-08-17
approved_by:
- '103000000000'
version_date:
  kaz: 2008-04-15
  rus: 2008-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/34771/kaz/15.04.2008
  rus: https://zan.gov.kz/client/#!/doc/34771/rus/15.04.2008
caused_by:
  code: '38863'
  requisite: Постановление Правительства Республики Казахстан от 15 апреля 2008 года № 339
  title:
    rus: Об утверждении лимитов штатной численности министерств и иных центральных исполнительных органов с учетом численности их территориальных органов и подведомственных им государственных учреждений
    kaz: Министрліктер мен өзге де орталық атқарушы органдардың олардың аумақтық органдарындағы және оларға ведомстволық бағыныстағы мемлекеттік мекемелердегі адам санын ескере отырып, штат санының лимиттерін бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/38863/rus
