act_code: '126606'
requisite: Постановление акимата Западно-Казахстанской области от 26 ноября 2018 года № 270. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 4 декабря 2018 года № 5418. Утратило силу постановлением акимата Западно-Казахстанской области от 25 февраля 2019 года № 45
title:
  rus: Об утверждении объемов субсидирования повышения продуктивности и качества продукции аквакультуры (рыбоводства)
  kaz: Акваөсірудің (балық өсіру шаруашылығы) өнімділігін және өнім сапасын арттыруды субсидиялау көлемдерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-11-26
approved_by:
- '159000000001'
version_date:
  kaz: 2018-11-26
  rus: 2018-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/126606/kaz/26.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126606/rus/26.11.2018
