act_code: '225253'
requisite: Постановление акимата города Астаны от 13 мая 2026 года № 508-1630
title:
  rus: Об установлении цен на товары (работы, услуги), производимые и реализуемые коммунальными казенными предприятиями в сфере культуры
  kaz: Мәдениет саласындағы коммуналдық қазыналық кәсіпорындар өндіретін және өткізетін тауарлардың (жұмыстардың, көрсетілетін қызметтердің) бағаларын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2026-05-13
approved_by:
- '151000000001'
version_date:
  kaz: 2026-05-13
  rus: 2026-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/225253/kaz/13.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225253/rus/13.05.2026
