act_code: '213831'
requisite: Постановление акимата Шортандинского района Акмолинской области от 28 августа 2025 года № А-3/189
title:
  rus: Об установлении размера платы за пользование жилищем из государственного жилищного фонда
  kaz: Мемлекеттік тұрғын үй қорынан тұрғын үйді пайдаланғаны үшін төлемақы мөлшерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-08-28
approved_by:
- '152019000001'
version_date:
  kaz: 2025-08-28
  rus: 2025-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/213831/kaz/28.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213831/rus/28.08.2025
