act_code: '102168'
requisite: Постановление акимата Байдибекского района Южно-Казахстанской области от 8 апреля 2016 года № 92. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 5 мая 2016 года № 3740. Утратило силу постановлением акимата Байдибекского района Южно-Казахстанской области от 31 марта 2017 года № 53
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих исполнительных органов финансируемых из районного бюджета и административных государственных служащих аппарата акима Байдибекского района корпуса «Б»
  kaz: «Б» корпусындағы аудандық бюджеттен қаржыландырылатын атқарушы органдардың мемлекеттік әкімшілік қызметшілері мен Бәйдібек ауданы әкімі аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: ПОСТ
type_codes:
- МЕТ
- ПОСТ
approved_on: 2016-04-08
approved_by:
- '166003000001'
version_date:
  kaz: 2016-04-08
  rus: 2016-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/102168/kaz/08.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102168/rus/08.04.2016
