act_code: '193221'
requisite: Постановление акимата Западно-Казахстанской области от 14 августа 2023 года № 191
title:
  rus: О создании государственного учреждения «Управление мобилизационной подготовки и гражданской обороны Западно-Казахстанской области»
  kaz: «Батыс Қазақстан облысының жұмылдыру даярлығы және азаматтық қорғау басқармасы» мемлекеттік мекемесін құру туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2023-08-14
approved_by:
- '159000000001'
version_date:
  kaz: 2023-08-14
  rus: 2023-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/193221/kaz/14.08.2023
  rus: https://zan.gov.kz/client/#!/doc/193221/rus/14.08.2023
