act_code: '30238'
requisite: Постановление Правительства Республики Казахстан от 9 ноября 2006 года № 1072
title:
  rus: Об утверждении Типового положения о юридических службах государственных органов Республики Казахстан
  kaz: Қазақстан Республикасы мемлекеттiк органдарының заң қызметтерi туралы үлгi ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2006-11-09
approved_by:
- '103000000000'
version_date:
  kaz: 2011-07-30
  rus: 2011-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/30238/kaz/30.07.2011
  rus: https://zan.gov.kz/client/#!/doc/30238/rus/30.07.2011
caused_by:
  code: '59864'
  requisite: Постановление Правительства Республики Казахстан от 30 июля 2011 года № 885
  title:
    rus: О внесении изменения и дополнений в постановления Правительства Республики Казахстан от 10 декабря 2002 года № 1300 "О Регламенте Правительства Республики Казахстан" и от 9 ноября 2006 года № 1072 "Об утверждении Типового положения о юридических службах государственных органов Республики Казахстан"
    kaz: Қазақстан Республикасы Үкіметінің "Қазақстан Республикасы Үкіметінің Регламенті туралы" 2002 жылғы 10 желтоқсандағы № 1300 және "Қазақстан Республикасы мемлекеттік органдарының заң қызметтері туралы үлгі ережені бекіту туралы" 2006 жылғы 9 қарашадағы № 1072 қаулыларына өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59864/rus
