act_code: '59496'
requisite: Постановление акимата Костанайской области от 10 июня 2011 года № 259. Зарегистрировано Департаментом юстиции Костанайской области 8 июля 2011 года № 3767. Утратило силу - Постановлением акимата Костанайской области от 26 марта 2012 года № 139
title:
  rus: Об утверждении перечня объектов областной коммунальной собственности по Костанайской области, подлежащих приватизации
  kaz: Қостанай облысы бойынша жекешелендіруге жататын облыстық коммуналдық меншіктегі объектілердің тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-06-10
approved_by:
- '162000000001'
version_date:
  kaz: 2011-06-10
  rus: 2011-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/59496/kaz/10.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59496/rus/10.06.2011
