act_code: '94743'
requisite: Постановление акимата Карагандинской области от 12 августа 2015 года № 45/08. Зарегистрировано Департаментом юстиции Карагандинской области 23 сентября 2015 года № 3414. Утратило силу постановлением акимата Карагандинской области от 3 июля 2020 года № 41/04 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере физической культуры и спорта
  kaz: Дене шынықтыру және спорт саласында мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2015-08-12
approved_by:
- '160000000001'
version_date:
  kaz: 2016-11-21
  rus: 2016-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/94743/kaz/21.11.2016
  rus: https://zan.gov.kz/client/#!/doc/94743/rus/21.11.2016
caused_by:
  code: '108926'
  requisite: Постановление акимата Карагандинской области от 21 ноября 2016 года № 83/02. Зарегистрировано Департаментом юстиции Карагандинской области 22 декабря 2016 года № 4060. Утратило силу постановлением акимата Карагандинской области от 3 июля 2020 года № 41/04 (вводится в действие со дня первого официального опубликования)
  title:
    rus: О внесении изменений в постановление акимата Карагандинской области от 12 августа 2015 года № 45/08 «Об утверждении регламентов государственных услуг в сфере физической культуры и спорта»
    kaz: «Дене шынықтыру және спорт саласында мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы» Қарағанды облысы әкімдігінің 2015 жылғы 12 тамыздағы № 45/08 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108926/rus
