act_code: '21701'
requisite: Постановление Правительства Республики Казахстан от 28 октября 2004 года № 1118
title:
  rus: Вопросы Министерства иностранных дел Республики Казахстан
  kaz: Қазақстан Республикасы Сыртқы iстер министрлiгiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2004-10-28
approved_by:
- '103000000000'
version_date:
  kaz: 2019-07-31
  rus: 2019-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/21701/kaz/31.07.2019
  rus: https://zan.gov.kz/client/#!/doc/21701/rus/31.07.2019
caused_by:
  code: '133677'
  requisite: Постановление Правительства Республики Казахстан от 31 июля 2019 года № 561
  title:
    rus: О переименовании некоторых республиканских государственных учреждений и внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Кейбiр республикалық мемлекеттiк мекемелерді қайта атау және Қазақстан Республикасы Үкiметiнiң кейбiр шешiмдерiне өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/133677/rus
