act_code: '4406'
requisite: Постановление Правительства Республики Казахстан от 27 октября 1999 года N 1612
title:
  rus: О некоторых вопросах финансового регулирования государственного закупа зерна урожая 1999 года
  kaz: 1999 жылдың астығын мемлекеттік сатып алуды қаржылық реттеудің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1999-10-26
approved_by:
- '103000000000'
version_date:
  rus: 1999-10-26
source:
  rus: https://zan.gov.kz/client/#!/doc/4406/rus/26.10.1999
