act_code: '93574'
requisite: Постановление акимата Мангистауской области от 11 августа 2015 года № 240. Зарегистрировано Департаментом юстиции Мангистауской области от 10 сентября 2015 года № 2824. Утратило силу постановлением акимата Мангистауской области от 10 марта 2020 года № 40
title:
  rus: Об утверждении регламента государственной услуги "Выдача лицензии на оказание услуг по складской деятельности с выпусзком зерновых расписок"
  kaz: «Астық қолхаттарын шығара отырып, қойма қызметі бойынша қызметтер көрсетуге лицензия беру» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-08-11
approved_by:
- '163000000001'
version_date:
  kaz: 2017-05-29
  rus: 2017-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/93574/kaz/29.05.2017
  rus: https://zan.gov.kz/client/#!/doc/93574/rus/29.05.2017
caused_by:
  code: '113370'
  requisite: Постановление акимата Мангистауской области от 29 мая 2017 года № 133. Зарегистрировано Департаментом юстиции Мангистауской области 5 июля 2017 года № 3389. Утратило силу постановлением акимата Мангистауской области от 10 марта 2020 года № 40
  title:
    rus: О внесении изменений в постановление акимата Мангистауской области от 11 августа 2015 года № 240 «Об утверждении регламента государственной услуги «Выдача лицензии на оказание услуг по складской деятельности с выдачей зерновых расписок»
    kaz: Маңғыстау облысы әкімдігінің 2015 жылғы 11 тамыздағы № 240 «Астық қолхаттарын беру арқылы қойма қызметі бойынша қызметтер  көрсетуге лицензия беру» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы» қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/113370/rus
