act_code: '88492'
requisite: Постановление акимата Катон-Карагайского района Восточно-Казахстанской области от 19 марта 2015 года № 107. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 апреля 2015 года № 3855. Утратило силу постановлением акимата Катон-Карагайского района Восточно-Казахстанской области от 30 декабря 2020 года № 380 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении мест для размещения агитационных печатных материалов для кандидатов в Президенты Республики Казахстан по  Катон-Карагайскому району
  kaz: Қазақстан Республикасы Президенттігіне үміткерлерге Катонқарағай ауданы бойынша үгіттік баспа материалдарын орналастыру үшін орындар белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-03-19
approved_by:
- '157014000001'
version_date:
  kaz: 2015-03-19
  rus: 2015-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/88492/kaz/19.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88492/rus/19.03.2015
