act_code: '8021'
requisite: Постановление Правительства Республики Казахстан от 31 января 2001 года № 163
title:
  rus: О переименовании отдельных республиканских государственных казенных предприятий Министерства образования и науки Республики Казахстан
  kaz: Қазақстан Республикасы Білім және ғылым министрлігінің жекелеген республикалық мемлекеттік қазыналық кәсіпорындарын қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2001-01-31
approved_by:
- '103000000000'
version_date:
  kaz: 2001-01-31
  rus: 2001-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/8021/kaz/31.01.2001
  rus: https://zan.gov.kz/client/#!/doc/8021/rus/31.01.2001
