act_code: '58047'
requisite: Постановление акимата Есильского района Акмолинской области от 18 марта 2011 года № А-3/64. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 1 апреля 2011 года № 1-11-135
title:
  rus: Об организации и обеспечении проведения очередного призыва граждан на срочную воиннскую службу в апреле-июне и октябре-декабре 2011 года
  kaz: 2011 жылдың сәуір-маусымында және қазан-желтоқсанында азаматтарды мерзімді әскери қызметке шақыруды ұйымдастыру және қамтамасыз ету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-03-18
approved_by:
- '152012000001'
version_date:
  kaz: 2011-07-29
  rus: 2011-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/58047/kaz/29.07.2011
  rus: https://zan.gov.kz/client/#!/doc/58047/rus/29.07.2011
caused_by:
  code: '60366'
  requisite: Постановление акимата Есильского района Акмолинской области от 29 июля 2011 года № А-7/210. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 9 сентября 2011 года № 1-11-140
  title:
    rus: О внесении изменений в постановление акимата Есильского района от 18 марта 2011 года № А-3/64 "Об организации и обеспечении проведения очередного призыва граждан на срочную воинскую службу в апреле-июне и октября-декабря 2011 года"
    kaz: Есіл ауданы әкімдігінің 2011 жылдың 18 наурызындағы № А-3/64 "2011 жылдың сәуір-маусымында және қазан-желтоқсанында азаматтарды мерзімді әскери қызметке кезекті шақырылуын жүргізуді ұйымдастыру және қамтамасыз ету туралы" қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60366/rus
