act_code: '97792'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 2015 года № 1186
title:
  rus: Об утверждении Правил празднования Дня государственных символов Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік рәміздері күнін мерекелеу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2015-12-31
approved_by:
- '103000000000'
version_date:
  kaz: 2015-12-31
  rus: 2015-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/97792/kaz/31.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97792/rus/31.12.2015
