act_code: '78167'
requisite: Постановление акимата Мангистауской области от 13 марта 2014 года № 46. Зарегистрировано Департаментом юстиции Мангистауской области 20 марта 2014 года № 2370. Утратило силу постановлением акимата Мангистауской области от 15 марта 2019 года № 46
title:
  rus: Об утверждении положения государственного учреждения "Управление пассажирского транспорта и автомобильных дорог Мангистауской области"
  kaz: '"Маңғыстау облысының жолаушылар көлігі және автомобиль жолдары басқармасы" мемлекеттiк мeкeмeciнің ережесін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-03-13
approved_by:
- '163000000001'
version_date:
  kaz: 2014-03-13
  rus: 2014-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/78167/kaz/13.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78167/rus/13.03.2014
