act_code: '67699'
requisite: Постановление акимата Тимирязевского района Северо-Казахстанской области от 21 августа 2012 года № 223. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 сентября 2012 года № 1845. Утратило силу постановлением акимата Тимирязевского района Северо-Казахстанской области от 22 мая 2013 года № 128
title:
  rus: Об утверждении регламента электронной государственной услуги "Выдача справок безработным гражданам"
  kaz: '"Жұмыссыз азаматтарға анықтама беру" электрондық мемлекеттік қызмет регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2012-08-21
approved_by:
- '165012000001'
version_date:
  kaz: 2012-08-21
  rus: 2012-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/67699/kaz/21.08.2012
  rus: https://zan.gov.kz/client/#!/doc/67699/rus/21.08.2012
