act_code: '17131'
requisite: Постановление Правительства Республики Казахстан от 2 октября 2003 года N 1018. Утратило силу постановлением Правительства Республики Казахстан от 7 июля 2007 года N 580 (вводится в действие с 9 августа 2007 года)
title:
  rus: О некоторых вопросах лицензирования деятельности по заготовке древесины на участках государственного лесного фонда, осуществляемой лесопользователями, и внесении дополнений в некоторые решения Правительства Республики Казахстан
  kaz: Мемлекеттiк орман қоры учаскелерiнде орман пайдаланушылар жүзеге асыратын сүрек дайындау жөнiндегi қызметтi лицензиялаудың кейбiр мәселелерi және Қазақстан Республикасы Yкiметiнiң кейбiр шешiмдерiне толықтырулар енгiзу туралы
form: ПОСТ
type_codes:
- ПОСТ
- ТРЕБ
approved_on: 2003-10-01
approved_by:
- '103000000000'
version_date:
  rus: 2007-07-07
source:
  rus: https://zan.gov.kz/client/#!/doc/17131/rus/07.07.2007
caused_by:
  code: '33952'
  requisite: Постановление Правительства Республики Казахстан от 7 июля 2007 года № 580. Утратило силу постановлением Правительства Республики Казахстан от 21 ноября 2012 года № 1474
  title:
    rus: Об утверждении квалификационных требований к деятельности по заготовке древесины на участках государственного лесного фонда, осуществляемой лесопользователями
    kaz: Мемлекеттік орман қорының учаскелерінде орман пайдаланушылар жүзеге асыратын сүрек дайындау жөніндегі қызметке қойылатын біліктілік талаптарын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/33952/rus
