act_code: '9836'
requisite: "Постановление Правительства Республики Казахстан от 2 сентября 2001 года N 1131. \r\n     Утратило силу - постановлением Правительства РК от 25 июля 2002 года № 832 ~P020832 ."
title:
  rus: О ставке вознаграждения по кредитам, предоставляемым из республиканского бюджета, а также по суммам, отвлеченным из республиканского бюджета в целях выполнения обязательств по государственным гарантиям
  kaz: Мемлекеттік кепілдіктер бойынша міндеттемелерді орындау мақсатында республикалық бюджеттен берілген несиелер бойынша, сондай-ақ республикалық бюджеттен оқшауландырылған сомалар бойынша сыйақы ставкасы туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2001-09-01
approved_by:
- '103000000000'
version_date:
  kaz: 2001-09-01
  rus: 2001-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/9836/kaz/01.09.2001
  rus: https://zan.gov.kz/client/#!/doc/9836/rus/01.09.2001
