act_code: '2777'
requisite: Постановление Правительства Республики Казахстан от 18 октября 1996 года № 1286. Утратило силу постановлением Правительства Республики Казахстан от 2 апреля 2011 года № 347
title:
  rus: Об утверждении Положения о порядке захоронения вредных веществ и сброса сточных вод в недра
  kaz: Қазақстан Республикасында зиянды заттарды және пайдаланылған ағын суды жер қойнауына көмудiң тәртiбi туралы Ереженi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1996-10-17
approved_by:
- '103000000000'
version_date:
  rus: 1996-10-17
source:
  rus: https://zan.gov.kz/client/#!/doc/2777/rus/17.10.1996
