act_code: '50097'
requisite: Решение Уральского городского маслихата Западно-Казахстанской области от 24 декабря 2009 года № 24-5 и постановление акимата города Уральска Западно-Казахстанской области от 18 июня 2009 года № 1548. Зарегистрировано Управлением юстиции города Уральска Западно-Казахстанской области 19 января 2010 года № 7-1-163
title:
  rus: О переименовании улицы "Крылатская" города Уральска
  kaz: Орал қаласының "Крылатская" көшесінің атауын өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2009-12-24
approved_by:
- '159002000001'
- '159002000002'
version_date:
  kaz: 2009-12-24
  rus: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50097/kaz/24.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50097/rus/24.12.2009
