act_code: '170040'
requisite: Постановление Правительства Республики Казахстан от 25 июля 2022 года № 517
title:
  rus: Об определении условий и механизмов кредитования субъектов промышленно-инновационной деятельности через финансовые институты, а также финансового агента, осуществляющего кредитование субъектов промышленно-инновационной деятельности
  kaz: Өнеркәсіптік-инновациялық қызмет субъектілеріне қаржы институттары, сондай-ақ өнеркәсіптік-инновациялық қызмет субъектілеріне кредит беруді жүзеге асыратын қаржы агенті арқылы кредит беру шарттары мен тетіктерін айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
- УСЛ
approved_on: 2022-07-25
approved_by:
- '103000000000'
version_date:
  kaz: 2022-07-25
  rus: 2022-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/170040/kaz/25.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170040/rus/25.07.2022
