act_code: '7783'
requisite: Постановление Правления Национального Банка Республики Казахстан от 25 ноября 2000 года № 433. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2001 года № 1352. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 31 августа 2016 года № 208 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил осуществления безналичных платежей между клиентом и обслуживающим его банком
  kaz: Клиент пен оған қызмет көрсететiн банктiң арасында қолма-қол жасалмайтын төлемдердi жүзеге асыру ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2000-11-25
approved_by:
- '117000000000'
version_date:
  kaz: 2007-07-20
  rus: 2007-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/7783/kaz/20.07.2007
  rus: https://zan.gov.kz/client/#!/doc/7783/rus/20.07.2007
caused_by:
  code: '34805'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 20 июля 2007 года N 76. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 августа 2007 года N 4880
  title:
    rus: О внесении изменений в некоторые нормативные правовые акты Национального Банка Республики Казахстан по вопросам идентификационных номеров
    kaz: Қазақстан Республикасы Ұлттық Банкінің сәйкестендіру нөмірлерінің мәселелері жөніндегі кейбір нормативтік құқықтық актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/34805/rus
