act_code: '46416'
requisite: Маңғыстау облысы Маңғыстау ауданы әкімдігінің 2009 жылғы 15 мамырда № 125 қаулысы. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2009 жылғы 8 маусымда № 11-5-82 болып тіркелді
title:
  rus: Халықты жұмыспен қамтуға жәрдесетін қосымша шаралар туралы
  kaz: Халықты жұмыспен қамтуға жәрдесетін қосымша шаралар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-05-15
approved_by:
- '163004000001'
version_date:
  kaz: 2009-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/46416/kaz/15.05.2009
