act_code: '99750'
requisite: Постановление акимата Хромтауского района Актюбинской области от 10 февраля 2016 года № 31. Зарегистрировано Департаментом юстиции Актюбинской области 1 марта 2016 года № 4757. Утратило силу постановлением акимата Хромтауского района Актюбинской области от 22 декабря 2020 года № 414
title:
  rus: Об утверждении государственного образовательного заказа на дошкольное воспитание и обучение, размер родительской платы по Хромтаускому району
  kaz: Хромтау ауданы бойынша мектепке дейiнгi тәрбие мен оқытуға мемлекеттiк бiлiм беру тапсырысын, ата-ана төлемақысының мөлшерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-02-10
approved_by:
- '153013000001'
version_date:
  kaz: 2016-02-10
  rus: 2016-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/99750/kaz/10.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99750/rus/10.02.2016
