act_code: '10235'
requisite: Постановление Правления Национального Банка Республики Казахстан от 30 июня 2001 года N 272/1. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 октября 2001 г. за N 1654. Утратило силу - постановлением Правления Национального Банка РК от 13 сентября 2004 года N 119
title:
  rus: Об утверждении изменений в Инструкцию о порядке открытия и ведения банками второго уровня специальных счетов граждан Республики Казахстан, амнистированных в связи с легализацией ими денег, утвержденную постановлением Правления Национального Банка Республики Казахстан от 9 апреля 2001 года N 89
  kaz: Қазақстан Республикасының Ұлттық Банкi Басқармасының 2001 жылғы 9 сәуiрдегi N 89 қаулысымен бекiтiлген Ақшаны жария етуiне байланысты Қазақстан Республикасының рақымшылық жасалған азаматтарына екiншi деңгейдегi банктердiң арнайы есепшоттар ашу және жүргiзу тәртiбi туралы нұсқаулыққа өзгерiстердi бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2001-06-29
approved_by:
- '117000000000'
version_date:
  kaz: 2001-06-29
  rus: 2001-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/10235/kaz/29.06.2001
  rus: https://zan.gov.kz/client/#!/doc/10235/rus/29.06.2001
