act_code: '23108'
requisite: Постановление Правительства Республики Казахстан от 5 марта 2005 года N 214. Утратило силу постановлением Правительства Республики Казахстан от 15 апреля 2008 года N 339
title:
  rus: Об утверждении лимитов штатной численности государственных учреждений, подведомственных центральным исполнительным органам Республики Казахстан
  kaz: Қазақстан Республикасының орталық атқарушы органдарына ведомстволық бағынысты мемлекеттік мекемелер штат санының лимиттерiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2005-03-05
approved_by:
- '103000000000'
version_date:
  kaz: 2006-05-02
  rus: 2006-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/23108/kaz/02.05.2006
  rus: https://zan.gov.kz/client/#!/doc/23108/rus/02.05.2006
caused_by:
  code: '27469'
  requisite: Постановление Правительства Республики Казахстан от 2 мая 2006 года № 353. Утратило силу постановлением Правительства Республики Казахстан от 15 апреля 2008 года № 339
  title:
    rus: О внесении изменения в постановление Правительства Республики Казахстан от 5 марта 2005 года N 214
    kaz: Қазақстан Республикасы Yкiметiнiң 2005 жылғы 5 наурыздағы N 214 қаулысына өзгерiс енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/27469/rus
