act_code: '44257'
requisite: Постановление акимата Костанайской области от 20 января 2009 года № 45. Зарегистрировано Департаментом юстиции Костанайской области 19 февраля 2009 года № 3670. Утратило силу постановлением акимата Костанайской области от 19 февраля 2016 года № 71
title:
  rus: Об определении перечня должностей специалистов в области здравоохранения, социального обеспечения, образования и культуры, являющихся гражданскими служащими и работающих в сельской местности, для которых за счет средств областного бюджета устанавливаются повышенные не менее чем на двадцать пять процентов должностные оклады и тарифные ставки по сравнению с окладами и ставками гражданских служащих, занимающихся этими видами деятельности в городских условиях
  kaz: Облыстық бюджет қаражаты есебінен қызметтің осы түрлерiмен қалалық жағдайда айналысатын азаматтық қызметшiлердiң айлықақыларымен және ставкаларымен салыстырғанда кемiнде жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтiк ставкалар белгіленетін, азаматтық қызметші болып табылатын және ауылдық жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру және мәдениет саласындағы мамандар лауазымдарының тізбесін айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2009-01-20
approved_by:
- '162000000001'
version_date:
  kaz: 2011-07-20
  rus: 2011-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/44257/kaz/20.07.2011
  rus: https://zan.gov.kz/client/#!/doc/44257/rus/20.07.2011
caused_by:
  code: '60025'
  requisite: Постановление акимата Костанайской области от 20 июля 2011 года № 292. Зарегистрировано Департаментом юстиции Костанайской области 11 августа 2011 года № 3771. Утратило силу постановлением акимата Костанайской области от 19 февраля 2016 года № 71
  title:
    rus: О внесении изменения в постановление акимата от 20 января 2009 года № 45 "Об определении перечня должностей специалистов здравоохранения, социального обеспечения, образования, культуры и спорта, работающих в аульной (сельской) местности, для которых устанавливаются повышенные не менее чем на двадцать пять процентов должностные оклады и тарифные ставки, за счет средств областного бюджета"
    kaz: Әкімдіктің 2009 жылғы 20 қантардағы № 45 "Облыстық бюджет қаражаты есебінен ауылдық (селолық) жерде жұмыс істейтін және кемінде жиырма бес процент жоғары лауазымдық жалақылар мен тарифтік ставкаларды белгіленетін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандары лауазымдарының тізбесін белгілеу туралы" қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60025/rus
