act_code: '88186'
requisite: Постановление акимата города Караганды от 30 декабря 2014 года № 60/03. Зарегистрировано Департаментом юстиции Карагандинской области 22 января 2015 года № 2943
title:
  rus: Об утверждении перечня предприятий, организаций, учреждений города Караганды, организующих общественные работы на 2015 год
  kaz: 2015 жылға арналған қоғамдық жұмыстарды ұйымдастыратын Қарағанды қаласы кәсiпорындарының, ұйымдарының, мекемелерiнiң тiзбесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2014-12-30
approved_by:
- '160002000001'
version_date:
  kaz: 2014-12-30
  rus: 2014-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/88186/kaz/30.12.2014
  rus: https://zan.gov.kz/client/#!/doc/88186/rus/30.12.2014
