act_code: '102119'
requisite: Постановление акимата Жамбылской области от 31 марта 2016 года №91. Зарегистрировано Департаментом юстиции Жамбылской области 6 мая 2016 года № 3058. Утратило силу постановлением акимата Жамбылской области от 19 марта 2021 года № 73 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере жилищно-коммунального хозяйства
  kaz: Тұрғын үй-коммуналдық шаруашылық саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-03-31
approved_by:
- '158000000001'
version_date:
  kaz: 2017-09-11
  rus: 2017-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/102119/kaz/11.09.2017
  rus: https://zan.gov.kz/client/#!/doc/102119/rus/11.09.2017
caused_by:
  code: '114924'
  requisite: Постановление акимата Жамбылской области от 11 сентября 2017 года № 193. Зарегистрировано Департаментом юстиции Жамбылской области 27 сентября 2017 года № 3534. Утратило силу постановлением акимата Жамбылской области от 19 марта 2021 года № 73 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в постановление акимата Жамбылской области от 31 марта 2016 года № 91 «Об утверждении регламентов государственных услуг в сфере  жилищно-коммунального хозяйства»
    kaz: «Тұрғын үй-коммуналдық шаруашылық саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы» Жамбыл облысы әкімдігінің 2016 жылғы 31 наурыздағы № 91 қаулысына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114924/rus
