act_code: '45767'
requisite: Постановление акимата города Семей Восточно-Казахстанской области от 3 апреля 2009 года № 415. Зарегистрировано в Управлении юстиции города Семей Департамента юстиции Восточно-Казахстанской области 6 мая 2009 года за № 5-2-110. Утратило силу постановлением акимата города Семей Восточно-Казахстанской области от 30 декабря 2009 года № 1627
title:
  rus: Об организации очередного призыва на срочную воинскую службу граждан 1982-1991 годов рождения в апреле-июне и октябре-декабре 2009 года
  kaz: 1982-1991 жылдары туған азаматтарды 2009 жылғы сәуір-маусымда және қазан-желтоқсанда мерзімді әскери қызметке кезекті шақыруды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-04-03
approved_by:
- '157003000001'
version_date:
  kaz: 2009-04-03
  rus: 2009-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/45767/kaz/03.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45767/rus/03.04.2009
