act_code: '2379'
requisite: Постановление Кабинета Министpов Республики Казахстан от 6 мая 1993 года № 365. Утратило силу постановлением Правительства Республики Казахстан от 17 марта 2003 года № 258
title:
  rus: О таpифах на пеpевозки гpузов железнодоpожным тpанспоpтом
  kaz: Темiр жол көлiгiмен жүк тасымалдаудың тарифтерi туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1993-05-05
approved_by:
- '103000000000'
version_date:
  kaz: 1993-05-05
  rus: 1993-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/2379/kaz/05.05.1993
  rus: https://zan.gov.kz/client/#!/doc/2379/rus/05.05.1993
