act_code: '74305'
requisite: Постановление акимата города Курчатов Восточно-Казахстанской области от 14 августа 2013 года № 45. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 09 сентября 2013 года № 3058. Утратило силу - постановлением акимата города Курчатов Восточно-Казахстанской области от 10.02.2016 № 361
title:
  rus: Об установлении квоты рабочих мест для инвалидов, лиц, состоящих на учете  службы пробации уголовно-исполнительной инспекции, а также для лиц, освобожденных из мест лишения свободы
  kaz: Мүгедектер үшін, қылмыстық-атқару инспекциясының пробация қызметі есебінде тұрған, сондай-ақ бас бостандығынан айыру орындарынан босап шыққан тұлғаларға жұмыс орындарының квотасын белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-08-14
approved_by:
- '157004000001'
version_date:
  kaz: 2013-08-14
  rus: 2013-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/74305/kaz/14.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74305/rus/14.08.2013
