act_code: '127716'
requisite: Постановление акимата города Жанаозен Мангистауской области от 21 ноября 2018 года № 618. Зарегистрировано Департаментом юстиции Мангистауской области 29 декабря 2018 года № 3768. Утратило силу постановлением акимата города Жанаозен Мангистауской области от 27 августа 2019 года № 582
title:
  rus: Об утверждении государственного образовательного заказа на среднее образование города Жанаозен на 2018-2019 годы
  kaz: 2018-2019 жылдарға арналған Жаңаөзен қаласының орта білім беруге мемлекеттік білім беру тапсырысын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2018-11-21
approved_by:
- '163003000001'
version_date:
  kaz: 2018-11-21
  rus: 2018-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/127716/kaz/21.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127716/rus/21.11.2018
