act_code: '2980'
requisite: Постановление Правительства Республики Казахстан от 16 сентября 1996 г. N 1119. Утратило силу - постановлением Правительства РК от 12 августа 2000 г. N 1238 ~P001238.
title:
  rus: Об утверждении Положения о прохождении службы должностными лицами в таможенных органах Республики Казахстан и текста Присяги должностных лиц таможенных органов Республики Казахстан
  kaz: Лауазымды адамдардың Қазақстан Республикасының кеден органдарына қызмет өткеруi туралы ереженi және Қазақстан Республикасының кеден органдары лауазымды адамдарының антының мәтiнiн бекiту туралы<*>
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1996-09-15
approved_by:
- '103000000000'
version_date:
  rus: 1997-04-01
source:
  rus: https://zan.gov.kz/client/#!/doc/2980/rus/01.04.1997
caused_by:
  code: '1235'
  requisite: Постановление Правительства Республики Казахстан от 2 апреля 1997 г. N 459. Утратило силу - постановлением Правительства РК от 12 августа 2000 г. N 1238
  title:
    rus: О внесении изменений в постановление Правительства Республики Казахстан от 16 сентября 1996 г. N 1119
    kaz: Қазақстан Республикасы Үкiметiнiң 1996 жылғы 16 қыркүйектегi N 1119 қаулысына өзгерiстер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/1235/rus
