act_code: '216371'
requisite: Постановление акимата района Беимбета Майлина Костанайской области от 24 октября 2025 года № 219. Отменено постановлением акимата района Беимбета Майлина Костанайской области от 10 августа 2026 года № 160 (вводится в действие со дня подписания)
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Межрегионэнерготранзит»
  kaz: «Межрегионэнерготранзит» жауапкершілігі шектеулі серіктестігіне қауымдық сервитут белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-10-24
approved_by:
- '162016000001'
version_date:
  kaz: 2025-10-24
  rus: 2025-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/216371/kaz/24.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216371/rus/24.10.2025
