act_code: '129387'
requisite: Постановление акимата Сарыагашского района Туркестанской области от 15 января 2019 года № 17. Зарегистрировано Департаментом юстиции Туркестанской области 15 января 2019 года № 4892. Утратило силу постановлением акимата Сарыагашского района Туркестанской области от 24 ноября 2021 года № 396 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении квоты рабочих мест для инвалидов
  kaz: Мүгедектер үшiн жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-01-15
approved_by:
- '166009000001'
version_date:
  kaz: 2019-07-10
  rus: 2019-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/129387/kaz/10.07.2019
  rus: https://zan.gov.kz/client/#!/doc/129387/rus/10.07.2019
caused_by:
  code: '133241'
  requisite: Постановление акимата Сарыагашского района Туркестанской области от 10 июля 2019 года № 270. Зарегистрировано Департаментом юстиции Туркестанской области 11 июля 2019 года № 5132. Утратило силу постановлением акимата Сарыагашского района Туркестанской области от 24 ноября 2021 года № 396 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в постановление акимата Сарыагашского района от 15 января 2019 года № 17 «Об установлении квоты рабочих мест для инвалидов»
    kaz: «Мүгедектер үшiн жұмыс орындарына квота белгілеу туралы» Сарыағаш ауданы әкімдігінің 2019 жылғы 15 қаңтардағы № 17 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133241/rus
