act_code: '210908'
requisite: Постановление акимата города Астаны от 30 мая 2025 года № 509-1566
title:
  rus: Об утверждении норм потребления товарного газа для получателей адресной социальной помощи и жилищной помощи по городу Астане
  kaz: Астана қаласы бойынша атаулы әлеуметтік көмек және тұрғын үй көмегін алушылар үшін тауарлық газды тұтыну нормаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-05-30
approved_by:
- '151000000001'
version_date:
  kaz: 2025-05-30
  rus: 2025-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/210908/kaz/30.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210908/rus/30.05.2025
