act_code: '18323'
requisite: Постановление Правительства Республики Казахстан от 22 января 2004 года N 68
title:
  rus: 'О некоторых вопросах акционерных обществ "Инвестиционная компания: Инвестиционный Фонд Казахстана", "Банк Развития Казахстана", "Национальный инновационный фонд"'
  kaz: '"Инвестициялық компания: Қазақстанның Инвестициялық Қоры", "Қазақстанның Даму Банкi", "Ұлттық инновациялық қор" акционерлiк қоғамдарының кейбiр мәселелерi туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-01-22
approved_by:
- '103000000000'
version_date:
  kaz: 2004-10-27
  rus: 2004-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/18323/kaz/27.10.2004
  rus: https://zan.gov.kz/client/#!/doc/18323/rus/27.10.2004
caused_by:
  code: '21711'
  requisite: Постановление Правительства Республики Казахстан от 28 октября 2004 года N 1119. Утратило силу постановлением Правительства Республики Казахстан от 24 апреля 2008 года N 387
  title:
    rus: Некоторые вопросы Министерства финансов Республики Казахстан
    kaz: Қазақстан Республикасы Қаржы министрлiгiнiң кейбiр мәселелерi
  link: https://zan.gov.kz/client/#!/doc/21711/rus
