act_code: '43578'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 2008 года № 1355. Утратило силу постановлением Правительства Республики Казахстан от 19 марта 2012 года № 340
title:
  rus: Об утверждении перечня акционерных обществ и хозяйственных товариществ, сто процентов голосующих акций (долей участия) которых принадлежат государству, у которых государственные органы, осуществляющие права владения и пользования ими, приобретают товары, работы и услуги без применения норм Закона Республики Казахстан "О государственных закупках", регламентирующих выбор поставщика и заключение с ним договора о государственных закупках
  kaz: Дауыс беретін акцияларының (қатысу үлестерінің) жүз пайызы мемлекетке тиесілі, оларды иелену және пайдалану құқығын жүзеге асыратын мемлекеттік органдар "Мемлекеттік сатып алу туралы" Қазақстан Республикасы Заңының өнім берушіні таңдауды және олармен мемлекеттік сатып алу туралы шарт жасасуды регламенттейтін нормаларын қолданбай тауарларды, жұмыстарды және қызметтерді сатып алатын акционерлік қоғамдар мен шаруашылық серіктестіктердің тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2008-12-31
approved_by:
- '103000000000'
version_date:
  kaz: 2010-01-28
  rus: 2010-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/43578/kaz/28.01.2010
  rus: https://zan.gov.kz/client/#!/doc/43578/rus/28.01.2010
caused_by:
  code: '50353'
  requisite: Постановление Правительства Республики Казахстан от 28 января 2010 года № 33. Утратило силу постановлением Правительства Республики Казахстан от 19 марта 2012 года № 340
  title:
    rus: О внесении дополнения в постановление Правительства Республики Казахстан от 31 декабря 2008 года № 1355
    kaz: Қазақстан Республикасы Үкіметінің 2008 жылғы 31 желтоқсандағы № 1355 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50353/rus
