act_code: '15210'
requisite: Постановление Правления Национального Банка Республики Казахстан от 21 марта 2003 года № 96. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 апреля 2003 года № 2252. Утратил силу постановленим Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 29 декабря 2008 года № 241
title:
  rus: Об уставном капитале накопительных пенсионных фондов
  kaz: Жинақтаушы зейнетақы қорларының жарғылық капиталы туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2003-03-21
approved_by:
- '117000000000'
version_date:
  kaz: 2003-03-21
  rus: 2003-03-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/15210/kaz/21.03.2003
  rus: https://zan.gov.kz/client/#!/doc/15210/rus/21.03.2003
