act_code: '81610'
requisite: Постановление акимата Павлодарской области от 26 июня 2014 года № 214/6. Зарегистрировано Департаментом юстиции Павлодарской области 28 июля 2014 года № 3895. Утратило силу постановлением акимата Павлодарской области от 29 января 2018 года № 28/1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Положения о государственном учреждении "Управление архитектуры и градостроительства Павлодарской области"
  kaz: '"Павлодар облысының сәулет және қала құрылысы басқармасы" мемлекеттік мекемесі туралы ережені бекіту туралы'
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2014-06-26
approved_by:
- '164000000001'
version_date:
  kaz: 2016-02-25
  rus: 2016-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/81610/kaz/25.02.2016
  rus: https://zan.gov.kz/client/#!/doc/81610/rus/25.02.2016
caused_by:
  code: '100474'
  requisite: Постановление акимата Павлодарской области от 25 февраля 2016 года № 54/2. Зарегистрировано Департаментом юстиции Павлодарской области 24 марта 2016 года № 5008. Утратило силу постановлением акимата Павлодарской области от 29 января 2018 года № 28/1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в постановление акимата Павлодарской области от 26 июня 2014 года № 214/6 «Об утверждении Положения о государственном учреждении «Управление архитектуры и градостроительства Павлодарской области»
    kaz: Павлодар облысы әкімдігінің 2014 жылғы 26 маусымдағы «Павлодар облысының сәулет және қала құрылысы басқармасы» мемлекеттік мекемесі туралы ережені  бекіту туралы» № 214/6 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100474/rus
