act_code: '219064'
requisite: Постановление акимата города Жезказган области Ұлытау от 19 декабря 2025 года № 55/01
title:
  rus: Об утверждении тарифов на оказание специальных социальных услуг на 2025 год
  kaz: 2025 жылға арналған арнаулы әлеуметтік қызметтер көрсетуге тарифтерді бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-12-19
approved_by:
- '169002000001'
version_date:
  kaz: 2025-12-19
  rus: 2025-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219064/kaz/19.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219064/rus/19.12.2025
