act_code: '56644'
requisite: Постановление Правительства Республики Казахстан от 31 декабря 2010 года № 1518. Утратил силу постановлением Правительства Республики Казахстан от 28 декабря 2017 года № 902 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил определения перечня импортируемых на территорию Республики Казахстан с территории государств-членов Таможенного союза товаров, предназначенных для промышленной переработки, и перечня готовой продукции, полученной при указанной промышленной переработке, а также перечня налогоплательщиков Республики Казахстан, импортирующих такие товары
  kaz: Кеден одағына мүше мемлекеттердің аумағынан Қазақстан Республикасының аумағына импортталатын, өнеркәсіптік қайта өңдеуге арналған тауарлардың тізбесін және көрсетілген өнеркәсіптік қайта өңдеу кезінде алынған дайын өнімнің тізбесін, сондай-ақ осындай тауарларды импорттайтын Қазақстан Республикасы салық төлеушілерінің тізбесін айқындау қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2010-12-31
approved_by:
- '103000000000'
version_date:
  kaz: 2010-12-31
  rus: 2010-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/56644/kaz/31.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56644/rus/31.12.2010
