act_code: '577'
requisite: Постановление Правительства Республики Казахстан от 24 апреля 1998 года № 384. Утратило силу постановлением Правительства Республики Казахстан от 7 мая 1999 года № 553
title:
  rus: Вопросы Комитета здравоохранения Министерства образования, культуры и здравоохранения Республики Казахстан
  kaz: Қазақстан Республикасының Бiлiм, мәдениет және денсаулық сақтау министрлiгi Денсаулық сақтау комитетiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-04-23
approved_by:
- '103000000000'
version_date:
  rus: 1998-09-20
source:
  rus: https://zan.gov.kz/client/#!/doc/577/rus/20.09.1998
caused_by:
  code: '1225'
  requisite: Постановление Правительства Республики Казахстан от 21 сентября 1998 г. N 929 Утратило силу - постановлением Правительства РК от 7 мая 1999 г. N 553 ~P990553
  title:
    rus: О внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкiметiнiң кейбiр шешiмдерiне өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/1225/rus
