act_code: '214156'
requisite: Совместные постановление акимата Абайского района Карагандинской области от 11 сентября 2025 года № 45/01 и решение Абайского районного маслихата Карагандинской области от 11 сентября 2025 года № 38/354
title:
  rus: Об изменении и установлении границы (черты) села Агрогородок Мичуринского сельского округа Абайского района Карагандинской области
  kaz: Қарағанды облысы Абай ауданының Мичурин ауылдық округі Агрогородок ауылының шекарасын (шегін) өзгерту және белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2025-09-11
approved_by:
- '160011000001'
- '160011000002'
version_date:
  kaz: 2025-09-11
  rus: 2025-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/214156/kaz/11.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214156/rus/11.09.2025
