act_code: '102193'
requisite: Постановление Правительства Республики Казахстан от 12 мая 2016 года № 287. Утратило силу постановлением Правительства Республики Казахстан от 22 сентября 2023 года № 830
title:
  rus: Об утверждении Правил вывода из эксплуатации ядерных и радиационных установок
  kaz: Ядролық және радиациялық қондырғыларды пайдаланудан шығару қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2016-05-12
approved_by:
- '103000000000'
version_date:
  kaz: 2016-05-12
  rus: 2016-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/102193/kaz/12.05.2016
  rus: https://zan.gov.kz/client/#!/doc/102193/rus/12.05.2016
