act_code: '19395'
requisite: Постановление акимата Зерендинского района Акмолинской области от 10 марта 2004 года № 62. Зарегистрировано Департаментом юстиции Акмолинской области 31 марта 2004 года № 2386
title:
  rus: Зеренді ауданы әкімдігінің жанынан тұрғын үй комиссиясын құру туралы
  kaz: О создании жилищной комиссии при акимате Зерендинского района
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-03-10
approved_by:
- '152015000001'
version_date:
  kaz: 2004-03-10
  rus: 2004-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/19395/kaz/10.03.2004
  rus: https://zan.gov.kz/client/#!/doc/19395/rus/10.03.2004
