act_code: '60359'
requisite: Постановление акимата Мангистауской области от 23 августа 2011 года № 248. Зарегистрировано Департаментом юстиции Мангистауской области 6 сентября 2011 года № 2106. Утратило силу письмом Мангистауского областного акимата от 11 июля 2012 года № 01-30-1018
title:
  rus: О некоторых вопросах субсидирования сельсхозтоваропроизводителей из средств областного бюджета на повышение урожайности и качества продукции растениеводства
  kaz: Өсімдік шаруашылығы өнімінің шығымдылығы мен сапасын арттыруға облыстық бюджет қаражатынан ауыл шаруашылығы тауарын өндірушілерді субсидиялаудың кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-08-23
approved_by:
- '163000000001'
version_date:
  kaz: 2011-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/60359/kaz/23.08.2011
