act_code: '131402'
requisite: Постановление акимата Байдибекского района Туркестанской области от 6 мая 2019 года № 132. Зарегистрировано Департаментом юстиции Туркестанской области 8 мая 2019 года № 5034. Утратило силу постановлением акимата Байдибекского района Туркестанской области от 11 декабря 2020 года № 464 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об определении мест для размещения агитационных печатных материалов
  kaz: Үгіттік баспа материалдарын орналастыру үшін орындар белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-05-06
approved_by:
- '166003000001'
version_date:
  kaz: 2019-05-06
  rus: 2019-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/131402/kaz/06.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131402/rus/06.05.2019
