act_code: '21682'
requisite: Постановление Правительства Республики Казахстан от 28 октября 2004 года № 1117
title:
  rus: Вопросы Министерства здравоохранения Республики Казахстан
  kaz: Қазақстан Республикасы Денсаулық сақтау министрлiгiнiң мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2004-10-27
approved_by:
- '103000000000'
version_date:
  kaz: 2004-12-15
  rus: 2004-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/21682/kaz/15.12.2004
  rus: https://zan.gov.kz/client/#!/doc/21682/rus/15.12.2004
caused_by:
  code: '22240'
  requisite: Постановление Правительства Республики Казахстан от 15 декабря 2004 года N 1327
  title:
    rus: Вопросы Комитета по контролю в сфере оказания медицинских услуг Министерства здравоохранения Республики Казахстан
    kaz: Қазақстан Республикасы Денсаулық сақтау министрлігі медициналық қызмет көрсету саласындағы бақылау комитетiнiң мәселелерi
  link: https://zan.gov.kz/client/#!/doc/22240/rus
