act_code: '108757'
requisite: Постановление акимата Махамбетского района Атырауской области от 23 ноября 2016 года № 341. Зарегистрировано Департаментом юстиции Атырауской области 28 декабря 2016 года № 3731. Утратило силу постановлением Махамбетского районного акимата Атырауской области от 28 сентября 2017 года № 307
title:
  rus: Об утверждении государственного образовательного заказа на дошкольное воспитание и обучение, размера подушевого финансирования и родительской платы по Махамбетскому району
  kaz: Махамбет ауданы бойынша мектепке дейiнгi тәрбие мен оқытуға мемлекеттiк бiлiм беру тапсырысын, жан басына шаққандағы қаржыландыру және ата-ананың ақы төлеу мөлшерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-11-23
approved_by:
- '156004000001'
version_date:
  kaz: 2016-11-23
  rus: 2016-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108757/kaz/23.11.2016
  rus: https://zan.gov.kz/client/#!/doc/108757/rus/23.11.2016
