act_code: '193408'
requisite: Совместные постановление акимата области Жетісу от 14 февраля 2024 года № 44 и решение маслихата области Жетісу от 14 февраля 2024 года № 14-85. Зарегистрировано Департаментом юстиции области Жетісу 16 февраля 2024 года № 139-19
title:
  rus: Об изменении и установлении границ города Жаркент и сельских округов Панфиловского района
  kaz: Панфилов ауданының Жаркент қаласы мен ауылдық округтерінің шекараларын өзгерту және белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2024-02-14
approved_by:
- '170000000002'
version_date:
  kaz: 2024-02-14
  rus: 2024-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/193408/kaz/14.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193408/rus/14.02.2024
