act_code: '18456'
requisite: Батыс Қазақстан облысы Казталов ауданы әкімдігінің 2004 жылғы 16 қаңтардағы № 10 қаулысы. Батыс Қазақстан облысының Әділет департаментінде 2004 жылғы 30 қаңтарда № 2467 болып тіркелді
title:
  rus: Аудан әкімдігі жанынан Шағын және орта бизнес мәселелері жөніндегі комиссия құру туралы
  kaz: Аудан әкімдігі жанынан Шағын және орта бизнес мәселелері жөніндегі комиссия құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-01-16
approved_by:
- '159009000001'
version_date:
  kaz: 2004-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/18456/kaz/16.01.2004
