act_code: '15831'
requisite: Постановление Правительства Республики Казахстан от 11 июня 2003 года № 568. Утратило силу постановлением Правительства Республики Казахстан от 10 августа 2012 года № 1041
title:
  rus: Об утверждении Правил поставки, транспортировки и реализации природного газа, Правил поставки, перевозки и пользования сжиженными углеводородными газами
  kaz: Табиғи газды жеткiзу, тасымалдау және сату ережесiн, Сұйытылған көмiрсутектi газдарды жеткізу, тасымалдау және пайдалану ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2003-06-10
approved_by:
- '103000000000'
version_date:
  kaz: 2008-01-16
  rus: 2008-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/15831/kaz/16.01.2008
  rus: https://zan.gov.kz/client/#!/doc/15831/rus/16.01.2008
caused_by:
  code: '37232'
  requisite: Постановление Правительства Республики Казахстан от 16 января 2008 года № 22. Утратило силу постановлением Правительства Республики Казахстан от 10 августа 2012 года № 1041
  title:
    rus: О внесении дополнений и изменений в постановление Правительства Республики Казахстан от 11 июня 2003 года № 568
    kaz: Қазақстан Республикасы Үкіметінің 2003 жылғы 11 маусымдағы N 568 қаулысына толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/37232/rus
