act_code: '15202'
requisite: Постановление Правительства Республики Казахстан от 30 апреля 2003 года № 421. Утратило силу постановлением Правительства Республики Казахстан от 8 июня 2011 года № 645
title:
  rus: Об утверждении Правил проведения аккредитации негосударственных научных организаций
  kaz: Мемлекеттiк емес ғылыми ұйымдарды аккредитациялауды жүргiзу ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2003-04-29
approved_by:
- '103000000000'
version_date:
  kaz: 2003-04-29
  rus: 2003-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/15202/kaz/29.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15202/rus/29.04.2003
