act_code: '9983'
requisite: Постановление Правительства Республики Казахстан от 14 сентября 2001 года № 1212. Утратило силу постановлением Правительства Республики Казахстан от 23 декабря 2006 года № 1277
title:
  rus: Об утверждении Правил введения государственного регулирования цен на товары (работы, услуги) субъектов рынка, занимающих доминирующее (монопольное) положение на товарном рынке
  kaz: Тауар рыногында үстем (монополиялық) жағдайға ие рынок субъектiлерi тауарларының (жұмыстарының, қызметтер көрсетуінің) бағаларын мемлекеттік реттеудi енгізу ережесiн бекiту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2001-09-13
approved_by:
- '103000000000'
version_date:
  kaz: 2001-09-13
  rus: 2001-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/9983/kaz/13.09.2001
  rus: https://zan.gov.kz/client/#!/doc/9983/rus/13.09.2001
