act_code: '39537'
requisite: Постановление Глубоковского районного акимата Восточно-Казахстанской области от 14 апреля 2008 года № 855. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 24 апреля 2008 года за № 5-9-82. Утратило силу постановлением Глубоковского районного акимата Восточно-Казахстанской области от 9 декабря 2011 года № 1422
title:
  rus: Об определении перечня должностей специалистов образования, культуры, спорта, социального обеспечения, которым установлено повышение к должностным окладам за работу в аульной (сельской) местности
  kaz: Ауылдық (селолық) жердегі жұмысы үшін лауазымдық айлықақыларын көтеру белгіленген әлеуметтік қамтамасыз ету, білім, мәдениет және спорт мамандары лауазымдарының тізімін анықтау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-04-14
approved_by:
- '157010000001'
version_date:
  kaz: 2008-04-14
  rus: 2008-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/39537/kaz/14.04.2008
  rus: https://zan.gov.kz/client/#!/doc/39537/rus/14.04.2008
