act_code: '31590'
requisite: Постановление акимата города Рудного Костанайской области от 5 января 2007 года № 5. Зарегистрировано Управлением юстиции города Рудного Костанайской области 29 января 2007 года № 9-2-69. Срок действия постановления - до 1 января 2008 года
title:
  rus: О реализации решения Рудненского городского маслихата от 22 декабря 2006 года № 390 «О городском бюджете города Рудного на 2007 год»
  kaz: О реализации решения Рудненского городского маслихата от 22 декабря 2006 года № 390 «О городском бюджете города Рудного на 2007 год»
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-01-05
approved_by:
- '162021000001'
version_date:
  rus: 2007-01-05
source:
  rus: https://zan.gov.kz/client/#!/doc/31590/rus/05.01.2007
