act_code: '2056'
requisite: Постановление Правительства Республики Казахстан от 25 декабря 1998 года № 1334
title:
  rus: О реализации Закона Республики Казахстан "О республиканском бюджете на 1999 год"
  kaz: '"1999 жылға арналған республикалық бюджет туралы" Қазақстан Республикасының Заңын іске асыру туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1998-12-25
approved_by:
- '103000000000'
version_date:
  kaz: 2000-01-03
  rus: 2000-01-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/2056/kaz/03.01.2000
  rus: https://zan.gov.kz/client/#!/doc/2056/rus/03.01.2000
caused_by:
  code: '5146'
  requisite: Постановление Правительства Республики Казахстан от 3 января 2000 года № 8а
  title:
    rus: О погашении кредиторской задолженности по выплате государственных социальных пособий
    kaz: Мемлекеттік әлеуметтік жәрдемақыларды төлеу жөніндегі кредиторлық берешекті өтеу туралы
  link: https://zan.gov.kz/client/#!/doc/5146/rus
