act_code: '99118'
requisite: Постановление Правительства Республики Казахстан от 18 февраля 2016 года № 78
title:
  rus: Об утверждении Правил медицинского и санаторно-курортного обеспечения сотрудников и членов их семей, проживающих совместно с ними, пенсионеров правоохранительных органов, а также детей сотрудников, погибших при исполнении служебных обязанностей, до достижения ими совершеннолетия, в соответствующих государственных организациях здравоохранения
  kaz: Құқық қорғау органдарының қызметкерлерін және олармен бірге тұратын отбасы мүшелерін, зейнеткерлерін, сондай-ақ қызметтік міндеттерін атқару кезінде қаза тапқан қызметкерлердің балаларын олар кәмелеттік жасқа толғанға дейін тиісті мемлекеттік денсаулық сақтау ұйымдарында медициналық және санаторий-курорттық қамтамасыз ету қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2016-02-18
approved_by:
- '103000000000'
version_date:
  kaz: 2022-10-26
  rus: 2022-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/99118/kaz/26.10.2022
  rus: https://zan.gov.kz/client/#!/doc/99118/rus/26.10.2022
caused_by:
  code: '173188'
  requisite: Постановление Правительства Республики Казахстан от 26 октября 2022 года № 850
  title:
    rus: О внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкiметiнiң кейбір шешiмдерiне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173188/rus
