act_code: '212011'
requisite: Постановление Правительства Республики Казахстан от 3 июля 2025 года № 506
title:
  rus: Об утверждении Правил регистрации и учета государственных и гарантированных государством займов, займов под поручительство государства, государственных гарантий, государственных гарантий по поддержке экспорта, государственных гарантий по поддержке частного предпринимательства и поручительств государства
  kaz: Мемлекеттік және мемлекет кепілдік берген қарыздарды, мемлекет кепілгерлігімен берілетін қарыздарды, мемлекеттік кепілдіктерді, экспортты қолдау бойынша мемлекеттік кепілдіктерді, жеке кәсіпкерлікті қолдау бойынша мемлекеттік кепілдіктер мен мемлекет кепілгерліктерін тіркеу және есепке алу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2025-07-03
approved_by:
- '103000000000'
version_date:
  kaz: 2025-07-03
  rus: 2025-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/212011/kaz/03.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212011/rus/03.07.2025
