act_code: '49437'
requisite: Постановление акимата Айыртауского района Северо-Казахстанской области от 23 ноября 2009 года № 263. Зарегистрировано Управлением юстиции Айыртауского района Северо-Казахстанской области 20 декабря 2009 года № 13-3-111. Утратило силу - постановлением акимата Айыртауского района Северо-Казахстанской области от 6 января 2010 года № 1
title:
  rus: О предоставлении социальной помощи на зубопротезирование в 2009 году
  kaz: 2009 жылы тіс протездеуге әлеуметтік көмек көрсету туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-11-23
approved_by:
- '165003000001'
version_date:
  kaz: 2009-11-23
  rus: 2009-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49437/kaz/23.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49437/rus/23.11.2009
