act_code: '129970'
requisite: Постановление акимата Уалихановского района Северо-Казахстанской области от 27 марта 2019 года № 57. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 марта 2019 года № 5276. Утратило силу постановлением акимата Уалихановского района Северо-Казахстанской области от 18 марта 2021 года № 51  (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении квоты рабочих мест для трудоустройства лиц, состоящих на учете службы пробации
  kaz: Пробация қызметінің есебінде тұрған адамдарды жұмысқа орналастыру үшін жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2019-03-27
approved_by:
- '165013000001'
version_date:
  kaz: 2019-12-18
  rus: 2019-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/129970/kaz/18.12.2019
  rus: https://zan.gov.kz/client/#!/doc/129970/rus/18.12.2019
caused_by:
  code: '137150'
  requisite: Постановление акимата Уалихановского района Северо-Казахстанской области от 18 декабря 2019 года № 283. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 декабря 2019 года № 5738. Утратило силу постановлением акимата Уалихановского района Северо-Казахстанской области от 18 марта 2021 года № 51  (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в постановление акимата Уалихановского района Северо-Казахстанской области от 27 марта 2019 года № 57 «Об установлении квоты рабочих мест для трудоустройства лиц, состоящих на учете службы пробации»
    kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы әкімдігінің 2019 жылғы 27 наурыздағы № 57 «Пробация қызметінің есебінде тұрған адамдарды жұмысқа орналастыру үшін жұмыс орындарына квота белгілеу туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137150/rus
