act_code: '174959'
requisite: Постановление акимата Созакского района Туркестанской области от 28 ноября 2022 года № 344. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 декабря 2022 года № 30933
title:
  rus: Об утверждении Правил организации и проведения мероприятий по реконструкции, текущему или капитальному ремонту наружных стен, кровли многоквартирных жилых домов, направленных на придание единого архитектурного облика Созакскому району
  kaz: Созақ ауданына бірыңғай сәулеттік келбет беруге бағытталған, көппәтерлі тұрғын үйлердің сыртқы қабырғаларын, шатырларын реконструкциялау, ағымдағы немесе күрделі жөндеу жөніндегі іс-шараларды ұйымдастыру және жүргізу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-11-28
approved_by:
- '166010000001'
version_date:
  kaz: 2024-08-27
  rus: 2024-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/174959/kaz/27.08.2024
  rus: https://zan.gov.kz/client/#!/doc/174959/rus/27.08.2024
caused_by:
  code: '200127'
  requisite: Постановление акимата Созакского района Туркестанской области от 27 августа 2024 года № 211. Зарегистрировано в Департаменте юстиции Туркестанской области 28 августа 2024 года № 6582-13
  title:
    rus: О внесении изменения в постановление акимата Созакского района от 22 ноября 2022 года № 344 «Об утверждении Правил организации и проведения мероприятий по текущему или капитальному ремонту фасадов, кровли многоквартирных жилых домов, направленных на придание единого архитектурного облика Созакскому району»
    kaz: Созақ ауданы әкiмдiгiнiң 2022 жылғы 28 қарашадағы «Созақ ауданына бірыңғай сәулеттік келбет беруге бағытталған, көппәтерлі тұрғын үйлердің қасбеттерін, шатырларын ағымдағы немесе күрделі жөндеу жөніндегі іс-шараларды ұйымдастыру және жүргізу қағидаларын бекіту туралы» № 344 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200127/rus
