act_code: '1420'
requisite: Постановление Кабинета Министров Республики Казахстан от 7 января 1993 года N 16
title:
  rus: Об организации деятельности Торгового представительства Республики Казахстан в Республике Беларусь
  kaz: Қазақстан Республикасының Беларусь Республикасындағы Сауда өкiлдiгiнiң қызметiн ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1993-01-07
approved_by:
- '103000000000'
version_date:
  kaz: 1994-02-28
  rus: 1994-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/1420/kaz/28.02.1994
  rus: https://zan.gov.kz/client/#!/doc/1420/rus/28.02.1994
