act_code: '40705'
requisite: Решение Уральского городского маслихата Западно-Казахстанской области от 2 июля 2008 года № 9-12 и постановление акимата города Уральска Западно-Казахстанской области от 5 июня 2008 года № 1403. Зарегистрировано Управлением юстиции города Уральск Западно-Казахстанской области 15 июля 2008 года № 7-1-103
title:
  rus: О присвоении наименования 6-му микрорайону "Микрорайон имени Кунаева Д.А."
  kaz: 6-шағынауданына "Д.А.Қонаев атындағы шағынаудан" атауын тағайындау туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2008-07-02
approved_by:
- '159002000001'
- '159002000002'
version_date:
  kaz: 2008-07-02
  rus: 2008-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/40705/kaz/02.07.2008
  rus: https://zan.gov.kz/client/#!/doc/40705/rus/02.07.2008
