act_code: '160863'
requisite: Постановление акимата Житикаринского района Костанайской области от 25 ноября 2021 года № 262
title:
  rus: Об утверждении Положения о государственном учреждении «Отдел занятости и социальных программ акимата Житикаринского района»
  kaz: «Жітіқара ауданы әкімдігінің жұмыспен қамту және әлеуметтік бағдарламалар бөлімі» мемлекеттік мекемесі туралы ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2021-11-25
approved_by:
- '162008000001'
version_date:
  kaz: 2023-10-16
  rus: 2023-10-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/160863/kaz/16.10.2023
  rus: https://zan.gov.kz/client/#!/doc/160863/rus/16.10.2023
caused_by:
  code: '187387'
  requisite: Постановление акимата Житикаринского района Костанайской области от 16 октября 2023 года № 211
  title:
    rus: О внесении изменения в постановление акимата Житикаринского района от 25 ноября 2021 года № 262 «Об утверждении Положения о государственном учреждении «Отдел занятости и социальных программ акимата Житикаринского района»
    kaz: Жітіқара ауданы әкімдігінің 2021 жылғы 25 қарашадағы № 262 «Жітіқара ауданы әкімдігінің жұмыспен қамту және әлеуметтік бағдарламалар бөлімі» мемлекеттік мекемесі туралы ережені бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187387/rus
