act_code: '215635'
requisite: Постановление акимата Хромтауского района Актюбинской области от 8 октября 2025 года № 257
title:
  rus: Об утвержении тарифов на оказание специальных социальных услуг
  kaz: Арнаулы әлеуметтік қызметтер көрсетуге арналған тарифтерді бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-10-08
approved_by:
- '153013000001'
version_date:
  kaz: 2025-10-08
  rus: 2025-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/215635/kaz/08.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215635/rus/08.10.2025
