act_code: '57806'
requisite: Постановление акимата Бескарагайского района Восточно-Казахстанской области от 3 марта 2011 года № 73. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 28 марта 2011 года за № 5-7-93. Утратило силу постановлением акимата Бескарагайского района Восточно-Казахстанской области от 10 января 2012 года № 3
title:
  rus: Об организации общественных оплачиваемых работ в 2011 году
  kaz: 2011 жылы ақылы қоғамдық жұмыстарды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-03-03
approved_by:
- '157009000001'
version_date:
  kaz: 2011-03-03
  rus: 2011-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/57806/kaz/03.03.2011
  rus: https://zan.gov.kz/client/#!/doc/57806/rus/03.03.2011
