act_code: '64908'
requisite: Постановление Правления Национального Банка Республики Казахстан от 24 февраля 2012 года № 69. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 апреля 2012 года № 7572. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 26 июля 2019 года № 124 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил раскрытия инсайдерской информации на рынке ценных бумаг
  kaz: Бағалы қағаздар нарығында Инсайдерлік ақпаратты ашу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2012-02-24
approved_by:
- '117000000000'
version_date:
  kaz: 2012-02-24
  rus: 2012-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/64908/kaz/24.02.2012
  rus: https://zan.gov.kz/client/#!/doc/64908/rus/24.02.2012
