act_code: '33537'
requisite: Постановление акимата города Усть-Каменогорска Восточно-Казахстанской области от 24 мая 2007 года № 1050, решение Усть-Каменогорского городского маслихата от 24 мая 2007 года № 33/11. Зарегистрировано управлением юстиции города Усть-Каменогорска Департамента юстиции Восточно-Казахстанской области 1 июня 2007 года за № 5-1-62
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-05-24
approved_by:
- '157002000001'
- '157002000002'
version_date:
  kaz: 2007-05-24
  rus: 2007-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/33537/kaz/24.05.2007
  rus: https://zan.gov.kz/client/#!/doc/33537/rus/24.05.2007
