act_code: '291'
requisite: Постановление Кабинета Министров Республики Казахстан от 16 марта 1994 года N 275. Утратило силу - постановлением Правительства РК от 9 февраля 2005 г. N 124
title:
  rus: О мерах по совершенствованию гражданской обороны Республики Казахстан
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫНЫҢ АЗАМАТТЫҚ ҚОРҒАНЫСТЫ ЖЕТIЛДIРУ ШАРАЛАРЫ ТУРАЛЫ
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1994-03-16
approved_by:
- '103000000000'
version_date:
  rus: 1996-04-28
source:
  rus: https://zan.gov.kz/client/#!/doc/291/rus/28.04.1996
