act_code: '692'
requisite: Постановление Кабинета Министров Республики Казахстан от 22 июля 1994 г. N 826. Утратило силу - постановлением Правительства РК от 27 июля 2005 г. N 781
title:
  rus: О Порядке получения централизованных (директивных) кредитов Национального банка Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық банкiнiң орталықтандырылған (директивтiк) кредиттерiн алу тәртiбi туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1994-07-21
approved_by:
- '103000000000'
version_date:
  kaz: 1994-08-10
  rus: 1994-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/692/kaz/10.08.1994
  rus: https://zan.gov.kz/client/#!/doc/692/rus/10.08.1994
