act_code: '75425'
requisite: Постановление акимата Жанакорганского района Кызылординской области от 31 октября 2013 года N 476. Зарегистрировано Департаментом юстиции Кызылординской области 20 ноября 2013 года N 4541
title:
  rus: Об утверждении государственного образовательного заказа на дошкольное воспитание и обучение, размеров подушевого финансирования и родительской платы на 2013 год
  kaz: 2013 жылға мектепке дейінгі тәрбие мен оқытуға мемлекеттік білім беру тапсырысын, жан басына шаққандағы қаржыландыру және ата-ананың ақы төлеу мөлшерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2013-10-31
approved_by:
- '161009000001'
version_date:
  kaz: 2013-10-31
  rus: 2013-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/75425/kaz/31.10.2013
  rus: https://zan.gov.kz/client/#!/doc/75425/rus/31.10.2013
