act_code: '103701'
requisite: Постановление Правительства Республики Казахстан от 29 декабря 1995 года № 1894. Утратило силу постановлением Правительства Республики Казахстан от 7 июня 2012 года № 753
title:
  rus: О реализации Закона Республики Казахстан "О лицензировании"
  kaz: '"Лицензиялау туралы" Қазақстан Республикасының Заңын iске асыру туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1995-12-29
approved_by:
- '103000000000'
version_date:
  kaz: 2007-05-29
  rus: 2007-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/103701/kaz/29.05.2007
  rus: https://zan.gov.kz/client/#!/doc/103701/rus/29.05.2007
caused_by:
  code: '33453'
  requisite: Постановление Правительства Республики Казахстан от 29 мая 2007 года № 438
  title:
    rus: Вопросы Национального космического агентства Республики Казахстан
    kaz: Қазақстан Республикасы Ұлттық ғарыш агенттігінің мәселелері
  link: https://zan.gov.kz/client/#!/doc/33453/rus
