act_code: '61189'
requisite: Постановление Правительства Республики Казахстан от 28 октября 2011 года № 1219. Утратило силу постановлением Правительства Республики Казахстан от 29 октября 2015 года № 862
title:
  rus: Об утверждении Типового положения о службе безопасности и охраны труда в организации
  kaz: Ұйымдағы еңбек қауіпсіздігі және еңбекті қорғау қызметі жөніндегі үлгілік ережені бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2011-10-28
approved_by:
- '103000000000'
version_date:
  kaz: 2012-06-01
  rus: 2012-06-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/61189/kaz/01.06.2012
  rus: https://zan.gov.kz/client/#!/doc/61189/rus/01.06.2012
caused_by:
  code: '65924'
  requisite: Постановление Правительства Республики Казахстан от 1 июня 2012 года № 731
  title:
    rus: О внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкiметiнiң кейбiр шешiмдерiне өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/65924/rus
