act_code: '37614'
requisite: Постановление Правительства Республики Казахстан от 8 февраля 2008 года № 124. Утратило силу постановлением Правительства Республики Казахстан от 21 августа 2015 года № 657
title:
  rus: Об утверждении Правил учета потребления озоноразрушающих веществ
  kaz: Озон қабатын бұзатын заттарды тұтынуды есепке алу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2008-02-08
approved_by:
- '103000000000'
version_date:
  kaz: 2012-05-31
  rus: 2012-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/37614/kaz/31.05.2012
  rus: https://zan.gov.kz/client/#!/doc/37614/rus/31.05.2012
caused_by:
  code: '65871'
  requisite: Постановление Правительства Республики Казахстан от 31 мая 2012 года № 714. Утратило силу постановлением Правительства Республики Казахстан от 21 августа 2015 года № 657
  title:
    rus: О внесении изменений в постановление Правительства Республики Казахстан от 8 февраля 2008 года № 124 "Об утверждении Правил государственного учета источников выбросов парниковых газов в атмосферу и потребления озоноразрушающих веществ"
    kaz: '"Парниктік газдарды атмосфераға шығаруды және озон қабатын бұзатын заттарды тұтыну көздерін мемлекеттік есепке алу ережесін бекіту туралы" Қазақстан Республикасы Үкіметінің 2008 жылғы 8 ақпандағы № 124 қаулысына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/65871/rus
