act_code: '17690'
requisite: Постановление Правительства Республики Казахстан от 5 декабря 2003 года № 1237. Утратило силу постановлением Правительства Республики Казахстан от 19 ноября 2014 года № 1210
title:
  rus: Об утверждении перечня и создании республиканских служб гражданской обороны и чрезвычайных ситуаций
  kaz: Азаматтық қорғаныс пен төтенше жағдайлар республикалық қызметтерiнiң тiзбесiн бекiту және оларды құру туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРЧ
approved_on: 2003-12-05
approved_by:
- '103000000000'
version_date:
  kaz: 2005-11-03
  rus: 2005-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/17690/kaz/03.11.2005
  rus: https://zan.gov.kz/client/#!/doc/17690/rus/03.11.2005
caused_by:
  code: P050001097_
