act_code: '87384'
requisite: Постановление акимата Индерского района Атырауской области от 27 февраля 2015 года № 55. Зарегистрировано Департаментом юстиции Атырауской области 5 марта 2015 года № 3120. Утратило силу постановлением акимата Индерского района Атырауской области от 24 февраля 2023 года № 34 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении мест для размещения агитационных печатных материалов по Индерскому району для всех кандидатов в Президенты, депутаты Сената и Мажилиса Парламента, маслихатов и членов иных органов местного самоуправления Республики Казахстан
  kaz: Қазақстан Республикасы Президентiне, Парламентiнiң Сенаты мен Мәжiлiсi, мәслихаттары депутаттарына және өзге де жергілікті өзін-өзі басқару органдары мүшелеріне барлық кандидаттар үшін Индер ауданы бойынша үгіттік баспа материалдарын орналастыру үшін орындар белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-02-27
approved_by:
- '156008000001'
version_date:
  kaz: 2015-02-27
  rus: 2015-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/87384/kaz/27.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87384/rus/27.02.2015
