act_code: '51682'
requisite: Оңтүстік Қазақстан облысы Ордабасы ауданы әкімдігінің 2010 жылғы 15 наурыздағы N 96 Қаулысы. Оңтүстік Қазақстан облысы Ордабасы ауданының Әділет басқармасында 2010 жылғы 6 сәуірде N 14-8-80 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Ордабасы ауданы әкімдігінің 2011 жылғы 19 қазандағы N 365 Қаулысымен
title:
  rus: Аудандық коммуналдық меншік туралы
  kaz: Аудандық коммуналдық меншік туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-03-15
approved_by:
- '166006000001'
version_date:
  kaz: 2010-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/51682/kaz/15.03.2010
