act_code: '27728'
requisite: Постановление Акимата города Кокшетау от 9 марта 2006 года № А-3/324. Зарегистрировано Управлением юстиции города Кокшетау 13 марта 2006 года № 1-1-40. Утратило силу - постановлением акимата города Кокшетау от 12 мая 2010 года № А-5/756
title:
  rus: О местах размещения агитационных печатных материалов кандидатов в депутаты маслихатов, вместо выбывших
  kaz: Мәслихаттан шыққан депутаттардың орнына кандидаттардың үгітпе баспа материалдарын орналастыру орындары туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-03-09
approved_by:
- '152002000001'
version_date:
  kaz: 2006-03-09
  rus: 2006-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/27728/kaz/09.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27728/rus/09.03.2006
