act_code: '103544'
requisite: Постановление акимата города Темиртау Карагандинской области от 2 июня 2016 года № 22/3
title:
  rus: О нормативных правовых актах акимата города Темиртау
  kaz: Теміртау қаласы әкімдігінің нормативтік құқықтық актілері туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-06-02
approved_by:
- '160005000001'
version_date:
  kaz: 2016-06-02
  rus: 2016-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/103544/kaz/02.06.2016
  rus: https://zan.gov.kz/client/#!/doc/103544/rus/02.06.2016
