act_code: '41937'
requisite: Қызылорда облысы Сырдария ауданы әкімдігінің 2008 жылғы 19 қыркүйектегі N 482 қаулысы. Қызылорда облысының Әділет департаменті Сырдария аудандық Әділет басқармасында 2008 жылғы 21 қазанда 10-8-73 тіркелді. Күші жойылды - Қызылорда облысы Сырдария ауданы әкімдігінің 2011 жылғы 22 желтоқсандағы N 532 қаулысымен
title:
  rus: Жекелеген санаттағы азаматтарға әлеуметтік төлемдердің кейбір түрлерін төлеудің нұсқаулықтарын бекіту туралы
  kaz: Жекелеген санаттағы азаматтарға әлеуметтік төлемдердің кейбір түрлерін төлеудің нұсқаулықтарын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-09-19
approved_by:
- '161007000001'
version_date:
  kaz: 2008-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/41937/kaz/19.09.2008
