act_code: '91950'
requisite: Постановление от 27.05.2015 № 94, Национальный банк Республики Казахстан. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 июля 2015 года № 11660
title:
  rus: Об утверждении Требований к внешним независимым экспертам по принципам исламского финансирования, а также определении случаев привлечения лизингодателями внешних независимых экспертов по принципам исламского финансирования для получения заключения о соответствии сделок исламского лизинга принципам исламского финансирования
  kaz: Исламдық қаржыландыру қағидаттары бойынша сыртқы тәуелсіз сарапшыларға қойылатын талаптарды, сондай-ақ лизинг берушілердің исламдық лизинг мәмілелерінің исламдық қаржыландыру қағидаттарына сәйкестігі туралы қорытынды алу үшін исламдық қаржыландыру қағидаттары бойынша сыртқы тәуелсіз сарапшыларды тарту жағдайларын айқындау туралы
form: ПОСТ
type_codes:
- ПОСТ
- ТРЕБ
approved_on: 2015-05-27
approved_by:
- '117000000000'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/91950/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91950/rus/27.05.2015
