act_code: '39818'
requisite: Постановление Правительства Республики Казахстан от 30 мая 2008 года № 523. Утратило силу постановлением Правительства Республики Казахстан от 6 декабря 2012 года № 1553
title:
  rus: О некоторых вопросах возмещения затрат на аудит эмитентов финансовых инструментов, допущенных на специальную торговую площадку регионального финансового центра города Алматы
  kaz: Алматы қаласының өңірлік қаржы орталығының арнайы сауда алаңына жіберілген қаржы құралдары эмитенттерінің аудитіне жұмсалған шығындарды өтеудің кейбір мәселелері туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2008-05-30
approved_by:
- '103000000000'
version_date:
  kaz: 2008-05-30
  rus: 2008-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/39818/kaz/30.05.2008
  rus: https://zan.gov.kz/client/#!/doc/39818/rus/30.05.2008
