act_code: '217898'
requisite: Постановление акимата Абайского района Карагандинской области от 2 декабря 2025 года № 62/01
title:
  rus: О создании коммунального государственного учреждения «Центр поддержки семьи Абайского района» отдела занятости и социальных программ Абайского района Карагандинской области
  kaz: Қарағанды облысы Абай ауданының жұмыспен қамту және әлеуметтік бағдарламалар бөлімінің «Абай ауданының отбасын қолдау орталығы» коммуналдық мемлекеттік мекемесін құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2025-12-02
approved_by:
- '160011000001'
version_date:
  kaz: 2025-12-02
  rus: 2025-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/217898/kaz/02.12.2025
  rus: https://zan.gov.kz/client/#!/doc/217898/rus/02.12.2025
