act_code: '77487'
requisite: Постановление Правительства Республики Казахстан от 19 февраля 2014 года № 111. Утратило силу постановлением Правительства Республики Казахстан от 12 октября 2015 года № 821
title:
  rus: Об утверждении стандартов государственных услуг "Выдача удостоверений лицам без гражданства и видов на жительство иностранцам, постоянно проживающим в Республике Казахстан", "Регистрация и выдача разрешений иностранцам и лицам без гражданства на постоянное жительство в Республике Казахстан", "Регистрация приема и выхода из гражданства Республики Казахстан" и "Присвоение и продление статуса беженца в Республике Казахстан"
  kaz: '"Қазақстан Республикасында тұрақты тұратын азаматтығы жоқ адамдарға куәлiктер және шетелдiктерге тұруға ықтиярхаттар беру", "Шетелдiктер мен азаматтығы жоқ адамдарды тiркеу және оларға Қазақстан Республикасында тұрақты тұруға рұқсат беру", "Қазақстан Республикасының азаматтығын қабылдауды және одан шығуды тiркеу" және "Қазақстан Республикасында босқын мәртебесін беру және ұзарту" мемлекеттік көрсетілетін қызметтер стандарттарын бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
- СТНД
approved_on: 2014-02-19
approved_by:
- '103000000000'
version_date:
  kaz: 2014-02-19
  rus: 2014-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/77487/kaz/19.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77487/rus/19.02.2014
