act_code: '60057'
requisite: Постановление Правительства Республики Казахстан от 9 августа 2011 года № 920
title:
  rus: Об утверждении Правил продажи объектов приватизации
  kaz: Жекешелендіру объектілерін сату қағидасын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2011-08-09
approved_by:
- '103000000000'
version_date:
  kaz: 2011-08-09
  rus: 2011-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/60057/kaz/09.08.2011
  rus: https://zan.gov.kz/client/#!/doc/60057/rus/09.08.2011
