act_code: '171134'
requisite: Постановление акимата города Шымкент от 24 марта 2022 года № 427
title:
  rus: Об утверждении Положении коммунального государственного учреждения «Управление развития комфортной городской среды города Шымкент»
  kaz: «Шымкент қаласының қалалық жайлы ортаны дамыту басқармасы» коммуналдық мемлекеттік мекемесінің ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
approved_on: 2022-03-24
approved_by:
- '167000000001'
version_date:
  kaz: 2026-04-02
  rus: 2026-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/171134/kaz/02.04.2026
  rus: https://zan.gov.kz/client/#!/doc/171134/rus/02.04.2026
caused_by:
  code: '223876'
  requisite: Постановление акимата города Шымкент от 2 апреля 2026 года № 1244
  title:
    rus: О переименовании некоторых учреждений акимата города Шымкент
    kaz: Шымкент қаласы әкімдігінің кейбір мекемелерін қайта атау туралы
  link: https://zan.gov.kz/client/#!/doc/223876/rus
