act_code: '181146'
requisite: Постановление акимата Туркестанской области от 11 мая 2023 года № 85. Зарегистрировано Департаментом юстиции Туркестанской области 12 мая 2023 года № 6267-13
title:
  rus: Об исключении из учетных данных населенного пункта Сырдария сельского округа Кожатогай города Арыс
  kaz: Арыс қаласы Қожатоғай ауылдық округінің Сырдария елді мекенін есепті деректерден шығару туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2023-05-11
approved_by:
- '166000000001'
version_date:
  kaz: 2023-05-11
  rus: 2023-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/181146/kaz/11.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181146/rus/11.05.2023
