act_code: '35411'
requisite: Постановление акимата города Семей Восточно-Казахстанской области от 2 октября 2007 года № 1251. Зарегистрировано в Управлении юстиции города Семей Департамента юстиции Восточно-Казахстанской области 22 октября 2007 года № 5-2-68. Утратило силу постановлением акимата города Семей Восточно-Казахстанской области от 22 ноября 2007 года № 1495
title:
  rus: О наложении карантина по заболеванию 1330 на село Акбулак Акбулакского сельского округа
  kaz: О наложении карантина по заболеванию 1330 на село Акбулак Акбулакского сельского округа
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2007-10-02
approved_by:
- '157003000001'
version_date:
  rus: 2007-10-02
source:
  rus: https://zan.gov.kz/client/#!/doc/35411/rus/02.10.2007
