act_code: '50743'
requisite: Постановление от 04.02.2010 №256, Акимат Жалагашского района
title:
  rus: Жалағаш кентіндегі жекелеген көшелерін қайта атау туралы
  kaz: Жалағаш кентіндегі жекелеген көшелерін қайта атау туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-02-04
approved_by:
- '161006000001'
version_date:
  kaz: 2010-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/50743/kaz/04.02.2010
