act_code: '67453'
requisite: Постановление акимата Аккайынского района Северо-Казахстанской области от 10 августа 2012 года № 205. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 августа 2012 года № 13-2-162. Утратило силу постановлением акимата Аккайынского района Северо-Казахстанской области от 24 мая 2013 года № 141
title:
  rus: Об утверждении регламентов государственных услуг аппаратов акимов сельских (аульных) округов Аккайынского района
  kaz: Аққайың ауданының селолық (ауылдық) округі әкімдер аппараттарының мемлекеттік қызмет регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2012-08-10
approved_by:
- '165005000001'
version_date:
  rus: 2012-11-19
source:
  rus: https://zan.gov.kz/client/#!/doc/67453/rus/19.11.2012
caused_by:
  code: '69026'
  requisite: Постановление акимата Аккайынского района Северо-Казахстанской области от 19 ноября 2012 года № 296. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 7 декабря 2012 года № 1981. Утратило силу - постановлением акимата Аккайынского района Северо-Казахстанской области от 24 мая 2013 года № 141
  title:
    rus: О внесении изменений в постановление акимата Аккайынского района Северо-Казахстанской области от 10 августа 2012 года № 205 "Об утверждении регламентов государственных услуг аппаратов акимов сельских (аульных) округов Аккайынского района"
    kaz: '"Аққайың ауданының селолық (ауылдық) округі әкімдер аппараттарының мемлекеттік қызмет регламенттерін бекіту туралы" Солтүстік Қазақстан облысы Аққайың аудандық әкімдігінің 2012 жылғы 10 тамыздағы № 205 қаулысына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/69026/rus
