act_code: '2918'
requisite: Постановление Правления Национального Банка Республики Казахстан от 28 марта 1999 года № 37. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 мая 1999 года № 754. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 3 февраля 2014 года № 14
title:
  rus: Об утверждении Правил установления корреспондентских отношений между Национальным Банком Республики Казахстан и банками, а также организациями, осуществляющими отдельные виды банковских операций
  kaz: Қазақстан Республикасының Ұлттық Банкі мен банктер, сондай-ақ банк операцияларының жекелеген түрлерін жүзеге асыратын ұйымдар арасында корреспонденттік қатынастар орнату ережелерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 1999-03-28
approved_by:
- '117000000000'
version_date:
  kaz: 2002-05-12
  rus: 2002-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/2918/kaz/12.05.2002
  rus: https://zan.gov.kz/client/#!/doc/2918/rus/12.05.2002
caused_by:
  code: '12523'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 13 мая 2002 года № 172. Зарегистрировано Министерством юстиции Республики Казахстан 20 июня 2002 года № 1888. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 3 февраля 2014 года № 14
  title:
    rus: О внесении изменений и дополнений в постановление Правления Национального Банка Республики Казахстан от 28 марта 1999 года № 37 "Об утверждении Правил установления корреспондентских отношений между Национальным Банком Республики Казахстан и банками второго уровня, а также организациями, осуществляющими отдельные виды банковских операций"
    kaz: Қазақстан Республикасының Ұлттық Банкі Басқармасының "Қазақстан Республикасы Ұлттық Банкі мен екінші деңгейдегі банктердің, сондай-ақ банк операцияларының жекелеген түрлерін жүзеге асыратын ұйымдардың арасында корреспонденттік қатынастар орнату жөніндегі ережелерді бекіту туралы" 1999 жылғы 28 наурыздағы N 37 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/12523/rus
