act_code: '164355'
requisite: Постановление Правительства Республики Казахстан от 7 февраля 2022 года № 54
title:
  rus: О переводе земель запаса в земли особо охраняемых природных территорий
  kaz: Босалқы жерлерді ерекше қорғалатын табиғи аумақтардың жерлеріне ауыстыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-02-07
approved_by:
- '103000000000'
version_date:
  kaz: 2022-02-07
  rus: 2022-02-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/164355/kaz/07.02.2022
  rus: https://zan.gov.kz/client/#!/doc/164355/rus/07.02.2022
