act_code: '146456'
requisite: Постановление акимата Северо-Казахстанской области от 19 сентября 2020 года № 246. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 сентября 2020 года № 6539. Утратило силу постановлением акимата Северо-Казахстанской области от 20 декабря 2020 года № 338 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-09-19
approved_by:
- '165000000001'
version_date:
  kaz: 2020-11-10
  rus: 2020-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/146456/kaz/10.11.2020
  rus: https://zan.gov.kz/client/#!/doc/146456/rus/10.11.2020
caused_by:
  code: '148393'
  requisite: Постановление акимата Северо-Казахстанской области от 10 ноября 2020 года № 308. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 ноября 2020 года № 6646. Утратило силу постановлением акимата Северо-Казахстанской области от 20 декабря 2020 года № 338 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении дополнения в постановление акимата Северо-Казахстанской области от 19 сентября 2020 года № 246 «Об установлении карантина»
    kaz: «Карантин белгілеу туралы» Солтүстік Қазақстан облысы әкімдігінің 2020 жылғы 19 қыркүйектегі № 246 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148393/rus
