act_code: '7887'
requisite: Постановление Правительства Республики Казахстан от 13 января 2001 года № 43
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Беларусь о сотрудничестве в области печати и информации
  kaz: Қазақстан Республикасының Үкіметі мен Беларусь Республикасының Үкіметі арасындағы Баспасөз және ақпарат саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2001-01-13
approved_by:
- '103000000000'
version_date:
  kaz: 2001-01-13
  rus: 2001-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/7887/kaz/13.01.2001
  rus: https://zan.gov.kz/client/#!/doc/7887/rus/13.01.2001
