act_code: '11936'
requisite: Постановление Атырауского областного акимата от 27 марта 2002 года № 139. Зарегистрировано Управлением юстиции Атырауской области 18 апреля 2002 года за № 918
title:
  rus: О ходе выполнения Постановления Правительства Республики Казахстан от 15 мая 2000 года № 721 «О мерах по дальнейшему развитию начального и среднего профессионального образования Республики Казахстан»
  kaz: О ходе выполнения Постановления Правительства Республики Казахстан от 15 мая 2000 года № 721 «О мерах по дальнейшему развитию начального и среднего профессионального образования Республики Казахстан»
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2002-03-27
approved_by:
- '156000000001'
version_date:
  rus: 2002-03-27
source:
  rus: https://zan.gov.kz/client/#!/doc/11936/rus/27.03.2002
