act_code: '57333'
requisite: Постановление акимата Карасуского района Костанайской области от 18 февраля 2011 года № 60. Зарегистрировано Управлением юстиции Карасуского района Костанайской области 18 февраля 2011 года № 9-13-122. Утратило силу постановлением акимата Карасуского района Костанайской области от 26 июня 2015 года № 161
title:
  rus: Об определении мест для размещения агитационных печатных материалов
  kaz: Үгіттік баспа материалдарын орналастыру үшін орындарды белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2011-02-18
approved_by:
- '162011000001'
version_date:
  kaz: 2011-02-18
  rus: 2011-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/57333/kaz/18.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57333/rus/18.02.2011
