act_code: '24377'
requisite: Постановление Акимата Акмолинской области от 01 июня 2005 года № А-6/182. Зарегистрировано Департаментом юстиции Акмолинской области 7 июня 2005 года № 3140. Утратило силу - постановлением акимата Акмолинмкой области от 12 января 2006 года № А-1/16
title:
  rus: О плане мероприятий по реализации приоритетных направлений работы малой ассамблеи народов Казахстана Акмолинской области на 2005 год
  kaz: О плане мероприятий по реализации приоритетных направлений работы малой ассамблеи народов Казахстана Акмолинской области на 2005 год
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2005-06-01
approved_by:
- '152000000001'
version_date:
  rus: 2005-06-01
source:
  rus: https://zan.gov.kz/client/#!/doc/24377/rus/01.06.2005
