act_code: '200596'
requisite: Постановление акимата города Уральска Западно-Казахстанской области от 11 сентября 2024 года № 2125. Зарегистрирован в Департаменте юстиции Западно-Казахстанской области 12 сентября 2024 года № 7429-07
title:
  rus: Об утверждении перечня социально-значимых убыточных маршрутов, подлежащих субсидированию на внутреннем водном транспорте по городу Уральск на 2024 год
  kaz: Орал қаласы бойынша 2024 жылға субсидиялауға жататын ішкі су көлігіндегі әлеуметтік маңызы бар шығынды маршруттар тізбесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2024-09-11
approved_by:
- '159002000001'
version_date:
  kaz: 2024-09-11
  rus: 2024-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/200596/kaz/11.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200596/rus/11.09.2024
