act_code: '44396'
requisite: Батыс Қазақстан облысы Зеленов ауданы әкімдігінің 2009 жылғы 9 қаңтардағы № 25 қаулысы. Батыс Қазақстан облысы Зеленов ауданы әділет басқармасында 2009 жылғы 20 ақпанда № 7-7-83 тіркелді. Күші жойылды - Батыс Қазақстан облысы Зеленов ауданы әкімдігінің 2010 жылғы 5 қаңтардағы № 17 қаулысымен
title:
  rus: 2009 жылғы қоғамдық жұмыстарды ұымдастыру және қаржыландыру туралы
  kaz: 2009 жылғы қоғамдық жұмыстарды ұымдастыру және қаржыландыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-01-09
approved_by:
- '159008000001'
version_date:
  kaz: 2009-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/44396/kaz/16.07.2009
caused_by:
  code: '47190'
  requisite: Батыс Қазақстан облысы Зеленов ауданы әкімдігінің 2009 жылғы 16 шілдедегі № 309 қаулысы. Батыс Қазақстан облысы Зеленов ауданы әділет басқармасында 2009 жылғы 5 тамызда № 7-7-92 тіркелді. Күші жойылды - Батыс Қазақстан облысы Зеленов ауданы әкімдігінің 2014 жылғы 10 қазандағы № 816 қаулысымен
  title:
    rus: Аудан әкімдігінің 2009 жылғы 9 қаңтардағы "2009 жылғы қоғамдық жұмыстарды ұйымдастыру және қаржыландыру туралы" № 25 қаулысына өзгерістер енгізу туралы
    kaz: Аудан әкімдігінің 2009 жылғы 9 қаңтардағы "2009 жылғы қоғамдық жұмыстарды ұйымдастыру және қаржыландыру туралы" № 25 қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47190/rus
