act_code: '120535'
requisite: Постановление акимата города Костаная Костанайской области от 15 марта 2018 года № 656. Зарегистрировано Департаментом юстиции Костанайской области 11 апреля 2018 года № 7692. Утратило силу постановлением акимата города Костаная Костанайской области от 5 января 2026 года № 1 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении норматива отчисления части чистого дохода коммунальных государственных предприятий города Костаная
  kaz: Қостанай қаласының коммуналдық мемлекеттік кәсіпорындарының таза кірісінің бір бөлігін аудару нормативін белгілеу туралы
form: ПОСТ
type_codes:
- НОРМ
- ПОСТ
approved_on: 2018-03-15
approved_by:
- '162002000001'
version_date:
  kaz: 2020-03-31
  rus: 2020-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/120535/kaz/31.03.2020
  rus: https://zan.gov.kz/client/#!/doc/120535/rus/31.03.2020
caused_by:
  code: '140809'
  requisite: Постановление акимата города Костаная Костанайской области от 31 марта 2020 года № 576. Зарегистрировано Департаментом юстиции Костанайской области 31 марта 2020 года № 9071. Утратило силу постановлением акимата города Костаная Костанайской области от 5 января 2026 года № 1 (вводится в действие после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в постановление акимата от 15 марта 2018 года № 656 «Об установлении норматива отчисления части чистого дохода коммунальных государственных предприятий города Костаная»
    kaz: Әкімдіктің 2018 жылғы 15 наурыздағы № 656 «Қостанай қаласының коммуналдық мемлекеттік кәсіпорындарының таза кірісінің бөлігін аудару нормативін белгілеу туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140809/rus
