act_code: '51025'
requisite: Постановление акимата Есильского района Акмолинской области от 28 января 2010 года № А-1/20. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 2 марта 2010 года № 1-11-114. Утратило силу - постановлением акимата Есильского района Акмолинской области от 24 декабря 2010 года № А-12/381
title:
  rus: Об организации общественных работ в Есильском районе на 2010 год
  kaz: 2010 жылға Есіл ауданында қоғамдық жұмыстарын ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-01-28
approved_by:
- '152012000001'
version_date:
  kaz: 2010-03-26
  rus: 2010-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/51025/kaz/26.03.2010
  rus: https://zan.gov.kz/client/#!/doc/51025/rus/26.03.2010
caused_by:
  code: '52095'
  requisite: Постановление акимата Есильского района Акмолинской области от 26 марта 2010 года № А-3/75. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 23 апреля 2010 года № 1-11-116. Утратило силу - постановлением акимата Есильского района Акмолинской области от 24 декабря 2010 года № А-12/381
  title:
    rus: О внесении изменения в постановление акимата Есильского района "Об организации общественных работ в Есильском районе на 2010 год" от 28 января 2010 года № А-1/20
    kaz: Есіл аудан әкімдігінің "2010 жылға Есіл ауданында қоғамдық жұмыстарын ұйымдастыру туралы" қаулысына өзгерту енгізу туралы 2010 жылғы 28 қаңтардағы № А-1/20
  link: https://zan.gov.kz/client/#!/doc/52095/rus
