act_code: '104747'
requisite: Постановление акимата Северо-Казахстанской области от 16 июня 2016 года № 225. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 июля 2016 года № 3822. Утратило силу постановлением акимата Северо-Казахстанской области от 29 марта 2018 года № 87
title:
  rus: Об утверждении регламента государственной услуги «Субсидирование повышения урожайности и качества продукции растениеводства, стоимости  горюче-смазочных материалов и других товарно-материальных ценностей, необходимых для проведения весенне-полевых и уборочных работ, путем субсидирования производства приоритетных культур»
  kaz: «Басым дақылдар өндiрудi субсидиялау арқылы өсiмдiк шаруашылығы өнiмiнiң шығымдылығы мен сапасын арттыруды, жанар-жағармай материалдарының және көктемгi егiс пен егiн жинау жұмыстарын жүргiзу үшін қажеттi басқа да тауарлық-материалдық құндылықтардың құнын субсидиялау» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2016-06-16
approved_by:
- '165000000001'
version_date:
  kaz: 2016-06-16
  rus: 2016-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/104747/kaz/16.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104747/rus/16.06.2016
