act_code: '92665'
requisite: Постановление от 22.07.2015 №а-7/357, Акимат Бурабайского района. Утратило силу постановлением акимата Бурабайского района Акмолинской области от 22 апреля 2016 года № а-4/159
title:
  rus: Об установлении квоты рабочих мест для лиц, состоящих на учете службы пробации Бурабайского района, а также лиц, освобожденных из мест лишения свободы и для несовершеннолетних выпускников интернатных организаций в Бурабайском районе
  kaz: Бурабай ауданында Бурабай ауданының пробация қызметінің есебінде тұрған адамдар үшін, сондай-ақ бас бостандығынан айыру орындарынан босатылған адамдар үшін және интернаттық ұйымдарды бiтiрушi кәмелетке толмағандар үшін жұмыс орындарына квота белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-07-22
approved_by:
- '152020000001'
version_date:
  kaz: 2015-07-22
  rus: 2015-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/92665/kaz/22.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92665/rus/22.07.2015
