act_code: '5550'
requisite: Постановление Правительства Республики Казахстан от 17 марта 2000 года N 412
title:
  rus: О некоторых вопросах обеспечения горюче-смазочными материалами сельскохозяйственных товаропроизводителей
  kaz: Ауыл шаруашылығы тауар өндiрушiлерiн жанар-жағармай материалдарымен қамтамасыз етудiң кейбiр мәселелерi туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2000-03-17
approved_by:
- '103000000000'
version_date:
  kaz: 2000-07-09
  rus: 2000-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/5550/kaz/09.07.2000
  rus: https://zan.gov.kz/client/#!/doc/5550/rus/09.07.2000
caused_by:
  code: '6395'
  requisite: Постановление Правительства Республики Казахстан от 10 июля 2000 года N 1041
  title:
    rus: О внесении изменений и дополнений в постановления Правительства Республики Казахстан от 4 марта 2000 года N 353 и от 17 марта 2000 года N 412
    kaz: Қазақстан Республикасы Yкіметiнің 2000 жылғы 4 наурыздағы N 353 және 2000 жылғы 17 наурыздағы N 412 қаулыларына өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/6395/rus
