act_code: '33971'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 30 марта 2007 года № 61. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 июня 2007 года № 4772. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 26 марта 2012 года № 133
title:
  rus: Об утверждении Правил добровольной ликвидации страховых (перестраховочных) организаций
  kaz: Сақтандыру (қайта сақтандыру) ұйымдарын ерікті тарату ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2007-03-30
approved_by:
- '109000000000'
version_date:
  kaz: 2007-03-30
  rus: 2007-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/33971/kaz/30.03.2007
  rus: https://zan.gov.kz/client/#!/doc/33971/rus/30.03.2007
