act_code: '18577'
requisite: Постановление Правительства Республики Казахстан от 13 февраля 2004 года № 174. Утратило силу постановлением Правительства Республики Казахстан от 19 апреля 2012 года № 493
title:
  rus: О расходах, связанных с подготовкой к перевозке тела, перевозкой тела, погребением, изготовлением и установкой надгробного памятника военнослужащим, военнообязанным, призванным на военные сборы, погибшим при прохождении военной службы или умершим в результате увечья (ранения, травмы, контузии), заболевания
  kaz: Әскери қызметті өткеру кезiнде қаза тапқан немесе мертiгу (жаралану, жарақат алу, контузия), ауру салдарынан қайтыс болған әскери қызметшiлердiң, әскери жиындарға шақырылған әскери мiндеттiлердiң мәйiттерiн жеткiзудi әзiрлеуге, мәйiттерiн жеткiзуге, жерлеуге, құлпытас дайындауға және оны орнатуға байланысты шығыстар туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-02-13
approved_by:
- '103000000000'
version_date:
  kaz: 2004-02-13
  rus: 2004-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/18577/kaz/13.02.2004
  rus: https://zan.gov.kz/client/#!/doc/18577/rus/13.02.2004
