act_code: '161675'
requisite: Постановление акимата Карасуского района Костанайской области от 9 декабря 2021 года № 202
title:
  rus: Об утверждении Правил предоставления коммунальных услуг в Карасуском районе
  kaz: Қарасу ауданында коммуналдық көрсетілетін қызметтерді ұсыну қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2021-12-09
approved_by:
- '162011000001'
version_date:
  kaz: 2024-04-18
  rus: 2024-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/161675/kaz/18.04.2024
  rus: https://zan.gov.kz/client/#!/doc/161675/rus/18.04.2024
caused_by:
  code: '195898'
  requisite: Постановление акимата Карасуского района Костанайской области от 18 апреля 2024 года № 118
  title:
    rus: О внесении изменения в постановление акимата Карасуского района от 9 декабря 2021 года № 202 «Об утверждении Правил предоставления коммунальных услуг в Карасуском районе»
    kaz: Қарасу ауданы әкімдігінің «Қарасу ауданында коммуналдық көрсетілетін қызметтерді ұсыну қағидаларын бекіту туралы» 2021 жылғы 9 желтоқсандағы № 202 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195898/rus
