act_code: '144817'
requisite: Постановление Правления Национального Банка Республики Казахстан от 14 июля 2020 года № 86. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2020 года № 20972. Действовал до 1 января 2023 года в соответствии с пунктом 5 настоящего постановления
title:
  rus: Об установлении пределов отклонения курса покупки от курса продажи иностранной валюты за тенге по операциям, проводимым через обменные пункты
  kaz: Айырбастау пункттері арқылы жүргізілетін операциялар бойынша шетел валютасын теңгеге сатып алу бағамының сату бағамынан ауытқу шектерін белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2020-07-14
approved_by:
- '117000000000'
version_date:
  kaz: 2022-03-31
  rus: 2022-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/144817/kaz/31.03.2022
  rus: https://zan.gov.kz/client/#!/doc/144817/rus/31.03.2022
caused_by:
  code: '166276'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 31 марта 2022 года № 30. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 апреля 2022 года № 27488
  title:
    rus: О внесении изменения в постановление Правления Национального Банка Республики Казахстан от 14 июля 2020 года № 86 «Об установлении пределов отклонения курса покупки от курса продажи иностранной валюты за тенге по операциям, проводимым через обменные пункты»
    kaz: «Айырбастау пункттері арқылы жүргізілетін операциялар бойынша шетел валютасын теңгеге сатып алу бағамының сату бағамынан ауытқу шектерін белгілеу туралы» Қазақстан Республикасы Ұлттық Банкі Басқармасының 2020 жылғы 14 шілдедегі № 86 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166276/rus
