act_code: '35962'
requisite: Постановление Правительства Республики Казахстан от 29 ноября 2007 года № 1146. Утратило силу постановлением Правительства Республики Казахстан от 12 октября 2015 года № 821
title:
  rus: Об утверждении криминалистических требований и методов испытания гражданского и служебного оружия и патронов к нему, Правил выдачи заключений на соответствие криминалистическим требованиям гражданского и служебного оружия и патронов к нему
  kaz: Азаматтық және қызметтік қару мен оның патрондарына криминалистік талаптар мен оларды сынау әдістерін, Азаматтық және қызметтік қару мен оның патрондарының криминалистік талаптарға сәйкестігіне қорытындылар беру қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ТРЕБ
approved_on: 2007-11-29
approved_by:
- '103000000000'
version_date:
  kaz: 2007-11-29
  rus: 2007-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/35962/kaz/29.11.2007
  rus: https://zan.gov.kz/client/#!/doc/35962/rus/29.11.2007
