act_code: '43782'
requisite: Постановление акимата Аулиекольского района Костанайской области от 15 января 2009 года № 6. Зарегистрировано Управлением юстиции Аулиекольского района Костанайской области 27 января 2009 года № 9-7-90. Утратило силу в связи с истечением срока действия (письмо акима Аулиекольского района Костанайской области от 12 апреля 2010 года № 04-10/234)
title:
  rus: Об установлении перечня целевых групп населения в Аулиекольском районе на 2009 год
  kaz: Әулиекөл ауданында 2009 жылға тұрғындардың нысаналы топтарының тізбесін белгілеуде туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-01-15
approved_by:
- '162005000001'
version_date:
  kaz: 2009-07-23
  rus: 2009-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43782/kaz/23.07.2009
  rus: https://zan.gov.kz/client/#!/doc/43782/rus/23.07.2009
caused_by:
  code: '47382'
  requisite: Постановление акимата Аулиекольского района Костанайской области от 23 июля 2009 года № 183. Зарегистрировано Управлением юстиции Аулиекольского района Костанайской области 14 августа 2009 года № 9-7-102. Утратило силу в связи с истечением срока действия (письмо акима Аулиекольского района Костанайской области от 12 апреля 2010 года № 04-10/234)
  title:
    rus: О внесении изменений и дополнения в постановление акимата района от 15 января 2009 года № 6 "Об утверждении перечня целевых груп населения в Аулиекольском района на 2009 год"
    kaz: Әкімдіктің 2009 жылғы 15 қаңтардағы № 6 "Әулиекөл ауданында 2009 жылға тұрғындардың нысаналы топтарының тізбесін бекіту туралы" қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47382/rus
