act_code: '38915'
requisite: Постановление акимата Наурзумского района Костанайской области от 25 марта 2008 года № 67. Зарегистрировано Управлением юстиции Наурзумского района Костанайской области 10 апреля 2008 года № 9-16-69
title:
  rus: Об утверждении инструкции по оказанию социальной помощи, безработным направленным на профессиональную подготовку, повышение квалификации и переподготовку
  kaz: Кәсіби даярлауға, біліктілігін арттыруға және қайта даярлауға жіберілген жұмыссыздарға әлеуметтік көмек көрсету жөніндегі нұсқаулықты бекіту туралы
form: ПОСТ
type_codes:
- ИНСТ
- ПОСТ
approved_on: 2008-03-25
approved_by:
- '162014000001'
version_date:
  kaz: 2008-03-25
  rus: 2008-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/38915/kaz/25.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38915/rus/25.03.2008
