act_code: '40712'
requisite: Оңтүстік Қазақстан облысы Арыс қаласы әкімдігінің 2008 жылғы 3 маусымдағы N 354 қаулысы. Оңтүстік Қазақстан облысы Арыс қаласының Әділет Басқармасында 2008 жылғы 14 шілдеде N 14-2-59 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Арыс қаласының әкімдігінің 2009 жылғы 15 қазандағы N 444 Қаулысымен
title:
  rus: Арыс қалалық ауыл шаруашылығы бөлімінің мемлекеттік қызмет көрсетудің стандартын бекіту туралы
  kaz: Арыс қалалық ауыл шаруашылығы бөлімінің мемлекеттік қызмет көрсетудің стандартын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-06-03
approved_by:
- '166016000001'
version_date:
  kaz: 2008-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/40712/kaz/03.06.2008
