act_code: '121989'
requisite: Постановление Правления Национального Банка Республики Казахстан от 27 апреля 2018 года № 70. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 мая 2018 года № 16922
title:
  rus: Об утверждении Правил продажи и выкупа Национальным Банком Республики Казахстан банкнот и монет национальной валюты Республики Казахстан, в том числе в специальной упаковке
  kaz: Қазақстан Республикасы Ұлттық Банкінің Қазақстан Республикасы ұлттық валютасының банкноттары мен монеталарын, оның ішінде арнаулы қаптамалардағы банкноттары мен монеталарын сату және сатып алу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2018-04-27
approved_by:
- '117000000000'
version_date:
  kaz: 2024-10-30
  rus: 2024-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/121989/kaz/30.10.2024
  rus: https://zan.gov.kz/client/#!/doc/121989/rus/30.10.2024
caused_by:
  code: '202493'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 30 октября 2024 года № 66. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 ноября 2024 года № 35355
  title:
    rus: О внесении изменений и дополнения в постановление Правления Национального Банка Республики Казахстан от 27 апреля 2018 года № 70 «Об утверждении Правил продажи и выкупа Национальным Банком Республики Казахстан банкнот и монет национальной валюты Республики Казахстан»
    kaz: «Қазақстан Республикасы Ұлттық Банкiнiң Қазақстан Республикасы ұлттық валютасының банкноттары мен монеталарын сату және сатып алу қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық Банкі Басқармасының 2018 жылғы 27 сәуірдегі № 70 қаулысына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202493/rus
