act_code: '6763'
requisite: Постановление Правительства Республики Казахстан от 9 августа 2000 года N 1227
title:
  rus: О некоторых организациях Комитета по стандартизации, метрологии и сертификации Министерства энергетики, индустрии и торговли Республики Казахстан
  kaz: Қазақстан Республикасының Энергетика, индустрия және сауда министрлiгі Стандарттау, метрология және сертификаттау жөнiндегі комитетiнiң кейбiр ұйымдары туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2000-08-08
approved_by:
- '103000000000'
version_date:
  kaz: 2001-10-31
  rus: 2001-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/6763/kaz/31.10.2001
  rus: https://zan.gov.kz/client/#!/doc/6763/rus/31.10.2001
caused_by:
  code: '10247'
  requisite: Постановление Правительства Республики Казахстан от 31 октября 2001 года N 1384
  title:
    rus: О внесении изменения и дополнения в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкiметiнiң кейбiр шешiмдерiне өзгерiс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/10247/rus
