act_code: '170008'
requisite: Постановление акимата города Приозерск Карагандинской области от 5 июля 2022 года № 24/183. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 июля 2022 года № 28753
title:
  rus: Об определении и утверждении мест размещения нестационарных торговых объектов на территории города Приозерск
  kaz: Приозерск қаласының аумағында стационарлық емес сауда объектілерін орналастыру орындарын айқындау және бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2022-07-05
approved_by:
- '160009000001'
version_date:
  kaz: 2025-04-25
  rus: 2025-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/170008/kaz/25.04.2025
  rus: https://zan.gov.kz/client/#!/doc/170008/rus/25.04.2025
caused_by:
  code: '209536'
  requisite: Постановление акимата города Приозерск Карагандинской области от 25 апреля 2025 года № 15/60. Зарегистрировано Департаментом юстиции Карагандинской области 28 апреля 2025 года № 6761-09
  title:
    rus: О внесении изменения в постановление акимата города Приозерск от 5 июля 2022 года № 24/183 «Об определении и утверждении мест размещения нестационарных торговых объектов на территории города Приозерск»
    kaz: Приозерск қаласының әкімдігінің 2022 жылғы 5 шілдедегі № 24/183 «Приозерск қаласының аумағында стационарлық емес сауда объектілерін орналастыру орындарын айқындау және бекіту туралы» қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209536/rus
