act_code: '66222'
requisite: Постановление Мактааральского районного акимата Южно-Казахстанской области от 10 мая 2012 года № 941. Зарегистрировано Управлением юстиции Мактааральского района Южно-Казахстанской области 14 июня 2012 года № 14-7-167. Утратило силу постановлением акимата Мактааральского района Южно-Казахстанской области от 19 марта 2015 года № 363
title:
  rus: Об определении видов общественных работ для привлечения граждан, осужденных на привлечение к общественным работам
  kaz: Қоғамдық жұмысқа тартуға сотты болған азаматтар тартылатын қоғамдық жұмыстардың түрлерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-05-10
approved_by:
- '166005000001'
version_date:
  kaz: 2012-05-10
  rus: 2012-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/66222/kaz/10.05.2012
  rus: https://zan.gov.kz/client/#!/doc/66222/rus/10.05.2012
