act_code: '43602'
requisite: Оңтүстік Қазақстан облысы Ордабасы ауданы әкімдігінің 2008 жылғы 24 желтоқсандағы N 550 қаулысы. Оңтүстік Қазақстан облысы Ордабасы ауданының Әділет басқармасында 2009 жылғы 16 қаңтарда N 14-8-61 тіркелді
title:
  rus: 2009 жылы жұмыссыздарды қоғамдық жұмыстарға жіберу туралы
  kaz: 2009 жылы жұмыссыздарды қоғамдық жұмыстарға жіберу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-12-24
approved_by:
- '166006000001'
version_date:
  kaz: 2010-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43602/kaz/26.03.2010
