act_code: '20650'
requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 12 июня 2004 года N 158. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 июля 2004 года N 2954. Утратило силу - постановлением Правления Агентство Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 30 апреля 2007 года N 124
title:
  rus: Об утверждении Правил проведения аттестации физических лиц для работы на рынке ценных бумаг, выдачи квалификационных свидетельств, а также приостановления действия или отзыва квалификационных свидетельств
  kaz: Бағалы қағаздар рыногындағы жұмыс үшін жеке тұлғаларды аттестациядан өткізу, біліктілік куәліктерін беру, сонымен қатар біліктілік куәліктерінің қолданысын тоқтата тұру немесе қайтарып алу ережесін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2004-06-11
approved_by:
- '109000000000'
version_date:
  kaz: 2005-05-28
  rus: 2005-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/20650/kaz/28.05.2005
  rus: https://zan.gov.kz/client/#!/doc/20650/rus/28.05.2005
caused_by:
  code: '24589'
  requisite: Постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 28 мая 2005 года N 158. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 июля 2005 года за N 3716. Утратило силу - постановлением Правления Агентство Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 30 апреля 2007 года N 124
  title:
    rus: О внесении дополнений и изменений в постановление Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 12 июня 2004 года N 158 "Об утверждении Правил проведения аттестации физических лиц для работы на рынке ценных бумаг, выдачи квалификационных свидетельств, а также приостановления действия или отзыва квалификационных свидетельств"
    kaz: Қазақстан Республикасы Қаржы нарығын және қаржы ұйымдарын реттеу мен қадағалау агенттігі Басқармасының "Бағалы қағаздар рыногындағы жұмыс үшін жеке тұлғаларды аттестациядан өткізу, біліктілік куәліктерін беру, сонымен қатар біліктілік куәліктерінің қолданысын тоқтата тұру немесе қайтарып алу ережесін бекіту туралы" 2004 жылғы 12 маусымдағы N 158 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24589/rus
