act_code: '44667'
requisite: Жамбыл облысы Жуалы аудандық әкімиятының 2009 жылғы 28 қаңтардағы № 44 қаулысы. Жамбыл облысы Жуалы ауданының әділет басқармасында 2009 жылғы 5 наурызда 6-4-69 нөмірімен тіркелді
title:
  rus: 2009 жылы нысаналы топтардағы азаматтарға әлеуметтік жұмыс орындарын ұйымдастыру туралы
  kaz: 2009 жылы нысаналы топтардағы азаматтарға әлеуметтік жұмыс орындарын ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-01-28
approved_by:
- '158005000001'
version_date:
  kaz: 2009-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44667/kaz/28.01.2009
