act_code: '201116'
requisite: Совместные решение маслихата Алматинской области от 25 сентября 2024 года № 26-135 и постановление акимата Алматинской области от 25 сентября 2024 года № 299. Зарегистрировано Департаментом юстиции Алматинской области 26 сентября 2024 года № 6170-05
title:
  rus: Об установлении границ (черты) города Алатау Алматинской области
  kaz: Алматы облысы Алатау қаласының шекарасын (шегін) белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2024-09-25
approved_by:
- '154000000001'
- '154000000002'
version_date:
  kaz: 2024-09-25
  rus: 2024-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/201116/kaz/25.09.2024
  rus: https://zan.gov.kz/client/#!/doc/201116/rus/25.09.2024
