act_code: '108312'
requisite: Нормативное постановление Верховного Суда Республики Казахстан от 25 ноября 2016 года № 7
title:
  rus: О судебной практике рассмотрения гражданских дел по спорам, вытекающим из договоров банковского займа
  kaz: Банктік қарыз шарттарынан туындайтын даулар бойынша азаматтық істерді қараудың сот практикасы туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-11-25
approved_by:
- '105000000000'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/108312/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/108312/rus/29.09.2022
caused_by:
  code: '172476'
  requisite: Нормативное постановление Верховного Суда Республики Казахстан от 29 сентября 2022 года № 7
  title:
    rus: О внесении изменений и дополнений в нормативное постановление Верховного Суда Республики Казахстан от 25 ноября 2016 года № 7 «О судебной практике рассмотрения гражданских дел по спорам, вытекающим из договоров банковского займа»
    kaz: «Банктік қарыз шарттарынан туындайтын даулар бойынша азаматтық істерді қараудың сот практикасы туралы» Қазақстан Республикасы Жоғарғы Сотының 2016 жылғы 25 қарашадағы № 7 нормативтік қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172476/rus
