act_code: '42445'
requisite: Батыс Қазақстан облысы Казталов ауданы әкімдігінің 2008 жылғы 24 қазандағы № 337 қаулысы. Батыс Қазақстан облысы Казталов ауданы әділет басқармасында 2008 жылғы 25 қарашада № 7-8-78 тіркелді. Күші жойылды - Батыс Қазақстан облысы Казталов ауданы әкімдігінің 2009 жылғы 25 қарашадағы № 313 қаулысымен
title:
  rus: Талдықұдық ауылдық округі бойынша ірі қара малы арасында "бруцеллез" ауруының тіркелуіне байланысты шектеу салу туралы
  kaz: Талдықұдық ауылдық округі бойынша ірі қара малы арасында "бруцеллез" ауруының тіркелуіне байланысты шектеу салу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-10-24
approved_by:
- '159009000001'
version_date:
  kaz: 2008-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/42445/kaz/24.10.2008
