act_code: '51444'
requisite: Постановление акимата Иртышского района Павлодарской области от 12 февраля 2010 года № 28/1. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 24 марта 2010 года № 12-7-96. Утратило силу постановлением акимата Иртышского района Павлодарской области от 26 мая 2010 года № 189/4
title:
  rus: О наложении ограничительных мероприятий по ТОО имени "Абая", КХ "Нан" села Голубовка Иртышского района
  kaz: Ертіс ауданы Голубовка ауылының "Абай" атындағы ЖШС, "Нан" ШҚ шектеулі шараларды салу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-02-12
approved_by:
- '164007000001'
version_date:
  kaz: 2010-02-12
  rus: 2010-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/51444/kaz/12.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51444/rus/12.02.2010
