act_code: '143928'
requisite: Постановление акимата Жамбылской области от 15 июня 2020 года № 130 и решение Жамбылского областного маслихата от 15 июня 2020 года № 47-9. Зарегистрировано Департаментом юстиции Жамбылской области 18 июня 2020 года № 4633
title:
  rus: Об изменении границы (черты) города Шу и Толебийского сельского округа Шуского района Жамбылской области
  kaz: Жамбыл облысы Шу ауданының Шу қаласы және Төле би ауылдық округінің шекараларын (шегін) өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2020-06-15
approved_by:
- '158000000001'
- '158000000002'
version_date:
  kaz: 2020-06-15
  rus: 2020-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/143928/kaz/15.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143928/rus/15.06.2020
