act_code: '88482'
requisite: Постановление от 15.01.2015 №2/3, Акимат г. Приозерск. Утратило силу постановлением акимата города Приозерск Карагандинской области от 18 июня 2015 года № 25/2
title:
  rus: Об утверждении Правил расчета ставки арендной платы при передаче коммунального имущества города Приозерск в имущественный наем (аренду)
  kaz: Приозерск қаласының коммуналдық мүлкін мүліктік жалдауға (жалға алуға) беру кезінде жалдау ақысының мөлшерлемесін есептеу қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2015-01-15
approved_by:
- '160009000001'
version_date:
  kaz: 2015-01-15
  rus: 2015-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/88482/kaz/15.01.2015
  rus: https://zan.gov.kz/client/#!/doc/88482/rus/15.01.2015
