act_code: '19895'
requisite: Постановление акимата Егиндыкольского района Акмолинской области от 25 апреля 2004 года № а-4/30. Зарегистрировано Управлением юстиции Акмолинской области 17 мая 2004 года № 2522. Утратило силу постановлением акимата Егиндыкольского района Акмолинской области от 24 марта 2005 года № а-3/39
title:
  rus: О создании штаба при акимате Егиндыкольского района по координации деятельности районных ведомств по формированию электронных списков, регистрации, учету избирателей
  kaz: Егіндікөл ауданы әкімдігі жанынан сайлаушылардың электрондық тізімдерін түзу, оларды тіркеу және есепке алу жөніндегі аудандық ведомстволар қызметін үйлестіру жөніндегі штаб құру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-04-24
approved_by:
- '152009000001'
version_date:
  kaz: 2004-04-24
  rus: 2004-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/19895/kaz/24.04.2004
  rus: https://zan.gov.kz/client/#!/doc/19895/rus/24.04.2004
