act_code: '228077'
requisite: Совместные постановление акимата Осакаровского района Карагандинской области от 21 июля 2026 года № 70/01 и решение Осакаровского районного маслихата Карагандинской области от 22 июля 2026 года № 53/514
title:
  rus: Об изменении и установлении границ населенных пунктов Родниковского сельского округа Осакаровского района Карагандинской области
  kaz: Қарағанды облысы Осакаров ауданы Родников ауылдық округінің елді мекендерінің шекараларын өзгерту және белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2026-07-21
approved_by:
- '160018000001'
- '160018000002'
version_date:
  kaz: 2026-07-21
  rus: 2026-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/228077/kaz/21.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228077/rus/21.07.2026
