act_code: '159988'
requisite: Совместные постановление акимата Карагандинской области от 22 октября 2021 года № 76/01 и решение Карагандинского областного маслихата от 22 октября 2021 года № 116. Зарегистрированы в Министерстве юстиции Республики Казахстан 5 ноября 2021 года № 25030
title:
  rus: Об изменении границ (черты) города Балхаш и Актогайского района Карагандинской области
  kaz: Қарағанды облысы Балқаш қаласы мен Ақтоғай ауданының шекараларын (шегін) өзгерту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕШ
approved_on: 2021-10-22
approved_by:
- '160000000001'
- '160000000002'
version_date:
  kaz: 2021-10-22
  rus: 2021-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/159988/kaz/22.10.2021
  rus: https://zan.gov.kz/client/#!/doc/159988/rus/22.10.2021
