act_code: '101214'
requisite: Постановление Правительства Республики Казахстан от 14 апреля 2016 года № 214
title:
  rus: Об утверждении Правил использования целевых текущих трансфертов из республиканского бюджета на 2016 год областными бюджетами, бюджетами городов Астаны и Алматы на здравоохранение, на реализацию Плана мероприятий по обеспечению прав и улучшению качества жизни инвалидов в Республике Казахстан на 2012 – 2018 годы и услуги по замене и настройке речевых процессоров к кохлеарным имплантам
  kaz: Облыстық бюджеттердің, Астана және Алматы қалалары бюджеттерінің денсаулық сақтауға, Қазақстан Республикасында мүгедектердің құқықтарын қамтамасыз ету және өмір сүру сапасын жақсарту жөніндегі 2012 - 2018 жылдарға арналған іс-шаралар жоспарын іске асыруға және кохлеарлық импланттарға сөйлеу процессорларын ауыстыру және теңшеу жөніндегі көрсетілетін қызметтерге 2016 жылға арналған республикалық бюджеттен берілетін ағымдағы нысаналы трансферттерді пайдалану қағидаларын бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- ПРАВ
approved_on: 2016-04-14
approved_by:
- '103000000000'
version_date:
  kaz: 2016-04-14
  rus: 2016-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/101214/kaz/14.04.2016
  rus: https://zan.gov.kz/client/#!/doc/101214/rus/14.04.2016
