act_code: '223096'
requisite: Постановление акимата Алгинского района Актюбинской области от 4 марта 2026 года № 62
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью "Freedom Telecom Operations"
  kaz: «Freedom Telecom Operations» жауапкершілігі шектеулі серіктестігіне қауымдық сервитут белгілеу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2026-03-04
approved_by:
- '153004000001'
version_date:
  kaz: 2026-03-04
  rus: 2026-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/223096/kaz/04.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223096/rus/04.03.2026
