act_code: '46621'
requisite: Шығыс Қазақстан облысы Катонқарағай ауданы әкімдігінің 2009 жылғы 13 маусымдағы № 4178 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық Әділет басқармасында 2009 жылғы 22 маусымда № 5-13-60 тіркелді. Қаулының қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - (Катонқарағай ауданы әкімінің 2010 жылғы 12 қаңтардағы № 6 хаты)
title:
  rus: Әлеуметтік жұмыс орындарын ұйымдастыру туралы
  kaz: Әлеуметтік жұмыс орындарын ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2009-06-13
approved_by:
- '157014000001'
version_date:
  kaz: 2009-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/46621/kaz/13.06.2009
