act_code: '43473'
requisite: Шығыс Қазақстан облысы Катонқарағай ауданы әкімдігінің 2008 жылғы 25 желтоқсандағы № 3739 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық Әділет басқармасында 2009 жылғы 14 қаңтарда № 5-13-52 тіркелді. Қаулының қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Катонқарағай ауданы әкімінің 2010 жылғы 12 қаңтардағы № 6 хатымен
title:
  rus: 2009 жылға ақылы қоғамдық жұмыстарды ұйымдастыру туралы
  kaz: 2009 жылға ақылы қоғамдық жұмыстарды ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-12-25
approved_by:
- '157014000001'
version_date:
  kaz: 2009-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/43473/kaz/05.06.2009
caused_by:
  code: '46620'
  requisite: Шығыс Қазақстан облысы Катонқарағай ауданы әкімдігінің 2009 жылғы 5 маусымдағы № 4164 қаулысы. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық әділет басқармасында 2009 жылғы 22 маусымда № 5-13-59 тіркелді. Қаулының қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - (Катонқарағай ауданы әкімінің 2010 жылғы 12 қаңтардағы № 6 хаты)
  title:
    rus: 2008 жылғы 25 желтоқсандағы "2009 жылға ақылы қоғамдық жұмыстарды ұйымдастыру туралы" № 3739 қаулысына толықтырулар енгізу туралы
    kaz: 2008 жылғы 25 желтоқсандағы "2009 жылға ақылы қоғамдық жұмыстарды ұйымдастыру туралы" № 3739 қаулысына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46620/rus
