act_code: '880'
requisite: Постановление Кабинета Министров Республики Казахстан от 30 сентября 1993 года № 979. Утратило силу постановлением Правительства Республики Казахстан от 17 сентября 1997 года № 1347
title:
  rus: Об утверждении Положения о мониторинге земель Республики Казахстан
  kaz: Қазақстан Республикасының Жер мониторингi туралы Ережесiн бекiту жайында
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1993-09-30
approved_by:
- '103000000000'
version_date:
  rus: 1993-09-30
source:
  rus: https://zan.gov.kz/client/#!/doc/880/rus/30.09.1993
