act_code: '94534'
requisite: Постановление акимата Карагандинской области от 15 сентября 2015 года № 53/01. Зарегистрировано Департаментом юстиции Карагандинской области 14 октября 2015 года № 3445. Утратило силу постановлением акимата Карагандинской области от 31 января 2020 года № 05/02 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в области семеноводства
  kaz: Тұқым шаруашылығы саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
- РЕГЛ
approved_on: 2015-09-15
approved_by:
- '160000000001'
version_date:
  kaz: 2018-07-24
  rus: 2018-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/94534/kaz/24.07.2018
  rus: https://zan.gov.kz/client/#!/doc/94534/rus/24.07.2018
caused_by:
  code: '124168'
  requisite: Постановление акимата Карагандинской области от 24 июля 2018 года № 37/01. Зарегистрировано Департаментом юстиции Карагандинской области 13 августа 2018 года № 4892. Утратило силу постановлением акимата Карагандинской области от 31 января 2020 года № 05/02 (вводится в действие со дня первого официального опубликования)
  title:
    rus: О внесении изменений в некоторые постановления акимата Карагандинской области
    kaz: Қарағанды облысының кейбір қаулыларына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124168/rus
