act_code: '26328'
requisite: Постановление Правительства Республики Казахстан от 6 января 2006 года № 3
title:
  rus: О включении в состав автомобильных дорог общего пользования республиканского значения автомобильных дорог Казталовка - Жанибек - граница Российской Федерации и Ленинский - Аксу - Коктобе - Большой Акжар - город Курчатов
  kaz: Казталов - Жәнiбек - Ресей Федерациясының шекарасы және Ленинск - Ақсу - Көктөбе - Yлкен Ақжар - Курчатов қаласы автомобиль жолдарын республикалық маңызы бар жалпы пайдаланымдағы автомобиль жолдарының құрамына енгiзу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2006-01-06
approved_by:
- '103000000000'
version_date:
  kaz: 2006-01-06
  rus: 2006-01-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/26328/kaz/06.01.2006
  rus: https://zan.gov.kz/client/#!/doc/26328/rus/06.01.2006
