act_code: '21723'
requisite: Постановление Правительства Республики Казахстан от 28 октября 2004 года № 1120
title:
  rus: Вопросы Министерства юстиции Республики Казахстан
  kaz: Қазақстан Республикасы Әділет министрлігінің мәселелерi
form: ПОСТ
type_codes:
- ПОЛ
- ПОСТ
- ПРЧ
approved_on: 2004-10-28
approved_by:
- '103000000000'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/21723/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/21723/rus/23.07.2021
caused_by:
  code: '157403'
  requisite: Постановление Правительства Республики Казахстан от 23 июля 2021 года № 511
  title:
    rus: О внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157403/rus
