act_code: '67816'
requisite: Постановление акимата Костанайской области от 20 августа 2012 года № 381. Зарегистрировано Департаментом юстиции Костанайской области 27 сентября 2012 года № 3837. Утратило силу - Постановлением акимата Костанайской области от 20 ноября 2013 года № 508
title:
  rus: Об утверждении регламента электронной государственной услуги "Выдача архивных справок"
  kaz: '"Мұрағаттық анықтамалар беру" электрондық мемлекеттік қызмет регламентін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2012-08-20
approved_by:
- '162000000001'
version_date:
  kaz: 2013-03-15
  rus: 2013-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/67816/kaz/15.03.2013
  rus: https://zan.gov.kz/client/#!/doc/67816/rus/15.03.2013
caused_by:
  code: '72238'
  requisite: Постановление акимата Костанайской области от 15 марта 2013 года № 98. Зарегистрировано Департаментом юстиции Костанайской области 24 апреля 2013 года № 4107. Утратило силу - Постановлением акимата Костанайской области от 20 ноября 2013 года № 508
  title:
    rus: О внесении изменения в постановление акимата от 20 августа 2012 года № 381 "Об утверждении регламента электронной государственной услуги "Выдача архивных справок"
    kaz: Әкімдіктің 2012 жылғы 20 тамыздағы № 381 "Мұрағаттық анықтамалар беру" электрондық мемлекеттік қызмет регламентін бекіту туралы" қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72238/rus
