act_code: '18359'
requisite: Постановление Правительства Республики Казахстан от 28 января 2004 года N 96
title:
  rus: О распределении целевых трансфертов областным бюджетам на развитие малых городов, в том числе с депрессивной экономикой
  kaz: Шағын қалаларды, соның iшiнде экономикасы күйзелiске ұшыраған қалаларды дамытуға облыстық бюджеттерге мақсатты трансферттердi бөлу туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2004-01-28
approved_by:
- '103000000000'
version_date:
  kaz: 2004-01-28
  rus: 2004-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/18359/kaz/28.01.2004
  rus: https://zan.gov.kz/client/#!/doc/18359/rus/28.01.2004
