act_code: '99403'
requisite: Постановление Шиелийского районного акимата Кызылординской области от 12 января 2016 года № 700. Зарегистрировано Департаментом юстиции Кызылординской области 15 февраля 2016 года № 5357. Утратило силу постановлением Шиелийского районного акимата Кызылординской области от 24.06.2016 № 835.
title:
  rus: Об утверждении Положения коммунального государственного учреждения "Шиелийский районный отдел физический культуры и спорта"
  kaz: '"Шиелі аудандық дене шынықтыру және спорт бөлімі" коммуналдық мемлекеттік мекемесінің Ережесін бекіту туралы'
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2016-01-12
approved_by:
- '161008000001'
version_date:
  kaz: 2016-01-12
  rus: 2016-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/99403/kaz/12.01.2016
  rus: https://zan.gov.kz/client/#!/doc/99403/rus/12.01.2016
