act_code: '82818'
requisite: Постановление Кабинета Министров Республики Казахстан от 23 августа 1995 г. N 1170. Утратило силу постановлением Правительства Республики Казахстан от 20 апреля 2023 года № 316
title:
  rus: Об организации международных авиаперевозок в аэропортах Республики Казахстан по временной схеме
  kaz: Қазақстан Республикасының әуежайларында халықаралық авиатасымалдарын уақытша схема бойынша ұйымдастыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 1995-08-23
approved_by:
- '103000000000'
version_date:
  rus: 1997-04-24
source:
  rus: https://zan.gov.kz/client/#!/doc/82818/rus/24.04.1997
caused_by:
  code: '1394'
  requisite: Постановление Правительства Республики Казахстан от 25 апреля 1997 года № 660. Утратило силу постановлением Правительства Республики Казахстан от 20 апреля 2023 года № 316 (вводится в действие со дня его подписания)
  title:
    rus: 'ИМПОРТ: О внесении дополнений в постановление Правительства Республики Казахстан от 23 августа 1995 года № 1170'
    kaz: 'ИМПОРТ: Қазақстан Республикасы Үкiметiнiң 1995 жылғы 23 тамыздағы № 1170 қаулысына толықтырулар енгiзу туралы'
  link: https://zan.gov.kz/client/#!/doc/1394/rus
