act_code: '38863'
requisite: Постановление Правительства Республики Казахстан от 15 апреля 2008 года № 339
title:
  rus: Об утверждении лимитов штатной численности министерств и иных центральных исполнительных органов с учетом численности их территориальных органов и подведомственных им государственных учреждений
  kaz: Министрліктер мен өзге де орталық атқарушы органдардың олардың аумақтық органдарындағы және оларға ведомстволық бағыныстағы мемлекеттік мекемелердегі адам санын ескере отырып, штат санының лимиттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-04-15
approved_by:
- '103000000000'
version_date:
  kaz: 2026-01-13
  rus: 2026-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/38863/kaz/13.01.2026
  rus: https://zan.gov.kz/client/#!/doc/38863/rus/13.01.2026
caused_by:
  code: '221312'
  requisite: Постановление Правительства Республики Казахстан от 13 января 2026 года № 8
  title:
    rus: О реорганизации республиканского государственного предприятия на праве хозяйственного ведения «Государственный институт проведения работ по обследованию земель» Комитета по управлению земельными ресурсами Министерства сельского хозяйства Республики Казахстан
    kaz: Қазақстан Республикасы Ауыл шаруашылығы министрлігі Жер ресурстарын басқару комитетінің «Жерлерге зерттеп-қарау жұмыстарын жүргізу мемлекеттік институты» шаруашылық жүргізу құқығындағы республикалық мемлекеттік кәсіпорнын қайта ұйымдастыру туралы
  link: https://zan.gov.kz/client/#!/doc/221312/rus
