act_code: '38863'
requisite: Постановление Правительства Республики Казахстан от 15 апреля 2008 года № 339
title:
  rus: Об утверждении лимитов штатной численности министерств и иных центральных исполнительных органов с учетом численности их территориальных органов и подведомственных им государственных учреждений
  kaz: Министрліктер мен өзге де орталық атқарушы органдардың олардың аумақтық органдарындағы және оларға ведомстволық бағыныстағы мемлекеттік мекемелердегі адам санын ескере отырып, штат санының лимиттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-04-15
approved_by:
- '103000000000'
version_date:
  kaz: 2016-10-18
  rus: 2016-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/38863/kaz/18.10.2016
  rus: https://zan.gov.kz/client/#!/doc/38863/rus/18.10.2016
caused_by:
  code: '107380'
  requisite: Постановление Правительства Республики Казахстан от 18 октября 2016 года № 594. Утратило силу постановлением Правительства Республики Казахстан от 21 июля 2018 года № 444
  title:
    rus: Некоторые вопросы Министерства по делам религий и гражданского общества Республики Казахстан
    kaz: Қазақстан Республикасы Дін істері және азаматтық қоғам министрлігінің кейбір мәселелері
  link: https://zan.gov.kz/client/#!/doc/107380/rus
