act_code: '38863'
requisite: Постановление Правительства Республики Казахстан от 15 апреля 2008 года № 339
title:
  rus: Об утверждении лимитов штатной численности министерств и иных центральных исполнительных органов с учетом численности их территориальных органов и подведомственных им государственных учреждений
  kaz: Министрліктер мен өзге де орталық атқарушы органдардың олардың аумақтық органдарындағы және оларға ведомстволық бағыныстағы мемлекеттік мекемелердегі адам санын ескере отырып, штат санының лимиттерін бекіту туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2008-04-15
approved_by:
- '103000000000'
version_date:
  kaz: 2016-07-22
  rus: 2016-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/38863/kaz/22.07.2016
  rus: https://zan.gov.kz/client/#!/doc/38863/rus/22.07.2016
caused_by:
  code: '1082'
  requisite: Постановление Правительства Республики Казахстан от 22 июля 2016 года № 427
  title:
    rus: О некоторых вопросах Национального университета обороны имени Первого Президента Республики Казахстан - Лидера Нации
    kaz: Қазақстан Республикасының Тұңғыш Президенті – Елбасы атындағы Ұлттық қорғаныс университетінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/1082/rus
