act_code: '51306'
requisite: Павлодар облысы Май аудандық әкімдігінің 2010 жылғы 18 ақпандағы № 19/2 қаулысы. Павлодар облысы Май ауданының Әділет басқармасында 2010 жылғы 17 наурызда № 12-10-93 тіркелген
title:
  rus: Май ауданында 2010 жылы кәсіби даярлау, қайта даярлау және олардың біліктілігін арттыру туралы
  kaz: Май ауданында 2010 жылы кәсіби даярлау, қайта даярлау және олардың біліктілігін арттыру туралы
form: ПОСТ
type_codes:
- ПОСТ
approved_on: 2010-02-18
approved_by:
- '164010000001'
version_date:
  kaz: 2010-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/51306/kaz/18.02.2010
